Repository wordpress-mobile/WordPress-Android, pull requests merged in 2018-08, with the labels that each got.

#8140 Fix crash on device rotation while scrolling in the media library
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/people/PeopleListFragment.java
Labels: GIF support, [Type] Crash

#8119 Issue/7996 actionable empty states (Part 4)
  WordPress/src/main/java/org/wordpress/android/ui/ActionableEmptyView.kt
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/people/PeopleListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderBlogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/stockmedia/StockMediaPickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserFragment.java
  WordPress/src/main/res/drawable/ic_stock_media.xml
  WordPress/src/main/res/layout/media_browser_activity.xml
  WordPress/src/main/res/layout/media_grid_fragment.xml
  WordPress/src/main/res/layout/stock_media_picker_activity.xml
  WordPress/src/main/res/layout/theme_browser_fragment.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
Labels: General

#8124 Add support for gifs to local media picker
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/ThumbnailLoader.java
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ImageUtils.java
Labels: GIF support, Posting/Editing

#8143 Screenshot automation: improve reliability across all locales
  WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java
Labels: General

#8145 Favor the feedId when previewing a site
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderActivityLauncher.java
Labels: Groundskeeping, Reader

#8151 Hide Jetpack security pref for self-hosted (non-jp) sites
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
Labels: Groundskeeping, Site Settings

#8146 Changed logout confirmation to account for local changes
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java
  WordPress/src/main/res/values/strings.xml
Labels: Groundskeeping

#8152 Remove the plurals version of the logout message
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java
  WordPress/src/main/res/values/strings.xml
Labels: Groundskeeping

#7977 Add missing tests to rewind feature
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/RewindStatusService.kt
  WordPress/src/test/java/org/wordpress/android/ui/activitylog/RewindStatusServiceTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModelTest.kt
Labels: Activity Log

#8127 Automate taking screenshots across specified devices
  .gitignore
  WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java
  fastlane/Fastfile
  fastlane/actions/download_metadata.rb
  fastlane/actions/take_android_emulator_screenshots.rb
  fastlane/helpers/android_virtual_device_helper.rb
Labels: General

#8138 Add glide to ReaderPhotoView
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaPreviewFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaSettingsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/blocks/NoteBlock.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderPhotoView.java
  WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt
  WordPress/src/main/java/org/wordpress/android/util/image/ImagePlaceholderManager.kt
  WordPress/src/main/java/org/wordpress/android/util/image/ImageType.kt
  WordPress/src/main/java/org/wordpress/android/util/image/getters/WPCustomImageGetter.kt
Labels: GIF support, Reader

#8159 Hotfix - picking a feature image for a post results in crash sometimes
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
Labels: Posting/Editing, [Type] Crash

#8121 Issue/8035 fabric optout
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/util/CrashlyticsUtils.java
Labels: Analytics

#8142 Search in Properly Placed Pages
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/networking/PageStore.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/networking/PageStoreTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/LiveDataUtils.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PagesViewModelTest.kt
Labels: Properly placed pages

#8166 Merge release/10.6 into develop
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/people/PeopleListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt
Labels: releases

#8168 Use the migrated PageStore from FluxC
  WordPress/src/main/java/org/wordpress/android/models/pages/PageModel.kt
  WordPress/src/main/java/org/wordpress/android/models/pages/PageStatus.kt
  WordPress/src/main/java/org/wordpress/android/networking/PageStore.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageListFragment.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt
  WordPress/src/test/java/org/wordpress/android/networking/PageStoreTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PagesViewModelTest.kt
  build.gradle
Labels: Properly placed pages

#8169 Use the fixed page store that includes trashed pages
  build.gradle
Labels: Properly placed pages

#8171 News Card - adds service layer
  WordPress/src/main/java/org/wordpress/android/models/news/LocalNewsItem.kt
  WordPress/src/main/java/org/wordpress/android/models/news/NewsItem.kt
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/ui/news/LocalNewsService.kt
  WordPress/src/main/java/org/wordpress/android/ui/news/NewsService.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/news/LocalNewsServiceTest.kt
Labels: News Card

#8164 Introduced UI to list domain suggestions.
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/domainregister/suggestionslist/DomainSuggestionsActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/domainregister/suggestionslist/DomainSuggestionsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/domainregister/suggestionslist/DomainSuggestionsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/domainregister/suggestionslist/DomainSuggestionsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/domainregister/DomainSuggestionsViewModel.kt
  WordPress/src/main/res/layout/activity_domain_suggestions_activity.xml
  WordPress/src/main/res/layout/domain_suggestion_list_item.xml
  WordPress/src/main/res/layout/domain_suggestions_fragment.xml
  WordPress/src/main/res/layout/my_site_fragment.xml
  WordPress/src/main/res/values/colors.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/AppLog.java
Labels: Domain Search

#8174 Issue/add tags empty
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsTagListActivity.java
  WordPress/src/main/res/layout/site_settings_tag_list_activity.xml
  WordPress/src/main/res/menu/tag_list.xml
  WordPress/src/main/res/values/strings.xml
Labels: Site Settings

#8161 Zendesk: Adds new custom fields.
  WordPress/src/main/java/org/wordpress/android/support/ZendeskHelper.kt
Labels: Zendesk

#8184 Fix crash when loading video thumbnail
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java
Labels: Media, [Type] Crash

#8177 Delete /future folder
  WordPress/src/future/res/drawable-xxxhdpi/my_site_icon_sharing.png
  WordPress/src/future/svg/stats_widget_promo_header.svg
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java
  WordPress/src/main/res/drawable-hdpi/ic_share_24dp.png
  WordPress/src/main/res/drawable-hdpi/my_site_icon_sharing.png
  WordPress/src/main/res/drawable-xhdpi/ic_share_24dp.png
  WordPress/src/main/res/drawable-xhdpi/my_site_icon_sharing.png
  WordPress/src/main/res/drawable-xxhdpi/ic_share_24dp.png
  WordPress/src/main/res/drawable-xxhdpi/my_site_icon_sharing.png
  WordPress/src/main/res/layout/my_site_fragment.xml
  WordPress/src/main/res/menu/media_settings.xml
Labels: General

#8178 PPP: Page editing
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/networking/PageUploadUtil.kt
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageParentFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/SnackbarMessageHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/util/DateTimeExtensions.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt
  WordPress/src/main/res/drawable/ic_gridicons_page_14dp.xml
  WordPress/src/main/res/layout/page_item.xml
  WordPress/src/main/res/layout/page_list_item.xml
  WordPress/src/main/res/layout/pages_fragment.xml
  WordPress/src/main/res/menu/page_more.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PagesViewModelTest.kt
  build.gradle
Labels: Properly placed pages

#8187 News Card - ViewModel
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/news/LocalNewsService.kt
  WordPress/src/main/java/org/wordpress/android/ui/news/NewsManager.kt
  WordPress/src/main/java/org/wordpress/android/ui/news/NewsService.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/news/LocalNewsServiceTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/news/NewsManagerTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/reader/ReaderPostListViewModelTest.kt
Labels: News Card, Reader

#8200 Issue/8199 memory leaks
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderLikingUsersView.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSiteHeaderView.java
Labels: [Type] Crash

#8188 News Card - integration
  WordPress/src/main/java/org/wordpress/android/ui/news/NewsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/main/res/layout/news_card.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
Labels: News Card, Reader, [Status] Needs Code Review

#8205 Feature/news card tracks
  WordPress/src/main/java/org/wordpress/android/ui/news/NewsTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/news/NewsTrackerHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/news/NewsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/AnalyticsUtils.java
  WordPress/src/test/java/org/wordpress/android/viewmodel/reader/ReaderPostListViewModelTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Analytics, News Card, Reader

#8207 Remote jetpack install
  WordPress/build.gradle
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/JetpackConnectionResultActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/JetpackConnectionWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/JetpackRemoteInstallActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/JetpackRemoteInstallFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/JetpackRemoteInstallViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/JetpackRemoteInstallViewState.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsConnectJetpackActivity.java
  WordPress/src/main/res/drawable/ic_exclamation_mark_88dp.xml
  WordPress/src/main/res/drawable/ic_jetpack_icon_green_88dp.xml
  WordPress/src/main/res/layout/jetpack_remote_install_activity.xml
  WordPress/src/main/res/layout/jetpack_remote_install_fragment.xml
  WordPress/src/main/res/layout/notifications_fragment_notes_list.xml
  WordPress/src/main/res/layout/stats_jetpack_connection_activity.xml
  WordPress/src/main/res/values-v21/stats_styles.xml
  WordPress/src/main/res/values/colors.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/JetpackRemoteInstallViewModelTest.kt
  build.gradle
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java
  libs/login/WordPressLoginFlow/src/main/res/values/strings.xml
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/AppLog.java
Labels: Jetpack

#8173 Prevent double-opening acivities
  WordPress/src/main/AndroidManifest.xml
Labels: [Type] Broken Window

#8206 News card notification in the bottom nav bar
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainNavigationView.kt
  WordPress/src/main/java/org/wordpress/android/ui/news/NewsManager.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/news/NewsManagerTest.kt
Labels: News Card, Reader, [Status] Not Ready for Review

#8218 Issue/8215 empty followed tags
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderTagFragment.java
  WordPress/src/main/res/values/strings.xml
Labels: General

#8240 Support fragment migration: Media
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaEditFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridFragment.java
  WordPress/src/main/res/layout/media_edit_fragment.xml
Labels: General, Media

#8241 Support fragment migration: Publicize section
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeBaseFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListActivity.java
Labels: General, Sharing

#8232 Issue/deep indented parentheses
  WordPress/src/androidTest/java/org/wordpress/android/ui/plans/RemoteTests.java
  WordPress/src/main/java/org/wordpress/android/datasets/SiteSettingsTable.java
  WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java
  WordPress/src/main/java/org/wordpress/android/ui/FullScreenDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/services/NotificationsUpdateLogic.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/NotificationsActions.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/NotificationsUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/plans/models/Plan.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPreviewFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/SelectCategoriesActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/ReleaseNotesActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsDialogPreference.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderCommentListActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/ReferrerSpamHelper.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsCommentsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsFollowersFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsInsightsMostPopularFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsSingleItemDetailsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsViewAllActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsViewHolder.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/datasets/StatsTable.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/service/StatsServiceLogic.java
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/VideoOptimizer.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java
Labels: General

#8231 Issue/jetpack install drawables
  WordPress/src/main/java/org/wordpress/android/ui/JetpackRemoteInstallViewState.kt
  WordPress/src/main/res/drawable/ic_plans_grey_24dp.xml
  WordPress/src/main/res/drawable/ic_plans_grey_36dp.xml
  WordPress/src/main/res/drawable/ic_plans_jetpack_green_88dp.xml
  WordPress/src/main/res/drawable/img_illustration_info_outline_88dp.xml
  WordPress/src/main/res/layout/activity_log_item_detail.xml
  WordPress/src/main/res/layout/jetpack_remote_install_fragment.xml
  WordPress/src/main/res/layout/my_site_fragment.xml
  WordPress/src/test/java/org/wordpress/android/ui/JetpackRemoteInstallViewModelTest.kt
Labels: General

#8237 Handle Test Push Notifications sent by MC
  WordPress/src/main/java/org/wordpress/android/push/GCMMessageService.java
Labels: Core, Support

#8245 Bump Aztec version to v.1.3.8
  libs/editor/WordPressEditor/build.gradle
Labels: Aztec

#8246 Issue/missing fab string
  WordPress/src/main/res/values/strings.xml
Labels: Site Settings, Tag/Category Management

#8230 Issue/8217 empty followed sites
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderBlogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/res/values/strings.xml
Labels: General

#8249 Fixing Quick Start DB migration from 10.7 to 10.8
  build.gradle
Labels: [Status] Not Ready for Review

#8247 Fix NPE uploading local media
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/util/FluxCUtils.java
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/MediaUtils.java
Labels: Media

#8226 Issue/8216-empty-site-picker
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
  WordPress/src/main/res/layout/site_picker_activity.xml
  WordPress/src/main/res/values/strings.xml
Labels: General, Site Picker

#8213 Checkstyle rules updates
  config/checkstyle.xml
Labels: [Type] Enhancement

#8242 Support fragment migration: People section
  WordPress/src/main/java/org/wordpress/android/models/RoleUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/people/PeopleListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/people/PeopleManagementActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/people/PersonDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/people/RoleChangeDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/people/RoleSelectDialogFragment.java
Labels: General, People Management

#8243 Support fragment migration: Themes browser
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserFragment.java
Labels: General, Themes

#8248 Support fragment migration: Post list section
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostPreviewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostPreviewFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListFragment.java
  WordPress/src/main/java/org/wordpress/android/widgets/WPAlertDialogFragment.java
Labels: General, Post List

#8244 Support fragment migration: Stats section
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsAbstractFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsViewAllActivity.java
Labels: General, Stats

#8254 Support fragment migration: MainActivity and related fragments
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainNavigationView.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostWebViewCachingFragment.java
Labels: General

#8256 Add unhandled events to Tracking
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Broken Window

#8229 Merge working News Card feature branch into develop
  WordPress/src/main/java/org/wordpress/android/models/news/LocalNewsItem.kt
  WordPress/src/main/java/org/wordpress/android/models/news/NewsItem.kt
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainNavigationView.kt
  WordPress/src/main/java/org/wordpress/android/ui/news/LocalNewsService.kt
  WordPress/src/main/java/org/wordpress/android/ui/news/NewsManager.kt
  WordPress/src/main/java/org/wordpress/android/ui/news/NewsService.kt
  WordPress/src/main/java/org/wordpress/android/ui/news/NewsTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/news/NewsTrackerHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/news/NewsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/AnalyticsUtils.java
  WordPress/src/main/res/layout/news_card.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/news/LocalNewsServiceTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/news/NewsManagerTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/reader/ReaderPostListViewModelTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: News Card

#8260 Issue/quick start strings
  WordPress/src/main/res/values/strings.xml
Labels: General

#8211 Help the developer out if $ANDROID_HOME isn’t set
  .gitignore
  Gemfile
  Gemfile.lock
  fastlane/helpers/android_virtual_device_helper.rb
Labels: General

#8259 Support fragment migration: AuthenticationDialogUtils
  WordPress/src/main/java/org/wordpress/android/util/AuthenticationDialogUtils.java
  WordPress/src/main/java/org/wordpress/android/widgets/AuthErrorDialogFragment.java
Labels: General, [Pri] High

#8257 Support fragment migration: MyProfile screen
  WordPress/src/main/java/org/wordpress/android/ui/prefs/MyProfileActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/MyProfileFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/ProfileInputDialogFragment.java
Labels: General

#8263 Fix missing icons in Stats widget
  WordPress/src/main/res/layout/stats_widget_layout.xml
Labels: Stats, [Type] Broken Window
