Repository wordpress-mobile/WordPress-Android, pull requests merged in 2019-08, with the labels that each got.

#10226 Feature/back forward navigation
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/util/URLFilteredWebViewClient.java
  WordPress/src/main/res/menu/webview.xml
Labels: Previews, [Status] Needs Code Review

#10310 Issue/fix editor menu non selectable with enter key
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java
  libs/editor/WordPressEditor/src/main/res/layout/fragment_aztec_editor.xml
Labels: [Status] Needs Code Review

#10296 Feature/support for right click on long pressable views
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/giphy/GiphyMediaViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaSettingsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsTagListActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderCommentListActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stockmedia/StockMediaPickerActivity.java
  WordPress/src/main/java/org/wordpress/android/util/ViewUtils.kt
Labels: Chromebooks, [Status] Needs Code Review

#10312 Fix simple date format concurrency issue
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/AppLog.java
Labels: Core, [Type] Bug

#10316 Use FluxC 1.2.0-beta-1
  build.gradle
Labels: releases

#10317 Merge 13.0 release notes into master
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  build.gradle
Labels: releases

#10311 Do not show publish confirmation dialog on submit for review
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostActionHandler.kt
Labels: Post List, Posting/Editing

#10318 Setting light toolbar for Web Preview
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
Labels: Previews, [Status] Needs Code Review

#10320 Fix PostListItemUiStateHelper unit tests
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Post List

#10212 Hide previews for published posts on Jetpack sites
  WordPress/src/main/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelper.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelperTest.kt
Labels: Offline Support

#10327 Update the 12.9 release notes to add a note about the block editor
  WordPress/metadata/PlayStoreStrings.po
Labels: releases

#10300 Add additional properties to the Block Editor activation events
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsInterface.java
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsMetadata.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Analytics, Posting/Editing

#10326 Feature/desktop preview
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/JetpackConnectionWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/PreviewModeMenuAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeWebActivity.java
  WordPress/src/main/java/org/wordpress/android/util/URLFilteredWebViewClient.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/wpwebview/WPWebViewViewModel.kt
  WordPress/src/main/res/drawable/ic_arrow_right_white_24dp.xml
  WordPress/src/main/res/drawable/ic_devices_white_24dp.xml
  WordPress/src/main/res/drawable/preview_mode_indicator_background.xml
  WordPress/src/main/res/drawable/web_preview_navbar_selector.xml
  WordPress/src/main/res/layout/preview_mode_popup_menu_item.xml
  WordPress/src/main/res/layout/wpwebview_activity.xml
  WordPress/src/main/res/menu/webview.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/WPWebViewViewModelTest.kt
Labels: Previews

#10325 Fix #10162: Remove unused code related to PostPreviewActivity/PostPreviewFragment
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostPreviewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostPreviewFragment.java
  WordPress/src/main/res/layout/post_preview_activity.xml
  WordPress/src/main/res/layout/post_preview_fragment.xml
  WordPress/src/main/res/menu/post_preview.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/key_strings.xml
  WordPress/src/main/res/values/strings.xml
Labels: Offline Support, Previews

#10293 Feature/plans talkback improvements
  WordPress/src/main/java/org/wordpress/android/ui/FullScreenDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/plans/PlansListAdapter.kt
  WordPress/src/main/res/layout/full_screen_dialog_fragment.xml
  WordPress/src/main/res/layout/plan_details_fragment.xml
  WordPress/src/main/res/layout/plan_feature_item.xml
  WordPress/src/main/res/layout/plans_list_item.xml
  WordPress/src/main/res/values/strings.xml
Labels: Accessibility, [Status] Needs Code Review

#10322 Make remote preview works for drafts on self hosted sites
  WordPress/src/main/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelper.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelperTest.kt
Labels: Offline Support

#10332 Fix v13.0 editors opt-in migration strategy problems
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsInterface.java
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  build.gradle
Labels: gutenberg-mobile

#10339 Hotfix 13.0 - Do not override editor preference already set on the remote on update
  build.gradle
Labels: gutenberg-mobile

#10330 Fix alert window size on Chromebooks and Tablets
  WordPress/src/main/java/org/wordpress/android/ui/prefs/DetailListPreference.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFormatDialog.java
  WordPress/src/main/java/org/wordpress/android/ui/utils/UiHelpers.kt
  WordPress/src/main/res/values/dimens.xml
Labels: [Status] Needs Code Review

#10338 Fix potential NPE in WPWebviewActivity
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
Labels: Webviews

#10321 Pull in login changes from woo-android
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java
Labels: Login

#10345 Hotfix - 13.0 - Do not override editors on sites update
  build.gradle
Labels: Site Settings

#10347 Fix/gb editor translations
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java
Labels: gutenberg-mobile, i18n

#10353 Invoke remote-auto-save when exiting the editor
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Offline Support

#10356 Fix submit/publish button on post list items on self-hosted sites
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListViewModelTest.kt
Labels: Post List

#10351 Don't save post when it wasn't edited during the current session
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Offline Support, Posting/Editing

#10355 Refactor get upload action methods
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListUploadStatusTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUploadAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadActionUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/main/java/org/wordpress/android/util/NetworkUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModelConnector.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostListMainViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterTest.kt
Labels: Offline Support, Tech debt

#10358 Merge release 13.0 into develop
  WordPress/build.gradle
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsInterface.java
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java
  build.gradle
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsMetadata.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java
Labels: releases

#10333 Merge/master remote previews+develop
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/JetpackConnectionWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/PreviewModeMenuAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeWebActivity.java
  WordPress/src/main/java/org/wordpress/android/util/URLFilteredWebViewClient.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/wpwebview/WPWebViewViewModel.kt
  WordPress/src/main/res/drawable/ic_arrow_right_white_24dp.xml
  WordPress/src/main/res/drawable/ic_devices_white_24dp.xml
  WordPress/src/main/res/drawable/preview_mode_indicator_background.xml
  WordPress/src/main/res/drawable/web_preview_navbar_selector.xml
  WordPress/src/main/res/layout/preview_mode_popup_menu_item.xml
  WordPress/src/main/res/layout/wpwebview_activity.xml
  WordPress/src/main/res/menu/webview.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/WPWebViewViewModelTest.kt
Labels: Previews

#10366 Add _container_ id to post_list_item_compact
  WordPress/src/main/res/layout/post_list_item_compact.xml
Labels: Post List

#10319 Auto-upload/save all posts/pages with local changes
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListEventListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PreviewStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadServiceFacade.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/test/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterTest.kt
  build.gradle
Labels: Posting/Editing, [Type] Enhancement

#10342 Issue/10207 pending upload labels
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListDialogHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListEventListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListUploadStatusTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUploadAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadActionUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/NetworkUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUploadStatus.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModelConnector.kt
  WordPress/src/main/res/layout/post_list_item.xml
  WordPress/src/main/res/layout/post_list_item_compact.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostListMainViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListViewModelTest.kt
Labels: Offline Support, Post List

#10343 Add cancel pending auto-upload action on post list items
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostActionHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListActionTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUploadAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/widgets/PostListButtonType.kt
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Offline Support, Post List, Posting/Editing

#10324 Fix #10219 restore page before edit or view
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListViewModel.kt
  WordPress/src/main/res/layout/page_list_item.xml
Labels: Pages List, Previews

#10348 Issue/10331 remove wpnumberpicker
  WordPress/src/main/java/org/wordpress/android/ui/WPNumberPicker.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/NumberPickerDialog.java
  WordPress/src/main/res/layout/number_picker_dialog.xml
  WordPress/src/main/res/values/styles.xml
Labels: [Pri] High, [Status] Needs Code Review, [Type] Bug

#10376 Fix fb publicize
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeWebViewFragment.java
Labels: Sharing, [Type] Bug

#10379 Update FluxC to the latest release
  build.gradle
Labels: releases

#10380 Fix migration in v13.1
  build.gradle
Labels: Post List, [Type] Bug, [Type] Crash

#10378 Fixes Publicize connection flow
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeActions.java
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeConstants.java
Labels: Sharing, [Status] Not Ready for Review, [Type] Bug

#10276 Display author on post list items
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemType.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/res/layout/post_list_item.xml
  WordPress/src/main/res/layout/post_list_item_compact.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Post List

#10384 Merge release 13.1 into develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
  build.gradle
Labels: releases

#10367 Track details about editor on editor related analytics events
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Posting/Editing

#10387 Fix inflation issue on lenovo
  WordPress/src/main/res/layout/filter_spinner_item.xml
  WordPress/src/main/res/layout/toolbar_main_spinner_item.xml
  WordPress/src/main/res/values/styles.xml
Labels: Comments, Reader

#10393 Merge Release/13.1 into Develop
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: releases

#10335 Feature/move notification settings to notifications list
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java
  WordPress/src/main/res/layout/me_fragment.xml
  WordPress/src/main/res/menu/notifications_list_menu.xml
  WordPress/src/main/res/values/strings.xml
Labels: Information Architecture, [Status] Needs Code Review

#10297 Issue/update color scheme
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt
  WordPress/src/main/res/drawable/bg_rectangle_primary_60_16dp.xml
  WordPress/src/main/res/values/stats_styles.xml
Labels: General, [Status] Needs Code Review

#10400 WPWebViewViewModel: Remove log call on WebView errors
  WordPress/src/main/java/org/wordpress/android/viewmodel/wpwebview/WPWebViewViewModel.kt
Labels: [Type] Bug

#10405 Remove HistoryListFragment.onSaveInstanceState
  WordPress/src/main/java/org/wordpress/android/ui/posts/HistoryListFragment.kt
Labels: [Type] Bug

#10412 Increase offscreen page limit to fix crash in history
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: [Type] Crash

#10417 Merge release 13.0.1 into 13.1
  WordPress/src/main/java/org/wordpress/android/ui/posts/HistoryListFragment.kt
Labels: releases

#10392 Add unit tests for UploadActionUseCase
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadActionUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadActionUseCaseTest.kt
Labels: Offline Support, Tech debt, Testing

#10386 Synchronize Reader Search adapter
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderSearchSuggestionAdapter.java
Labels: Reader

#10388 Fix NPE in UploadService
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
Labels: Posting/Editing, [Type] Crash

#10290 Open keyboard on expand click on Full screen comment
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/ui/CommentFullScreenDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/CommentFullScreenDialogViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/CommentFullScreenDialogViewModelTest.kt
Labels: Comments

#10396 Issue/improving mobile desktop previews
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/wpwebview/WPWebViewViewModel.kt
  WordPress/src/main/res/layout/progress_layout.xml
  WordPress/src/main/res/layout/wpwebview_activity.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/WPWebViewViewModelTest.kt
Labels: Previews, [Status] Needs Code Review

#10419 Merge Release/13.1 into develop
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/HistoryListFragment.kt
Labels: releases

#10422 AS 3.5: Update main style config and project config
  .idea/codeStyleSettings.xml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
Labels: Core

#10421 Update release toolkit
  Gemfile.lock
  fastlane/Pluginfile
Labels: Tooling

#10404 Provide installable APK for every Pull Request
  .circleci/config.yml
  .configure
  .configure-files/automattic.jks.enc
  .configure-files/google-services.json.enc
  .configure-files/gradle.properties.enc
  .configure-files/sentry.properties.enc
  .gitignore
  WordPress/build.gradle
Labels: Tooling

#10424 Re-add update-metadata-source action
  fastlane/actions/android_update_metadata_source.rb
Labels: Tooling

#10425 Updated hint text for moved notification settings
  WordPress/src/main/res/values/strings.xml
Labels: Notifications

#10301 Use site timezone in the Overview card
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/DateSelectorViewUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateFormatter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateSelector.kt
  WordPress/src/main/res/layout/stats_date_selector.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/StatsDateSelectorTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetListViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateFormatterTest.kt
  build.gradle
Labels: Stats Refresh

#10429 Remove obsolete stats tests
  WordPress/src/androidTest/java/org/wordpress/android/ui/stats/RemoteTests.java
Labels: Stats Refresh

#10402 Fix private post gets published as public
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostUtilsUnitTest.kt
Labels: Posting/Editing

#10411 Stats - File downloads stats card
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsViewType.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/NavigationTarget.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModelFactory.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/FileDownloadsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsNavigator.kt
  WordPress/src/main/res/layout/stats_block_empty_item.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/FileDownloadsUseCaseTest.kt
  build.gradle
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Stats Refresh

#10431 Update FluxC to 1.2.1-beta-2
  build.gradle
Labels: Stats Refresh

#10423 Add tracks to UploadStarter
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsTrackerWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Analytics, Offline Support

#10432 PR Template: Make release notes checkbox clearer
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Tooling

#10409 UsernameChangerFullScreenDialogFragment made abstract for extensibility
  WordPress/src/androidTest/java/org/wordpress/android/ui/accounts/signup/UsernameChangerFullScreenDialogFragmentTest.kt
  WordPress/src/debug/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/BaseUsernameChangerFullScreenDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/UsernameChangerFullScreenDialogFragment.kt
Labels: /Me, [Type] Enhancement

#10362 Feature/quick actions v1
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/res/layout/my_site_fragment.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/styles.xml
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Information Architecture

#10430 Feature/fix follower totals card
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowerTotalsUseCase.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowerTotalsUseCaseTest.kt
Labels: Stats Refresh

#10428 CircleCI: Fix installable build job for branches with no PR
  .circleci/config.yml
Labels: Tooling

#10439 Update FluxC to 1.3.0
  build.gradle
Labels: releases

#10442 Merge Release/13.2 to develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
Labels: releases

#10391 Feature/populate domain info phone prefix when selecting country
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt
  WordPress/src/main/java/org/wordpress/android/util/DomainPhoneNumberUtils.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/domains/DomainRegistrationDetailsViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/util/DomainPhoneNumberUtilsTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/domains/DomainRegistrationDetailsViewModelTest.kt
Labels: Domain Credit, [Status] Needs Code Review

#10426 Fixes #10108: Add auto save conflict dialog
  .idea/inspectionProfiles/profiles_settings.xml
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostActionHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostConflictResolver.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListDialogHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModelConnector.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListViewModelTest.kt
  build.gradle
Labels: Offline Support, Post List, [Status] Needs Copy Review

#10449 Update release toolkit to 0.7.2
  Gemfile.lock
  fastlane/Pluginfile
Labels: Tooling

#10420 Refresh widgets on stats refresh
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AllTimeStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TodayStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/WidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/utils/WidgetUtils.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AllTimeStatsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TodayStatsUseCaseTest.kt
Labels: Stats Refresh

#10451 Rename conflict autosave to autosave revision
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostActionHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostConflictResolver.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListDialogHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/res/values/strings.xml
Labels: Offline Support, Post List

#10452 Stop auto-uploading pages
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PagesViewModelTest.kt
Labels: Offline Support, Pages List

#10456 Issue/fix notification header text color
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/detail/ActivityLogDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/adapters/NotesAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/blocks/CommentUserNoteBlock.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/blocks/FooterNoteBlock.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/blocks/HeaderNoteBlock.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/blocks/NoteBlock.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/blocks/NoteBlockClickableSpan.java
Labels: [Status] Needs Code Review, [Type] Bug

#10436 Implemented change username functionality in the Account Settings
  WordPress/src/androidTest/java/org/wordpress/android/ui/accounts/signup/UsernameChangerFullScreenDialogFragmentTest.kt
  WordPress/src/debug/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/ui/FullScreenDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/BaseUsernameChangerFullScreenDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SettingsUsernameChangerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/UsernameChangerFullScreenDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AccountSettingsFragment.java
  WordPress/src/main/res/layout/settings_username_changer_confirm_dialog.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  build.gradle
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Enhancement

#10445 Stats - missing view all data
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/SelectedDateProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateSelector.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsNavigator.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/StatsDateSelectorTest.kt
Labels: Stats Refresh

#10453 CircleCI: Update caching for installable build jobs
  .circleci/config.yml
Labels: Tooling

#10390 Update Color 2.1.0
  WordPress/src/main/res/values/colors.xml
Labels: General

#10470 Using content margin instead of normal one.
  WordPress/src/main/res/layout/me_fragment.xml
Labels: [Status] Needs Code Review
