Repository wordpress-mobile/WordPress-Android, pull requests merged in 2019-06, with the labels that each got.

#9961 Track site_created event
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SiteCreationTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/services/SiteCreationServiceManager.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/services/SiteCreationServiceManagerTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Analytics, Site Creation

#9972 Fix './gradlew build' in libs/mocks
  libs/mocks/WordPressMocks/build.gradle
Labels: Tooling

#9973 Exclude language resources from App Bundle splitting to allow in-app switching
  WordPress/build.gradle
Labels: Tooling

#9974 Merge release/12.5 into release/12.6
  libs/mocks/WordPressMocks/build.gradle
Labels: releases

#9975 CircleCI: Update Orb to latest
  .circleci/config.yml
Labels: Tooling

#9976 Merge Release/12.6 into develop
  WordPress/build.gradle
  libs/mocks/WordPressMocks/build.gradle
Labels: releases

#9932 Stats Widget - Add Color selection dialog fragment to configuration activity
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/ColorSelectionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsViewsWidgetConfigureFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsWidgetSiteSelectionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsWidgetViewModel.kt
  WordPress/src/main/res/layout/stats_color_selector.xml
  WordPress/src/main/res/layout/stats_views_widget_configure_activity.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsWidgetViewModelTest.kt
Labels: Stats Refresh

#9980 Merge changes from incorrect branch to the widget readonly branch
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/ColorSelectionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsViewsWidgetConfigureFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsWidgetSiteSelectionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsWidgetViewModel.kt
  WordPress/src/main/res/layout/stats_color_selector.xml
  WordPress/src/main/res/layout/stats_views_widget_configure_activity.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsWidgetViewModelTest.kt
Labels: Stats Refresh

#9981 Update Firebase Test Lab credentials
  .circleci/.firebase.secrets.json.enc
Labels: Tooling

#9992 Merge Release/12.6 into Develop
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: releases

#9993 Merge Release/12.5 into Master
  WordPress/build.gradle
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-ms/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  libs/mocks/WordPressMocks/build.gradle
Labels: releases

#9892 Issue/9739 domain contact form refactoring
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/domains/DomainRegistrationDetailsViewModel.kt
  WordPress/src/main/res/layout/domain_registration_details_fragment.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/util/AppLog.java
  WordPress/src/test/java/org/wordpress/android/viewmodel/domains/DomainRegistrationDetailsViewModelTest.kt
Labels: Domain Credit, [Status] Needs Code Review

#9963 Do not display password for self-hosted sites
  WordPress/src/main/java/org/wordpress/android/ui/prefs/BlogPreferencesActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/EditTextPreferenceWithValidation.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SummaryEditTextPreference.java
  WordPress/src/main/java/org/wordpress/android/util/ValidationUtils.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/site_settings.xml
Labels: [Type] Enhancement

#9950 Stats views widget
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/ColorSelectionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsViewsWidget.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsViewsWidgetConfigureFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsViewsWidgetConfigureViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsWidgetSiteAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsWidgetSiteSelectionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsWidgetSiteViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsListProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsWidgetListProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsWidgetListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/WidgetService.kt
  WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt
  WordPress/src/main/res/drawable/bg_rectangle_gray_0_top_radius_4dp.xml
  WordPress/src/main/res/drawable/bg_rectangle_gray_700_top_radius_4dp.xml
  WordPress/src/main/res/drawable/bg_rectangle_gray_800_radius_4dp.xml
  WordPress/src/main/res/drawable/bg_rectangle_white_radius_4dp.xml
  WordPress/src/main/res/layout/stats_views_widget_dark.xml
  WordPress/src/main/res/layout/stats_views_widget_item_dark.xml
  WordPress/src/main/res/layout/stats_views_widget_item_light.xml
  WordPress/src/main/res/layout/stats_views_widget_light.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/xml/stats_views_widget_info.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsViewsWidgetConfigureViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsWidgetListViewModelTest.kt
Labels: Stats Refresh

#10005 Fix #9563: Improve Offline View Post UX
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/JetpackConnectionWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/JetpackConnectionWebViewClient.java
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPreviewFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostPreviewFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SiteCreationPreviewFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/main/java/org/wordpress/android/util/ErrorManagedWebViewClient.kt
  WordPress/src/main/java/org/wordpress/android/util/URLFilteredWebViewClient.java
  WordPress/src/main/java/org/wordpress/android/util/WPWebViewClient.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/wpwebview/WPWebViewViewModel.kt
  WordPress/src/main/res/drawable/img_illustration_cloud_off_152dp.xml
  WordPress/src/main/res/layout-land/site_creation_preview_screen.xml
  WordPress/src/main/res/layout/main_activity.xml
  WordPress/src/main/res/layout/progress_layout.xml
  WordPress/src/main/res/layout/site_creation_preview_screen_default.xml
  WordPress/src/main/res/layout/site_creation_preview_web_view_container.xml
  WordPress/src/main/res/layout/site_creation_verticals_screen.xml
  WordPress/src/main/res/layout/wpwebview_activity.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/WPWebViewViewModelTest.kt
Labels: Offline Support

#9956 Fix upload notification not shown on retry
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
Labels: Posting/Editing

#10006 Update work library for AndroidX and update deprecated classes
  WordPress/build.gradle
  WordPress/src/androidTest/java/org/wordpress/android/e2e/LoginTests.java
  WordPress/src/androidTest/java/org/wordpress/android/support/DemoModeEnabler.kt
  WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java
  WordPress/src/androidTest/java/org/wordpress/android/util/UploadWorkerTest.kt
  build.gradle
Labels: Core

#10004 [GB-Mobile] Fix for Permissions Denied dialog loop
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java
Labels: gutenberg-mobile

#10009 Fix issue where two identical drafts were created
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java
Labels: Posting/Editing

#10010 Improve error messaging when changing account settings
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AccountSettingsFragment.java
Labels: /Me

#10003 Start uploadService as foreground service
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadServiceFacade.kt
Labels: [Type] Enhancement

#9996 Issue/update html strings
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsConnectJetpackActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/TitleViewHolder.kt
  WordPress/src/main/res/layout/domain_registration_details_fragment.xml
  WordPress/src/main/res/layout/notifications_list_fragment.xml
  WordPress/src/main/res/layout/stats_jetpack_connection_activity.xml
  WordPress/src/main/res/layout/stats_quick_scan_item.xml
  WordPress/src/main/res/values/strings.xml
Labels: Notifications, Stats, [Status] Needs Code Review, i18n

#9970 Widget links to stats activity
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/BaseListUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/SelectedDateProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/management/InsightsManagementFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/management/InsightsManagementViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AnnualSiteStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsViewsWidget.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsWidgetListProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsWidgetListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/SelectedSectionManager.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateSelector.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsNavigator.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsSiteProvider.kt
  WordPress/src/main/res/layout/stats_color_selector.xml
  WordPress/src/main/res/layout/stats_views_widget_dark.xml
  WordPress/src/main/res/layout/stats_views_widget_item_dark.xml
  WordPress/src/main/res/layout/stats_views_widget_item_light.xml
  WordPress/src/main/res/layout/stats_views_widget_light.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/StatsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/AuthorsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ClicksUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/CountryViewsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/PostsAndPagesUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ReferrersUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/SearchTermsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/VideoPlaysUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AnnualSiteStatsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/SelectedSectionManagerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/StatsSiteProviderTest.kt
Labels: Stats Refresh

#10013 Stats Views widget errors
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsViewsWidget.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsViewsWidgetConfigureFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsWidgetListProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsWidgetListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsWidgetUpdater.kt
  WordPress/src/main/res/layout/stats_views_widget_dark.xml
  WordPress/src/main/res/layout/stats_views_widget_light.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsWidgetListViewModelTest.kt
Labels: Stats Refresh

#10033 alpha-173 / 736 version bump
  WordPress/build.gradle
Labels: releases

#10036 Issue/10031 Add comments to Tracks events which are part of critical path
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SiteCreationTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/services/SiteCreationServiceManager.kt
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Analytics

#10024 Fix SAVE action in the editor on local drafts
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Posting/Editing

#10042 Handle 2FA error for OAuth client during login
  README.md
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AccountSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/res/values/strings.xml
  build.gradle
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginBaseFormFragment.java
  libs/login/WordPressLoginFlow/src/main/res/values/strings.xml
Labels: /Me, Login

#10047 Update login library subtree
  libs/login/WordPressLoginFlow/build.gradle
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupEmailFragment.java
Labels: Login

#10048 Remove feature flag and custom domain check from plugins row visibility check
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginUtils.java
Labels: [Status] Needs Code Review

#10049 Merge release/12.6 into develop
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-da/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-uz/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
Labels: releases

#10050 Merge release 12.7 into develop
  RELEASE-NOTES.txt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
Labels: releases

#10055 Gutenberg/Android X: Apply Java 1.8 compileOptions even when building from binaries
  WordPress/build.gradle
Labels: Tooling, gutenberg-mobile

#10066 Merge Release/12.7 into develop
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: releases

#10034 Use the stylesheet field as identifier for the customizer url
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeWebActivity.java
Labels: Themes

#10063 Fixed issues with domain contact form.
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainProductDetails.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/domains/DomainRegistrationDetailsViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/domains/DomainRegistrationDetailsViewModelTest.kt
  build.gradle
Labels: Domain Credit

#10045 Shorten numbers on small widgets
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsWidget.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/alltime/AllTimeWidgetListProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/alltime/AllTimeWidgetListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/alltime/AllTimeWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/TodayWidgetListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/TodayWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/utils/WidgetUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetListProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtils.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/alltime/AllTimeWidgetListViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetListViewModelTest.kt
Labels: Stats Refresh

#10052 Extract configuration view models
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/alltime/AllTimeWidgetListProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/alltime/AllTimeWidgetListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/alltime/AllTimeWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/ColorSelectionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsColorSelectionViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsSiteSelectionViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetConfigureFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetConfigureViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetSiteAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetSiteSelectionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetSiteViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/TodayWidgetListProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/TodayWidgetListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/TodayWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/utils/StatsIntentUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/utils/WidgetUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetUpdater.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/alltime/AllTimeWidgetListViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsColorSelectionViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsSiteSelectionViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetConfigureViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/TodayWidgetListViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetListViewModelTest.kt
Labels: Stats Refresh

#10058 Add tracks to the insights management
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/management/InsightsManagementViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/ItemPopupMenuHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsAnalyticsUtils.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Stats Refresh

#10078 Remove Comments view all screen
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModelFactory.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/CommentsUseCase.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/CommentsUseCaseTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Stats Refresh

#10069 Only run UI tests from org.wordpress.android.e2e on Firebase Test Lab
  .circleci/config.yml
Labels: Testing, Tooling

#10070 Connected Tests: Fix deprecation warnings after Android X upgrade
  WordPress/src/androidTest/java/org/wordpress/android/e2e/flows/LoginFlow.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/flows/SignupFlow.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/EditorPage.java
  WordPress/src/androidTest/java/org/wordpress/android/support/BaseTest.java
  WordPress/src/androidTest/java/org/wordpress/android/support/PlaceholderComparison.java
  WordPress/src/androidTest/java/org/wordpress/android/support/WPSupportUtils.java
  WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPLocaleTestRule.java
  WordPress/src/androidTest/java/org/wordpress/android/util/UploadWorkerTest.kt
Labels: Testing

#10075 Fix wrong Y axis values in Swedish
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/LargeValueFormatter.kt
Labels: Stats Refresh

#10051 Fix 9612 and 9825 - Posting: Update primary and secondary options + new Update confirmation dialog
  RELEASE-NOTES.txt
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/EditorPage.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/res/menu/edit_post.xml
  WordPress/src/main/res/menu/edit_post_legacy.xml
  WordPress/src/main/res/values/strings.xml
Labels: Offline Support, Posting/Editing

#9667 Open sites in the internal browser
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/util/URLFilteredWebViewClient.java
Labels: General, [Status] Needs Design Review

#10073 Create percentage bars in Stats cards
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/AuthorsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/PostsAndPagesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TagsAndCategoriesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ExpandableItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ListItemWithIconViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtils.kt
  WordPress/src/main/res/drawable/stats_bar_background.xml
  WordPress/src/main/res/layout/stats_block_list_item.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/AuthorsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/PostsAndPagesUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TagsAndCategoriesUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtilsTest.kt
Labels: Stats Refresh

#10074 Issue/9815 domain credit cta
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/plans/PlanUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  WordPress/src/main/res/layout/my_site_fragment.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/util/PlanUtilsTest.kt
  WordPress/src/test/java/org/wordpress/android/util/SiteUtilsTest.kt
Labels: Domain Credit, [Status] Needs Code Review

#10103 Fix #10093: Fix a NPE in the theme webactivity
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeWebActivity.java
  WordPress/src/main/res/layout/theme_web_activity.xml
Labels: Offline Support

#10105 Revert: Start uploadService as foreground service (656e7268)
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadServiceFacade.kt
Labels: Offline Support, [Type] Crash

#10023 issue/62-simple post search
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewState.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListType.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/util/ThrottleLiveData.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListEmptyUiState.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/res/layout/post_list_activity.xml
  WordPress/src/main/res/menu/posts_list_toggle_view_layout.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostListMainViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListViewModelTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Status] Needs Code Review, [Status] Needs Design Review

#10097 [Editor] Make sure editor session starts (with `content_type=new`) matches post_created event
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostEditorAnalyticsSession.java
Labels: Analytics, Posting/Editing

#10083 Fix #10059: limit auto initiated upload to 10 errors or cancellations
  WordPress/src/main/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarter.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
  WordPress/src/test/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarterTest.kt
  build.gradle
Labels: Offline Support

#10060 Stats Minified widget
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsWidget.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/alltime/AllTimeWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/minified/MinifiedWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/minified/StatsMinifiedWidget.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/minified/StatsMinifiedWidgetConfigureFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/minified/StatsMinifiedWidgetConfigureViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/TodayWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/utils/WidgetUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetListProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetUpdater.kt
  WordPress/src/main/res/layout/stats_widget_configure_fragment.xml
  WordPress/src/main/res/layout/stats_widget_minified_dark.xml
  WordPress/src/main/res/layout/stats_widget_minified_light.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/stats_minified_widget_info.xml
Labels: Stats Refresh

#10082 Improve stats architecture to reduce unnecessary refreshes
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/BaseListUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostHeaderUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BaseStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/GranularStatefulUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/GranularStatelessUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/AuthorsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ClicksUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ReferrersUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/CommentsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowersUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ManagementControlUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ManagementNewsCardUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TagsAndCategoriesUseCase.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/BaseStatsUseCaseTest.kt
Labels: Stats Refresh

#10091 Add additional tracking to stats
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/SelectedDateProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsAnalyticsUtils.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Stats Refresh

#10095 Update FluxC reference
  build.gradle
Labels: General

#9957 Changes related to deep linking email marketing
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/DeepLinkingIntentReceiverActivity.java
Labels: Site Creation

#10099 Show error when loading fails the first time
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/UiModelMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/SelectedDateProvider.kt
Labels: Stats Refresh

#10109 Check login status in widget configuration
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsColorSelectionViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsDataTypeSelectionViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsSiteSelectionViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetColorSelectionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetConfigureFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetDataTypeSelectionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/minified/StatsMinifiedWidgetConfigureFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/utils/WidgetUtils.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsColorSelectionViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsDataTypeSelectionViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsSiteSelectionViewModelTest.kt
Labels: Stats Refresh

#10111 Add Stats widget tracking
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/WidgetService.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/alltime/AllTimeWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetConfigureFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetConfigureViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/minified/MinifiedWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/minified/StatsMinifiedWidgetConfigureFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/TodayWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/utils/StatsIntentUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/utils/WidgetUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsAnalyticsUtils.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetConfigureViewModelTest.kt
Labels: Stats Refresh

#10114 Remove unnecessary launch rule
  WordPress/src/androidTest/java/org/wordpress/android/e2e/LoginTests.java
  WordPress/src/androidTest/java/org/wordpress/android/support/BaseTest.java
Labels: Testing

#10115 Issue/9815 domain suggestion header
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainSuggestionsFragment.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/domains/DomainSuggestionsViewModel.kt
  WordPress/src/main/res/layout/domain_suggestion_list_item.xml
  WordPress/src/main/res/layout/domain_suggestions_fragment.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/domains/DomainSuggestionsViewModelTest.kt
Labels: Domain Credit

#10116 Add Slack notifications to CircleCI connected tests
  .circleci/config.yml
Labels: Testing

#10118 [Analytics] Add post_type prop to editor events
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java
Labels: Analytics, Posting/Editing

#10120 Fix flakiness when entering image in publish test
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/EditorPage.java
Labels: Testing

#10121 Use a sample DSN that won't crash when used
  gradle.properties-example
Labels: Tooling

#10122 Previews and labels for Stats widgets
  RELEASE-NOTES.txt
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/TodayWidgetBlockListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/TodayWidgetListViewModel.kt
  WordPress/src/main/res/drawable-hdpi/stats_all_time_widget_preview.png
  WordPress/src/main/res/drawable-hdpi/stats_minified_widget_preview.png
  WordPress/src/main/res/drawable-hdpi/stats_today_widget_preview.png
  WordPress/src/main/res/drawable-hdpi/stats_views_widget_preview.png
  WordPress/src/main/res/drawable-mdpi/stats_all_time_widget_preview.png
  WordPress/src/main/res/drawable-mdpi/stats_minified_widget_preview.png
  WordPress/src/main/res/drawable-mdpi/stats_today_widget_preview.png
  WordPress/src/main/res/drawable-mdpi/stats_views_widget_preview.png
  WordPress/src/main/res/drawable-xhdpi/stats_all_time_widget_preview.png
  WordPress/src/main/res/drawable-xhdpi/stats_minified_widget_preview.png
  WordPress/src/main/res/drawable-xhdpi/stats_today_widget_preview.png
  WordPress/src/main/res/drawable-xhdpi/stats_views_widget_preview.png
  WordPress/src/main/res/drawable-xxhdpi/stats_all_time_widget_preview.png
  WordPress/src/main/res/drawable-xxhdpi/stats_minified_widget_preview.png
  WordPress/src/main/res/drawable-xxhdpi/stats_today_widget_preview.png
  WordPress/src/main/res/drawable-xxhdpi/stats_views_widget_preview.png
  WordPress/src/main/res/drawable-xxxhdpi/stats_all_time_widget_preview.png
  WordPress/src/main/res/drawable-xxxhdpi/stats_minified_widget_preview.png
  WordPress/src/main/res/drawable-xxxhdpi/stats_today_widget_preview.png
  WordPress/src/main/res/drawable-xxxhdpi/stats_views_widget_preview.png
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/stats_all_time_widget_info.xml
  WordPress/src/main/res/xml/stats_minified_widget_info.xml
  WordPress/src/main/res/xml/stats_today_widget_info.xml
  WordPress/src/main/res/xml/stats_views_widget_info.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/TodayWidgetBlockListViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/TodayWidgetListViewModelTest.kt
Labels: Stats Refresh

#10110 Allow alpha and beta versions to live in the same branch
  Gemfile
  Gemfile.lock
  WordPress/build.gradle
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/actions/android_codefreeze.rb
  tools/update-name-alpha-beta.sh
  tools/update-name-core.sh
  tools/update-name-release.sh
  tools/update-release-names.sh
Labels: releases

#10124 Update minified widget title
  WordPress/src/main/res/layout/stats_minified_widget_configure_activity.xml
Labels: Stats Refresh

#10101 Address AT issues after domain registration
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/RequestCodes.java
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/domains/DomainRegistrationDetailsViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/util/NoDelayCoroutineDispatcher.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/domains/DomainRegistrationDetailsViewModelTest.kt
  build.gradle
Labels: Jetpack Plugins
