Repository wordpress-mobile/WordPress-Android, pull requests merged in 2019-07, with the labels that each got.

#10125 Merge release 12.7 into develop
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/RequestCodes.java
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/domains/DomainRegistrationDetailsViewModel.kt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-bg/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-cy/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-hr/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-is/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-ms/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/util/NoDelayCoroutineDispatcher.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/domains/DomainRegistrationDetailsViewModelTest.kt
  build.gradle
Labels: releases

#10119 Add support for retrying media upload when updating post from editor
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
  WordPress/src/main/res/values/strings.xml
Labels: Posting/Editing

#10128 Merge Release/12.8 into develop.
  RELEASE-NOTES.txt
  WordPress/build.gradle
Labels: releases

#10126 Merge Release/12.7 into Master
  WordPress/build.gradle
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/RequestCodes.java
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainProductDetails.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeWebActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadServiceFacade.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/domains/DomainRegistrationDetailsViewModel.kt
  WordPress/src/main/res/layout/theme_web_activity.xml
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-bg/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-cy/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-hr/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-is/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-ms/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/util/NoDelayCoroutineDispatcher.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/domains/DomainRegistrationDetailsViewModelTest.kt
  build.gradle
Labels: releases

#10138 Fix a typo in a string
  WordPress/src/main/res/values/strings.xml
Labels: i18n

#10134 Issue/9815 email verification reminder
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationCompletedEvent.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationResultFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationStepsListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainSuggestionsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/util/DomainRegistrationUtils.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/domains/DomainRegistrationDetailsViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/domains/DomainRegistrationDetailsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/domains/DomainRegistrationMainViewModelTest.kt
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ToastUtils.java
Labels: Domain Credit, [Status] Needs Code Review

#10148 Fixed infinite loop in toast utils
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ToastUtils.java
Labels: [Pri] Blocking, [Status] Needs Code Review

#10143 Fastlane: Builds automation
  .configure
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
  tools/build-all-app-bundles.sh
  tools/build-alpha-beta-app-bundles.sh
  tools/build-app-bundle-core.sh
  tools/build-release-app-bundle.sh
Labels: Tooling

#10142 Update to targetSdkVersion 28
  WordPress/build.gradle
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginPrologueAnimationFragment.java
  build.gradle
  libs/editor/WordPressEditor/src/main/res/layout/alert_create_link.xml
  libs/editor/WordPressEditor/src/main/res/layout/dialog_image_options.xml
  libs/editor/WordPressEditor/src/main/res/layout/fragment_edit_post_content.xml
  libs/login/WordPressLoginFlow/build.gradle
  libs/login/WordPressLoginFlow/src/main/res/layout-land/login_magic_link_request_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/layout-land/login_magic_link_sent_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/layout-land/signup_bottom_sheet_dialog.xml
  libs/login/WordPressLoginFlow/src/main/res/layout-land/signup_magic_link.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_email_password_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_email_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_form_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_input_row.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_magic_link_request_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_username_password_screen.xml
Labels: Core

#10131 Use correct colors and shorten value in country map
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/BlockDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/CountryViewsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/MapLegendViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/MapViewHolder.kt
  WordPress/src/main/res/drawable/bg_rectangle_gradient_accent_50_accent.xml
  WordPress/src/main/res/layout/stats_block_map_legend_item.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/CountryViewsUseCaseTest.kt
Labels: Stats Refresh

#10144 Update strings.xml to import Aztec strings
  WordPress/src/main/res/values/strings.xml
Labels: i18n

#10153 Add local changes label to page scheduled in offline
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageItem.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListViewModel.kt
Labels: Offline Support, Pages List

#10152 Logout issue with stats
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/WidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/alltime/AllTimeWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/minified/MinifiedWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/TodayWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/utils/WidgetUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetUpdater.kt
  WordPress/src/main/res/layout/stats_widget_minified_dark.xml
  WordPress/src/main/res/layout/stats_widget_minified_light.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/values/strings.xml
Labels: Stats Refresh, [Type] Bug

#10159 Merge release/12.8 into develop
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/WidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/alltime/AllTimeWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/minified/MinifiedWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/TodayWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/utils/WidgetUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetUpdater.kt
  WordPress/src/main/res/layout/stats_widget_minified_dark.xml
  WordPress/src/main/res/layout/stats_widget_minified_light.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/values/strings.xml
Labels: releases

#10158 Merge Release/12.8 into Master
  .configure
  Gemfile.lock
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/WidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/alltime/AllTimeWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/minified/MinifiedWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/TodayWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/utils/WidgetUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetUpdater.kt
  WordPress/src/main/res/layout/stats_widget_minified_dark.xml
  WordPress/src/main/res/layout/stats_widget_minified_light.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/values/strings.xml
  fastlane/Fastfile
  fastlane/Pluginfile
  tools/build-all-app-bundles.sh
  tools/build-alpha-beta-app-bundles.sh
  tools/build-app-bundle-core.sh
  tools/build-release-app-bundle.sh
Labels: releases

#10160 Fix failing CI test
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/EditorPage.java
Labels: Testing

#10127 Fix #9561: Remove "Discard Local Changes" in the Editor and in PostPreviewActivity
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostPreviewActivity.java
  WordPress/src/main/res/layout/post_preview_activity.xml
  WordPress/src/main/res/menu/edit_post.xml
  WordPress/src/main/res/values/strings.xml
Labels: Offline Support, Posting/Editing

#10085 Issue/9728 posts remote preview
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncherWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/RequestCodes.java
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewMenuUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewUsageCategory.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostActionHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostInfoType.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListEventListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListRemotePreviewState.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUploadAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/ProgressDialogHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/ProgressDialogUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostEvents.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/wpwebview/WPWebViewViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostListMainViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/WPWebViewViewModelTest.kt
  build.gradle
Labels: Offline Support

#10130 [Analytics] Fix for editor_post_published event that is bumped multiple times on save
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Analytics

#10133 Default to Gutenberg upon opening a block based post
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/res/values/strings.xml
Labels: Gutenberg

#10173 Merge release/12.8 into develop
  WordPress/build.gradle
Labels: releases

#10179 Updated post search prompt
  WordPress/src/main/res/values/strings.xml
Labels: [Status] Needs Code Review

#10172 Rename LocalDraftUploadStarter to UploadStarter
  WordPress/src/androidTest/java/org/wordpress/android/util/UploadWorkerTest.kt
  WordPress/src/debug/java/org/wordpress/android/WordPressDebug.java
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt
  WordPress/src/main/java/org/wordpress/android/util/UploadWorker.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostListMainViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PagesViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListViewModelTest.kt
Labels: Offline Support, [Type] Enhancement

#10182 Merge release/12.8 into master
  WordPress/build.gradle
  WordPress/src/main/res/values/strings.xml
Labels: i18n, releases

#10184 Merge Release/12.8 into develop
  WordPress/src/main/res/values/strings.xml
Labels: releases

#10181 Issue/10087 domain suggestions on clear
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt
Labels: Site Creation, [Type] Enhancement

#10193 Fix #10021: auto upload local drafts with the Draft status only
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarter.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarterTest.kt
Labels: Offline Support

#10196 Merge hotfix 12.7.1 into release 12.8
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarter.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarterTest.kt
Labels: releases

#10178 Issue/only show dotblog domain suggestion for blogger plan sites
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/plans/PlansConstants.java
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/domains/DomainSuggestionsViewModel.kt
  WordPress/src/test/java/org/wordpress/android/util/SiteUtilsTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/domains/DomainSuggestionsViewModelTest.kt
  build.gradle
Labels: Domain Search, [Status] Needs Code Review

#10199 Merge release 12.7.1 into 12.8
  WordPress/build.gradle
Labels: releases

#10140 Full screen comments
  RELEASE-NOTES.txt
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/CollapseFullScreenDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/CommentFullScreenDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderCommentListActivity.java
  WordPress/src/main/res/color/accent_neutral_300_selector.xml
  WordPress/src/main/res/drawable/bg_oval_color_control_highlight_ripple_20dp.xml
  WordPress/src/main/res/drawable/ic_chevron_up_white_24dp.xml
  WordPress/src/main/res/drawable/ic_send_accent_neutral_300_24dp.xml
  WordPress/src/main/res/layout/collapse_full_screen_dialog_fragment.xml
  WordPress/src/main/res/layout/comment_dialog_fragment.xml
  WordPress/src/main/res/layout/reader_activity_comment_list.xml
  WordPress/src/main/res/layout/reader_include_comment_box.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
Labels: Comments

#10135 Issue/9815 domain registration analytics
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/domains/DomainRegistrationDetailsViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/domains/DomainRegistrationDetailsViewModelTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Domain Credit, [Status] Needs Code Review

#10136 Remove Domain Registration feature flag
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
Labels: Domain Credit, [Status] Needs Code Review

#10183 Move publish to new screen
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/HistoryListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostDatePickerDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostDatePickerDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostSettingsUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostTimePickerDialogFragment.kt
  WordPress/src/main/res/color/neutral_500_neutral_200_selector.xml
  WordPress/src/main/res/layout/edit_post_published_settings_fragment.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
Labels: Posting/Editing

#10171 Update upload media errors for published/scheduled/etc..
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Offline Support

#10204 Fix issue when media in post were sometimes uploaded with local path
  WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadHandler.java
Labels: Media, Posting/Editing

#10202 Merge Release/12.7.1 into master
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarter.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarterTest.kt
Labels: releases

#10211 Merge 12.7.1 into develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterTest.kt
Labels: releases

#10079 Issue/9560 offline featured image
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaPreviewFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaSettingsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/blocks/NoteBlock.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/FeaturedImageHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderPhotoView.java
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/segments/SiteCreationSegmentViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadHandler.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
  WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt
  WordPress/src/main/res/layout/edit_post_settings_fragment.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
Labels: Media, Offline Support, Posting/Editing

#10209 GB - Set editor preference to the remote site
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/util/WPPrefUtils.java
  build.gradle
Labels: Posting/Editing, gutenberg-mobile

#10186 Add tests to the new publish settings
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostSettingsUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/DateUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/LocaleManagerWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostSettingsUtilsTest.kt
Labels: Posting/Editing

#10213 Filter out non-jetpack self-hosted sites from widgets
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsSiteSelectionViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsSiteSelectionViewModelTest.kt
Labels: Stats Refresh

#10216 Post publish - Merge tested branch to feature branch
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostSettingsUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/DateUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/LocaleManagerWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostSettingsUtilsTest.kt
Labels: Posting/Editing

#10218 Merge release/12.8 into develop
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
Labels: releases

#10220 Merge final 12.8 into develop
  WordPress/build.gradle
Labels: releases

#10221 Merge Release/12.8 into Master
  WordPress/build.gradle
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
Labels: releases

#10222 Merge Release/12.9 into develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
  build.gradle
Labels: releases

#10190 Feature/web preview navbar
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/wpwebview/WPWebViewViewModel.kt
  WordPress/src/main/res/drawable/ic_arrow_right_white_24dp.xml
  WordPress/src/main/res/drawable/ic_devices_white_24dp.xml
  WordPress/src/main/res/drawable/web_preview_navbar_selector.xml
  WordPress/src/main/res/layout/wpwebview_activity.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/WPWebViewViewModelTest.kt
Labels: Previews, [Status] Needs Code Review, [Status] Needs Design Review

#10185 Limit Trashed Posts actions to delete and restore
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostActionHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListActionTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/util/ContextUtils.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemDataSource.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemType.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/widgets/PostListButtonType.kt
  WordPress/src/main/res/layout/post_list_item_skeleton.xml
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Offline Support

#10150 Merge login lib changes and implement new interface methods
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginAnalyticsTracker.java
  WordPress/src/main/res/values/strings.xml
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginAnalyticsListener.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginListener.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginMode.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java
  libs/login/WordPressLoginFlow/src/main/res/layout/login_email_password_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_email_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_form_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_site_address_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/values/strings.xml
  libs/login/gradle.properties-example
Labels: Login

#10198 Issue/10189 Clears old data from previous visits to wizard steps
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVM.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVMTest.kt
Labels: Site Creation

#10223 Fix failing UI tests
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/sites/rest_v2_sites_158396482_gutenberg.json
Labels: Testing

#10236 [GB] - Revert synching editor preference to the backend
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/util/WPPrefUtils.java
Labels: Posting/Editing, Site Settings

#10225 Add UI test documentation
  WordPress/src/androidTest/java/org/wordpress/android/e2e/README.md
  libs/mocks/README.md
Labels: Documentation

#10156 Feature/beta hotfix tooling
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: Tooling

#10176 Update finalize_release lane
  .bundle/config
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/actions/android_current_branch_is_hotfix.rb
  fastlane/actions/android_finalize_prechecks.rb
  fastlane/actions/android_update_metadata.rb
  fastlane/actions/android_update_metadata_source.rb
  tools/release-checks.sh
Labels: Tooling, releases

#10233 Issue/9937 all-open plugin enables annotations for open only in debug
  WordPress/build.gradle
  WordPress/src/debug/java/org/wordpress/android/testing/OpenForTesting.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt
  WordPress/src/release/java/org/wordpress/android/testing/OpenForTesting.kt
  build.gradle
Labels: [Type] Enhancement

#10243 Fixed VM context and empty field focus issue.
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt
Labels: Domain Credit, [Pri] Blocking

#10248 Merge release 12.9 into develop
  .bundle/config
  Gemfile.lock
  WordPress/build.gradle
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/full_description.txt
  WordPress/metadata/release_notes.txt
  WordPress/metadata/short_description.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/util/WPPrefUtils.java
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/actions/android_current_branch_is_hotfix.rb
  fastlane/actions/android_finalize_prechecks.rb
  fastlane/actions/android_update_metadata.rb
  fastlane/actions/android_update_metadata_source.rb
  tools/release-checks.sh
Labels: releases

#10249 Reintroduce 64 bit support
  WordPress/build.gradle
Labels: Gutenberg, Tooling

#10234 Feature/move existing actions to navbar and restyle toolbar
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
  WordPress/src/main/res/layout/wpwebview_activity.xml
  WordPress/src/main/res/menu/webview.xml
  WordPress/src/main/res/values/strings.xml
Labels: [Status] Needs Code Review

#10201 Feature/toggle between preview modes
  WordPress/src/main/java/org/wordpress/android/ui/PreviewModeMenuAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/wpwebview/WPWebViewViewModel.kt
  WordPress/src/main/res/drawable/preview_mode_indicator_background.xml
  WordPress/src/main/res/layout/preview_mode_popup_menu_item.xml
  WordPress/src/main/res/layout/wpwebview_activity.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/WPWebViewViewModelTest.kt
Labels: Previews, [Status] Needs Code Review

#10251 Add better error message for Facebook connection
  WordPress/src/main/java/org/wordpress/android/models/PublicizeService.java
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeActions.java
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeEvents.java
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListActivity.java
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Bug

#10247 Replace "GENERIC_ERROR" with "Couldn't perform operation"
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Post List

#10240 Use local post ID in HistoryList to fix TransactionTooLargeException
  WordPress/src/main/java/org/wordpress/android/ui/posts/HistoryListFragment.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/history/HistoryViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/history/HistoryViewModelTest.kt
Labels: [Type] Enhancement

#10245 Remove newPushedPost dispatch (should only exist on FluxC's side)
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListEventListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java
Labels: Offline Support, Previews

#10261 Fixes #10260: Update network_security_config.xml to allow clear text communication...
  WordPress/src/main/res/xml/network_security_config.xml
Labels: Core

#10266 Stop loading images in the content as featured images on post list
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFeaturedImageTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModelConnector.kt
Labels: Media, Post List

#10265 Fix featured image upload on self-hosted sites
  build.gradle
Labels: Offline Support, [Type] Bug

#10267 Move photon url logic from VH to VM
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostViewHolderConfig.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListViewModelTest.kt
Labels: Post List

#10255 Add realtime site address validation
  WordPress/src/main/res/values/strings.xml
  libs/login/WordPressLoginFlow/build.gradle
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressValidator.java
  libs/login/WordPressLoginFlow/src/main/res/values/strings.xml
  libs/login/WordPressLoginFlow/src/test/java/org/wordpress/android/login/LoginSiteAddressValidatorTest.java
Labels: [Type] Enhancement

#10269 Merge Release/12.9 into develop
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt
  WordPress/src/main/res/xml/network_security_config.xml
  build.gradle
Labels: releases

#10229 Publish notification dialog
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostNotificationTimeDialogFragment.kt
  WordPress/src/main/res/layout/edit_post_published_settings_fragment.xml
  WordPress/src/main/res/layout/post_notification_type_selector.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModelTest.kt
Labels: Posting/Editing

#10264 Run connected tests on CI for every PR
  .circleci/config.yml
Labels: Tooling

#10246 Add publish event to calendar
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModel.kt
  WordPress/src/main/res/layout/edit_post_published_settings_fragment.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModelTest.kt
Labels: Posting/Editing

#10271 Revert "Run connected tests on CI for every PR"
  .circleci/config.yml
Labels: Tooling

#10232 Update login library with latest changes from WCAndroid
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginListener.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java
Labels: Login

#10275 Fix/update fastlane
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
Labels: Tooling

#10250 Post scheduling tests
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PublishNotificationReceiver.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PublishNotificationReceiverViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PublishNotificationReceiverViewModelTest.kt
Labels: Posting/Editing

#10281 Issue/9538 publish post pending review
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Post List

#10274 Stats accessibility improvements 1
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/BlockDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/FourColumnsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/QuickScanItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ValueViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/ContentDescriptionHelper.kt
  WordPress/src/main/res/layout/stats_block_bar_chart_item.xml
  WordPress/src/main/res/layout/stats_block_legend_item.xml
  WordPress/src/main/res/layout/stats_loading_view.xml
  WordPress/src/main/res/layout/stats_quick_scan_item.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetListViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/ContentDescriptionHelperTest.kt
Labels: Stats Refresh

#10237 GB - Bump unsupported blocks list to Tracks
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostEditorAnalyticsSession.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragmentAbstract.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java
Labels: Analytics, Posting/Editing

#10244 Feature/allow preview mode switch for site preview and posts view only
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/JetpackConnectionWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeWebActivity.java
  WordPress/src/main/res/layout/wpwebview_activity.xml
Labels: [Status] Needs Code Review

#10277 Stats accessibility improvements 2
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostAverageViewsPerDayUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDetailMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostMonthsAndYearsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostRecentWeeksUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/AuthorsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ClicksUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/CountryViewsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/PostsAndPagesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ReferrersUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/SearchTermsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/VideoPlaysUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AnnualStatsMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/CommentsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowerTotalsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowersUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PublicizeUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TagsAndCategoriesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ExpandableItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ListItemWithIconViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/ContentDescriptionHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/ServiceMapper.kt
  WordPress/src/main/res/layout/stats_block_activity_item.xml
  WordPress/src/main/res/layout/stats_block_header_item.xml
  WordPress/src/main/res/layout/stats_block_list_item.xml
  WordPress/src/main/res/layout/stats_block_map_legend_item.xml
  WordPress/src/main/res/layout/stats_block_single_activity.xml
  WordPress/src/main/res/layout/stats_block_web_view_item.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostAverageViewsPerDayUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDetailMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostMonthsAndYearsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostRecentWeeksUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/AuthorsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ClicksUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/CountryViewsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/PostsAndPagesUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ReferrersUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/SearchTermsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/VideoPlaysUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AnnualStatsMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/CommentsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowerTotalsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowersUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PublicizeUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TagsAndCategoriesUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/ServiceMapperTest.kt
Labels: Stats Refresh

#10294 Run connected tests on CI for every PR(round 2)
  .circleci/config.yml
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/EditorPage.java
Labels: Testing

#10254 Move editor preference option to Site Settings screen
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/HelpActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostEditorAnalyticsSession.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsInterface.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java
  WordPress/src/main/res/values/key_strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/app_settings.xml
  WordPress/src/main/res/xml/site_settings.xml
  build.gradle
Labels: Gutenberg, Posting/Editing, Site Settings

#10289 Show retry when submit for review fails
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Post List, Posting/Editing, [Type] Bug

#10302 Fix NPE on login screen when tapping Help icon
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
Labels: Login, [Pri] Blocking

#10304 Revert "Run connected tests on CI for every PR(round 2)"
  .circleci/config.yml
Labels: Testing, Tooling

#10307 Merge the bumped version number
  WordPress/build.gradle
Labels: releases

#10280 Track signed in event on sign up
  WordPress/src/main/java/org/wordpress/android/modules/LoginAnalyticsModule.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginAnalyticsTracker.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/Login2FaFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginAnalyticsListener.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailPasswordFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginUsernamePasswordFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java
Labels: Signup

#10284 Post scheduling readonly
  RELEASE-NOTES.txt
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/HistoryListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostDatePickerDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostDatePickerDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostNotificationScheduleTimeDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostSettingsUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostTimePickerDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PublishNotificationReceiver.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PublishNotificationReceiverViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/DateUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/LocaleManagerWrapper.kt
  WordPress/src/main/res/color/neutral_50_neutral_20_selector.xml
  WordPress/src/main/res/layout/edit_post_published_settings_fragment.xml
  WordPress/src/main/res/layout/post_notification_type_selector.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostSettingsUtilsTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PublishNotificationReceiverViewModelTest.kt
Labels: Stats Refresh

#10272 Fixes #9122: remote preview for pages
  RELEASE-NOTES.txt
  WordPress/lint-baseline.xml
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncherWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPreviewFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostActionHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PreviewStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt
  WordPress/src/main/res/layout/edit_post_preview_fragment.xml
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostListMainViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PagesViewModelTest.kt
Labels: Offline Support, Previews

#10306 Remove usages of buggy DateTimeUtils methods
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderCommentActions.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderPostActions.java
  build.gradle
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/AppLog.java
Labels: Core, [Type] Bug

#10273 Stop recreating fragments on author filter changed
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsPagerAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModelConnector.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListViewModelTest.kt
Labels: Post List, Tech debt

#10309 Merge 13.0 into develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/metadata/release_notes.txt
Labels: releases
