Repository wordpress-mobile/WordPress-Android, pull requests merged in 2019-04, with the labels that each got.

#9480 Lowercased Block editor for core convention
  RELEASE-NOTES.txt
Labels: [Type] Bug

#9497 Prevent NPE when session tracker has not been initialized
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: [Type] Crash

#9500 Cherry picks null check commit
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: [Type] Crash

#9484 Filter posts by author
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/AuthorFilterSelection.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsPagerAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/AuthorSelectionAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/image/ImagePlaceholderManager.kt
  WordPress/src/main/java/org/wordpress/android/util/image/ImageType.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/res/drawable-ldrtl/tab_layout_gradient.xml
  WordPress/src/main/res/drawable/post_list_author_background.xml
  WordPress/src/main/res/drawable/tab_layout_gradient.xml
  WordPress/src/main/res/layout/post_list_activity.xml
  WordPress/src/main/res/layout/post_list_author_selection.xml
  WordPress/src/main/res/layout/post_list_author_selection_dropdown.xml
  WordPress/src/main/res/values/colors.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  build.gradle
Labels: Post List

#9505 Add .blog subdomain support to new site creation flow
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/NewSiteCreationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/NewSiteCreationDomainsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/NewSiteCreationDomainsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/NewSitePreviewViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/usecases/CreateSiteUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/usecases/FetchDomainsUseCase.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/NewSiteCreationDomainsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/previews/CreateSiteUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/previews/NewSitePreviewViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/usecases/FetchDomainsUseCaseTest.kt
  build.gradle
Labels: Site Creation

#9491 Feature/9182 multiple labels
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiState.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Post List, [Type] Enhancement

#9493 Issue/9286 post list error screens
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
Labels: Post List, [Type] Enhancement

#9471 Issue/update uihelpers
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/UiHelpers.kt
Labels: [Type] Enhancement

#9512 Issue/9511 fix followers crash
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModel.kt
Labels: Notifications, Stats, [Type] Crash

#9519 Merge release/12.1 into develop
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModel.kt
Labels: releases

#9514 Post list name refactoring
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiState.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/res/layout/post_list_item.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Post List

#9467 Issue/9340 Swiping Between Unread Notifications Does Not Remove Unread Badge
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailActivity.java
Labels: Notifications, [Type] Bug

#9508 Reflects ListStore Grand Refactor from FluxC for post list
  WordPress/src/main/java/org/wordpress/android/ui/PagedListDiffItemCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemDataSource.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemType.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
  build.gradle
Labels: Post List

#9523 Fixes broken Images on private sites in local preview
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPreviewFragment.java
Labels: [Type] Bug

#9524 Bring fix images private sites solution to release 12 1
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPreviewFragment.java
Labels: Posting/Editing

#9535 Aztec - Log NumberFormatException in CleaningUtils
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Aztec

#9525 Fix a minor visual issue in the reader post cards
  WordPress/src/main/res/layout/reader_cardview_post.xml
  WordPress/src/main/res/layout/reader_site_header_view.xml
  WordPress/src/main/res/values/dimens.xml
Labels: Design, Reader, [Status] Needs Code Review, [Status] Needs Design Review

#9537 Merge release/12.1 into develop
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-ms/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
Labels: releases

#9536 Issue/8475 post list skeleton
  WordPress/src/main/java/org/wordpress/android/widgets/PostListButtonType.kt
  WordPress/src/main/res/layout/post_list_item.xml
  WordPress/src/main/res/layout/post_list_item_skeleton.xml
  WordPress/src/main/res/values/dimens.xml
Labels: Post List

#9539 Hotfix: Encode frame-nonce while showing blog post previews
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
Labels: Jetpack, Post List

#9544 Fix first publish analytics
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
Labels: Analytics, Posting/Editing

#9564 Moved Fabric initialization up
  WordPress/src/main/java/org/wordpress/android/WordPress.java
Labels: Analytics

#9546 Issue/9545 primary button color
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/NewSiteCreationSiteInfoViewModel.kt
  WordPress/src/main/res/drawable/bg_rectangle_primary_radius_margin_extra_small.xml
  WordPress/src/main/res/layout/new_site_creation_domains_screen.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/styles.xml
Labels: General

#9579 Merge release/12.1 into release/12.2
  .configure
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
Labels: releases

#9578 Merge release/12.1 into develop
  .configure
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
Labels: releases

#9580 Merge release/12.2 into develop
  WordPress/metadata/release_notes.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AllTimeStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AllTimeStatsUseCaseTest.kt
Labels: releases

#9584 Fix crash in all time stats in 12 1
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AllTimeStatsUseCase.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AllTimeStatsUseCaseTest.kt
Labels: Stats Refresh, [Type] Crash

#9532 Fix padding in layer-lists on api 22
  RELEASE-NOTES.txt
  WordPress/src/main/res/drawable/bg_oval_alert_red_minus_white_16dp.xml
  WordPress/src/main/res/drawable/bg_oval_blue_medium_customize_white_40dp.xml
  WordPress/src/main/res/drawable/bg_oval_blue_wordpress_plus_white_16dp.xml
  WordPress/src/main/res/drawable/bg_oval_grey_customize_white_40dp.xml
  WordPress/src/main/res/drawable/bg_oval_grey_multiple_users_white_40dp.xml
  WordPress/src/main/res/drawable/bg_oval_grey_plans_32dp.xml
  WordPress/src/main/res/drawable/bg_oval_grey_user_32dp.xml
  WordPress/src/main/res/drawable/bg_oval_pink_500_multiple_users_white_40dp.xml
  WordPress/src/main/res/drawable/bg_rectangle_grey_lighten_20_globe_32dp.xml
  WordPress/src/main/res/drawable/bg_rectangle_grey_lighten_20_user_32dp.xml
Labels: [Type] Bug

#9592 Merge release/12.2 into develop
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: releases

#9526 Issue/long press hint
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaSettingsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
Labels: General, [Status] Needs Code Review

#9588 Post List trash/restore/delete actions
  WordPress/src/main/java/org/wordpress/android/ui/posts/CriticalPostActionTracker.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemDataSource.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemType.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
  build.gradle
Labels: Post List

#9590 Split PostListViewModel into several files
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostActionHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostConflictResolver.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListActionTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListDialogHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListEventListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFeaturedImageTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewState.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListUploadStatusTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/AuthorSelectionAdapter.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListEmptyUiState.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
Labels: Post List

#9596 Fix stats crash
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsSiteProvider.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/StatsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/StatsSiteProviderTest.kt
Labels: Stats Refresh, [Type] Crash

#9600 Post List: Move common logic to the main ViewModel
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostActionHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostConflictResolver.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListEventListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewState.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUploadAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModelConnector.kt
Labels: Post List

#9601 Redirect to username/pass login on email_login_not_allowed
  RELEASE-NOTES.txt
  WordPress/src/main/res/values/strings.xml
  build.gradle
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailPasswordFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginWpcomService.java
  libs/login/WordPressLoginFlow/src/main/res/values/strings.xml
Labels: Login

#9606 Update login subtree
  libs/login/.idea/checkstyle-idea.xml
  libs/login/.idea/codeStyles/Project.xml
  libs/login/WordPressLoginFlow/build.gradle
  libs/login/config/checkstyle.xml
  libs/login/gradle/wrapper/gradle-wrapper.properties
Labels: Login

#9597 Fix RTL in refreshed stats
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/HeaderViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/QuickScanItemViewHolder.kt
  WordPress/src/main/res/layout/stats_block_activity_item.xml
  WordPress/src/main/res/layout/stats_block_header_item.xml
  WordPress/src/main/res/layout/stats_block_referred_item.xml
  WordPress/src/main/res/layout/stats_block_tabs_item.xml
  WordPress/src/main/res/layout/stats_quick_scan_item.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostAverageViewsPerDayUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostMonthsAndYearsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostRecentWeeksUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/AuthorsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ClicksUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/CountryViewsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/PostsAndPagesUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ReferrersUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/SearchTermsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/VideoPlaysUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AllTimeStatsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/CommentsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/MostPopularInsightsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PublicizeUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TagsAndCategoriesUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TodayStatsUseCaseTest.kt
Labels: Stats Refresh

#9619 Merge Release/12.2 into develop
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsSiteProvider.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/StatsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/StatsSiteProviderTest.kt
Labels: releases

#9615 Issue/update snackbar duration
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostPreviewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/AccessibilityUtils.java
Labels: General, [Status] Needs Code Review

#9617 Minor color scheme fixes
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/widgets/PostListButtonType.kt
Labels: Post List

#9594 Replace event/observeEvent with Event wrapper for single actions
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/NavigationTarget.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/BaseListUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostAverageViewsPerDayUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostMonthsAndYearsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostRecentWeeksUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BaseStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/SelectedDateProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PublicizeUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TagsAndCategoriesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateSelector.kt
  WordPress/src/main/java/org/wordpress/android/util/LiveDataUtils.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/Event.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/StatsDateSelectorTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/PostsAndPagesUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryUseCaseTest.kt
Labels: Stats Refresh

#9620 Fix issue with snackbar being dismissed by invisible WPMainActivity
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
Labels: Post List

#9613 Post List: Move to Draft
  WordPress/src/main/java/org/wordpress/android/ui/posts/CriticalPostActionTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostActionHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListActionTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/widgets/PostListButtonType.kt
  WordPress/src/main/res/values/strings.xml
  build.gradle
Labels: Post List

#9628 Issue/9599 notifications empty flash
  WordPress/src/main/java/org/wordpress/android/ui/notifications/adapters/NotesAdapter.java
Labels: Notifications, [Status] Needs Code Review, [Type] Broken Window, [Type] Bug

#9635 Add digit to Overview and Latest post big value
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryUseCase.kt
Labels: Stats Refresh

#9633 Issue/9610 update keylines notifications
  RELEASE-NOTES.txt
  WordPress/src/main/res/layout/notifications_list_item.xml
  WordPress/src/main/res/values/dimens.xml
Labels: Notifications, [Status] Needs Code Review, [Type] Enhancement

#9634 Remove primary 500 transparent
  WordPress/src/main/res/drawable-ldrtl/tab_layout_gradient.xml
  WordPress/src/main/res/drawable/tab_layout_gradient.xml
  WordPress/src/main/res/values/colors.xml
Labels: Post List

#9583 Hide author selection filter for users who can't see posts of others
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
Labels: Post List

#9626 Update login library from subtree
  WordPress/src/main/res/values/drawables.xml
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/Login2FaFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java
  libs/login/WordPressLoginFlow/src/main/res/drawable/login_email_alert.xml
  libs/login/WordPressLoginFlow/src/main/res/layout-land/login_magic_link_sent_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/layout-land/signup_magic_link.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_magic_link_sent_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/signup_magic_link.xml
Labels: Login

#9587 Add WordPress Android version to issue template
  .github/ISSUE_TEMPLATE.md
Labels: Tooling

#9632 Fixes site icon not updating correctly after switch site
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsInterface.java
Labels: Site Settings

#9629 Fixes Twitter publicize connections
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeActions.java
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeConstants.java
Labels: Sharing

#9627 Restore user agent for WebViewActivity
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/WebViewActivity.java
Labels: [Type] Bug

#9640 Minor fixes in post list
  WordPress/src/main/java/org/wordpress/android/ui/posts/CriticalPostActionTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostActionHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListActionTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListType.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/widgets/PostListButtonType.kt
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Post List

#9643 Introduce PostFetcher - prevent duplicate requests
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostFetcher.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemDataSource.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModelConnector.kt
Labels: Post List

#9641 Show warning dialog when trashing post with local changes
  WordPress/src/main/java/org/wordpress/android/ui/posts/CriticalPostActionTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostActionHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListDialogHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/res/values/strings.xml
Labels: Post List

#9636 Annual stats block in Stats
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AnnualSiteStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtils.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AnnualSiteStatsUseCaseTest.kt
  build.gradle
Labels: Stats Refresh

#9517 Issue/add share site
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderConstants.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListActivity.java
  WordPress/src/main/res/menu/share.xml
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Reader

#9645 Improve the error message for invalid site url in login flow
  WordPress/src/main/res/values/strings.xml
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java
  libs/login/WordPressLoginFlow/src/main/res/values/strings.xml
Labels: Login

#9540 Issue/remove load drawable
  WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt
Labels: Tech debt, [Status] Needs Code Review

#9623 Issue/crash context notifications
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragmentPage.java
Labels: Notifications, [Status] Needs Code Review, [Type] Crash

#9669 Update CODESTYLE.md with checkstyle plugin and ktlint
  CODESTYLE.md
Labels: Tooling

#9654 Track tabChanged and authorFilterSelectionChanged events in post list
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Post List

#9670 Fixes an issue which can result in gaps in the Reader
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/services/post/ReaderPostLogic.java
Labels: Reader

#9672 Issue/remove objective c
  .idea/codeStyles/Project.xml
Labels: Tooling

#9673 Merge release/12.2 into develop
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-ms/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
Labels: i18n

#9683 Fix crash - revert some of the changes made in 7c5243c and 22cc80c
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
Labels: Post List

#9676 Issue/optimize illustration vectors 1
  WordPress/lint-baseline.xml
  WordPress/src/main/res/drawable/img_confetti_284dp.xml
  WordPress/src/main/res/drawable/img_giphy_100dp.xml
  WordPress/src/main/res/drawable/img_illustration_add_media_150dp.xml
  WordPress/src/main/res/drawable/img_illustration_checkmark_280dp.xml
  WordPress/src/main/res/drawable/img_illustration_email_alert_120dp.xml
  WordPress/src/main/res/drawable/img_illustration_info_outline_88dp.xml
Labels: General, [Status] Needs Code Review

#9661 Post settings / publish save issues
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Posting/Editing

#9443 Add the new StatsActivity to the locale manager
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsActivity.kt
Labels: Accessibility, Localization, [Type] Enhancement

#9680 Issue/optimize illustration vectors 5
  WordPress/src/main/res/drawable/img_illustration_site_about_182dp.xml
  WordPress/src/main/res/drawable/img_illustration_site_about_280dp.xml
  WordPress/src/main/res/drawable/img_illustration_site_error_camera_pencils_226dp.xml
  WordPress/src/main/res/drawable/img_illustration_site_website_cards_80dp.xml
Labels: General, [Status] Needs Code Review

#9679 Issue/optimize illustration vectors 4
  WordPress/lint-baseline.xml
  WordPress/src/main/res/drawable/img_illustration_notifications_152dp.xml
  WordPress/src/main/res/drawable/img_promo_editor.xml
Labels: General, [Status] Needs Code Review

#9693 Issue/site creation button
  WordPress/src/main/res/layout-land/new_site_creation_preview_screen.xml
  WordPress/src/main/res/layout/new_site_creation_preview_screen_default.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/styles.xml
Labels: Site Creation, [Status] Needs Code Review

#9706 Update checkstyle config from automattic/style-config-android
  WordPress/src/main/java/org/wordpress/android/widgets/WPDialogSnackbar.java
  WordPress/src/main/java/org/wordpress/android/widgets/WPSnackbar.java
  WordPress/src/main/java/org/wordpress/android/widgets/WPSwipeSnackbar.java
  config/checkstyle.xml
  libs/utils/.idea/checkstyle-idea.xml
  libs/utils/.idea/codeStyles/Project.xml
  libs/utils/config/checkstyle.xml
Labels: Core, Lint

#9705 Fix uploading media label not shown on post list screen
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListEventListener.kt
Labels: Post List

#9695 Back date post label
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/res/values/strings.xml
Labels: Posting/Editing

#9707 Issue/9490 post list retry status
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Post List, Posting/Editing

#9681 Issue/optimize illustration vectors 6
  WordPress/lint-baseline.xml
  WordPress/src/main/res/drawable/img_illustration_site_media_camera_pencils_80dp.xml
  WordPress/src/main/res/drawable/img_promo_stats_widget.xml
Labels: General, [Status] Needs Code Review

#9692 Issue/jetpack install tint
  WordPress/src/main/java/org/wordpress/android/ui/JetpackRemoteInstallFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/JetpackRemoteInstallViewState.kt
  WordPress/src/main/res/layout/jetpack_remote_install_fragment.xml
Labels: Jetpack, [Status] Needs Code Review

#9682 Issue/optimize illustration vectors 7
  WordPress/lint-baseline.xml
  WordPress/src/main/res/drawable/img_illustration_stats_226dp.xml
Labels: General, [Status] Needs Code Review

#9678 Issue/optimize illustration vectors 3
  WordPress/lint-baseline.xml
  WordPress/src/main/res/drawable/img_illustration_insights_94dp.xml
  WordPress/src/main/res/drawable/img_illustration_media_105dp.xml
  WordPress/src/main/res/drawable/img_illustration_posts_75dp.xml
  WordPress/src/main/res/drawable/img_illustration_site_blog_cup_80dp.xml
  WordPress/src/main/res/drawable/img_illustration_site_brush_191dp.xml
  WordPress/src/main/res/drawable/img_illustration_site_wordpress_camera_pencils_226dp.xml
Labels: General, [Status] Needs Code Review

#9677 Issue/optimize illustration vectors 2
  WordPress/lint-baseline.xml
  WordPress/src/main/res/drawable/img_illustration_empty_results_216dp.xml
  WordPress/src/main/res/drawable/img_illustration_hand_checkmark_button_124dp.xml
  WordPress/src/main/res/drawable/img_illustration_pages_104dp.xml
Labels: General, [Status] Needs Code Review

#9637 Stats Refresh: Follower totals block
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowerTotalsUseCase.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowerTotalsUseCaseTest.kt
  build.gradle
Labels: Stats Refresh

#9713 Feature/wpandroid database downgrade
  WordPress/src/debug/java/org/wordpress/android/WPWellSqlConfig.kt
  WordPress/src/debug/java/org/wordpress/android/WordPressDebug.java
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  gradle.properties-example
Labels: Core

#9716 Update success message of the Jetpack remote install flow
  WordPress/src/main/res/values/strings.xml
Labels: Jetpack

#9714 Proposal: Keep scroll position of post list on insert when necessary
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
Labels: Post List

#9721 issue/9616-reader-audio
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderWebView.java
Labels: Reader

#9719 Issue/jetpack install punctuation
  WordPress/src/main/res/values/strings.xml
Labels: Jetpack, [Status] Needs Code Review

#9711 Issue/9703 site creation background
  WordPress/src/main/res/drawable/bg_rectangle_neutral_0_radius_margin_extra_large.xml
  WordPress/src/main/res/layout/new_site_creation_domains_screen.xml
  WordPress/src/main/res/layout/new_site_creation_preview_screen_default.xml
  WordPress/src/main/res/layout/new_site_creation_preview_web_view_container.xml
  WordPress/src/main/res/layout/new_site_creation_skip_button_container.xml
Labels: Site Creation, [Type] Bug

#9657 Feature/master post filters 9184
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListViewLayoutType.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemType.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/res/drawable/ic_view_post_compact_white_24dp.xml
  WordPress/src/main/res/drawable/ic_view_post_full_white_24dp.xml
  WordPress/src/main/res/layout/post_list_item.xml
  WordPress/src/main/res/layout/post_list_item_compact.xml
  WordPress/src/main/res/menu/edit_comment.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/ids.xml
Labels: Post List, [Type] Enhancement

#9727 Localize Terms of Service URL
  WordPress/src/main/java/org/wordpress/android/Constants.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AboutActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsConnectJetpackActivity.java
  WordPress/src/main/java/org/wordpress/android/util/WPUrlUtils.java
  WordPress/src/main/res/values/strings.xml
Labels: i18n

#9735 Issue/lint baseline vectors
  WordPress/lint-baseline.xml
Labels: Tooling

#9742 Use global scope for global operation in insights management
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/management/InsightsManagementViewModel.kt
Labels: Stats Refresh

#9731 Issue/9724 post filters toggle fixes
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
Labels: Post List

#9753 Readd some entries to .gitignore
  .gitignore
Labels: Tooling

#9755 Merge release 12.3 into develop
  .configure
  .gitignore
  WordPress/build.gradle
  WordPress/lint.xml
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java
  WordPress/src/main/java/org/wordpress/android/networking/GravatarApi.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SiteCreationService.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragmentPage.java
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/CriticalPostActionTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/VideoOptimizer.java
  WordPress/src/main/java/org/wordpress/android/util/CrashLoggingUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/CrashlyticsUtils.java
  WordPress/src/main/java/org/wordpress/android/util/FluxCUtils.java
  WordPress/src/main/java/org/wordpress/android/util/HtmlToSpannedConverter.java
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  WordPress/src/main/java/org/wordpress/android/util/WPMediaUtils.java
  WordPress/src/main/java/org/wordpress/android/util/analytics/service/InstallationReferrerServiceLogic.java
  gradle.properties-example
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Tooling

#9758 Issue/9745 post list author selection fix
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewState.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/AuthorSelectionAdapter.kt
  WordPress/src/main/java/org/wordpress/android/util/image/ImagePlaceholderManager.kt
  WordPress/src/main/java/org/wordpress/android/util/image/ImageType.kt
Labels: Post List, [Type] Bug

#9756 Issue/update contributing drawables
  CONTRIBUTING.md
Labels: General

#9737 Issue/site creation search
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SearchInputWithHeader.kt
  WordPress/src/main/res/layout/new_site_creation_search_input_item.xml
  WordPress/src/main/res/values/dimens.xml
Labels: Site Creation, [Status] Needs Code Review

#9754 [GB Mobile] Disable multiple photos popup from Aztec in GB mobile
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserType.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: gutenberg-mobile

#9736 Update README.md
  README.md
Labels: [Type] Enhancement
