Repository wordpress-mobile/WordPress-Android, pull requests merged in 2019-12, with the labels that each got.

#10794 Extract and refactor EditPostActivity.onEditorEvent
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/EditorTracker.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/EditorTrackerTest.kt
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragmentAbstract.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java
Labels: Post-Logic-Improvements, Tech debt

#10798 Move purgeMediaToPostAssociationIfNotInPostAnymore to UseCase
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/AztecEditorFragmentStaticWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/CleanUpMediaToPostAssociationUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/EditorMedia.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/test/java/org/wordpress/android/CoroutinesUtils.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/media/CleanUpMediaToPostAssociationUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/media/EditorMediaTest.kt
Labels: Post-Logic-Improvements, Tech debt

#10891 EditPostActivity: Move save logic to ViewModel
  WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/PendingDraftsNotificationsUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/AztecEditorWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/AztecEditorFragmentStaticWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadServiceFacade.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/EditPostViewModelTest.kt
Labels: Posting/Editing, [Type] Enhancement

#10889 Merge 13.8 into develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/src/main/res/values/strings.xml
  build.gradle
Labels: releases

#10900 Replace lock with logging to fix deadlock when opening the editor
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/test/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/EditPostRepositoryTest.kt
Labels: Posting/Editing, [Type] Bug

#10913 Merge 13.8 release notes (and a beta release) into master
  WordPress/build.gradle
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/test/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/EditPostRepositoryTest.kt
Labels: releases

#10880 Update jQuery version from 2.1.3 to 3.4.1 in the Hybrid editor
  libs/editor/WordPressEditor/src/main/assets/android-editor.html
  libs/editor/WordPressEditor/src/main/assets/libs/jquery-2.1.3.min.js
  libs/editor/WordPressEditor/src/main/assets/libs/jquery-3.4.1.min.js
Labels: [Type] Enhancement

#10892 Allow user to change display name and password at the same time during signup
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.java
Labels: Signup

#10914 Accessibility : Edit Post ViewPager no longer announces itself
  WordPress/src/main/res/layout/new_edit_post_activity.xml
Labels: Accessibility, Aztec, [Status] Needs Code Review

#10874 Updated Aztec version to v1.3.35
  WordPress/build.gradle
  libs/editor/WordPressEditor/build.gradle
  libs/login/WordPressLoginFlow/build.gradle
Labels: Aztec, Tech debt, [Status] Not Ready for Merge

#10717 Site Creation Visual Cue for Unavailable or Invalid Domains
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainSanitizer.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/UrlUtilsWrapper.kt
  WordPress/src/main/res/layout/site_creation_domains_item.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainSanitizerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt
Labels: Site Creation, [Status] Needs Code Review, [Type] Enhancement

#10922 Accessibility : Sign Up/Login TalkBack Improvements
  WordPress/src/main/res/layout/login_signup_screen.xml
  WordPress/src/main/res/values/strings.xml
Labels: Accessibility, Login, Signup, [Status] Needs Copy Review

#10917 Accessibility : TalkBack EmptyView announcement fix
  WordPress/src/main/java/org/wordpress/android/ui/ActionableEmptyView.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
Labels: Accessibility, [Status] Needs Code Review, [Type] Bug

#10928 Bump Gutenberg progressive rollout from 10 to 30%
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
Labels: gutenberg-mobile

#10927 Update rest_v11_me_settings_post mock with the correct display and username values
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/me/rest_v11_me_settings_post.json
Labels: Testing

#10833 Fixed NPE in LoginUsernamePasswordFragment
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginUsernamePasswordFragment.java
Labels: [Type] Bug, [Type] Crash

#10954 Changing lifecycle owner to be the fragment instead of the activity.
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
Labels: Information Architecture, [Type] Crash

#10950 Use debug configuration for installable builds
  .circleci/config.yml
Labels: Tooling

#10898 Issue/10634 material pages list
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageParentActivity.kt
  WordPress/src/main/res/layout/actionable_empty_view.xml
  WordPress/src/main/res/layout/page_divider_item.xml
  WordPress/src/main/res/layout/page_empty_item.xml
  WordPress/src/main/res/layout/page_list_item.xml
  WordPress/src/main/res/layout/page_parent_list_item.xml
  WordPress/src/main/res/layout/page_parent_top_level_item.xml
  WordPress/src/main/res/layout/pages_fragment.xml
  WordPress/src/main/res/layout/pages_list_fragment.xml
  WordPress/src/main/res/layout/pages_parent_activity.xml
  WordPress/src/main/res/values-night/styles.xml
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/styles.xml
Labels: Dark Mode, Pages List, [Status] Needs Code Review

#10933 Post-Signup Interstitial: Create interstitial screen
  WordPress/src/debug/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/PostSignupInterstitialActivity.kt
  WordPress/src/main/res/drawable/img_illustration_construct_site_190dp.xml
  WordPress/src/main/res/layout-land/post_signup_interstitial_activity.xml
  WordPress/src/main/res/layout-sw600dp/post_signup_interstitial_activity.xml
  WordPress/src/main/res/layout/post_signup_interstitial_activity.xml
  WordPress/src/main/res/layout/post_signup_interstitial_default.xml
  WordPress/src/main/res/layout/post_signup_interstitial_landscape.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
Labels: Signup

#10956 Adding spent time in reader tracking
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/tracker/ReaderTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/tracker/ReaderTrackerInfo.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/DateProvider.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/ReaderTrackerTest.kt
Labels: Information Architecture, [Type] Enhancement

#10961 Fix 13.8 translations
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-eu/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
Labels: Localization, releases

#10947 Fix null siteModel when EditorMedia.start() is invoked
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Posting/Editing, [Type] Bug, [Type] Crash

#10963 Fastlane: Push current branch only, don't rely on local git configuration
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: releases

#10957 Issue/10691 primary secondary editor actions
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/EditorActionsProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/PrimaryEditorAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/SecondaryEditorAction.kt
  WordPress/src/main/java/org/wordpress/android/util/CrashLoggingUtilsWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/EditorActionsProviderTest.kt
Labels: Posting/Editing, Tech debt

#10972 Update Construct Site
  WordPress/src/main/res/drawable/img_illustration_construct_site_190dp.xml
Labels: Signup, [Status] Needs Code Review, [Type] Enhancement

#10915 Issue/10631 material post list
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewState.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/AuthorSelectionAdapter.kt
  WordPress/src/main/java/org/wordpress/android/widgets/PostListButtonType.kt
  WordPress/src/main/res/drawable-ldrtl/bg_rectangle_gradient_primary_50_transparent.xml
  WordPress/src/main/res/drawable/bg_rectangle_gradient_primary_50_transparent.xml
  WordPress/src/main/res/layout/post_list_activity.xml
  WordPress/src/main/res/layout/post_list_author_selection_dropdown.xml
  WordPress/src/main/res/layout/post_list_fragment.xml
  WordPress/src/main/res/layout/post_list_item.xml
  WordPress/src/main/res/layout/post_list_item_compact.xml
  WordPress/src/main/res/layout/post_list_item_skeleton.xml
  WordPress/src/main/res/layout/post_list_item_skeleton_compact.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/integers.xml
Labels: Dark Mode, Post List, [Status] Needs Code Review

#10991 Merge 13.9 release notes into master
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: releases

#10990 Merge 13.9 release notes (and a beta release) into develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: releases

#10916 Accessibility : Aztec Media Options TalkBack Improvements
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/stockmedia/StockMediaPickerActivity.java
  WordPress/src/main/java/org/wordpress/android/util/PhotoPickerUtils.java
  WordPress/src/main/res/layout/media_grid_item.xml
  WordPress/src/main/res/layout/media_picker_activity.xml
  WordPress/src/main/res/layout/photo_picker_thumbnail.xml
  WordPress/src/main/res/values/strings.xml
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/AccessibilityEventListener.java
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/AccessibilityUtils.java
Labels: Accessibility, Aztec, [Status] Needs Code Review, [Type] Enhancement

#10976 Post-Signup Interstitial: Display interstitial screen
  WordPress/src/androidTest/java/org/wordpress/android/e2e/SignUpTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/flows/SignupFlow.java
  WordPress/src/debug/AndroidManifest.xml
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/PostSignupInterstitialActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/SignupEpilogueActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/rest_v12_read_following_mine.json
Labels: Signup

#10942 Issue/10633 material media
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaSettingsActivity.java
  WordPress/src/main/res/drawable/button_frame.xml
  WordPress/src/main/res/layout/media_browser_activity.xml
  WordPress/src/main/res/layout/media_picker_activity.xml
  WordPress/src/main/res/layout/media_preview_activity.xml
  WordPress/src/main/res/layout/media_settings_activity.xml
  WordPress/src/main/res/values-night/styles.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/main/res/values/styles_calypso.xml
Labels: Dark Mode, [Status] Needs Code Review

#11006 Set focus on search view in site picker action bar
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
Labels: Site Picker, [Type] Enhancement

#11007 Fix confirmation message on syncing scheduled post changes
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostActionHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListDialogHelper.kt
  WordPress/src/main/res/values/strings.xml
Labels: Post List, Posting/Editing, [Status] Needs Copy Review, [Type] Bug

#11020 Fix post-signup interstitial for login with magic link
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginEpilogueActivity.java
Labels: Signup

#11014 Post-Signup Interstitial: Track interstitial screen events
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/PostSignupInterstitialActivity.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/accounts/PostSignupInterstitialViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/accounts/PostSignupInterstitialViewModelTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Signup, [Type] Enhancement

#11024 Add post-signup interstitial feature
  WordPress/src/androidTest/java/org/wordpress/android/e2e/SignUpTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/flows/SignupFlow.java
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginEpilogueActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/PostSignupInterstitialActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/SignupEpilogueActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/accounts/PostSignupInterstitialViewModel.kt
  WordPress/src/main/res/drawable/img_illustration_construct_site_190dp.xml
  WordPress/src/main/res/layout-land/post_signup_interstitial_activity.xml
  WordPress/src/main/res/layout-sw600dp/post_signup_interstitial_activity.xml
  WordPress/src/main/res/layout/post_signup_interstitial_activity.xml
  WordPress/src/main/res/layout/post_signup_interstitial_default.xml
  WordPress/src/main/res/layout/post_signup_interstitial_landscape.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/accounts/PostSignupInterstitialViewModelTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/rest_v12_read_following_mine.json
Labels: Signup

#11005 Remove (Yet! We're working on it) from the prompt
  WordPress/src/main/res/values/strings.xml
Labels: Reader, [Type] Task
