Repository wordpress-mobile/WordPress-Android, pull requests merged in 2019-05, with the labels that each got.

#9767 Fix PENDING for review posts when SUBMIT button pressed
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Posting/Editing

#9771 Add analytics to post list layout type toggle button
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Analytics, Post List

#9697 Issue/udpate author location
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/res/drawable-ldrtl/bg_rectangle_gradient_primary_500_transparent.xml
  WordPress/src/main/res/drawable-ldrtl/tab_layout_gradient.xml
  WordPress/src/main/res/drawable/bg_oval_transparent_stroke_white.xml
  WordPress/src/main/res/drawable/bg_rectangle_gradient_primary_500_transparent.xml
  WordPress/src/main/res/drawable/post_list_author_background.xml
  WordPress/src/main/res/drawable/tab_layout_gradient.xml
  WordPress/src/main/res/layout/post_list_activity.xml
  WordPress/src/main/res/layout/post_list_author_selection.xml
  WordPress/src/main/res/layout/post_list_author_selection_dropdown.xml
  WordPress/src/main/res/values/dimens.xml
Labels: Post List

#9710 Only show failure/success notifications for actions triggered from within the NotificationsProcessingService
  WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java
Labels: Comments, Notifications

#9764 Inflate post list menu item from xml instead of adding it dynamically
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/res/menu/posts_list_toggle_view_layout.xml
  WordPress/src/main/res/values/strings.xml
Labels: Post List

#9765 Add loading skeleton for compact items in posts list
  WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostListAdapter.kt
  WordPress/src/main/res/layout/post_list_item_skeleton_compact.xml
Labels: Post List

#9770 Post list view toggle fix design issues
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostViewHolderConfig.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostListAdapter.kt
  WordPress/src/main/res/layout/endlist_indicator.xml
  WordPress/src/main/res/layout/list_with_fab_endlist_indicator.xml
  WordPress/src/main/res/layout/post_list_item.xml
  WordPress/src/main/res/layout/post_list_item_compact.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
Labels: Post List

#9778 Update menu item title on post list screen to improve accessibility
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewState.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/res/menu/posts_list_toggle_view_layout.xml
  WordPress/src/main/res/values/strings.xml
Labels: Post List, [Type] Enhancement

#9776 Issue/9666 post list show real progress
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListEventListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemType.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Post List, [Type] Enhancement

#9785 Merge toggle post List item layout feature into develop
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListEventListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewState.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListViewLayoutType.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostViewHolderConfig.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemType.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/res/drawable/ic_view_post_compact_white_24dp.xml
  WordPress/src/main/res/drawable/ic_view_post_full_white_24dp.xml
  WordPress/src/main/res/layout/endlist_indicator.xml
  WordPress/src/main/res/layout/list_with_fab_endlist_indicator.xml
  WordPress/src/main/res/layout/post_list_item.xml
  WordPress/src/main/res/layout/post_list_item_compact.xml
  WordPress/src/main/res/layout/post_list_item_skeleton_compact.xml
  WordPress/src/main/res/menu/edit_comment.xml
  WordPress/src/main/res/menu/posts_list_toggle_view_layout.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/ids.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Post List

#9786 Fix empty view on post list shown for 0.1s
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListEmptyUiState.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
Labels: Post List

#9782 Fix screenshot capture issues
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/PostsListPage.java
  WordPress/src/androidTest/java/org/wordpress/android/support/WPSupportUtils.java
  WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java
  fastlane/ScreenshotFastfile
Labels: Tooling

#9694 Kotlin Lint
  WordPress/src/main/java/org/wordpress/android/models/news/LocalNewsItem.kt
  WordPress/src/main/java/org/wordpress/android/support/SupportHelper.kt
  WordPress/src/main/java/org/wordpress/android/support/ZendeskHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/ActionableEmptyView.kt
  WordPress/src/main/java/org/wordpress/android/ui/JetpackRemoteInstallViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/HelpActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/RewindStatusService.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/ActivityLogListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainNavigationView.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/blocks/GeneratedNoteBlock.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/FormattableContentClickHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/NotificationsUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/plans/PlansViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/BasicFragmentDialog.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/HistoryListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PromoDialog.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartMySitePrompts.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/NewSiteCreationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/NewSiteCreationDomainsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/NewSiteCreationDomainsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/NewSitePreviewViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/segments/NewSiteCreationSegmentsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/segments/NewSiteCreationSegmentsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/services/NewSiteCreationService.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/NewSiteCreationVerticalsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/NewSiteCreationVerticalsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/BlockDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/UiModelMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDetailMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/SelectedDateProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ClicksUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BlockListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/MapViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/TabsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/viewholders/BlockListViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/viewholders/LoadingViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/SelectedSectionManager.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/ServiceMapper.kt
  WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/SingleLiveEvent.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/SingleMediatorLiveEvent.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/history/HistoryViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/ActionPerformer.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/JetpackRemoteInstallViewModelTest.kt
Labels: Lint

#9653 Add View All screen for Annual stats
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsViewType.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/NavigationTarget.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModelFactory.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AnnualSiteStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AnnualStatsMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowersUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/SelectedSectionManager.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateSelector.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsNavigator.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AnnualSiteStatsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AnnualStatsMapperTest.kt
Labels: Stats Refresh

#9787 Fix crash in Annual site stats block
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AnnualSiteStatsUseCase.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AnnualSiteStatsUseCaseTest.kt
Labels: Stats Refresh

#9702 Fix a few ContentDescription lint errors
  WordPress/lint-baseline.xml
  libs/editor/WordPressEditor/src/main/res/layout/dialog_image_options.xml
  libs/editor/WordPressEditor/src/main/res/layout/format_bar.xml
  libs/login/WordPressLoginFlow/src/main/res/layout-land/login_magic_link_request_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_magic_link_request_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_username_password_screen.xml
Labels: Accessibility, Lint

#9688 Reduce the number of network calls in Stats
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/SelectedDateProvider.kt
  build.gradle
Labels: Performance, Stats Refresh

#9791 Fix failing tests caused by WP.com security
  WordPress/src/androidTest/java/org/wordpress/android/e2e/flows/LoginFlow.java
Labels: [Type] Bug

#9734 Update scripts to build Android App Bundles
  RELEASE-NOTES.txt
  tools/build-all-app-bundles.sh
  tools/build-alpha-beta-app-bundles.sh
  tools/build-apk-core.sh
  tools/build-app-bundle-core.sh
  tools/build-release-app-bundle.sh
  tools/install-app-bundle.sh
Labels: Tooling, [Type] Enhancement, releases

#9796 Merge release 12.3 into develop
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-cy/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-is/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-ms/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
Labels: General

#9797 Merge release 12.3 into develop
  WordPress/build.gradle
Labels: General

#9800 Merge release 12.4 into develop
  RELEASE-NOTES.txt
  WordPress/metadata/release_notes.txt
Labels: General

#9722 Fix #9562: Fix slug edition in Post Settings
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
Labels: Offline Support

#9749 Fix #9747: unescape author display names
  WordPress/src/main/java/org/wordpress/android/models/Person.java
Labels: [Type] Bug

#9759 Add link to post header and add tests
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostHeaderUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ReferredItemViewHolder.kt
  WordPress/src/main/res/layout/stats_block_referred_item.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostHeaderUseCaseTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Stats Refresh

#9761 Make current difference grey in Stats
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ValueViewHolder.kt
  WordPress/src/main/res/layout/stats_block_value_item.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCaseTest.kt
Labels: Stats Refresh

#9762 Fix #9760: Fix the empty screen in the History Revision when in airplane mode
  WordPress/src/main/java/org/wordpress/android/ui/posts/HistoryListFragment.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/history/HistoryViewModel.kt
  WordPress/src/main/res/layout/history_list_fragment.xml
  WordPress/src/main/res/values/strings.xml
Labels: Offline Support

#9757 Add missing track events to stats
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailActivity.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/StatsViewModelTest.kt
Labels: Stats Refresh

#9807 Do not crash when the annual model is empty
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AnnualSiteStatsUseCase.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AnnualSiteStatsUseCaseTest.kt
Labels: Stats Refresh, [Type] Crash

#9801 Update snackbar msg text from uploading post to uploading draft
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Post List

#9473 Issue/8829 null smart lock helper
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
Labels: Login, [Type] Bug

#9813 Merge 12.4 into develop
  WordPress/build.gradle
Labels: General

#9805 replace toast with snackbar when publishing a post while offline
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/main/res/layout/main_activity.xml
  WordPress/src/main/res/values/strings.xml
Labels: Offline Support

#9824 Track support opened and site creation service state updated
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Analytics

#9798 Add margins to post list for tablets
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListItemViewHolder.kt
  WordPress/src/main/res/layout/post_list_item.xml
  WordPress/src/main/res/layout/post_list_item_compact.xml
  WordPress/src/main/res/layout/post_list_item_skeleton.xml
  WordPress/src/main/res/layout/post_list_item_skeleton_compact.xml
  WordPress/src/main/res/values-w600dp/dimens.xml
  WordPress/src/main/res/values-w720dp/dimens.xml
  WordPress/src/main/res/values/dimens.xml
Labels: Post List

#9835 Make network mock for self hosted tests more flexible
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/self-hosted/rest_v11_sites_self-hosted.json
Labels: Tooling

#9834 Fix #9730: Improve failed media error in Aztec
  WordPress/src/main/res/values/strings.xml
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/TextDrawable.java
  libs/editor/WordPressEditor/src/main/res/values/colors.xml
  libs/editor/WordPressEditor/src/main/res/values/strings.xml
Labels: Offline Support

#9831 Fix #9826: make sure we Play Services are available before running the email hint picker.
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupEmailFragment.java
Labels: Login

#9842 Fix crash with missing view in StatsViewAllFragment
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
Labels: Stats Refresh, [Type] Crash

#9821 Make ConnectionStatusLiveData distinct
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/helpers/ConnectionStatusLiveData.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/history/HistoryViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/helpers/ConnectionStatusLiveDataTest.kt
Labels: [Type] Enhancement

#9774 Automatically upload local drafts
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListEventListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarter.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostListMainViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListViewModelTest.kt
  build.gradle
Labels: [Type] Bug

#9859 Fix #9804: Make sure we call registerPostModel even if it's already registered
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
Labels: Offline Support

#9830 Add responsible disclosure policy
  README.md
Labels: Tooling

#9794 Add links to Styles and Pull Request in README
  CODESTYLE.md
  README.md
Labels: [Type] Enhancement

#9781 Feature/adjust readme for 2fa issue
  README.md
Labels: [Type] Enhancement

#9868 Do not start Jetpack flow when leaving Connect activity
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsConnectJetpackActivity.java
Labels: Jetpack, [Type] Bug

#9836 Run connected tests nightly on Firebase Test Lab
  .circleci/.firebase.secrets.json.enc
  .circleci/config.yml
Labels: Tooling

#9882 Fix Android Test build errors caused by Gutenberg change
  WordPress/build.gradle
Labels: Gutenberg, Tooling

#9877 Update CONTRIBUTING.md based on the template
  CONTRIBUTING.md
Labels: [Type] Enhancement

#9883 Sign app for release in tools/install-app-bundle.sh
  libs/mocks/build.gradle
  tools/build-app-bundle-core.sh
  tools/gradle-functions.sh
  tools/install-app-bundle.sh
Labels: Tooling

#9867 A fix for a crash when uploading media on certain devices
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/MediaUtils.java
Labels: [Type] Crash

#9886 Merge release/12.4 into develop
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-az/strings.xml
  WordPress/src/main/res/values-bg/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-cy/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-eu/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-hi/strings.xml
  WordPress/src/main/res/values-hr/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-is/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-ms/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sr/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-th/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
Labels: General

#9793 Issue/9739 domain contact info and registration
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationResultFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationStepsListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainSuggestionsFragment.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/domains/DomainSuggestionsViewModel.kt
  WordPress/src/main/res/layout/domain_registration_details_fragment.xml
  WordPress/src/main/res/layout/domain_registration_result_fragment.xml
  WordPress/src/main/res/layout/domain_suggestions_fragment.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  build.gradle
Labels: [Status] Needs Design Review, [Status] Not Ready for Review

#9662 Fix animation on lowering Card height in stats list
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/BlockDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsBlockAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsBlockDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/viewholders/BlockListViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/WrappingLinearLayoutManager.kt
Labels: Stats Refresh

#9878 Make README.md build instructions more specific
  README.md
Labels: Documentation

#9862 Add connection pool that doesn't keep failed sockets
  WordPress/src/main/java/org/wordpress/android/networking/GravatarApi.java
Labels: [Type] Crash

#9857 Treat response.pagination field as nullable
  WordPress/src/main/java/org/wordpress/android/viewmodel/giphy/GiphyPickerDataSource.kt
Labels: [Type] Crash

#9869 LocalDraftUploadStarter: Upload from anywhere
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/modules/ThreadModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarter.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadServiceFacade.kt
  WordPress/src/main/java/org/wordpress/android/util/LiveDataUtils.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostListMainViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarterTest.kt
  WordPress/src/test/java/org/wordpress/android/util/LiveDataUtilsTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListViewModelTest.kt
Labels: Offline Support, [Type] Enhancement

#9891 Update Glide version to 4.9.0
  WordPress/build.gradle
  libs/login/WordPressLoginFlow/build.gradle
Labels: Tech debt

#9890 Update dagger version to v2.22.1
  WordPress/src/main/java/org/wordpress/android/ui/prefs/ReleaseNotesActivity.java
  build.gradle
  libs/login/WordPressLoginFlow/build.gradle
Labels: Tech debt

#9896 Update highlight color in quick start's Snackbar
  WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt
Labels: [Type] Enhancement

#9901 Fix editor_opened missing events on Activity restart
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
Labels: Analytics

#9910 Bump post created analytics only once
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Analytics, Posting/Editing, [Type] Bug

#9903 Stats Views widget setup
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsViewsWidget.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsViewsWidgetConfigureActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsViewsWidgetConfigureFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsListProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsWidgetViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/WidgetService.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/Event.kt
  WordPress/src/main/res/layout/stats_views_widget_configure_activity.xml
  WordPress/src/main/res/layout/stats_views_widget_configure_fragment.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/stats_views_widget_info.xml
Labels: Stats Refresh

#9911 Fix - static keyword removed from PostStore.getNumLocalChanges()
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java
  build.gradle
Labels: Tech debt

#9925 Fix for editor analytics session_end undercounted
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Analytics, Posting/Editing, [Type] Bug

#9795 Add additional publish flow test
  WordPress/build.gradle
  WordPress/src/androidTest/java/org/wordpress/android/e2e/EditorTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/EditorPage.java
  WordPress/src/androidTest/java/org/wordpress/android/support/WPSupportUtils.java
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/posts/rest_v11_sites_158396482_posts_5.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/posts/rest_v12_sites_id_posts_new.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/sites/rest_v11_sites_158396482_categories.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/sites/rest_v11_sites_158396482_taxonomies_category_terms.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/sites/rest_v11_sites_158396482_taxonomies_post_tag_terms.json
Labels: Testing

#9902 LocalDraftUploadStarter: Upload local draft pages
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarter.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarterTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PagesViewModelTest.kt
  build.gradle
Labels: Offline Support, [Type] Enhancement

#9930 Unregister connection broadcast receiver when app in background
  WordPress/src/main/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarter.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarterTest.kt
Labels: Offline Support, [Type] Bug

#9931 Remove classes and resources related to the old site creation flow
  WordPress/build.gradle
  WordPress/lint-baseline.xml
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/AbstractFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/HelpActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/NewBlogActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/SiteCreationActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SiteCreationBaseFormFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SiteCreationCategoryFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SiteCreationCreatingFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SiteCreationDomainAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SiteCreationDomainFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SiteCreationDomainLoaderFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SiteCreationListener.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SiteCreationService.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SiteCreationSiteDetailsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SiteCreationThemeAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SiteCreationThemeFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SiteCreationThemeLoaderFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/NewSiteCreationPreviewFragment.kt
  WordPress/src/main/res/drawable/ic_aside_white_24dp.xml
  WordPress/src/main/res/drawable/ic_search_neutral_24dp.xml
  WordPress/src/main/res/drawable/img_illustration_site_blog_cup_80dp.xml
  WordPress/src/main/res/drawable/img_illustration_site_error_camera_pencils_226dp.xml
  WordPress/src/main/res/drawable/img_illustration_site_media_camera_pencils_80dp.xml
  WordPress/src/main/res/drawable/img_illustration_site_website_cards_80dp.xml
  WordPress/src/main/res/layout/new_blog_activity.xml
  WordPress/src/main/res/layout/new_site_creation_search_input_item.xml
  WordPress/src/main/res/layout/site_creation_activity.xml
  WordPress/src/main/res/layout/site_creation_category_screen.xml
  WordPress/src/main/res/layout/site_creation_creating_screen.xml
  WordPress/src/main/res/layout/site_creation_domain_header.xml
  WordPress/src/main/res/layout/site_creation_domain_input.xml
  WordPress/src/main/res/layout/site_creation_domain_item.xml
  WordPress/src/main/res/layout/site_creation_domain_screen.xml
  WordPress/src/main/res/layout/site_creation_site_details_screen.xml
  WordPress/src/main/res/layout/site_creation_theme_header.xml
  WordPress/src/main/res/layout/site_creation_theme_item.xml
  WordPress/src/main/res/layout/site_creation_theme_screen.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Tech debt

#9936 Refactor and add additional tests to PagesViewModelTest
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PagesViewModelTest.kt
Labels: [Type] Enhancement

#9948 Remove mokneys python scripts
  .gitignore
  WordPress/src/androidTest/monkeys/README.md
  WordPress/src/androidTest/monkeys/create_wpcom_blog_from_settings.py
  WordPress/src/androidTest/monkeys/customizable_monkey.py
  WordPress/src/androidTest/monkeys/playstore-screenshots.py
  WordPress/src/androidTest/monkeys/settings.py-example
Labels: Tech debt

#9940 Issue/9920 editPostActivity.mOriginalPost investigation and fixes
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
Labels: Posting/Editing

#9909 Issue/9847 use workmanager to postpone uploadstarter run
  WordPress/build.gradle
  WordPress/src/androidTest/java/org/wordpress/android/util/UploadWorkerTest.kt
  WordPress/src/debug/AndroidManifest.xml
  WordPress/src/debug/java/org/wordpress/android/WordPressDebug.java
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarter.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/main/java/org/wordpress/android/util/UploadWorker.kt
  build.gradle
Labels: Offline Support

#9945 Automatically update Page List if an upload is completed in the background
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostEvents.java
  WordPress/src/main/java/org/wordpress/android/util/EventBusWrapper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PagesViewModelTest.kt
Labels: Pages List, [Type] Bug

#9894 Add news card to insights
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/BlockDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ManagementControlUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ManagementNewsCardUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BigTitleViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/DialogButtonsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ImageItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/TagViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/TextViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/ItemPopupMenuHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/NewsCardHandler.kt
  WordPress/src/main/java/org/wordpress/android/util/LiveDataUtils.kt
  WordPress/src/main/res/drawable-hdpi/insights_management_feature_image.png
  WordPress/src/main/res/drawable-hdpi/insights_management_feature_image_tab.png
  WordPress/src/main/res/drawable-mdpi/insights_management_feature_image.png
  WordPress/src/main/res/drawable-mdpi/insights_management_feature_image_tab.png
  WordPress/src/main/res/drawable-xhdpi/insights_management_feature_image.png
  WordPress/src/main/res/drawable-xhdpi/insights_management_feature_image_tab.png
  WordPress/src/main/res/drawable-xxhdpi/insights_management_feature_image.png
  WordPress/src/main/res/drawable-xxhdpi/insights_management_feature_image_tab.png
  WordPress/src/main/res/drawable-xxxhdpi/insights_management_feature_image.png
  WordPress/src/main/res/drawable-xxxhdpi/insights_management_feature_image_tab.png
  WordPress/src/main/res/drawable/bg_rectangle_red_500_radius_2dp.xml
  WordPress/src/main/res/layout/stats_block_big_title_item.xml
  WordPress/src/main/res/layout/stats_block_dialog_buttons_item.xml
  WordPress/src/main/res/layout/stats_block_image_item.xml
  WordPress/src/main/res/layout/stats_block_tag_item.xml
  WordPress/src/main/res/values-sw600dp-land/drawables.xml
  WordPress/src/main/res/values/drawables.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/StatsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ManagementNewsCardUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/NewsCardHandlerTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Stats Refresh

#9893 Refactor insights management control card
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/BlockDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/BaseListUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsBlock.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsBlockAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsBlockDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/UiModelMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ManagementControlUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ManagementNewsCardUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BigTitleViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/DialogButtonsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ImageItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/TagViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/TextViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/viewholders/BaseStatsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/viewholders/ControlViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/ItemPopupMenuHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/NewsCardHandler.kt
  WordPress/src/main/java/org/wordpress/android/util/LiveDataUtils.kt
  WordPress/src/main/res/drawable-hdpi/insights_management_feature_image.png
  WordPress/src/main/res/drawable-hdpi/insights_management_feature_image_tab.png
  WordPress/src/main/res/drawable-mdpi/insights_management_feature_image.png
  WordPress/src/main/res/drawable-mdpi/insights_management_feature_image_tab.png
  WordPress/src/main/res/drawable-xhdpi/insights_management_feature_image.png
  WordPress/src/main/res/drawable-xhdpi/insights_management_feature_image_tab.png
  WordPress/src/main/res/drawable-xxhdpi/insights_management_feature_image.png
  WordPress/src/main/res/drawable-xxhdpi/insights_management_feature_image_tab.png
  WordPress/src/main/res/drawable-xxxhdpi/insights_management_feature_image.png
  WordPress/src/main/res/drawable-xxxhdpi/insights_management_feature_image_tab.png
  WordPress/src/main/res/drawable/bg_rectangle_red_500_radius_2dp.xml
  WordPress/src/main/res/layout/stats_block_big_title_item.xml
  WordPress/src/main/res/layout/stats_block_dialog_buttons_item.xml
  WordPress/src/main/res/layout/stats_block_image_item.xml
  WordPress/src/main/res/layout/stats_block_link_button_item.xml
  WordPress/src/main/res/layout/stats_block_tag_item.xml
  WordPress/src/main/res/values-sw600dp-land/drawables.xml
  WordPress/src/main/res/values/drawables.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/StatsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/UiModelMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ManagementNewsCardUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/NewsCardHandlerTest.kt
  build.gradle
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Stats Refresh

#9929 Stats Widget - add site selector
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsViewsWidgetConfigureFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsWidgetSiteAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsWidgetSiteSelectionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/StatsWidgetSiteViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsWidgetViewModel.kt
  WordPress/src/main/res/layout/stats_widget_site_selector.xml
  WordPress/src/main/res/layout/stats_widget_site_selector_item.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/ViewsWidgetViewModelTest.kt
Labels: Stats Refresh

#9962 AutoUpload only publishable local drafts
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarter.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/LocalDraftUploadStarterTest.kt
Labels: Offline Support

#9965 Update README.md
  README.md
Labels: Documentation
