Repository wordpress-mobile/WordPress-Android, pull requests merged in 2019-03, with the labels that each got.

#9302 View more Posts & pages
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/GranularUseCaseFactory.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/AuthorsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ClicksUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/CountryViewsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/PostsAndPagesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ReferrersUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/SearchTermsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/VideoPlaysUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/CommentsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowersUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TagsAndCategoriesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsNavigator.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/PostsAndPagesUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/CommentsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowersUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TagsAndCategoriesUseCaseTest.kt
  build.gradle
Labels: Stats Refresh

#9351 Remove one layer from the View All screens
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/BaseListUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListViewModel.kt
  WordPress/src/main/res/layout-w528dp/stats_list_fragment.xml
  WordPress/src/main/res/layout-w720dp/stats_list_fragment.xml
  WordPress/src/main/res/layout/stats_list_fragment.xml
  WordPress/src/main/res/layout/stats_view_all_fragment.xml
  WordPress/src/main/res/values-w528dp/stats_styles.xml
  WordPress/src/main/res/values-w720dp/stats_styles.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowersUseCaseTest.kt
Labels: Stats Refresh

#9328 Issue/add color utilities
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaSettingsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderMenuAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderFollowButton.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsInsightsLatestPostSummaryFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsInsightsTodayFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsSingleItemDetailsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsUIHelper.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsVisitorsAndViewsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/LinkViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/util/ColorUtils.kt
  WordPress/src/main/java/org/wordpress/android/widgets/PostListButton.java
Labels: General, [Status] Needs Code Review

#9360 Remove negative infinity when item drops to zero
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewMapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewMapperTest.kt
Labels: Stats Refresh

#9254 Feature/prompt for review
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/widgets/AppRatingDialog.kt
  WordPress/src/main/res/values/strings.xml
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Status] Needs Code Review

#9363 Merge release/11.9 into develop
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
Labels: Tooling

#9357 Run Gradle build scan on CI builds
  build.gradle
Labels: Tooling

#9355 Issue/9349 update notifications tabs (Part 1)
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java
  WordPress/src/main/res/color/calypso_segmented_control_text.xml
  WordPress/src/main/res/drawable-ldrtl/calypso_segmented_control_button_end.xml
  WordPress/src/main/res/drawable-ldrtl/calypso_segmented_control_button_start.xml
  WordPress/src/main/res/drawable/calypso_segmented_control_background.xml
  WordPress/src/main/res/drawable/calypso_segmented_control_button.xml
  WordPress/src/main/res/drawable/calypso_segmented_control_button_end.xml
  WordPress/src/main/res/drawable/calypso_segmented_control_button_start.xml
  WordPress/src/main/res/drawable/calypso_segmented_control_normal.xml
  WordPress/src/main/res/drawable/calypso_segmented_control_normal_start.xml
  WordPress/src/main/res/drawable/calypso_segmented_control_selected.xml
  WordPress/src/main/res/drawable/calypso_segmented_control_selected_end.xml
  WordPress/src/main/res/drawable/calypso_segmented_control_selected_start.xml
  WordPress/src/main/res/layout/notifications_fragment_notes_list.xml
  WordPress/src/main/res/values/styles_calypso.xml
Labels: Notifications, [Status] Needs Code Review, [Type] Enhancement

#9353 Fix loading when site model is incomplete
  WordPress/src/main/java/org/wordpress/android/ui/JetpackConnectionResultActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/BaseListUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BaseStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/GranularStatefulUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/GranularStatelessUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/AuthorsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ClicksUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/CountryViewsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/PostsAndPagesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ReferrersUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/SearchTermsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/VideoPlaysUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AllTimeStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/CommentsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowersUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/MostPopularInsightsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PostingActivityUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PublicizeUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TagsAndCategoriesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TodayStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsSiteProvider.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/StatsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/BaseListUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/BaseStatsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/AuthorsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ClicksUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/CountryViewsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/PostsAndPagesUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ReferrersUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/SearchTermsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/VideoPlaysUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AllTimeStatsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/CommentsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowersUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/MostPopularInsightsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PublicizeUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TagsAndCategoriesUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TodayStatsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/StatsSiteProviderTest.kt
Labels: Stats Refresh

#9364 Add Violations plugin to comment on lint violations on CI
  .circleci/config.yml
  WordPress/build.gradle
  build.gradle
Labels: Tooling

#9372 Stalebot: Don't auto-close stale issues
  .github/stale.yml
Labels: Tooling

#9373 Revert "Code freeze: Don't add branch protection to individual release branches
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: Tooling

#9374 Removed Travis CI config
  .travis.yml
Labels: Tooling

#9376 Pull 'login' and 'utils' subtrees with new CI configs
  libs/login/.circleci/config.yml
  libs/login/.travis.yml
  libs/utils/.circleci/config.yml
  libs/utils/.travis.yml
Labels: Tooling

#9322 Make new Posts status `draft` by default
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/res/values/strings.xml
Labels: Posting/Editing

#9359 View all Referrers screen
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModelFactory.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ReferrersUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsNavigator.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ReferrersUseCaseTest.kt
  build.gradle
Labels: Stats Refresh

#9358 Infinite scrolling in stats view all
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/BlockDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowersUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/LoadingItemViewHolder.kt
  WordPress/src/main/res/layout/stats_block_loading_item.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowersUseCaseTest.kt
Labels: Stats Refresh

#9381 Take 2: Pull 'login' and 'utils' subtrees with new CI configs
  libs/login/.circleci/config.yml
  libs/login/.travis.yml
  libs/utils/.circleci/config.yml
  libs/utils/.travis.yml
Labels: Tooling

#9391 Merge release/11.9 into develop: Update .configure
  .configure
Labels: Tooling

#9394 Merge release/12.0 into develop
  RELEASE-NOTES.txt
  WordPress/metadata/release_notes.txt
Labels: releases

#9386 Update to new FluxC interceptor usage for Stetho
  WordPress/src/debug/java/org/wordpress/android/modules/InterceptorModule.java
  build.gradle
Labels: Core, Testing

#9399 Fix formatting in stalebot message
  .github/stale.yml
Labels: Tooling

#9383 Post detail activity setup
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/BaseListUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/DetailListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/SelectedDateProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/SelectedSectionManager.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsNavigator.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsPostProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsSiteProvider.kt
  WordPress/src/main/res/layout/stats_detail_activity.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/StatsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/BaseListUseCaseTest.kt
Labels: Stats Refresh

#9375 View all Clicks screen
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModelFactory.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ClicksUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsNavigator.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ClicksUseCaseTest.kt
  build.gradle
Labels: Stats Refresh

#9395 Date selector component
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModelFactory.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/BaseListUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/DaysListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/MonthsListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/SelectedDateProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/WeeksListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/YearsListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/InsightsListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateSelector.kt
  WordPress/src/main/java/org/wordpress/android/util/LiveDataUtils.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/StatsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/BaseListUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/StatsDateSelectorTest.kt
Labels: Stats Refresh

#9392 build-apk-core.sh: Only print logs on error
  tools/build-apk-core.sh
Labels: Tooling

#9301 Feature/9225 post list target post
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsPagerAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/res/values/strings.xml
Labels: Post List, [Status] Not Ready for Review

#9409 Update FluxC hash which updates sites/new endpoint to v1.1
  build.gradle
Labels: Site Creation

#9413 Add the remaining view all screens
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModelFactory.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/AuthorsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ClicksUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/CountryViewsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ReferrersUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/SearchTermsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/VideoPlaysUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PublicizeUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsNavigator.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/AuthorsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/CountryViewsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/SearchTermsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/VideoPlaysUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PublicizeUseCaseTest.kt
  build.gradle
Labels: Stats Refresh

#9361 Add UI tests for critical login flows
  WordPress/src/androidTest/java/org/wordpress/android/e2e/EditorTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/LoginTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/flows/LoginFlow.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/MePage.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/MySitesPage.java
  WordPress/src/androidTest/java/org/wordpress/android/support/BaseTest.java
  WordPress/src/androidTest/java/org/wordpress/android/support/WPSupportUtils.java
  WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java
  gradle.properties-example
Labels: Testing, [Status] Needs Code Review

#9417 Fix NPE when the view is gone when we want to change the elevation
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
Labels: Stats Refresh, [Type] Crash

#9414 Add post header use case for detail screen
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/BlockDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostHeaderUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ReferredItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsNavigator.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsPostProvider.kt
  WordPress/src/main/res/layout/stats_block_referred_item.xml
  WordPress/src/main/res/layout/stats_detail_fragment.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/values/strings.xml
  build.gradle
Labels: Stats Refresh

#9405 Add post overview block to stats detail screen
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/BlockDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/NavigationTarget.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/UiModelMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/DetailListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostHeaderUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BaseStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/SelectedDateProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/AuthorsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/PostsAndPagesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ReferredItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateSelector.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsNavigator.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsPostProvider.kt
  WordPress/src/main/java/org/wordpress/android/util/LiveDataUtils.kt
  WordPress/src/main/res/layout/stats_block_referred_item.xml
  WordPress/src/main/res/layout/stats_detail_activity.xml
  WordPress/src/main/res/layout/stats_detail_fragment.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/StatsDateSelectorTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryUseCaseTest.kt
  build.gradle
Labels: Stats Refresh

#9411 Issue/notifications settings feeds
  WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsFragment.java
Labels: Notifications, [Status] Needs Code Review, [Type] Bug

#9419 Initialize AppRatingDialog inside application class.
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
Labels: [Pri] High, [Type] Crash

#9418 Issue/notifications jetpack web
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsConnectJetpackActivity.java
Labels: Jetpack, Notifications, [Status] Needs Code Review, [Type] Bug

#9428 Issue/remove revisions flag
  WordPress/build.gradle
Labels: General, [Status] Needs Code Review

#9412 Add post yearly totals block
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsViewType.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/NavigationTarget.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModelFactory.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/DetailListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostMonthsAndYearsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsNavigator.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostMonthsAndYearsUseCaseTest.kt
Labels: Stats Refresh

#9427 Remove shared image information once it's been inserted in the Post
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Media, Posting/Editing, Sharing, [Type] Bug

#9423 Fix media upload error notifications & local Urls on Aztec
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadReadyProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
Labels: Media, Posting/Editing, [Pri] High, [Type] Bug

#9435 Design improvements to stats detail
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostAverageViewsPerDayUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDetailMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostMonthsAndYearsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostRecentWeeksUseCase.kt
  WordPress/src/main/res/layout/stats_block_referred_item.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostAverageViewsPerDayUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDetailMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostMonthsAndYearsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostRecentWeeksUseCaseTest.kt
Labels: Stats Refresh

#9438 Issue/post list snackbars
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
Labels: Post List, [Status] Needs Code Review

#9439 Fix metadata strings
  WordPress/metadata/PlayStoreStrings.po
Labels: i18n

#9440 Merge 12.0 into master
  RELEASE-NOTES.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadReadyProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
Labels: releases

#9406 Add cache to Insights
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BaseStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/CommentsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowersUseCase.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/BaseStatsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/AuthorsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ClicksUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/CountryViewsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/PostsAndPagesUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ReferrersUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/SearchTermsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/VideoPlaysUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AllTimeStatsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/CommentsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowersUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/MostPopularInsightsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PublicizeUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TagsAndCategoriesUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TodayStatsUseCaseTest.kt
  build.gradle
Labels: Stats Refresh

#9450 Merge release/12.0 into develop
  RELEASE-NOTES.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadReadyProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
Labels: releases

#9398 CircleCI: Update Orb to latest
  .circleci/config.yml
Labels: Tooling

#9421 Issue/9349 update notifications tabs (Part 2)
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragmentPage.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/adapters/NotesAdapter.java
  WordPress/src/main/res/drawable/bg_rectangle_rounded_primary_dark_ripple_primary_50.xml
  WordPress/src/main/res/drawable/notifications_new_notification_bar_background.xml
  WordPress/src/main/res/layout/notifications_list_fragment.xml
  WordPress/src/main/res/layout/notifications_list_fragment_page.xml
  WordPress/src/main/res/values/colors.xml
Labels: Notifications, [Status] Needs Code Review, [Type] Enhancement

#9444 Don’t try to turn off real devices for screenshots
  fastlane/helpers/android_virtual_device_helper.rb
Labels: [Type] Bug

#9449 Post stats detail readonly merge to develop
  RELEASE-NOTES.txt
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsViewType.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/BlockDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/NavigationTarget.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModelFactory.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/UiModelMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/DetailListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostAverageViewsPerDayUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDetailMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostHeaderUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostMonthsAndYearsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostRecentWeeksUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BaseStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/SelectedDateProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/AuthorsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/PostsAndPagesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ReferredItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/SelectedSectionManager.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateFormatter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateSelector.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsNavigator.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsPostProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsSiteProvider.kt
  WordPress/src/main/java/org/wordpress/android/util/LiveDataUtils.kt
  WordPress/src/main/res/layout/stats_block_referred_item.xml
  WordPress/src/main/res/layout/stats_detail_activity.xml
  WordPress/src/main/res/layout/stats_detail_fragment.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/StatsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/StatsDateSelectorTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostAverageViewsPerDayUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDetailMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostMonthsAndYearsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostRecentWeeksUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryUseCaseTest.kt
  build.gradle
Labels: Stats Refresh

#9454 Update CONTRIBUTING internal link
  CONTRIBUTING.md
Labels: General

#9455 Update the block spacing in Stats
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListFragment.kt
  WordPress/src/main/res/values/dimens.xml
Labels: Stats Refresh

#9425 Issue/9424 add domain registration feature flag
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginUtils.java
Labels: [Status] Needs Code Review

#9430 Refactor PostListButton type to enum
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostAdapterItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/widgets/PostListButton.java
  WordPress/src/main/java/org/wordpress/android/widgets/PostListButton.kt
  WordPress/src/main/java/org/wordpress/android/widgets/PostListButtonType.kt
  WordPress/src/main/res/values/attrs.xml
Labels: Post List, [Type] Enhancement

#9453 Insights redesign
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/BlockDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AllTimeStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/MostPopularInsightsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TodayStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/QuickScanItemViewHolder.kt
  WordPress/src/main/res/drawable/ic_time_white_24dp.xml
  WordPress/src/main/res/layout/stats_quick_scan_item.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AllTimeStatsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/MostPopularInsightsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TodayStatsUseCaseTest.kt
Labels: Stats Refresh

#9456 Issue/9447 stats page spacing
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
Labels: Stats Refresh, [Type] Enhancement

#9410 Site Creation Iteration 1.1
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/NewSiteCreationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/NewSiteCreationDomainViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/NewSiteCreationDomainsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/NewSiteCreationDomainsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SearchInputWithHeader.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SiteCreationSearchInputUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/NewSiteCreationPreviewFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/segments/NewSiteCreationSegmentsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/siteinfo/NewSiteCreationSiteInfoFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/NewSiteCreationSiteInfoViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/NewSiteCreationVerticalsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/NewSiteCreationVerticalsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/NewSiteCreationVerticalsViewModel.kt
  WordPress/src/main/res/layout-land/new_site_creation_preview_screen.xml
  WordPress/src/main/res/layout/new_site_creation_domains_item.xml
  WordPress/src/main/res/layout/new_site_creation_domains_screen.xml
  WordPress/src/main/res/layout/new_site_creation_header_item.xml
  WordPress/src/main/res/layout/new_site_creation_preview_header_item.xml
  WordPress/src/main/res/layout/new_site_creation_preview_screen_default.xml
  WordPress/src/main/res/layout/new_site_creation_search_input_item.xml
  WordPress/src/main/res/layout/new_site_creation_site_info_screen.xml
  WordPress/src/main/res/layout/new_site_creation_verticals_custom_suggestion_item.xml
  WordPress/src/main/res/layout/new_site_creation_verticals_screen.xml
  WordPress/src/main/res/layout/new_site_creation_verticals_suggestion_item.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/NewSiteCreationDomainsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/siteinfo/NewSiteCreationSiteInfoViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/verticals/NewSiteCreationVerticalsViewModelTest.kt
Labels: Site Creation, [Status] Needs Design Review

#9431 Feature/9182 post filters rows ui
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostAdapterItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostViewHolderConfig.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiState.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUploadStatus.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/widgets/PostListButtonType.kt
  WordPress/src/main/res/drawable/ic_cloud_upload_white_24dp.xml
  WordPress/src/main/res/layout/post_cardview.xml
  WordPress/src/main/res/layout/post_list_button.xml
  WordPress/src/main/res/layout/post_list_fragment.xml
  WordPress/src/main/res/layout/post_list_item.xml
  WordPress/src/main/res/layout/post_list_item_skeleton.xml
  WordPress/src/main/res/values-sw600dp/dimens.xml
  WordPress/src/main/res/values-sw720dp/dimens.xml
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Post List

#9047 Move insights up and down in the list
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/BaseListUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsBlockDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AllTimeStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/CommentsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowersUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/MostPopularInsightsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PostingActivityUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PublicizeUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TagsAndCategoriesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TodayStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/TitleViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/ItemPopupMenuHandler.kt
  WordPress/src/main/java/org/wordpress/android/util/LiveDataUtils.kt
  WordPress/src/main/res/drawable/ic_arrow_down_grey_dark_24dp.xml
  WordPress/src/main/res/drawable/ic_arrow_up_grey_dark_24dp.xml
  WordPress/src/main/res/drawable/ic_ellipsis_vertical_grey_darken_48dp.xml
  WordPress/src/main/res/drawable/ic_trash_grey_dark_24dp.xml
  WordPress/src/main/res/layout/stats_block_title_item.xml
  WordPress/src/main/res/layout/stats_list_fragment.xml
  WordPress/src/main/res/menu/menu_stats_item.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AllTimeStatsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/CommentsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowersUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/MostPopularInsightsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PublicizeUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TagsAndCategoriesUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TodayStatsUseCaseTest.kt
  build.gradle
Labels: Stats Refresh

#9463 Insights Management screen
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/NavigationTarget.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListItemDecoration.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/management/InsightsManagementActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/management/InsightsManagementFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/management/InsightsManagementViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsNavigator.kt
  WordPress/src/main/res/layout/insights_management_activity.xml
  WordPress/src/main/res/layout/insights_management_fragment.xml
  WordPress/src/main/res/layout/stats_empty_view.xml
  WordPress/src/main/res/menu/menu_stats_insights.xml
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  WordPress/src/main/res/values/strings.xml
Labels: Stats Refresh

#9462 Fix for lag when saving long posts in GB-HTML editor
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragmentAbstract.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/LegacyEditorFragment.java
  libs/editor/WordPressEditor/src/main/res/values/strings.xml
Labels: gutenberg-mobile

#9469 Update translations for 12.0 release
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
Labels: releases

#9472 Fix crash in stats detail
  build.gradle
Labels: Stats Refresh, [Type] Crash

#9474 Merge release/12.1 into develop
  RELEASE-NOTES.txt
  WordPress/metadata/release_notes.txt
  build.gradle
Labels: releases

#9475 Merge release/12.0 into develop
  .configure
Labels: releases

#9466 Issue/6836 enable back dating drafts
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostDatePickerDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/res/values/strings.xml
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ToastUtils.java
Labels: Posting/Editing

#9476 Merge Release/12.1 into develop
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostDatePickerDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/res/values/strings.xml
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/ToastUtils.java
Labels: releases

#9477 Merge Release/12.0 into master
  .configure
  WordPress/build.gradle
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
Labels: Tooling

#9362 edit comments in wordpress.java, WordPressDB.java and JobServiceId.java
  WordPress/src/main/java/org/wordpress/android/JobServiceId.java
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/WordPressDB.java
Labels: [Type] Enhancement

#9458 Issue/9426 domain registration prompt
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginDetailActivity.java
  WordPress/src/main/res/values/strings.xml
Labels: [Status] Needs Code Review

#9485 Issue/update uihelpers v2
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/detail/ActivityLogDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/NewSiteCreationPreviewFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/segments/NewSiteCreationSegmentsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/NewSiteCreationVerticalsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/UiHelpers.kt
Labels: [Type] Enhancement
