Repository wordpress-mobile/WordPress-Android, pull requests merged in 2019-09, with the labels that each got.

#10471 Change page list labels (private, etc) to be gray
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageItemViewHolder.kt
  WordPress/src/main/res/layout/page_list_item.xml
Labels: Accessibility, [Status] Needs Code Review, [Status] Needs Design Review

#10364 GB - Add additional check that makes sure the opt-in dialog is shown only once per site
  WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
Labels: gutenberg-mobile

#10473 Reduce icon size in Widgets to fix crash
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/utils/WidgetUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt
Labels: [Type] Crash

#10476 Sort more than 100 pages chronologically
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PageListViewModelTest.kt
Labels: Pages List

#10478 Default transition animation for site picker
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
Labels: Site Picker

#10468 Jetpack performance settings
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/WordPressDB.java
  WordPress/src/main/java/org/wordpress/android/models/JetpackSettingsModel.java
  WordPress/src/main/java/org/wordpress/android/models/SiteSettingsModel.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsInterface.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/WPComSiteSettings.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/WPSwitchPreference.java
  WordPress/src/main/res/color/primary_0_gray_20_gray_40_selector.xml
  WordPress/src/main/res/color/primary_0_gray_90_gray_50_selector.xml
  WordPress/src/main/res/layout/wp_preference_layout.xml
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/key_strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/site_settings.xml
Labels: Jetpack

#10448 Feature/added additional domain credit tracking
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/domains/DomainSuggestionsViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/domains/DomainRegistrationMainViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/domains/DomainSuggestionsViewModelTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Analytics, Domain Credit, [Status] Needs Code Review

#10485 Hide Sharing manage options for non-admins
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListFragment.java
  WordPress/src/main/res/layout/publicize_list_fragment.xml
Labels: Sharing

#10481 Show an empty screen when all insights are removed
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/UiModelMapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/UiModelMapperTest.kt
Labels: Stats, Stats Refresh

#10457 Don't override local changes unless user edits unpublished revision
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostActionHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
Labels: Offline Support, Post List, [Type] Bug

#10395 Fix UI tests
  WordPress/src/androidTest/java/org/wordpress/android/e2e/components/MasterbarComponent.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/EditorPage.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/MySitesPage.java
  WordPress/src/androidTest/java/org/wordpress/android/support/WPSupportUtils.java
Labels: Testing

#10314 Revert "Revert "Run connected tests on CI for every PR(round 2)""
  .circleci/config.yml
  .idea/codeStyles/Project.xml
Labels: Testing, Tooling

#10497 Fixes #8002: Add ability to change username
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/ui/FullScreenDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/BaseUsernameChangerFullScreenDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SettingsUsernameChangerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/UsernameChangerFullScreenDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AccountSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/PostsAndPagesUseCase.kt
  WordPress/src/main/res/layout/settings_username_changer_confirm_dialog.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  build.gradle
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: /Me

#10501 CircleCI: Use shallow clone to checkout repo
  .circleci/config.yml
Labels: Tooling

#10446 Issue/10370 auto upload error labels
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListUploadStatusTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadActionUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUploadStatus.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadActionUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
  build.gradle
Labels: Offline Support

#10517 Fix retry media upload on self hosted site
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
  build.gradle
Labels: Offline Support, Posting/Editing, Self-hosted

#10516 Upgrade fluxC to 1.4.0
  build.gradle
Labels: releases

#10458 Issue/10444 add tracks to unpublished revision dialog
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListDialogHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostListMainViewModelTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Analytics, Offline Support, Post List

#10519 Hide remote auto save completed notification
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java
Labels: Offline Support, [Type] Bug

#10498 Feature/move me tab to new activity
  WordPress/build.gradle
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MeActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainNavigationView.kt
  WordPress/src/main/res/layout/me_activity.xml
  WordPress/src/main/res/menu/my_site_menu.xml
Labels: /Me, Information Architecture, [Type] Enhancement

#10512 Enable cancel autoupload action for drafts and update labels
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Offline Support, [Status] Needs Copy Review

#10504 Issue/10503 overload login module theme
  WordPress/src/main/res/layout/login_epilogue_screen.xml
  WordPress/src/main/res/values/styles.xml
Labels: Login

#10520 Fix string translation in Stats
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/ui/news/LocalNewsService.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/DateUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/LocaleManagerWrapper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/ContextProvider.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/ResourceProvider.kt
  WordPress/src/test/java/org/wordpress/android/ui/news/LocalNewsServiceTest.kt
Labels: [Type] Bug

#10530 Enable using a local copy of WordPressMocks
  WordPress/build.gradle
  gradle.properties-example
  settings.gradle
Labels: Tooling

#10534 Fix/9748 npe in EditPostActivity onPrepareOptionsMenu
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: [Type] Bug

#10533 Fix invalid “Queued post” state in Post List for self-hosted sites
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Post List, Posting/Editing, Self-hosted

#10531 Do not upload post without local changes
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadActionUseCase.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadActionUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterTest.kt
Labels: Offline Support, Post List, Posting/Editing, [Type] Bug

#10529 Fix crash during auto-upload
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt
  build.gradle
Labels: Offline Support, Post List, Posting/Editing, [Type] Bug

#10521 Merge 13.3 into develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
Labels: releases

#10541 Merge `Issue/10503 overload login module theme` into `13.3`
  WordPress/src/main/res/layout/login_epilogue_screen.xml
  WordPress/src/main/res/values/styles.xml
Labels: releases
