Repository wordpress-mobile/WordPress-Android, pull requests merged in 2020-11, with the labels that each got.

#13240 issue/13195 updated parent class of nested webview.
  WordPress/src/main/java/org/wordpress/android/widgets/NestedWebView.kt
Labels: [Status] Needs Code Review, [Type] Bug

#13277 Issue/13149 ppn category tests
  WordPress/src/test/java/org/wordpress/android/ui/posts/prepublishing/PrepublishingAddCategoryViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/prepublishing/PrepublishingCategoriesViewModelTest.kt
Labels: Prepublishing Nudges, Tag/Category Management

#13269 Add PostMediaHandler.kt to add remote post ID to media on post uploaded
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostMediaHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java
  WordPress/src/test/java/org/wordpress/android/ui/uploads/PostMediaHandlerTest.kt
Labels: Media, Posting/Editing

#13280 Merge Release/16.1 back into develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#13217 Open local previews for atomic sites
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/StorePostViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelperTest.kt
Labels: Posting/Editing, [Type] Enhancement

#13242 Add from wp media lib for stories.
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/MediaPickerLauncher.kt
Labels: Media Picker Consolidation, [Type] Enhancement

#13278 Issue/13197 Google login NPE
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/GoogleFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginGoogleFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java
Labels: Login, [Type] Crash

#13282 Merge release notes for 16.1 into develop
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: Releases

#13218 [Home Page Picker] Populate thumbnail cells of the Home Page Picker Container
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/LayoutGridItemUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/LayoutsDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/ThumbDimensionProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/usecases/FetchHomePageLayoutsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/util/DisplayUtilsWrapper.kt
  WordPress/src/main/res/layout-land/home_page_picker_header_section.xml
  WordPress/src/main/res/layout-sw600dp/home_page_picker_bottom_toolbar.xml
  WordPress/src/main/res/layout-sw600dp/home_page_picker_header_section.xml
  WordPress/src/main/res/layout/home_page_picker_fragment.xml
  WordPress/src/main/res/layout/home_page_picker_header_section.xml
  WordPress/src/main/res/layout/home_page_picker_item.xml
  WordPress/src/main/res/values-sw600dp-land/dimens.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/theme/FetchHomePageLayoutsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerViewModelTest.kt
  build.gradle
Labels: Part of a WIP Feature, [Status] Needs Design Review, [Type] Enhancement

#13147 Add unit tests for MediaLibraryDataSource.kt
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/loader/MediaLibraryDataSource.kt
  WordPress/src/test/java/org/wordpress/android/ui/mediapicker/loader/MediaLibraryDataSourceTest.kt
Labels: Media Picker Consolidation, [Type] Enhancement

#13284 Update Prologue Third
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginProloguePageFragment.kt
  WordPress/src/main/res/layout/login_prologue_third.xml
  WordPress/src/main/res/values/strings.xml
Labels: Login, [Type] Enhancement, i18n

#13288 [Home Page Picker] Adds Loading Skeleton Animation
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/ThumbDimensionProvider.kt
  WordPress/src/main/res/layout/home_page_picker_fragment.xml
  WordPress/src/main/res/layout/home_page_picker_loading_skeleton.xml
Labels: Part of a WIP Feature, [Type] Enhancement

#13281 Media editing: Fix Glide cache issue for crop output file
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropViewModel.kt
Labels: Media, Media Editing

#13286 Update material and swipeToRefresh versions
  WordPress/build.gradle
  build.gradle
  libs/editor/WordPressEditor/build.gradle
  libs/login/WordPressLoginFlow/build.gradle
  libs/utils/WordPressUtils/build.gradle
Labels: Tech debt, [Type] Task

#13253 Fix reader launch on attachment view
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsConstants.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/NavigationTarget.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostHeaderUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/PostsAndPagesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsNavigator.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostHeaderUseCaseTest.kt
  build.gradle
Labels: Stats

#13295 Update photo view version
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaPreviewFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderPhotoView.java
  WordPress/src/main/res/layout/media_preview_fragment.xml
  WordPress/src/main/res/layout/reader_photo_view.xml
Labels: Tech debt, [Type] Task

#13298 WP Stories : Prepublishing fragment container no longer cut off by nav bar in Android 10
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingBottomSheetFragment.kt
Labels: WP Stories, [Type] Task

#13307 Remove out-dated checkstyle scripts
  tools/checkstyle.sh
  tools/compare-with-develop-style.sh
Labels: Tech debt, Tooling, [Type] Enhancement

#13289 Update dagger to 2.29.1
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  build.gradle
  libs/login/WordPressLoginFlow/build.gradle
Labels: Tech debt, [Type] Enhancement

#13296 Update shimmer effect library to 0.5.0
  WordPress/build.gradle
Labels: Tech debt, [Type] Enhancement

#13305 Fix/prologue strings
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginProloguePageFragment.kt
  WordPress/src/main/res/layout/login_prologue_third.xml
  WordPress/src/main/res/values/strings.xml
  fastlane/resources/values/strings.xml
Labels: Localization

#13306 Remove out-dated travis configuration
  .travis.yml
Labels: Tech debt, Tooling, [Type] Enhancement

#13309 Rename prod deps gradle task
  build.gradle
Labels: Tooling, [Type] Enhancement

#13315 Updating issue-triage to reference 'medium' priority instead of 'normal'
  docs/issue-triage.md
Labels: Documentation

#13317 Fix CI for release builds
  .circleci/config.yml
  WordPress/build.gradle
  fastlane/Fastfile
Labels: Tooling

#13300 Prepublishing bottom sheet : fixed an issue where the keyboard overlays fragment container
  WordPress/src/main/java/org/wordpress/android/util/KeyboardResizeViewUtil.java
Labels: Prepublishing Nudges, WP Stories, [Type] Task

#13308 Update out-dated checkstyle ide configuration instructions
  docs/coding-style.md
Labels: Documentation

#13311 Exclude support-annotations dependency from zendesk to skip jetifier
  WordPress/build.gradle
Labels: Tech debt

#13323 Featured image not showing on http pure self-hosted sites
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/FeaturedImageHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/SiteAccessibilityInfo.kt
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  WordPress/src/main/java/org/wordpress/android/util/SiteUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/FeaturedImageHelperTest.kt
Labels: Post List, [Type] Bug

#13270 Introduce activity log filters feature flag
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/ActivityLogListFragment.kt
  WordPress/src/main/java/org/wordpress/android/util/config/ActivityLogFiltersFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
  WordPress/src/main/res/layout/activity_log_list_fragment.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModelTest.kt
Labels: Jetpack, [Type] Task

#13335 Hide saving dialog on saving finished before preview
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/StorePostViewModel.kt
Labels: Posting/Editing, [Type] Bug

#13338 Merge release 16.0.1 into 16.1
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Releases

#13351 Release/16.0.1
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/StorePostViewModel.kt
Labels: Releases

#13291 Update OkHTTP library and FluxC
  WordPress/build.gradle
  build.gradle
  libs/editor/WordPressEditor/build.gradle
Labels: Core, [Type] Enhancement

#13325 Additional tracking information of media upload errors
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/usecases/CreateSiteUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadHandler.java
  build.gradle
Labels: Media, Media Picker Consolidation, [Type] Enhancement

#13334 Jetpack Section: Scan - Introduce feature flag
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/util/ScanFeatureConfig.kt
  WordPress/src/main/res/drawable/ic_scan_alt_white_24dp.xml
  WordPress/src/main/res/layout/my_site_fragment.xml
  WordPress/src/main/res/values/strings.xml
Labels: Jetpack, [Type] Task

#13354 Sync utils subtree
  libs/utils/.circleci/config.yml
  libs/utils/WordPressUtils/build.gradle
  libs/utils/gradle.properties-example
Labels: Tooling

#13358 [Modal Layout Picker] Prevents layout preview from creating a duplicate page
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: [Type] Bug

#13359 Fix issues in MockingInterceptor.kt
  WordPress/src/androidTest/java/org/wordpress/android/support/MockingInterceptor.kt
Labels: [Pri] High

#13363 Prevents saving post locally in preview mode
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: [Type] Bug

#13285 Use previous media picker in stories
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/MediaPickerLauncher.kt
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stories/StoriesMediaPickerResultHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/stories/StoryComposerActivity.kt
  WordPress/src/main/res/layout/photo_picker_fragment.xml
  WordPress/src/main/res/values/dimens.xml
Labels: Media Picker Consolidation, WP Stories, [Type] Task

#13366 Stories: Update minimum supported Jetpack version
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
Labels: WP Stories

#13368 Enable consolidated media picker
  WordPress/src/main/java/org/wordpress/android/util/config/ConsolidatedMediaPickerFeatureConfig.kt
Labels: Media, Media Picker Consolidation, [Type] Task

#13362 Copy media from system picker before they are passed down
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/insert/DeviceListInsertUseCase.kt
Labels: Media, Media Picker Consolidation, [Type] Bug

#13340 Setup new My Site fragment behind a feature flag
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainNavigationView.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/ImprovedMySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/util/config/MySiteImprovementsFeatureConfig.kt
Labels: /My site, My Site Dynamic Cards, [Type] Task

#13376 Fix configuration for Connected Tests and Screenshots
  .circleci/config.yml
Labels: Tooling

#13316 [Home Page Picker] Connect Choose to the flow of existing UI's
  WordPress/src/main/java/org/wordpress/android/ui/mlp/LayoutViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVM.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/services/SiteCreationServiceData.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/usecases/CreateSiteUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/usecases/FetchDomainsUseCase.kt
  WordPress/src/main/res/drawable/ic_layout_selection_check_24dp.xml
  WordPress/src/main/res/drawable/ic_layout_selection_overlay_153dp.xml
  WordPress/src/main/res/layout-land/modal_layout_picker_titlebar.xml
  WordPress/src/main/res/layout/home_page_picker_fragment.xml
  WordPress/src/main/res/layout/home_page_picker_item.xml
  WordPress/src/main/res/layout/home_page_picker_titlebar.xml
  WordPress/src/main/res/layout/modal_layout_picker_layouts_card.xml
  WordPress/src/main/res/layout/modal_layout_picker_titlebar.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/previews/CreateSiteUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/services/SiteCreationServiceManagerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerViewModelTest.kt
  build.gradle
Labels: Part of a WIP Feature, [Status] Needs Design Review, [Type] Enhancement

#13321 [Home Page Picker] Hides preview button (Round 1)
  WordPress/src/main/res/layout-sw600dp/home_page_picker_bottom_toolbar.xml
  WordPress/src/main/res/layout/home_page_picker_bottom_toolbar.xml
Labels: [Type] Enhancement

#13336 [Home Page Picker] Analytic Events
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SiteCreationTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerViewModelTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Part of a WIP Feature, [Type] Enhancement

#13372 Fix NPE in Reader tags
  build.gradle
Labels: Core, [Type] Bug

#13373 Fix UI tests after media picker update
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/EditorPage.java
  WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java
Labels: Media, Media Picker Consolidation, [Type] Bug

#13383 Catch IllegalArgumentException coming from Google Photos
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/MediaUtils.java
Labels: Media, Media Picker Consolidation, [Type] Crash

#13382 Issue/13312 fix infinite loading dialog
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/repository/ReaderDiscoverDataProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/repository/usecases/GetDiscoverCardsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/services/discover/ReaderDiscoverLogic.kt
  WordPress/src/main/java/org/wordpress/android/util/LiveDataUtils.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/repository/ReaderDiscoverDataProviderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/repository/usecases/GetDiscoverCardsUseCaseTest.kt
Labels: New Reader Android

#13384 Issue/13312 fix consistency of empty views
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderNavigationEvents.kt
  WordPress/src/main/res/layout/reader_discover_fragment_layout.xml
  WordPress/src/main/res/layout/reader_fullscreen_empty_with_action.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModelTest.kt
Labels: New Reader Android

#13381 Fix infinite saving post dialog in editor
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Posting/Editing

#13387 Remove didSucceed check from ReaderDiscoverDataProvider
  WordPress/src/main/java/org/wordpress/android/ui/reader/repository/ReaderDiscoverDataProvider.kt
Labels: New Reader Android

#13385 Fix importing media from external sources i.e. google photos
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/CopyMediaToAppStorageUseCase.kt
  WordPress/src/main/java/org/wordpress/android/util/MediaUtilsWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/photopicker/PhotoPickerViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/media/CopyMediaToAppStorageUseCaseTest.kt
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/MediaUtils.java
Labels: Media, Media Picker Consolidation, [Type] Crash

#13388 Update release notes for media picker project
  RELEASE-NOTES.txt
Labels: Media, Media Picker Consolidation, [Type] Task

#13319 Merge latest changes from Login-Flow library
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/UnifiedLoginTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginAnalyticsTracker.java
  WordPress/src/main/res/drawable/img_illustration_email_alert_120dp.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/drawables.xml
  WordPress/src/main/res/values/strings.xml
  libs/login/WordPressLoginFlow/build.gradle
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/Login2FaFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginAnalyticsListener.kt
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginBaseFormFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailPasswordFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginListener.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginMagicLinkRequestFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginMagicLinkSentFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginUsernamePasswordFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupEmailFragment.java
  libs/login/WordPressLoginFlow/src/main/res/layout/login_email_optional_site_creds_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_email_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_magic_link_sent_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/values/dimens.xml
  libs/login/WordPressLoginFlow/src/main/res/values/strings.xml
Labels: Login

#13377 Issue/13332 hide certain my site items for p2
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserActivity.java
Labels: P2, [Status] Needs Code Review

#13389 Merge Release/16.1 back into develop
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-kmr/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/956.txt
  fastlane/metadata/android/de-DE/changelogs/956.txt
  fastlane/metadata/android/en-US/changelogs/946.txt
  fastlane/metadata/android/en-US/changelogs/956.txt
  fastlane/metadata/android/es-ES/changelogs/946.txt
  fastlane/metadata/android/es-ES/changelogs/956.txt
  fastlane/metadata/android/fr-CA/changelogs/956.txt
  fastlane/metadata/android/fr-FR/changelogs/956.txt
  fastlane/metadata/android/in/changelogs/956.txt
  fastlane/metadata/android/it-IT/changelogs/946.txt
  fastlane/metadata/android/it-IT/changelogs/956.txt
  fastlane/metadata/android/iw-IL/changelogs/946.txt
  fastlane/metadata/android/iw-IL/changelogs/956.txt
  fastlane/metadata/android/ko-KR/changelogs/946.txt
  fastlane/metadata/android/ko-KR/changelogs/956.txt
  fastlane/metadata/android/nl-NL/changelogs/946.txt
  fastlane/metadata/android/nl-NL/changelogs/956.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/946.txt
  fastlane/metadata/android/ru-RU/changelogs/956.txt
  fastlane/metadata/android/sr/full_description.txt
  fastlane/metadata/android/sr/title.txt
  fastlane/metadata/android/sv-SE/changelogs/946.txt
  fastlane/metadata/android/sv-SE/changelogs/956.txt
  fastlane/metadata/android/tr-TR/changelogs/956.txt
  fastlane/metadata/android/zh-CN/changelogs/946.txt
  fastlane/metadata/android/zh-CN/changelogs/956.txt
  fastlane/metadata/android/zh-TW/changelogs/956.txt
Labels: Releases

#13400 Fix UI test selecting featured image
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/EditorPage.java
Labels: [Type] Bug

#13356 Introduce skeleton activity type filter screen in Activity Log
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/ActivityLogListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/filter/ActivityLogTypeFilterFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/filter/ActivityLogTypeFilterViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
  WordPress/src/main/res/layout/activity_log_list_fragment.xml
  WordPress/src/main/res/layout/activity_log_type_filter_fragment.xml
  WordPress/src/test/java/org/wordpress/android/ui/activitylog/list/filter/ActivityLogTypeFilterViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModelTest.kt
Labels: Activity Log, [Type] Task

#13364 Dismiss save popup on post upload and change events
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/StorePostViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/StorePostViewModelTest.kt
Labels: Posting/Editing

#13360 Setup UI layer for new MySite screen
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/mysite/ImprovedMySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapterDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/res/layout/new_my_site_fragment.xml
Labels: /My site, My Site Dynamic Cards, [Type] Task

#13399 [Home Page Picker] Preview Button functionality
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/FullscreenBottomSheetDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mlp/ModalLayoutPickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/DesignPreviewFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerViewModel.kt
  WordPress/src/main/res/layout-sw600dp/home_page_picker_bottom_toolbar.xml
  WordPress/src/main/res/layout/home_page_picker_bottom_toolbar.xml
  WordPress/src/main/res/layout/home_page_picker_preview_fragment.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerViewModelTest.kt
Labels: Part of a WIP Feature, Site Creation, [Status] Needs Design Review, [Type] Enhancement

#13404 Issue/13135 remove location settings
  .configure
  .configure-files/gradle.properties.enc
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/res/drawable/ic_location_white_24dp.xml
  WordPress/src/main/res/layout/edit_post_settings_fragment.xml
  WordPress/src/main/res/menu/post_settings_location_popup.xml
  WordPress/src/main/res/values/strings.xml
  gradle.properties-example
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Post Settings, [Status] Needs Code Review

#13412 Quick Start: Show missing indicator dot on the Add Page floating action button
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt
  WordPress/src/main/res/layout/pages_fragment.xml
Labels: Quick Start, [Type] Bug

#13324 Issue/13268 introduce date range picker screen in Activity Log
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/ActivityLogListFragment.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
  WordPress/src/main/res/color/on_surface_button_selector.xml
  WordPress/src/main/res/values-night/styles.xml
  WordPress/src/main/res/values/styles.xml
Labels: Activity Log, Jetpack

#13421 Load media library without storage permissions
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/mediapicker/MediaPickerViewModelTest.kt
Labels: Media, Media Picker Consolidation, [Type] Bug

#13422 Merge release notes for Release/16.2 into develop
  WordPress/metadata/PlayStoreStrings.po
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/mediapicker/MediaPickerViewModelTest.kt
Labels: Releases

#13416 Fix duplicate media upload issue
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
Labels: Media, Posting/Editing

#13429 Extract ListItemInteraction.kt from stats to reuse in My Site
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostAverageViewsPerDayUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostHeaderUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostMonthsAndYearsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostRecentWeeksUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/AuthorsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ClicksUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/CountryViewsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/FileDownloadsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/PostsAndPagesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/ReferrersUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/SearchTermsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/VideoPlaysUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/management/InsightsManagementMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/management/InsightsManagementViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/AnnualSiteStatsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowersUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ManagementControlUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ManagementNewsCardUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PublicizeUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/TagsAndCategoriesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/ListItemInteraction.kt
Labels: /My site, My Site Dynamic Cards, [Type] Task

#13386 [Home Page Picker] Adds polling mechanism for not generated thumbnails
  WordPress/src/main/java/org/wordpress/android/modules/WordPressGlideModule.kt
  WordPress/src/main/java/org/wordpress/android/networking/GlideMShotsLoader.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt
  build.gradle
Labels: Part of a WIP Feature, Site Creation, [Type] Enhancement

#13031 Fix/screenshot ui tests
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/PostsListPage.java
Labels: Testing

#13448 Fix site icon upload never starts
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
Labels: Media, [Type] Bug

#13420 Issue/13268 activity type filter screen skeleton
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/filter/ActivityLogTypeFilterAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/filter/ActivityLogTypeFilterFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/filter/ActivityLogTypeFilterViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/filter/ActivityLogTypeFilterViewModel.kt
  WordPress/src/main/res/layout/activity_log_type_filter_fragment.xml
  WordPress/src/main/res/layout/activity_log_type_filter_item.xml
  WordPress/src/main/res/values/styles.xml
Labels: Jetpack

#13438 Fix continuous uploading notification on trashing queued post with media
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java
Labels: Media

#13439 Init UiState for activity type filter screen
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/filter/ActivityLogTypeFilterAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/filter/ActivityLogTypeFilterViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/filter/ActivityLogTypeFilterViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/activitylog/list/filter/ActivityLogTypeFilterViewModelTest.kt
Labels: Activity Log

#13444 Add backup feature flag config
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/util/BackupFeatureConfig.kt
Labels: Jetpack Mobile, [Type] Task

#13441 Merge Release/16.2 back into develop
  WordPress/build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#13430 Extract basic dialog with view model
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/BasicDialog.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/BasicDialogViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/BasicDialogViewModelTest.kt
Labels: /My site, My Site Dynamic Cards, [Type] Task

#13431 Create site info block item
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/ui/mysite/ImprovedMySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapterDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteInfoViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SiteDialogModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SiteInfoBlockBuilder.kt
  WordPress/src/main/res/layout/my_site_info_block.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: /My site, My Site Dynamic Cards, [Type] Task

#13451 Selected site repository
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SelectedSiteRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsInterface.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsInterfaceWrapper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/ResourceProvider.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/SelectedSiteRepositoryTest.kt
Labels: /My site, My Site Dynamic Cards, [Type] Enhancement

#13458 [Gutenberg] Update PostUtils for File block
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostUtilsUnitTest.kt
Labels: Gutenberg

#13425 Add backup download progress checker
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/BackupDownloadProgressChecker.kt
  WordPress/src/test/java/org/wordpress/android/ui/activitylog/BackupDownloadProgressCheckerTest.kt
Labels: Jetpack Mobile

#13467 Fixes site creation domain text color in dark mode
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SiteCreationPreviewFragment.kt
Labels: Site Creation, [Type] Bug

#13472 Allows https redirection in webview
  WordPress/src/main/java/org/wordpress/android/util/URLFilteredWebViewClient.java
Labels: Site Creation, [Type] Bug

#13437 [Gutenberg] File Block - FileBlockProcessor for upload media url transformation
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/BlockProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/BlockProcessorFactory.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/FileBlockProcessor.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/MediaBlockType.java
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostUtilsUnitTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/FileBlockProcessorTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/TestContent.kt
Labels: Gutenberg, [Type] Task

#13445 Issue/13433 add p2 flag to analytics with site
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java
  WordPress/src/test/java/org/wordpress/android/util/analytics/AnalyticsUtilsTest.java
  WordPress/src/test/java/org/wordpress/android/util/analytics/AnalyticsUtilsTest.kt
Labels: Analytics, P2, [Status] Needs Code Review

#13436 Stories: Show 'New' tag for Story entry in bottom sheets
  WordPress/src/main/java/org/wordpress/android/ui/main/ActionListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MainActionListItem.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListCreateMenuViewModel.kt
  WordPress/src/main/res/layout/main_action_list_item.xml
  WordPress/src/main/res/values/strings.xml
Labels: /My site, Post List, WP Stories

#13415 Issue/12934 add header to p2 postcard to show author
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderDatabase.java
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java
  WordPress/src/main/java/org/wordpress/android/models/ReaderPost.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostUiStateBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderPostViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderPostDetailHeaderView.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/uistates/ReaderBlogSectionUiState.kt
  WordPress/src/main/res/drawable/bg_oval_stroke_p2_author_1dp.xml
  WordPress/src/main/res/layout/reader_blog_section_view.xml
  WordPress/src/main/res/layout/reader_cardview_xpost.xml
  WordPress/src/main/res/values-ldrtl/strings.xml
  WordPress/src/main/res/values-night/colors.xml
  WordPress/src/main/res/values/colors.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderPostUiStateBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt
Labels: P2, Reader, [Status] Needs Code Review, [Status] Needs Design Review

#13440 Error handling on Activity Type filter screen
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/filter/ActivityLogTypeFilterViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/filter/DummyActivityTypesProvider.kt
  WordPress/src/test/java/org/wordpress/android/ui/activitylog/list/filter/ActivityLogTypeFilterViewModelTest.kt
Labels: Jetpack Mobile

#13474 Login: Add null check for LoginBaseDiscoveryListener to prevent crash
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginBaseDiscoveryFragment.java
Labels: Login, [Type] Crash

#13426 Stories: Editor analytics tweaks
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/AddLocalMediaToPostUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/OptimizeMediaUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stories/StoriesMediaPickerResultHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/stories/StoryComposerActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stories/StoryComposerViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stories/media/StoryMediaSaveUploadBridge.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/media/AddLocalMediaToPostUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/media/EditorMediaTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stories/usecase/StoryEditorMediaTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Analytics, Posting/Editing, WP Stories

#13453 Create toolbar in the improved My Site fragment
  WordPress/src/main/java/org/wordpress/android/ui/mysite/ImprovedMySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/res/layout/new_my_site_fragment.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: /My site, My Site Dynamic Cards, [Type] Task

#13402 Issue/13401 jetpack my site section
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/res/layout/fragment_jetpack_security_settings.xml
  WordPress/src/main/res/layout/my_site_fragment.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/jetpack_settings.xml
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: /My site, Jetpack, Site Settings

#13450 Issue/13268 remote site
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/ActivityLogListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/filter/ActivityLogTypeFilterFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/filter/ActivityLogTypeFilterViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/activitylog/list/filter/ActivityLogTypeFilterViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModelTest.kt
Labels: Jetpack, Jetpack Mobile

#13480 Add tracking for whitelisted ips settings
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Analytics, Jetpack Security

#13459 Enable Stories in production
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/MySitesPage.java
Labels: WP Stories

#13475 Issue/13446 clean up comment related analytics
  WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderCommentListActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderCommentAdapter.java
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Analytics, Comments, P2

#13473 Follow unfollow post comments
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/FollowCommentsUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderCommentListActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderCommentListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderFollowCommentsHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderCommentAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/usecases/ReaderCommentsFollowUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/PostSubscribersApiCallsProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderCommentsPostHeaderView.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderFollowButton.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderFollowButtonType.kt
  WordPress/src/main/java/org/wordpress/android/util/config/FollowUnfollowCommentsFeatureConfig.kt
  WordPress/src/main/res/color/secondary_gray_20_disabled_selector.xml
  WordPress/src/main/res/drawable/ic_reader_follow_conversation_white_24dp.xml
  WordPress/src/main/res/drawable/ic_reader_following_conversation_white_24dp.xml
  WordPress/src/main/res/layout/reader_comments_post_header_view.xml
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/reader_styles.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/reader/ReaderCommentListViewModelTest.kt
Labels: P2, Reader, [Status] Needs Code Review, [Type] Enhancement

#13488 Adding analytics to follow unfollow comments feature.
  WordPress/src/main/java/org/wordpress/android/ui/reader/usecases/ReaderCommentsFollowUseCase.kt
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtilsWrapper.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: P2, Reader, [Type] Enhancement

#13492 Enable follow unfollow button in comments reader.
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/util/config/FollowUnfollowCommentsFeatureConfig.kt
Labels: P2, Reader, [Type] Task

#13495 Follow unfollow comments improving user error message.
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/PostSubscribersApiCallsProvider.kt
  WordPress/src/main/res/values/strings.xml
Labels: P2, Reader, [Type] Enhancement

#13447 Add status service for backup download
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/BackupDownloadProgressChecker.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/BackupDownloadStatusService.kt
  WordPress/src/test/java/org/wordpress/android/ui/activitylog/BackupDownloadStatusServiceTest.kt
Labels: Jetpack Mobile

#13498 Merge Release/16.3 back into develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/metadata/release_notes.txt
  WordPress/metadata/release_notes_short.txt
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#13503 [Home Page Picker] Mark Theme Selection as Completed as part of the Site Creation Flow
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModelTest.kt
Labels: Site Creation, [Type] Enhancement
