Repository wordpress-mobile/WordPress-Android, pull requests merged in 2020-04, with the labels that each got.

#11568 Page List : Empty editor when loading more items
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt
Labels: Pages List, [Type] Bug

#11535 Testing: Add optional connected tests on PRs
  .circleci/config.yml
Labels: Testing, [Status] Not Ready for Merge

#11567 Add Gutenberg specific checks to Code Freeze
  fastlane/Fastfile
Labels: Tooling

#11562 Add log encryption
  WordPress/build.gradle
  WordPress/src/androidTest/java/org/wordpress/android/util/EncryptionUtilsTest.java
  WordPress/src/androidTest/java/org/wordpress/android/util/EncryptionUtilsTest.kt
  WordPress/src/main/java/org/wordpress/android/util/EncryptionUtils.java
  WordPress/src/main/java/org/wordpress/android/util/encryptedlogging/EncryptedLogReader.kt
  WordPress/src/main/java/org/wordpress/android/util/encryptedlogging/EncryptedLogWriter.kt
  WordPress/src/main/java/org/wordpress/android/util/encryptedlogging/EncryptedSecretStreamKey.kt
  WordPress/src/main/java/org/wordpress/android/util/encryptedlogging/EncryptionUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/encryptedlogging/SecretStreamKey.kt
Labels: Tooling

#11536 Add log persistence
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  libs/utils/WordPressUtils/build.gradle
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/AppLog.java
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/helpers/logfile/LogFileCleaner.kt
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/helpers/logfile/LogFileHelpers.kt
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/helpers/logfile/LogFileProviderInterface.kt
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/helpers/logfile/LogFileWriter.kt
  libs/utils/WordPressUtils/src/test/java/org/wordpress/android/util/LogFileCleanerTest.kt
  libs/utils/WordPressUtils/src/test/java/org/wordpress/android/util/LogFileHelpersTest.kt
  libs/utils/WordPressUtils/src/test/java/org/wordpress/android/util/LogFileWriterTest.kt
Labels: Tooling

#11537 Fix/10930 email error dissapears on rotation - continued
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java
Labels: Login, [Type] Enhancement

#11566 Introduce leak canary to get rid of memory leaks
  WordPress/build.gradle
Labels: [Type] Enhancement

#11575 Testing: Make slack notification a parameter for connected tests
  .circleci/config.yml
Labels: Testing

#11540 Add reblog to reader post list
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderInterfaces.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/reblog/ReblogState.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/main/res/layout/reader_cardview_post.xml
  WordPress/src/main/res/layout/reader_include_post_detail_footer.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/reader/ReaderPostListViewModelTest.kt
Labels: Reader, [Type] Enhancement

#11455 Managing ssl parameter into query for JetPack.
  libs/utils/WordPressUtils/src/androidTest/java/org/wordpress/android/util/PhotonUtilsTest.java
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/PhotonUtils.java
Labels: Media, [Type] Bug

#11585 Merge gutenberg strings in the main strings.xml file
  WordPress/src/main/res/values/strings.xml
Labels: gutenberg-mobile

#11561 Issue/11386 is media in gutenberg body fix
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostUtilsUnitTest.kt
Labels: Media, Posting/Editing, gutenberg-mobile

#11584 Fix page upload directly from page list handled by PostUploadHandler
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadHandler.java
Labels: Posting/Editing, [Type] Crash

#11598 Using Gravatar in me menu.
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/utils/MeGravatarLoader.kt
  WordPress/src/main/java/org/wordpress/android/util/image/ImagePlaceholderManager.kt
  WordPress/src/main/java/org/wordpress/android/util/image/ImageType.kt
  WordPress/src/main/res/layout/me_action_layout.xml
  WordPress/src/main/res/menu/my_site_menu.xml
  WordPress/src/main/res/values/dimens.xml
Labels: /Me, IA, [Status] Needs Design Review, [Type] Enhancement

#11595 Merge 14.6 code freeze to develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
  build.gradle
Labels: releases

#11581 Reader : error inflating error textview
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/res/layout/reader_fragment_post_detail.xml
Labels: Reader, [Type] Bug

#11600 Commenting out the override method shouldOverrideUrlLoading() fixes the issue
  WordPress/src/main/res/xml/site_settings.xml
Labels: [Type] Bug

#11553 Handle user with no site
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/ActionableEmptyView.kt
  WordPress/src/main/java/org/wordpress/android/ui/RequestCodes.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/NoSiteToReblogActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderEvents.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.java
  WordPress/src/main/res/layout/reader_no_site_to_reblog.xml
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/strings.xml
Labels: Reader, [Type] Enhancement

#11601 Mark some string references untranslatable
  WordPress/src/main/res/values/strings.xml
Labels: Localization

#11618 Remove leak canary
  WordPress/build.gradle
Labels: [Type] Enhancement

#11609 Extract weekdays to the main strings.xml file
  WordPress/src/main/res/values/key_strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/site_settings.xml
Labels: Localization

#11623 Change parent style of NoDisplay activity to WordPress.NoActionBar
  WordPress/src/main/res/values/styles.xml
Labels: [Status] Needs Code Review, [Type] Crash

#11622 Merge 14.6 release notes to develop
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: releases

#11621 Merge 14.6 release notes to master
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: releases

#11522 Update FluxC to enable authenticated rest api requests to self-hosted sites
  WordPress/src/main/java/org/wordpress/android/ui/posts/reactnative/ReactNativeRequestHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/reactnative/ReactNativeUrlUtil.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/reactnative/ReactNativeRequestHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/reactnative/ReactNativeUrlUtilTest.kt
  build.gradle
Labels: gutenberg-mobile

#11624 Updates .configure to latest hash
  .configure
  .configure-files/gradle.properties.enc
Labels: Tooling

#11555 Customise Site Picker for Reblog Action
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
Labels: Reader, [Type] Task

#11608 Support multiple images on preview screen
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/ImageEditorInitializer.kt
  build.gradle
  libs/image-editor/ImageEditor/build.gradle
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/ImageEditor.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropFragment.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PagerAdapterObserver.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageAdapter.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageFragment.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewHolder.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModel.kt
  libs/image-editor/ImageEditor/src/main/res/drawable/preview_image_thumbnail_border.xml
  libs/image-editor/ImageEditor/src/main/res/drawable/preview_image_thumbnail_selector.xml
  libs/image-editor/ImageEditor/src/main/res/layout/crop_image_fragment.xml
  libs/image-editor/ImageEditor/src/main/res/layout/preview_image_fragment.xml
  libs/image-editor/ImageEditor/src/main/res/layout/preview_image_layout.xml
  libs/image-editor/ImageEditor/src/main/res/layout/preview_image_thumbnail.xml
  libs/image-editor/ImageEditor/src/main/res/navigation/nav_graph.xml
  libs/image-editor/ImageEditor/src/main/res/values-sw600dp/dimens.xml
  libs/image-editor/ImageEditor/src/main/res/values/colors.xml
  libs/image-editor/ImageEditor/src/main/res/values/dimens.xml
  libs/image-editor/ImageEditor/src/main/res/values/strings.xml
Labels: Media, Media Editing, [Status] Needs Code Review

#11628 Remove unnecessary pageActionsEnabled for upload as we use an overlay
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListEventListener.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PagesViewModelTest.kt
Labels: Pages List, [Type] Crash

#11578 Issue/9854 site creation loading
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SiteCreationPreviewFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/AniUtils.java
  WordPress/src/main/res/drawable-night/img_illustration_magician_hat_128.xml
  WordPress/src/main/res/drawable/img_illustration_magician_hat_128.xml
  WordPress/src/main/res/layout-land/site_creation_preview_screen.xml
  WordPress/src/main/res/layout/site_creation_preview_screen_default.xml
  WordPress/src/main/res/layout/site_creation_progress_creating_site.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModelTest.kt
Labels: Site Creation, [Status] Needs Design Review, [Type] Enhancement

#11639 Replace the dash with comma
  WordPress/src/main/res/values/strings.xml
Labels: gutenberg-mobile

#11626 Prepublishing Nudges : create core bottom sheet functionality
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingActionItemUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingActionsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingActionsDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingActionsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingActionsListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingActionsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingBottomSheetFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingViewModel.kt
  WordPress/src/main/res/layout/post_prepublishing_actions_fragment.xml
  WordPress/src/main/res/layout/post_prepublishing_bottom_sheet.xml
  WordPress/src/main/res/layout/prepublishing_action_list_item.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/posts/PrepublishingActionsViewModelTest.kt
Labels: Prepublishing Nudges, [Type] Task

#11636 Post & Page List : Changed auto upload text from cancel to cancel upload
  WordPress/src/main/java/org/wordpress/android/widgets/PostListButtonType.kt
  WordPress/src/main/res/menu/page_more.xml
  WordPress/src/main/res/values/strings.xml
Labels: Pages List, Post List, [Type] Enhancement

#11645 Support failed states for multiple images on preview screen
  WordPress/src/main/res/values/strings.xml
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageFragment.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewHolder.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModel.kt
  libs/image-editor/ImageEditor/src/main/res/layout/layout_retry.xml
  libs/image-editor/ImageEditor/src/main/res/values/strings.xml
  libs/image-editor/ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModelTest.kt
Labels: Media, Media Editing, [Status] Needs Code Review

#11655 Issue/11635 fix sharing intent receiver in dark mode
  WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverFragment.java
  WordPress/src/main/res/layout/share_intent_receiver_activity.xml
  WordPress/src/main/res/layout/share_intent_sites_listitem.xml
  WordPress/src/main/res/values/styles.xml
Labels: Dark Mode, [Status] Needs Code Review

#11611 Issue/11518 media picker actions
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserType.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/EditorPhotoPicker.kt
  WordPress/src/main/java/org/wordpress/android/util/WPMediaUtils.java
Labels: Gutenberg, Media, Media Editing

#11642 Add mobile Gutenberg localization to code freeze
  fastlane/Fastfile
Labels: Tooling

#11613 Me gravatar menu accessibility
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/utils/MeGravatarLoader.kt
  WordPress/src/main/res/layout/me_action_layout.xml
  WordPress/src/main/res/values/dimens.xml
Labels: /Me, [Status] Needs Code Review, [Type] Enhancement

#11660 Switch styles of the login and signup buttons
  WordPress/src/main/res/layout-land/login_signup_screen.xml
  WordPress/src/main/res/layout/login_signup_screen.xml
Labels: [Type] Enhancement

#11654 Fixing reader search suggestion in Dark Mode
  WordPress/src/main/res/layout/reader_listitem_suggestion_recycler.xml
Labels: Dark Mode, [Status] Needs Code Review

#11667 Merge 14.6 release notes change to master
  WordPress/build.gradle
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  WordPress/src/main/res/values/styles.xml
Labels: releases

#11666 Testing: Re-enable and refactor login tests that don't use magic links
  WordPress/src/androidTest/java/org/wordpress/android/e2e/LoginTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/flows/LoginFlow.java
  WordPress/src/androidTest/java/org/wordpress/android/support/BaseTest.java
Labels: Testing, [Status] Needs Code Review

#11658 Master custom image picker in gutenberg
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserType.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/EditorPhotoPicker.kt
  WordPress/src/main/java/org/wordpress/android/util/WPMediaUtils.java
Labels: Media, gutenberg-mobile

#11669 Testing: Update mocks for screenshot test
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/posts/posts-draft,pending.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/posts/posts-first.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/posts/posts-private,publish.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/stats/stats_publicize.json
Labels: Testing, Tooling

#11630 Update Fastlane and release-toolkit
  .circleci/config.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  fastlane/Pluginfile
Labels: Tooling

#11671 Testing: Re-enable magic link tests
  WordPress/build.gradle
  WordPress/src/androidTest/java/org/wordpress/android/e2e/LoginTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/SignUpTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/flows/SignupFlow.java
Labels: Testing, [Status] Needs Code Review

#11644 Prepublishing Nudges: PostSettingsTagsActivity extracted to PostSettingsTagsFragment
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostSettingsTagsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostSettingsTagsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/TagSelectedListener.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/TagsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/TagsRecyclerViewAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/TagsSelectedListener.java
  WordPress/src/main/res/layout/fragment_post_settings_tags.xml
  WordPress/src/main/res/layout/post_settings_tags_activity.xml
Labels: Prepublishing Nudges, [Status] Not Ready for Merge, [Type] Task

#11590 Feature/support private at sites
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderDatabase.java
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java
  WordPress/src/main/java/org/wordpress/android/models/ReaderPost.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/PrivateAtCookieRefreshProgressDialog.kt
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaPreviewFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaSettingsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/FeaturedImageHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPhotoViewerFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderPhotoView.java
  WordPress/src/main/java/org/wordpress/android/ui/utils/AuthenticationUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  WordPress/src/main/java/org/wordpress/android/util/WPUrlUtils.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/res/layout/wpwebview_activity.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PageListViewModelTest.kt
  build.gradle
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/PhotonUtils.java
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/UrlUtils.java
Labels: [Status] Needs Code Review, [Type] Enhancement

#11683 Fallback to featured image url in case thumbnail url is empty.
  WordPress/src/main/java/org/wordpress/android/ui/posts/FeaturedImageHelper.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/FeaturedImageHelperTest.kt
Labels: Posting/Editing, [Type] Bug

#11689 Fixing unit testing conflict not detected by github during merge.
  WordPress/src/test/java/org/wordpress/android/ui/posts/FeaturedImageHelperTest.kt
Labels: Testing, [Type] Bug

#11665 Issue/11153 support editing multiple images: open selected image on crop screen
  WordPress/src/main/res/values/strings.xml
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropFragment.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageFragment.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModel.kt
  libs/image-editor/ImageEditor/src/main/res/drawable/ic_crop_white_24dp.xml
  libs/image-editor/ImageEditor/src/main/res/menu/menu_preview_fragment.xml
  libs/image-editor/ImageEditor/src/main/res/navigation/nav_graph.xml
  libs/image-editor/ImageEditor/src/main/res/values/strings.xml
  libs/image-editor/ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModelTest.kt
Labels: Media, Media Editing

#11646 Issue/11151 insert preview bottom bar
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerFragment.java
  WordPress/src/main/res/layout/photo_picker_fragment.xml
  WordPress/src/main/res/values/strings.xml
Labels: Media, Media Editing, [Status] Needs Code Review

#11691 Set My site fragment title to 'My site' instead of using site title
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/res/values/strings.xml
Labels: /My site, [Status] Needs Code Review, [Type] Task

#11677 Issue/11153 (multiple images) update preview imageview + thumbnail after crop
  build.gradle
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropFragment.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropViewModel.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageAdapter.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageFragment.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModel.kt
  libs/image-editor/ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/crop/CropViewModelTest.kt
Labels: Media Editing

#11702 Speed up suggestion insertion by using a single transaction
  WordPress/src/main/java/org/wordpress/android/datasets/SuggestionTable.java
Labels: Performance

#11708 Unified Login & Sign-Up: Create Sign-Up From Login functionality for Email + Magic Link method
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java
Labels: Unified Login & Sign-Up, [Status] Needs Code Review, [Status] Needs Design Review, [Type] Task

#11695 Issue/11153 insert multiple edited images into gutenberg
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/util/WPMediaUtils.java
  WordPress/src/main/res/values/strings.xml
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropFragment.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageFragment.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModel.kt
  libs/image-editor/ImageEditor/src/main/res/layout/preview_image_fragment.xml
  libs/image-editor/ImageEditor/src/main/res/values/dimens.xml
  libs/image-editor/ImageEditor/src/main/res/values/strings.xml
  libs/image-editor/ImageEditor/src/main/res/values/styles.xml
Labels: Media, gutenberg-mobile

#11711 Introduce kotlin to LoginFlow and bump libraries
  build.gradle
  libs/login/WordPressLoginFlow/build.gradle
  libs/utils/WordPressUtils/build.gradle
Labels: [Type] Enhancement

#11725 Issue/11724 app settings crash
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-v28/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  WordPress/src/main/res/values/strings.xml
Labels: [Pri] High, [Type] Crash

#11729 Added a new icon for unknown file type.
  WordPress/src/main/java/org/wordpress/android/util/WPMediaUtils.java
  WordPress/src/main/res/drawable/ic_image_multiple_white_24dp.xml
Labels: Media, [Status] Needs Code Review

#11731 Merge 14.6.1 to release/14.7
  WordPress/build.gradle
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-v28/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
Labels: releases

#11714 Merge 14.7 code freeze to develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
  build.gradle
Labels: releases

#11732 Merge 14.7-rc-2 to develop
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/util/WPMediaUtils.java
  WordPress/src/main/res/drawable/ic_image_multiple_white_24dp.xml
Labels: releases

#11700 Remove unnecessary title interface from basic fragments
  WordPress/src/main/java/org/wordpress/android/ui/main/MainToolbarFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainNavigationView.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
Labels: [Type] Enhancement

#11696 Issue/11153 fix file loading error and other issues in PR #11695
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/ImageEditorInitializer.kt
  WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt
  WordPress/src/main/res/values/strings.xml
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/ImageEditor.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropViewModel.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageFragment.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModel.kt
  libs/image-editor/ImageEditor/src/main/res/values/strings.xml
Labels: Media, Media Editing, [Status] Needs Code Review

#11690 Issue/11153 (multiple images) media editing - update tests
  libs/image-editor/ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/crop/CropViewModelTest.kt
  libs/image-editor/ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModelTest.kt
Labels: Media, Media Editing

#11734 Better manage OnPostUploaded event for reblog in WPMainActivity.
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
Labels: Reader, [Type] Enhancement

#11656 Prepublishing Nudges : Core State & Navigation Functionality with Tags screen integration
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/GetPostTagsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostSettingsTagsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingActionClickedListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingActionsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingActionsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingBottomSheetFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingHomeAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingHomeDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingHomeFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingHomeItemUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingHomeListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingHomeViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingScreenClosedListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingTagsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingTagsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/TagsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/UpdatePostTagsUseCase.kt
  WordPress/src/main/res/anim/prepublishing_fragment_fade_in.xml
  WordPress/src/main/res/anim/prepublishing_fragment_fade_out.xml
  WordPress/src/main/res/layout/post_prepublishing_bottom_sheet.xml
  WordPress/src/main/res/layout/post_prepublishing_home_fragment.xml
  WordPress/src/main/res/layout/prepublishing_action_list_item.xml
  WordPress/src/main/res/layout/prepublishing_tags_fragment.xml
  WordPress/src/main/res/layout/prepublishing_toolbar.xml
  WordPress/src/main/res/values/colors.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/ui/posts/PrepublishingActionsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PrepublishingHomeViewModelTest.kt
Labels: Prepublishing Nudges, [Type] Task

#11688 Prepublishing Nudges : Fetch tags on first launch
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingViewModel.kt
Labels: Prepublishing Nudges, [Status] Not Ready for Merge

#11728 Prepublishing Nudges : extract publish settings fragment & viewmodel
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PublishSettingsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PublishSettingsViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PublishSettingsViewModelTest.kt
Labels: Prepublishing Nudges, [Type] Task

#11710 Prepublishing Nudges : Publish scheduling
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostDatePickerDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostNotificationScheduleTimeDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostTimePickerDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingBottomSheetFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingHomeViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PublishSettingsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PublishSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/prepublishing/PrepublishingPublishSettingsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/prepublishing/PrepublishingPublishSettingsViewModel.kt
  WordPress/src/main/res/layout/prepublishing_published_settings_fragment.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/posts/PrepublishingHomeViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/prepublishing/PrepublishingPublishSettingsViewModelTest.kt
Labels: Prepublishing Nudges

#11716 Prepublishing ViewModel tests
  WordPress/src/test/java/org/wordpress/android/ui/posts/PrepublishingHomeViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/prepublishing/PrepublishingTagsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/prepublishing/PrepublishingViewModelTest.kt
Labels: Prepublishing Nudges, [Status] Not Ready for Merge, [Type] Task

#11738 Merge 14.7 release notes to develop
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: releases

#11737 Merge 14.7 release notes to master
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: releases

#11726 Issue/8319 copy comment url phase 1
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java
  WordPress/src/main/res/drawable/ic_more_horiz_white_24dp.xml
  WordPress/src/main/res/layout/comment_action_footer.xml
  WordPress/src/main/res/menu/menu_comment_more.xml
  WordPress/src/main/res/values/strings.xml
  build.gradle
Labels: [Status] In Progress, [Type] Enhancement

#11717 Unified Login & Sign-Up: Create Sign-Up From Login functionality for Google Sign-In method
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/res/values/strings.xml
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/GoogleFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginGoogleFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java
  libs/login/WordPressLoginFlow/src/main/res/values/strings.xml
Labels: Unified Login & Sign-Up, [Type] Task

#11753 Remove automated tagging from code_freeze lane
  fastlane/Fastfile
Labels: Tooling

#11762 Issue/8319 copy comment url
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java
  WordPress/src/main/res/drawable/ic_more_horiz_white_24dp.xml
  WordPress/src/main/res/layout/comment_action_footer.xml
  WordPress/src/main/res/menu/menu_comment_more.xml
  WordPress/src/main/res/values/strings.xml
  build.gradle
Labels: Comments, [Type] Enhancement

#11761 Make notifications list title static
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java
Labels: [Type] Bug

#11757 Fix toolbar titles in PhotoPicker
  RELEASE-NOTES.txt
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerFragment.java
  WordPress/src/main/res/values/strings.xml
Labels: Media, Posting/Editing, [Type] Bug

#11740 Issue/11739 whats new feature flag and link to what's new announcement
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/res/values/key_strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/app_settings.xml
Labels: What's New, [Status] Needs Code Review

#11721 Smart lock from prologue
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
Labels: Unified Login & Sign-Up, [Type] Task

#11764 Merge 14.7-rc-3 to develop
  WordPress/build.gradle
Labels: releases

#11755 Update quick start subtitle size.
  WordPress/src/main/res/values/styles.xml
Labels: Dark Mode, [Status] Needs Code Review

#11719 Prepublishing Nudges : bottom sheet shown only once.
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/test/java/org/wordpress/android/ui/posts/prepublishing/PrepublishingTagsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/prepublishing/PrepublishingViewModelTest.kt
Labels: Prepublishing Nudges, [Type] Task

#11678 Issue/11633 material placeholders
  WordPress/src/main/java/org/wordpress/android/ui/AddQuickPressShortcutActivity.java
  WordPress/src/main/java/org/wordpress/android/util/image/ImagePlaceholderManager.kt
  WordPress/src/main/res/drawable/bg_oval_placeholder.xml
  WordPress/src/main/res/drawable/bg_oval_placeholder_user_32dp.xml
  WordPress/src/main/res/drawable/bg_oval_placholder_plans_32dp.xml
  WordPress/src/main/res/drawable/bg_rectangle_placeholder_globe_32dp.xml
  WordPress/src/main/res/drawable/bg_rectangle_placeholder_radius_2dp.xml
  WordPress/src/main/res/drawable/bg_rectangle_placeholder_themes_100dp.xml
  WordPress/src/main/res/drawable/bg_rectangle_placeholder_user_32dp.xml
  WordPress/src/main/res/drawable/plugin_placeholder.xml
  WordPress/src/main/res/layout/activity_log_item_detail.xml
  WordPress/src/main/res/layout/history_list_item.xml
  WordPress/src/main/res/layout/login_epilogue_sites_listitem.xml
  WordPress/src/main/res/layout/my_site_fragment.xml
  WordPress/src/main/res/layout/notifications_list_item.xml
  WordPress/src/main/res/layout/plan_details_fragment.xml
  WordPress/src/main/res/layout/plans_list_item.xml
  WordPress/src/main/res/layout/plugin_detail_activity.xml
  WordPress/src/main/res/layout/publicize_listitem_connection.xml
  WordPress/src/main/res/layout/publicize_listitem_service.xml
  WordPress/src/main/res/layout/reader_cardview_post.xml
  WordPress/src/main/res/layout/reader_cardview_xpost.xml
  WordPress/src/main/res/layout/reader_comments_post_header_view.xml
  WordPress/src/main/res/layout/reader_listitem_blog.xml
  WordPress/src/main/res/layout/reader_listitem_comment.xml
  WordPress/src/main/res/layout/reader_post_detail_header_view.xml
  WordPress/src/main/res/layout/reader_simple_post_view.xml
  WordPress/src/main/res/layout/reader_site_header_view.xml
  WordPress/src/main/res/layout/reader_site_search_result.xml
  WordPress/src/main/res/layout/site_picker_listitem.xml
  WordPress/src/main/res/layout/stats_block_list_item.xml
  WordPress/src/main/res/layout/theme_grid_item.xml
  WordPress/src/main/res/layout/wpwebview_activity.xml
  WordPress/src/main/res/values-night/colors.xml
  WordPress/src/main/res/values/colors.xml
Labels: Dark Mode, [Status] Needs Code Review

#11758 Issue/track media editor events
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/ImageEditorInitializer.kt
  WordPress/src/main/java/org/wordpress/android/util/WPMediaUtils.java
  build.gradle
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
  libs/image-editor/ImageEditor/build.gradle
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/EditImageActivity.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/ImageEditor.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropFragment.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropViewModel.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageFragment.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModel.kt
  libs/image-editor/ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/crop/CropViewModelTest.kt
  libs/image-editor/ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModelTest.kt
  libs/image-editor/ImageEditor/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: Media, Media Editing

#11773 Use shared debug store
  .configure
  .configure-files/automattic.jks.enc
  .configure-files/debug.keystore.enc
  .configure-files/gradle.properties.enc
  .gitignore
  Gemfile
  Gemfile.lock
  WordPress/build.gradle
  fastlane/Pluginfile
Labels: Tooling

#11784 Update lifecycle version
  WordPress/build.gradle
  build.gradle
Labels: [Type] Task

#11786 Fix copy string lint issue
  WordPress/src/main/java/org/wordpress/android/ui/AppLogViewerActivity.java
  WordPress/src/main/res/layout/media_settings_activity.xml
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-hi/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-kmr/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-ms/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  WordPress/src/main/res/values/strings.xml
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageFragment.kt
Labels: [Type] Bug

#11787 Downgrade nav component to 2̶.̶2̶.̶0̶ 2.0.0
  build.gradle
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/EditImageActivity.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/EditImageViewModel.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropFragment.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageFragment.kt
Labels: Media, Media Editing, [Type] Enhancement

#11781 Extract image editor tracking to a separate class
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/ImageEditorInitializer.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/ImageEditorTracker.kt
Labels: Media, Media Editing

#11793 Media editing fix tracking
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerActivity.java
Labels: Analytics, Media Editing

#11707 Added a focused state to cover Header and List toolbar buttons.
  WordPress/src/main/res/color/aztec_format_button_selector_color.xml
  WordPress/src/main/res/color/on_surface_emphasis_lowest.xml
  WordPress/src/main/res/values-night/styles.xml
  WordPress/src/main/res/values/styles.xml
Labels: Aztec, Dark Mode, [Status] Needs Code Review

#11788 Adding reblog dedicated tracking events.
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/PagePostCreationSourcesDetail.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Reader, [Type] Enhancement

#11770 Issue/11769 feature announcement dialog
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/whatsnew/FeatureAnnouncementDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/whatsnew/FeatureAnnouncementViewModel.kt
  WordPress/src/main/res/layout/feature_announcement_dialog_fragment.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/whatsnew/FeatureAnnouncementViewModelTest.kt
Labels: What's New, [Status] Needs Code Review
