Repository wordpress-mobile/WordPress-Android, pull requests merged in 2020-03, with the labels that each got.

#11385 Remove the Gutenberg dialog on new sites
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
Labels: gutenberg-mobile

#11378 Issue/10203 img local path
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostUtilsUnitTest.kt
Labels: Media, Posting/Editing, [Type] Bug

#11366 Issue/updating material reader bottom sheet
  WordPress/src/main/java/org/wordpress/android/ui/reader/SubfilterBottomSheetFragment.kt
  WordPress/src/main/res/color/primary_on_surface_selector.xml
  WordPress/src/main/res/drawable/bg_bottom_sheet_handle.xml
  WordPress/src/main/res/drawable/bg_bottom_sheet_handle_container.xml
  WordPress/src/main/res/layout/bottom_sheet_handle_view.xml
  WordPress/src/main/res/layout/subfilter_bottom_sheet.xml
  WordPress/src/main/res/values-v27/styles.xml
  WordPress/src/main/res/values/styles.xml
Labels: Dark Mode, [Status] Needs Code Review, [Status] Needs Design Review

#11373 Issue/material stats widget configuration
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/AddQuickPressShortcutActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/alltime/StatsAllTimeWidgetConfigureActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetColorSelectionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetDataTypeSelectionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetSiteSelectionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/minified/StatsMinifiedWidgetConfigureActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/StatsTodayWidgetConfigureActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/StatsViewsWidgetConfigureActivity.kt
  WordPress/src/main/res/drawable/list_divider.xml
  WordPress/src/main/res/layout/add_quickpress_shortcut.xml
  WordPress/src/main/res/layout/home_row.xml
  WordPress/src/main/res/layout/quick_press_input_dialog.xml
  WordPress/src/main/res/layout/quick_press_widget_configure_list_row.xml
  WordPress/src/main/res/layout/quickpress_widget_configure_activity.xml
  WordPress/src/main/res/layout/stats_all_time_widget_configure_activity.xml
  WordPress/src/main/res/layout/stats_color_selector.xml
  WordPress/src/main/res/layout/stats_data_type_selector.xml
  WordPress/src/main/res/layout/stats_minified_widget_configure_activity.xml
  WordPress/src/main/res/layout/stats_today_widget_configure_activity.xml
  WordPress/src/main/res/layout/stats_views_widget_configure_activity.xml
  WordPress/src/main/res/layout/stats_widget_configure_fragment.xml
  WordPress/src/main/res/layout/stats_widget_site_selector_item.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/values/strings.xml
Labels: Dark Mode, Stats, [Status] Needs Code Review, [Status] Needs Design Review

#11375 Dark SwipeRefreshLayout Indicator
  WordPress/src/main/java/org/wordpress/android/util/WPSwipeToRefreshHelper.java
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/helpers/SwipeToRefreshHelper.java
Labels: Dark Mode

#11417 Update Nokogiri to 1.10.9 to fix a warning
  Gemfile.lock
Labels: Tooling

#11419 Fix QuickStart dialog configuration change issue
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
Labels: /My site, [Type] Bug

#11423 Open blogs in external browser with custom domains
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
Labels: Post List, Webviews

#11427 Issue/11422 quick start weight
  WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt
Labels: NUX, [Status] Needs Code Review, [Type] Enhancement

#11426 Merge 14.4 code freeze and release notes into develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: releases

#11411 Add editor session startup time
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostEditorAnalyticsSession.java
Labels: Analytics, Performance, gutenberg-mobile

#11383 Fixing clickable state of notifications
  WordPress/src/main/res/layout/notifications_list_item.xml
Labels: Dark Mode, Notifications, [Status] Needs Code Review

#11445 [hackweek march2020] rename some string ids to help translators
  WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListType.kt
  WordPress/src/main/res/values/strings.xml
Labels: Localization

#11382 Update notifications styles
  WordPress/src/main/java/org/wordpress/android/ui/notifications/adapters/NotesAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/blocks/NoteBlockClickableSpan.java
  WordPress/src/main/java/org/wordpress/android/widgets/BadgedImageView.kt
  WordPress/src/main/res/drawable/bg_oval_neutral_20.xml
  WordPress/src/main/res/drawable/bg_oval_neutral_20_stroke_surface.xml
  WordPress/src/main/res/drawable/bg_oval_warning_dark.xml
  WordPress/src/main/res/layout/notifications_list_item.xml
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/dimens.xml
  build.gradle
Labels: Notifications, [Status] Needs Code Review

#11429 [Site Creation] Step 1: Remove verticals suggestions display
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/usecases/FetchVerticalsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationVerticalsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationVerticalsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationVerticalsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationVerticalsViewModel.kt
  WordPress/src/main/res/layout/site_creation_verticals_custom_suggestion_item.xml
  WordPress/src/main/res/layout/site_creation_verticals_screen.xml
  WordPress/src/main/res/layout/site_creation_verticals_suggestion_item.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/usecases/FetchVerticalsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationVerticalsViewModelTest.kt
Labels: Site Creation

#11178 Issue 9854 implement site creation dynamic texts experience
  WordPress/src/androidTest/java/org/wordpress/android/util/helpers/DynamicTextsProgressionHelperTest.kt
  WordPress/src/debug/AndroidManifest.xml
  WordPress/src/debug/java/org/wordpress/android/testing/TestActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SiteCreationPreviewFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/helpers/DynamicTextsProgressionHelper.kt
  WordPress/src/main/res/layout/progress_layout.xml
  WordPress/src/main/res/layout/site_creation_progress_text.xml
  WordPress/src/main/res/values/strings.xml
Labels: Site Creation, [Type] Enhancement

#11416 PageListDialogHelper shared events with pages now have a post type to differentiate
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListDialogHelper.kt
Labels: Post List, [Type] Enhancement

#11438 Fix NPE in Photo picker
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerFragment.java
Labels: [Type] Crash

#11434 [Site Creation] Step 1: Remove header and search input segments
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/usecases/FetchSegmentPromptUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationVerticalsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationVerticalsViewModel.kt
  WordPress/src/main/res/layout/site_creation_verticals_screen.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/usecases/FetchSegmentsPromptUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationVerticalsViewModelTest.kt
Labels: Site Creation

#11442 Fix crash on multiple tab selection
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
Labels: [Type] Crash

#11446 Fix crash when user creates a site after trying to sign up with an existing Google account
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
Labels: [Status] Needs Code Review, [Type] Crash

#11452 Docs: Add link to TalkBack Guidelines in Home
  docs/README.md
Labels: Documentation

#11440 [Site Creation] Step 2: Remove site info site creation step
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVM.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationStep.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/siteinfo/SiteCreationSiteInfoFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/siteinfo/SiteInfoScreenListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationSiteInfoViewModel.kt
  WordPress/src/main/res/layout/site_creation_site_info_screen.xml
  WordPress/src/main/res/layout/site_creation_skip_button_container.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVMTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/siteinfo/SiteCreationSiteInfoViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/siteinfo/SiteInfoUiStateTest.kt
  WordPress/src/test/java/org/wordpress/android/util/wizard/WizardManagerTest.kt
Labels: Site Creation

#11441 [Site Creation] Step 2: Remove site title and tagline in site creation
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVM.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/services/SiteCreationServiceData.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/services/SiteCreationServiceManager.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/usecases/CreateSiteUseCase.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/previews/CreateSiteUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/services/SiteCreationServiceManagerTest.kt
  build.gradle
Labels: Site Creation

#11395 Refactor image preview and crop features to use nav args
  ImageEditor/build.gradle
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropFragment.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropViewModel.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageFragment.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModel.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/utils/CropUtil.kt
  ImageEditor/src/main/res/navigation/nav_graph.xml
  ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/crop/CropViewModelTest.kt
  ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModelTest.kt
  build.gradle
Labels: Media, Media Editing

#11450 Align method signature to account for null possible values.
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderBlogTableWrapper.kt
Labels: Reader, [Type] Crash

#11392 Issue/11384 show done button on the crop screen
  ImageEditor/build.gradle
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/EditImageActivity.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropFragment.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropViewModel.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageFragment.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModel.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/utils/CropUtil.kt
  ImageEditor/src/main/res/drawable/ic_done_white_24dp.xml
  ImageEditor/src/main/res/layout/fragment_crop_image.xml
  ImageEditor/src/main/res/menu/menu_crop_fragment.xml
  ImageEditor/src/main/res/navigation/nav_graph.xml
  ImageEditor/src/main/res/values/strings.xml
  ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/crop/CropViewModelTest.kt
  ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModelTest.kt
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/RequestCodes.java
  build.gradle
Labels: Media, Media Editing

#11404 Issue/11387 update crop screen design
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropViewModel.kt
  ImageEditor/src/main/res/layout/activity_edit_image.xml
  ImageEditor/src/main/res/layout/fragment_preview_image.xml
  ImageEditor/src/main/res/values/colors.xml
  ImageEditor/src/main/res/values/styles.xml
Labels: Media, Media Editing

#11408 Fix/handle done menu visibility and crop error
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropFragment.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropViewModel.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/utils/ToastUtils.java
  ImageEditor/src/main/res/values/strings.xml
  ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/crop/CropViewModelTest.kt
Labels: Media, Media Editing

#11433 Comments : Prevent empty comment submission
  WordPress/src/main/java/org/wordpress/android/ui/CommentFullScreenDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderCommentListActivity.java
Labels: Comments, [Type] Enhancement

#11431 Me/ Profile - Change Photo - Image Preview Fix
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaPreviewFragment.java
  WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/UrlUtils.java
Labels: /Me, [Type] Bug

#11430 Sharing: Consistent messaging in Publicize to Facebook Page Error
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeConstants.java
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeErrorDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListActivity.java
  WordPress/src/main/res/layout/publicize_detail_fragment.xml
  WordPress/src/main/res/values/strings.xml
Labels: Sharing, [Type] Enhancement

#11447 Use event wrapper for single actions on crop screen
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropFragment.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropViewModel.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/viewmodel/Event.kt
  ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/crop/CropViewModelTest.kt
Labels: Media, Media Editing

#11353 Offline Pages : Scroll To Page Once Edited
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PagesViewModelTest.kt
Labels: Offline Support, Pages List, [Type] Enhancement

#11398 Offline Pages : Code Refactoring, Phase 1
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/CreatePageListItemActionsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/CreatePageListItemLabelsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageItemProgressUiStateUseCase.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PostModelUploadUiStateUseCase.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PostPageListLabelColorUseCase.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/SearchListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/CreatePageListItemActionsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/CreatePageListItemLabelsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PageListViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/SearchListViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListViewModelTest.kt
Labels: Offline Support, Pages List, [Type] Enhancement

#11399 Offline Pages : Code Refactoring, Phase 2
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/AutoSaveConflictResolver.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/CreatePageListItemLabelsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PostPageListLabelColorUseCase.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/CreatePageListItemLabelsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PagesViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PostPageListLabelColorUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Offline Support, Pages List, [Status] Not Ready for Merge, [Type] Enhancement

#11460 Update single domains step title
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVM.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/OnSkipClickedListener.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVMTest.kt
Labels: Site Creation

#11453 Issue/material insight management
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/management/InsightsManagementAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/management/InsightsManagementViewHolder.kt
  WordPress/src/main/res/layout/insights_management_header_item.xml
  WordPress/src/main/res/layout/insights_management_list_item.xml
  WordPress/src/main/res/values/stats_styles.xml
Labels: Dark Mode, Stats, [Status] Needs Code Review

#11474 Fix image transparency issue
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropFragment.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropViewModel.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageFragment.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModel.kt
  ImageEditor/src/main/res/navigation/nav_graph.xml
  ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/crop/CropViewModelTest.kt
  ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModelTest.kt
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Media, Media Editing

#11475 Update release notes for site creation steps removal
  RELEASE-NOTES.txt
Labels: Site Creation

#11472 Offline Support : Post List - Fix Upload Status Cache issue
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModelConnector.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/AutoSavePostIfNotDraftUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListViewModelTest.kt
Labels: Offline Support, Post List, [Type] Bug

#11470 Apply an unelevated card style to stats cards
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ManagementControlUseCase.kt
  WordPress/src/main/res/color/on_surface_divider.xml
  WordPress/src/main/res/layout/stats_list_block.xml
  WordPress/src/main/res/layout/stats_loading_view.xml
  WordPress/src/main/res/values-w528dp/dimens.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/styles.xml
Labels: Dark Mode, [Status] Needs Code Review, [Status] Needs Design Review, [Type] Enhancement

#11478 Fix failed uploads being retried indefinitely
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
Labels: Posting/Editing

#11477 Use remoteId instead of localId in AutoSavePostIfNotDraftUseCase
  WordPress/src/main/java/org/wordpress/android/ui/uploads/AutoSavePostIfNotDraftUseCase.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/AutoSavePostIfNotDraftUseCaseTest.kt
  build.gradle
Labels: Pages List, [Type] Crash

#11461 Update release notes for offline pages
  RELEASE-NOTES.txt
  WordPress/src/test/java/org/wordpress/android/ui/posts/AutoSavePostIfNotDraftUseCaseTest.kt
Labels: Offline Support, Pages List

#11473 Offline Support : Pages - Update publish snackbar copy
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/main/res/values/strings.xml
Labels: Offline Support, Pages List, [Type] Enhancement

#11459 Handle image load failure on preview screen
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageFragment.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModel.kt
  ImageEditor/src/main/res/drawable/ic_retry_white_24dp.xml
  ImageEditor/src/main/res/layout/fragment_preview_image.xml
  ImageEditor/src/main/res/layout/layout_retry.xml
  ImageEditor/src/main/res/values/dimens.xml
  ImageEditor/src/main/res/values/strings.xml
  ImageEditor/src/main/res/values/styles.xml
  ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModelTest.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/res/layout/edit_post_settings_fragment.xml
Labels: Media, Media Editing

#11421 Site Creation Remove Verticals and Site Info Steps - Master Issue
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVM.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationStep.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/OnSkipClickedListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SiteCreationTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/services/SiteCreationServiceData.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/services/SiteCreationServiceManager.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/siteinfo/SiteCreationSiteInfoFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/siteinfo/SiteInfoScreenListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/usecases/CreateSiteUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/usecases/FetchSegmentPromptUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/usecases/FetchVerticalsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationSiteInfoViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationVerticalsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationVerticalsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationVerticalsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationVerticalsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/VerticalsScreenListener.kt
  WordPress/src/main/res/layout/site_creation_site_info_screen.xml
  WordPress/src/main/res/layout/site_creation_skip_button_container.xml
  WordPress/src/main/res/layout/site_creation_verticals_custom_suggestion_item.xml
  WordPress/src/main/res/layout/site_creation_verticals_screen.xml
  WordPress/src/main/res/layout/site_creation_verticals_suggestion_item.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVMTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/previews/CreateSiteUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/services/SiteCreationServiceManagerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/siteinfo/SiteCreationSiteInfoViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/siteinfo/SiteInfoUiStateTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/usecases/FetchSegmentsPromptUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/usecases/FetchVerticalsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationVerticalsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/util/wizard/WizardManagerTest.kt
  build.gradle
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Site Creation, [Type] Task

#11480 Issue/disabling battery saver theme change on older devices
  WordPress/src/main/java/org/wordpress/android/util/AppThemeUtils.kt
  WordPress/src/main/res/values-v28/strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/app_settings.xml
Labels: Dark Mode, [Status] Needs Code Review

#11492 Fixes NullPointerException in onDiscoverySucceeded
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginBaseDiscoveryFragment.java
Labels: Login, [Pri] High, [Type] Crash

#11489 Use HashMap instead of SparseArray
  WordPress/lint.xml
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFeaturedImageTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListUploadStatusTracker.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
Labels: Post List, [Type] Crash

#11457 Check user rights to create content to give access to main bottom sheet
  WordPress/src/main/java/org/wordpress/android/ui/WPTooltipView.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MainFabUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModelTest.kt
Labels: Posting/Editing, [Type] Bug

#11493 Fix crash due to Uri support in ImageManager
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/ImageEditorInitializer.kt
Labels: Media Editing

#11497 Adding reader_tag_loaded event when user selects a tag in subfilter.
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
Labels: Analytics, [Type] Bug

#11484 Fix changesConfirmed flag on page list
  build.gradle
Labels: Offline Support, Pages List, Posting/Editing

#11502 Update FluxC to 1.6.8
  build.gradle
Labels: General

#11504 Merge 14.5 code freeze to develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
Labels: releases

#11503 Issue/fix aztec gallery dialog
  WordPress/src/main/java/org/wordpress/android/ui/posts/InsertMediaDialog.java
  WordPress/src/main/res/layout/insert_media_dialog.xml
  WordPress/src/main/res/values/styles_calypso.xml
Labels: Dark Mode, [Status] Needs Code Review

#11509 Move image editor library inside libs
  ImageEditor/.gitignore
  WordPress/build.gradle
  libs/image-editor/.gitignore
  libs/image-editor/ImageEditor/build.gradle
  libs/image-editor/ImageEditor/proguard-rules.pro
  libs/image-editor/ImageEditor/src/androidTest/kotlin/org/wordpress/android/imageeditor/ExampleInstrumentedTest.kt
  libs/image-editor/ImageEditor/src/main/AndroidManifest.xml
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/EditImageActivity.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/ImageEditor.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropFragment.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropViewModel.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageFragment.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModel.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/utils/ToastUtils.java
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/utils/UiHelpers.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/viewmodel/Event.kt
  libs/image-editor/ImageEditor/src/main/res/drawable/ic_done_white_24dp.xml
  libs/image-editor/ImageEditor/src/main/res/drawable/ic_retry_white_24dp.xml
  libs/image-editor/ImageEditor/src/main/res/layout/activity_edit_image.xml
  libs/image-editor/ImageEditor/src/main/res/layout/fragment_crop_image.xml
  libs/image-editor/ImageEditor/src/main/res/layout/fragment_preview_image.xml
  libs/image-editor/ImageEditor/src/main/res/layout/layout_retry.xml
  libs/image-editor/ImageEditor/src/main/res/menu/menu_crop_fragment.xml
  libs/image-editor/ImageEditor/src/main/res/navigation/nav_graph.xml
  libs/image-editor/ImageEditor/src/main/res/values/colors.xml
  libs/image-editor/ImageEditor/src/main/res/values/dimens.xml
  libs/image-editor/ImageEditor/src/main/res/values/strings.xml
  libs/image-editor/ImageEditor/src/main/res/values/styles.xml
  libs/image-editor/ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/crop/CropViewModelTest.kt
  libs/image-editor/ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModelTest.kt
  libs/image-editor/build.gradle
  libs/image-editor/gradle/wrapper/gradle-wrapper.jar
  libs/image-editor/gradle/wrapper/gradle-wrapper.properties
  libs/image-editor/gradlew
  libs/image-editor/gradlew.bat
  libs/image-editor/settings.gradle
  settings.gradle
Labels: Media Editing

#11516 Track media editor events
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Media Editing

#11521 Feature/master pages offline support
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageItemDiffUtil.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageSearchAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/SearchListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostModelUploadStatusTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/adapters/PostListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/UiHelpers.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/UiString.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/AutoSaveConflictResolver.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/CreatePageListItemActionsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/CreatePageListItemLabelsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageItemProgressUiStateUseCase.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListDialogHelper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListEventListener.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PostModelUploadUiStateUseCase.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PostPageListLabelColorUseCase.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/SearchListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemType.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModelConnector.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/uistate/ProgressBarUiState.kt
  WordPress/src/main/res/layout/page_list_item.xml
  WordPress/src/main/res/menu/page_more.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadUtilsTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/CreatePageListItemActionsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/CreatePageListItemLabelsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PageItemProgressUiStateUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PageListViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PagesViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PostPageListLabelColorUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/SearchListViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListViewModelTest.kt
  build.gradle
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Offline Support, Pages List

#11512 Remove crash when RecyclerView is already gone on view click
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderBlogAdapter.java
Labels: [Type] Crash

#11495 Testing: Switch connected tests to develop and release branches only
  .circleci/config.yml
Labels: Testing, [Status] Needs Code Review

#11514 Fix IndexOutOfBoundsException in ReaderPostAdapter
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java
Labels: [Type] Crash

#11520 Use custom image picker in gutenberg
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserType.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Gutenberg, Media, Media Editing, Posting/Editing

#11526 Update release notes for media editing in block editor
  RELEASE-NOTES.txt
Labels: Media Editing

#11505 Issue/use material alert dialog
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/NotificationsUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostNotificationScheduleTimeDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/DeleteSiteDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeErrorDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/util/SelfSignedSSLUtils.java
  WordPress/src/main/java/org/wordpress/android/util/WPPermissionUtils.java
  WordPress/src/main/java/org/wordpress/android/widgets/AppRatingDialog.kt
  WordPress/src/main/java/org/wordpress/android/widgets/AuthErrorDialogFragment.java
  WordPress/src/main/res/drawable/bg_rectangle_divider.xml
  WordPress/src/main/res/values/styles_calypso.xml
  libs/editor/WordPressEditor/build.gradle
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/ImageSettingsDialogFragment.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/LinkDialogFragment.java
  libs/editor/WordPressEditor/src/main/res/values/styles.xml
Labels: Dark Mode, [Status] Needs Code Review

#11507 Issue/nuke calypso styles
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/res/values/styles_calypso.xml
Labels: Dark Mode, [Status] Needs Code Review

#11101 Media Editing Basics Phase One - Master Issue
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/RequestCodes.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/ImageEditorInitializer.kt
  WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt
  WordPress/src/main/res/layout/edit_post_settings_fragment.xml
  build.gradle
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorEditMediaListener.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragmentAbstract.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java
  libs/image-editor/.gitignore
  libs/image-editor/ImageEditor/build.gradle
  libs/image-editor/ImageEditor/proguard-rules.pro
  libs/image-editor/ImageEditor/src/main/AndroidManifest.xml
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/EditImageActivity.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/ImageEditor.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropFragment.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/crop/CropViewModel.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageFragment.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModel.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/utils/ToastUtils.java
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/utils/UiHelpers.kt
  libs/image-editor/ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/viewmodel/Event.kt
  libs/image-editor/ImageEditor/src/main/res/drawable/ic_done_white_24dp.xml
  libs/image-editor/ImageEditor/src/main/res/drawable/ic_retry_white_24dp.xml
  libs/image-editor/ImageEditor/src/main/res/layout/activity_edit_image.xml
  libs/image-editor/ImageEditor/src/main/res/layout/fragment_crop_image.xml
  libs/image-editor/ImageEditor/src/main/res/layout/fragment_preview_image.xml
  libs/image-editor/ImageEditor/src/main/res/layout/layout_retry.xml
  libs/image-editor/ImageEditor/src/main/res/menu/menu_crop_fragment.xml
  libs/image-editor/ImageEditor/src/main/res/navigation/nav_graph.xml
  libs/image-editor/ImageEditor/src/main/res/values/colors.xml
  libs/image-editor/ImageEditor/src/main/res/values/dimens.xml
  libs/image-editor/ImageEditor/src/main/res/values/strings.xml
  libs/image-editor/ImageEditor/src/main/res/values/styles.xml
  libs/image-editor/ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/crop/CropViewModelTest.kt
  libs/image-editor/ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModelTest.kt
  libs/image-editor/build.gradle
  libs/image-editor/gradle/wrapper/gradle-wrapper.jar
  libs/image-editor/gradle/wrapper/gradle-wrapper.properties
  libs/image-editor/gradlew
  libs/image-editor/gradlew.bat
  libs/image-editor/settings.gradle
  settings.gradle
Labels: Media Editing, [Type] Enhancement

#11524 Fix and run WordPressUtils Tests
  .circleci/config.yml
  libs/utils/WordPressUtils/build.gradle
  libs/utils/WordPressUtils/src/androidTest/java/org/wordpress/android/util/ImageUtilsTest.java
  libs/utils/WordPressUtils/src/androidTest/java/org/wordpress/android/util/JSONUtilsTest.java
  libs/utils/WordPressUtils/src/androidTest/java/org/wordpress/android/util/ShortcodeUtilsTest.java
  libs/utils/WordPressUtils/src/androidTest/java/org/wordpress/android/util/UrlUtilsTest.java
Labels: Testing

#11528 Issue/nuke calypso styles
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/res/values/styles_calypso.xml
Labels: Dark Mode, [Status] Needs Code Review

#11443 Remove unnecessary errors from missing jetpack version
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  WordPress/src/test/java/org/wordpress/android/util/SiteUtilsTest.kt
Labels: [Type] Bug

#11527 Issue/11518 enable custom picker for video and Text&Media blocks
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserType.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Gutenberg, Media, Media Editing, Posting/Editing

#11530 Temporarily disable Editor UI tests
  WordPress/src/androidTest/java/org/wordpress/android/e2e/EditorTests.java
Labels: Posting/Editing, Testing

#11482 Add MediaEditor into localization script
  WordPress/src/main/res/values/strings.xml
  fastlane/Fastfile
Labels: Media Editing

#11549 Merge/14.4.1 to release/14.5
  RELEASE-NOTES.txt
  WordPress/build.gradle
Labels: releases

#11534 Add reblog to Reader Post Details
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/PagePostCreationSourcesDetail.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderIconCountView.java
  WordPress/src/main/java/org/wordpress/android/util/ReblogUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/UrlUtilsWrapper.kt
  WordPress/src/main/res/layout/reader_activity_post_pager.xml
  WordPress/src/main/res/layout/reader_include_post_detail_footer.xml
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/util/ReblogUtilsTest.kt
Labels: Reader, [Type] Enhancement

#11551 Merge release/14.5-rc-2 to develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: releases

#11550 Untangle http:// and wordpress:// deeplinking URLs
  RELEASE-NOTES.txt
  WordPress/src/main/AndroidManifest.xml
Labels: Core

#11559 Fix empty stats in post detail
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostAverageViewsPerDayUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostMonthsAndYearsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostRecentWeeksUseCase.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostAverageViewsPerDayUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostMonthsAndYearsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostRecentWeeksUseCaseTest.kt
Labels: Stats, [Type] Bug
