Repository wordpress-mobile/WordPress-Android, pull requests merged in 2020-01, with the labels that each got.

#10998 Issue/10151 add tracks to post settings featured image actions
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/FeaturedImageHelper.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Analytics, [Type] Task

#11035 Replace recursion with inline logic to fix stack overflow
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtils.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtilsTest.kt
Labels: Stats Refresh, [Type] Crash

#10996 Consolidate post saving in one place
  WordPress/src/main/java/org/wordpress/android/ui/notifications/receivers/NotificationsPendingDraftsReceiver.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/PendingDraftsNotificationsUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostSettingsUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/SavePostToDbUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/AztecEditorFragmentStaticWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/EditorMedia.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/RemoveMediaUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/main/java/org/wordpress/android/util/DateTimeUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/EditPostRepositoryTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/EditPostViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostSettingsUtilsTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/SavePostToDbUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/media/EditorMediaTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
  libs/editor/WordPressEditor/build.gradle
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/LiveTextWatcher.java
Labels: Posting/Editing, [Type] Enhancement

#11032 Bump Gutenberg progressive rollout phase 1 from 30 to 100%
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
Labels: gutenberg-mobile

#11038 Add tests for RemoveMediaUseCase
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/RemoveMediaUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadServiceFacade.kt
  WordPress/src/main/java/org/wordpress/android/util/MediaUtilsWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/media/RemoveMediaUseCaseTest.kt
Labels: Media, Posting/Editing

#11044 Merge release/13.9 to develop after 13.9-rc-2 beta release
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtilsTest.kt
Labels: releases

#10943 Issue/10636 material theme browser
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserFragment.java
  WordPress/src/main/res/layout-sw600dp/theme_grid_cardview_header.xml
  WordPress/src/main/res/layout/theme_browser_activity.xml
  WordPress/src/main/res/layout/theme_browser_fragment.xml
  WordPress/src/main/res/layout/theme_grid_cardview_header.xml
  WordPress/src/main/res/layout/theme_grid_item.xml
  WordPress/src/main/res/values-night/styles.xml
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/styles.xml
Labels: Dark Mode, Themes, [Status] Needs Code Review

#10955 Issue/10637 material people management
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/FilteredRecyclerView.java
  WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/people/PeopleListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/people/PeopleManagementActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/people/PersonDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/people/RoleChangeDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/people/RoleSelectDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/widgets/MultiUsernameEditText.java
  WordPress/src/main/res/drawable-ldrtl/people_list_divider.xml
  WordPress/src/main/res/drawable/people_list_divider.xml
  WordPress/src/main/res/layout/filtered_list_component.xml
  WordPress/src/main/res/layout/people_invite_error_view.xml
  WordPress/src/main/res/layout/people_invite_fragment.xml
  WordPress/src/main/res/layout/people_list_fragment.xml
  WordPress/src/main/res/layout/people_list_row.xml
  WordPress/src/main/res/layout/people_management_activity.xml
  WordPress/src/main/res/layout/person_detail_fragment.xml
  WordPress/src/main/res/layout/role_list_row.xml
  WordPress/src/main/res/layout/toolbar_main.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/styles.xml
Labels: Dark Mode, People Management, [Status] Needs Code Review

#11015 Site Creation Domain Selection Layout Fix
  WordPress/src/main/res/layout/site_creation_domains_item.xml
Labels: Site Creation, [Pri] Medium, [Type] Bug

#11033 Remove all item decorations to fix post list items spacing issues
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFragment.kt
Labels: Post List, [Type] Bug

#10781 Add @username suggestions to notification and reader full comment view.
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/CommentFullScreenDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderCommentListActivity.java
  WordPress/src/main/res/layout/comment_dialog_fragment.xml
Labels: Comments, [Status] Needs Design Review

#11027 Accessibility : Aztec UI Improvements
  libs/editor/WordPressEditor/src/main/res/values/colors.xml
Labels: Accessibility, Aztec, [Status] Needs Design Review, [Type] Enhancement

#10959 Add tests for featured image support in EditPostSettings
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/FeaturedImageHelper.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/FeaturedImageHelperTest.kt
Labels: Media, Posting/Editing, Tech debt

#11047 Move onMediaDeleted logic into EditorMedia
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/EditorMedia.kt
Labels: Media, Posting/Editing, Tech debt

#11042 QuickStart review for ia changes
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartMySitePrompts.kt
  WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartTaskDetails.java
  WordPress/src/main/res/layout/my_site_fragment.xml
  WordPress/src/main/res/values/strings.xml
Labels: IA, [Type] Enhancement

#11046 Accessibility : Free Photo Library Crash Fix
  WordPress/src/main/res/layout/media_picker_thumbnail.xml
  libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/AccessibilityUtils.java
Labels: Accessibility, Media

#11037 Master edit post activity refactoring
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/receivers/NotificationsPendingDraftsReceiver.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/PendingDraftsNotificationsUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/PendingDraftsNotificationsUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostSettingsUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/SavePostToDbUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/StorePostViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/EditorMedia.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/RemoveMediaUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadServiceFacade.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtils.java
  WordPress/src/main/java/org/wordpress/android/util/DateTimeUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/MediaUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/EditPostRepositoryTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostSettingsUtilsTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/SavePostToDbUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/StorePostViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/media/EditorMediaTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/media/RemoveMediaUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/GutenbergEditorFragment.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/LiveTextWatcher.java
Labels: Posting/Editing, [Type] Enhancement

#11058 Bump FluxC to version 1.5.8
  build.gradle
Labels: Posting/Editing

#11029 Fix #10747: Gutenberg rollout phase 2
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  WordPress/src/main/res/values/strings.xml
  build.gradle
Labels: gutenberg-mobile

#11045 Track gutenberg_enabled event during rollout
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java
Labels: gutenberg-mobile

#11056 Tooltip onboarding announcement for IA create FAB
  WordPress/src/main/java/org/wordpress/android/ui/WPTooltipView.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MainFabUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModel.kt
  WordPress/src/main/res/drawable/tooltip_arrow.xml
  WordPress/src/main/res/layout/main_activity.xml
  WordPress/src/main/res/layout/tooltip_above.xml
  WordPress/src/main/res/layout/tooltip_below.xml
  WordPress/src/main/res/layout/tooltip_left.xml
  WordPress/src/main/res/layout/tooltip_right.xml
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModelTest.kt
Labels: /My site, IA, [Status] Needs Copy Review, [Type] Enhancement

#11066 Analytics: Track phase 2 of the Gutenberg Rollout
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java
Labels: gutenberg-mobile

#11064 IA create content bottom sheet changes
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/main/ActionListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/AddContentAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MainActionListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MainBottomSheetFragment.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModelTest.kt
Labels: /My site, IA, [Type] Enhancement

#11069 Main fab bottom sheet expanded in landscape
  WordPress/src/main/java/org/wordpress/android/ui/main/MainBottomSheetFragment.kt
Labels: /My site, IA, [Type] Bug

#11075 Merge #11069 PR into develop.
  WordPress/src/main/java/org/wordpress/android/ui/main/MainBottomSheetFragment.kt
Labels: /My site, IA, [Type] Bug

#11060 Set gutenbergEnabled to false if all sites use Aztec
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java
  WordPress/src/test/java/org/wordpress/android/util/analytics/AnalyticsUtilsTest.java
Labels: Analytics

#10977 Issue/10641 material activity log
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/detail/ActivityLogDetailActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/ActivityLogListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/EventItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/blocks/NoteBlockClickableSpan.java
  WordPress/src/main/res/layout/activity_log_detail_activity.xml
  WordPress/src/main/res/layout/activity_log_item_detail.xml
  WordPress/src/main/res/layout/activity_log_list_activity.xml
  WordPress/src/main/res/layout/activity_log_list_event_item.xml
  WordPress/src/main/res/layout/activity_log_list_footer_item.xml
  WordPress/src/main/res/layout/activity_log_list_fragment.xml
  WordPress/src/main/res/layout/activity_log_list_header_item.xml
  WordPress/src/main/res/layout/activity_log_list_loading_item.xml
  WordPress/src/main/res/layout/activity_log_list_progress_item.xml
Labels: Activity Log, Dark Mode, [Status] Needs Code Review

#11057 Issue/10642 material plans and domains
  WordPress/build.gradle
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/FullScreenDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainSuggestionsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/plans/PlansActivity.kt
  WordPress/src/main/res/color/on_surface_disabled_selector.xml
  WordPress/src/main/res/color/secondary_disabled_selector.xml
  WordPress/src/main/res/color/secondary_variant_disabled_selector.xml
  WordPress/src/main/res/layout/domain_registration_details_fragment.xml
  WordPress/src/main/res/layout/domain_registration_result_fragment.xml
  WordPress/src/main/res/layout/domain_suggestion_list_item.xml
  WordPress/src/main/res/layout/domain_suggestions_activity.xml
  WordPress/src/main/res/layout/domain_suggestions_fragment.xml
  WordPress/src/main/res/layout/full_screen_dialog_fragment.xml
  WordPress/src/main/res/layout/plan_details_fragment.xml
  WordPress/src/main/res/layout/plan_feature_item.xml
  WordPress/src/main/res/layout/plans_activity.xml
  WordPress/src/main/res/layout/plans_list_fragment.xml
  WordPress/src/main/res/layout/plans_list_item.xml
  WordPress/src/main/res/values-night/styles.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/styles.xml
Labels: Dark Mode, Plans & Checkout, [Status] Needs Code Review

#11082 Merge 14.0 code freeze into develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
Labels: releases

#11084 Update Fastlane to 2.140.0
  Gemfile
  Gemfile.lock
Labels: Tooling

#11095 Bump Stetho version from 1.5.0 to 1.5.1
  WordPress/build.gradle
Labels: [Type] Crash

#11092 Accessibility : Reader - Decorative Icons Announcement Fix
  WordPress/src/main/res/layout/reader_cardview_post.xml
  WordPress/src/main/res/layout/reader_cardview_xpost.xml
  WordPress/src/main/res/values/strings.xml
Labels: Accessibility, Reader, TalkBack, [Type] Enhancement

#11094 Fix module with the Main dispatcher is missing
  build.gradle
Labels: Post List, [Type] Enhancement

#10989 Issue/10643 material plugins
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginUtils.java
  WordPress/src/main/java/org/wordpress/android/util/ContextExtensions.kt
  WordPress/src/main/res/layout/plugin_browser_activity.xml
  WordPress/src/main/res/layout/plugin_browser_row.xml
  WordPress/src/main/res/layout/plugin_detail_activity.xml
  WordPress/src/main/res/layout/plugin_info_row.xml
  WordPress/src/main/res/layout/plugin_list_fragment.xml
  WordPress/src/main/res/layout/plugin_list_row.xml
  WordPress/src/main/res/layout/plugin_ratings_cardview.xml
  WordPress/src/main/res/values-night/styles.xml
  WordPress/src/main/res/values/styles.xml
Labels: Dark Mode, [Status] Needs Code Review

#11096 Navigation Bar shadowed by bottom sheet
  WordPress/src/main/java/org/wordpress/android/ui/main/MainBottomSheetFragment.kt
  WordPress/src/main/res/layout/add_content_bottom_sheet.xml
  WordPress/src/main/res/values-v27/styles.xml
  WordPress/src/main/res/values/styles.xml
Labels: IA, [Type] Bug

#11089 Create FAB tooltip announce improvements
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModel.kt
Labels: IA, [Status] Needs Design Review, [Type] Enhancement

#11108 Merge 14.0 release notes into master
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: releases

#11070 Accessibility : Post List Improvements
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListItemViewHolder.kt
  WordPress/src/main/res/layout/post_list_activity.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
Labels: Accessibility, Post List, TalkBack, [Type] Enhancement

#11109 Accessibility: Sign Up - Terms of Service Announcement Fix
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupBottomSheetDialog.java
  libs/login/WordPressLoginFlow/src/main/res/values/strings.xml
Labels: Accessibility, Signup, TalkBack

#11114 Using postValue to account for background calls.
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/BaseListUseCase.kt
Labels: Stats, [Type] Crash

#11097 Fix search resume behavior.
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
Labels: Reader, [Type] Bug

#11106 Create FAB tooltip announce improvements
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModelTest.kt
Labels: IA, [Type] Enhancement

#11099 Disable long tap to remove Jetpack sites
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
Labels: Site Picker

#10925 Saving and restoring subfilter to/from shared prefs
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderBlogTableWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/SubfilterBottomSheetFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/subfilter/SubfilterListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/subfilter/SubfilterListItemMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/subfilter/SubfilterListItemMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/reader/ReaderPostListViewModelTest.kt
Labels: IA, Reader, [Type] Enhancement

#11098 Fixes not all post search results showing up sometimes
  RELEASE-NOTES.txt
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/MySitesPage.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemDataSource.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemDataSourceTest.kt
  build.gradle
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/posts/rest_v11_sites_158396482_posts-drafts.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/posts/rest_v11_sites_158396482_posts-future.json
Labels: Post List

#11107 Navigation Bar shadowed by bottom sheet
  WordPress/src/main/java/org/wordpress/android/ui/main/MainBottomSheetFragment.kt
  WordPress/src/main/res/layout/add_content_bottom_sheet.xml
  WordPress/src/main/res/values-v27/styles.xml
  WordPress/src/main/res/values/styles.xml
Labels: IA, [Type] Bug

#11118 Comment Dialog Layout
  WordPress/src/main/res/layout/comment_dialog_fragment.xml
Labels: [Status] Needs Code Review, [Type] Enhancement

#11054 Search view width fix.
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsTagListActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderBlogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserFragment.java
Labels: [Type] Enhancement

#11059 Accessibility : Bar Chart Improvements
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/BarChartAccessibilityHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtils.kt
  WordPress/src/main/res/layout/stats_block_bar_chart_item.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/LatestPostSummaryMapperTest.kt
Labels: Accessibility, Stats, TalkBack

#11023 Issue/10635 material comments
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/CollapseFullScreenDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/CommentFullScreenDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDialogs.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/EditCommentActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java
  WordPress/src/main/res/drawable/moderate_button_selector.xml
  WordPress/src/main/res/layout/collapse_full_screen_dialog_fragment.xml
  WordPress/src/main/res/layout/comment_action_footer.xml
  WordPress/src/main/res/layout/comment_activity.xml
  WordPress/src/main/res/layout/comment_detail_fragment.xml
  WordPress/src/main/res/layout/comment_dialog_fragment.xml
  WordPress/src/main/res/layout/comment_edit_activity.xml
  WordPress/src/main/res/layout/comment_list_fragment.xml
  WordPress/src/main/res/layout/comment_listitem.xml
  WordPress/src/main/res/layout/comments_detail_activity.xml
  WordPress/src/main/res/layout/reader_include_comment_box.xml
  WordPress/src/main/res/menu/menu_comments_cab.xml
  WordPress/src/main/res/values-night/styles.xml
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/integers.xml
  WordPress/src/main/res/values/reader_styles.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
Labels: Comments, Dark Mode, [Status] Needs Code Review

#11050 Move ReattachUploadMedia to a usecase
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/EditorMedia.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/ReattachUploadingMediaUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadServiceFacade.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/media/EditorMediaTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/media/ReattachUploadingMediaUseCaseTest.kt
Labels: Media, Posting/Editing, Tech debt

#11049 Accessibility : Posting Stats Improvement v2
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PostingActivityMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PostingActivityUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ActivityViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/util/ContentDescriptionListAnnouncer.kt
  WordPress/src/main/res/layout/stats_block_activity_item.xml
  WordPress/src/main/res/layout/stats_block_single_activity.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/PostingActivityMapperTest.kt
Labels: Accessibility, Stats Refresh, TalkBack

#11149 Reader → Fix crash when opening full screen comment page
  WordPress/src/main/java/org/wordpress/android/ui/CommentFullScreenDialogFragment.kt
Labels: Comments

#11113 IA Reader: adding scroll flags to reader toolbar.
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/reader/ReaderPostListViewModelTest.kt
Labels: IA, Reader, [Type] Enhancement

#11110 Issue/10712 material quick start
  WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartAdapter.java
  WordPress/src/main/res/color/material_surface_emphasis_medium.xml
  WordPress/src/main/res/color/quick_start_icon_selector.xml
  WordPress/src/main/res/drawable-sw600dp/bg_rectangle_white_radius_bottom_card.xml
  WordPress/src/main/res/drawable-sw600dp/bg_rectangle_white_radius_card.xml
  WordPress/src/main/res/drawable-sw600dp/bg_rectangle_white_radius_top_card.xml
  WordPress/src/main/res/drawable/bg_rectangle_white.xml
  WordPress/src/main/res/layout/promo_dialog.xml
  WordPress/src/main/res/layout/quick_start_completed_tasks_list_header.xml
  WordPress/src/main/res/layout/quick_start_dialog_fragment.xml
  WordPress/src/main/res/layout/quick_start_list_item.xml
  WordPress/src/main/res/values-night/styles.xml
  WordPress/src/main/res/values-sw600dp/styles.xml
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/drawables.xml
  WordPress/src/main/res/values/styles.xml
Labels: Dark Mode, [Status] Needs Code Review

#11138 Ignore wp-gallery tag while generating excerpt from post content
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostUtilsUnitTest.kt
Labels: Post List

#11156 Update PR Template For Accessibility
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Accessibility, [Type] Enhancement

#11134 Avoiding update subfilter status while we are in search mode.
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
Labels: IA, Reader, [Type] Bug

#11155 Site not removed from subfilter when unfollowed
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java
Labels: IA, Reader, [Type] Bug

#11163 Don't show post history button for self-hosted Jetpack-connected sites
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Posting/Editing

#11172 Add custom selector for password button
  libs/login/WordPressLoginFlow/src/main/res/drawable-hdpi/ic_password_visibility.png
  libs/login/WordPressLoginFlow/src/main/res/drawable-hdpi/ic_password_visibility_off.png
  libs/login/WordPressLoginFlow/src/main/res/drawable-mdpi/ic_password_visibility.png
  libs/login/WordPressLoginFlow/src/main/res/drawable-mdpi/ic_password_visibility_off.png
  libs/login/WordPressLoginFlow/src/main/res/drawable-xhdpi/ic_password_visibility.png
  libs/login/WordPressLoginFlow/src/main/res/drawable-xhdpi/ic_password_visibility_off.png
  libs/login/WordPressLoginFlow/src/main/res/drawable-xxhdpi/ic_password_visibility.png
  libs/login/WordPressLoginFlow/src/main/res/drawable-xxhdpi/ic_password_visibility_off.png
  libs/login/WordPressLoginFlow/src/main/res/drawable-xxxhdpi/ic_password_visibility.png
  libs/login/WordPressLoginFlow/src/main/res/drawable-xxxhdpi/ic_password_visibility_off.png
  libs/login/WordPressLoginFlow/src/main/res/drawable/selector_password_visibility.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_input_row.xml
Labels: [Type] Bug

#11157 Enable auto-uploading/remote-auto-saving for locally changed pages
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterConcurrentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadStarterTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Offline Support, Pages List

#11159 Issue/11140 introduce a new module for media editing
  ImageEditor/build.gradle
  ImageEditor/src/main/AndroidManifest.xml
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/EditImageActivity.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/HomeFragment.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/ImageEditor.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/fragments/MainImageFragment.kt
  ImageEditor/src/main/res/anim/fade_in.xml
  ImageEditor/src/main/res/anim/fade_out.xml
  ImageEditor/src/main/res/drawable/placeholder_image.xml
  ImageEditor/src/main/res/layout/edit_image_activity.xml
  ImageEditor/src/main/res/layout/home_fragment.xml
  ImageEditor/src/main/res/layout/main_image_fragment.xml
  ImageEditor/src/main/res/navigation/mobile_navigation.xml
  ImageEditor/src/main/res/navigation/nav_graph.xml
  ImageEditor/src/main/res/values/colors.xml
  ImageEditor/src/main/res/values/strings.xml
  ImageEditor/src/main/res/values/styles.xml
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  build.gradle
Labels: Media Editing

#11071 Issue/10639 material site settings
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/prefs/BlogPreferencesActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/DetailListPreference.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/EditTextPreferenceWithValidation.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/MultiSelectRecyclerViewAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/NumberPickerDialog.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/RelatedPostsDialog.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFormatDialog.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsTagListActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsTimezoneDialog.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SummaryEditTextPreference.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/WPPreference.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/WPStartOverPreference.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/WPSwitchPreference.java
  WordPress/src/main/java/org/wordpress/android/util/WPActivityUtils.java
  WordPress/src/main/java/org/wordpress/android/util/WPPrefUtils.java
  WordPress/src/main/res/color/black_translucent_50_neutral_70_selector.xml
  WordPress/src/main/res/color/primary_0_gray_20_gray_40_selector.xml
  WordPress/src/main/res/color/primary_0_gray_90_gray_50_selector.xml
  WordPress/src/main/res/color/primary_40_gray_90_gray_50_selector.xml
  WordPress/src/main/res/color/primary_40_neutral_40_selector.xml
  WordPress/src/main/res/color/quick_start_title_selector.xml
  WordPress/src/main/res/color/related_posts_preview_header.xml
  WordPress/src/main/res/drawable/tag_list_circle.xml
  WordPress/src/main/res/layout/detail_list_preference.xml
  WordPress/src/main/res/layout/detail_list_preference_title.xml
  WordPress/src/main/res/layout/learn_more_pref_old.xml
  WordPress/src/main/res/layout/list_editor.xml
  WordPress/src/main/res/layout/number_picker_dialog.xml
  WordPress/src/main/res/layout/related_posts_dialog.xml
  WordPress/src/main/res/layout/site_settings_activity.xml
  WordPress/src/main/res/layout/site_settings_format_dialog.xml
  WordPress/src/main/res/layout/site_settings_tag_detail_fragment.xml
  WordPress/src/main/res/layout/site_settings_tag_list_activity.xml
  WordPress/src/main/res/layout/site_settings_tag_list_row.xml
  WordPress/src/main/res/layout/site_settings_timezone_dialog.xml
  WordPress/src/main/res/layout/start_over_preference.xml
  WordPress/src/main/res/layout/wp_simple_list_item_1.xml
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/main/res/values/styles_calypso.xml
  WordPress/src/main/res/xml/site_settings.xml
Labels: Dark Mode, Site Settings, [Status] Needs Code Review

#11162 Accessibility: My Site - Create Button and Tooltip
  WordPress/src/main/res/layout/main_activity.xml
Labels: /My site, Accessibility, IA, TalkBack

#11186 Issue/11141 introduce media editing intermediary screen
  ImageEditor/build.gradle
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/EditImageActivity.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/HomeFragment.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageFragment.kt
  ImageEditor/src/main/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModel.kt
  ImageEditor/src/main/res/drawable/placeholder_image.xml
  ImageEditor/src/main/res/layout/activity_edit_image.xml
  ImageEditor/src/main/res/layout/fragment_preview_image.xml
  ImageEditor/src/main/res/navigation/nav_graph.xml
  ImageEditor/src/main/res/values/colors.xml
  ImageEditor/src/main/res/values/strings.xml
  ImageEditor/src/main/res/values/styles.xml
  ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/ExampleUnitTest.kt
  ImageEditor/src/test/kotlin/org/wordpress/android/imageeditor/preview/PreviewImageViewModelTest.kt
  WordPress/build.gradle
  build.gradle
Labels: Media, Media Editing

#11183 New design reader bottom sheet - step 1
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MainBottomSheetFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/SubfilterBottomSheetFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/subfilter/SubfilterListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/subfilter/SubfilterPageFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderModeInfo.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/main/res/drawable/bg_bottom_sheet_handle.xml
  WordPress/src/main/res/drawable/bg_bottom_sheet_handle_container.xml
  WordPress/src/main/res/drawable/ic_cross_small_white_24dp.xml
  WordPress/src/main/res/layout/add_content_bottom_sheet.xml
  WordPress/src/main/res/layout/subfilter_bottom_sheet.xml
  WordPress/src/main/res/layout/subfilter_component.xml
  WordPress/src/main/res/layout/subfilter_handle.xml
  WordPress/src/main/res/layout/subfilter_list.xml
  WordPress/src/main/res/values-v27/styles.xml
  WordPress/src/main/res/values-w600dp/dimens.xml
  WordPress/src/main/res/values-w720dp/dimens.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/viewmodel/reader/ReaderPostListViewModelTest.kt
Labels: IA, Reader, [Status] Needs Code Review, [Type] Enhancement

#11105 Fix npe in UploadService
  WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadHandler.java
Labels: Posting/Editing, [Type] Crash

#11207 Fix update gravatar feature
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
Labels: /Me, [Type] Bug

#11083 [TalkBack] Create Vision Accessibility Guideline docs
  docs/images/accessibility-guidelines/heading.png
  docs/images/accessibility-guidelines/heading_live.gif
  docs/images/accessibility-guidelines/image_inaccessible.png
  docs/images/accessibility-guidelines/post_actions.png
  docs/images/accessibility-guidelines/post_list.png
  docs/images/accessibility-guidelines/snackbar.gif
  docs/images/accessibility-guidelines/stats_chart.gif
  docs/images/accessibility-guidelines/stats_group.png
  docs/images/accessibility-guidelines/talkback_captions.png
  docs/talkback-guidelines.md
  docs/using-talkback.md
Labels: Accessibility, Documentation, TalkBack
