Repository wordpress-mobile/WordPress-Android, pull requests merged in 2021-04, with the labels that each got.

#14285 Decreases the preview WebView initial scale
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutPreviewFragment.kt
Labels: [Type] Bug

#14369 Deprecate wordpress blue and replace it with blue
  WordPress/src/main/res/values-night/colors.xml
  WordPress/src/main/res/values/colors.xml
Labels: [Type] Task

#14386 Integrate gutenberg-mobile release 1.50.0
  RELEASE-NOTES.txt
  WordPress/src/main/res/values/strings.xml
  build.gradle
Labels: gutenberg-mobile

#14391 Update app icons to new blue color
  RELEASE-NOTES.txt
  WordPress/src/main/res/drawable/app_icon_background.xml
  WordPress/src/main/res/drawable/app_icon_foreground.xml
  WordPress/src/main/res/mipmap-hdpi/app_icon.png
  WordPress/src/main/res/mipmap-xhdpi/app_icon.png
  WordPress/src/main/res/mipmap-xxhdpi/app_icon.png
  WordPress/src/main/res/mipmap-xxxhdpi/app_icon.png
Labels: Design

#14381 Limit Classic editor access on Simple WP.com sites to existing Classic posts
  WordPress/src/androidTest/java/org/wordpress/android/e2e/EditorTests.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
Labels: Aztec-obsolete, gutenberg-mobile

#14393 Merge Release/17.0 into develop
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/StoriesEventListener.kt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/1016.txt
  fastlane/metadata/android/ar/changelogs/1023.txt
  fastlane/metadata/android/de-DE/changelogs/1016.txt
  fastlane/metadata/android/de-DE/changelogs/1023.txt
  fastlane/metadata/android/en-US/changelogs/1016.txt
  fastlane/metadata/android/en-US/changelogs/1023.txt
  fastlane/metadata/android/es-ES/changelogs/1016.txt
  fastlane/metadata/android/es-ES/changelogs/1023.txt
  fastlane/metadata/android/fr-CA/changelogs/1016.txt
  fastlane/metadata/android/fr-CA/changelogs/1023.txt
  fastlane/metadata/android/fr-FR/changelogs/1016.txt
  fastlane/metadata/android/fr-FR/changelogs/1023.txt
  fastlane/metadata/android/id/changelogs/1016.txt
  fastlane/metadata/android/id/changelogs/1023.txt
  fastlane/metadata/android/it-IT/changelogs/1016.txt
  fastlane/metadata/android/it-IT/changelogs/1023.txt
  fastlane/metadata/android/iw-IL/changelogs/1016.txt
  fastlane/metadata/android/iw-IL/changelogs/1023.txt
  fastlane/metadata/android/ja-JP/changelogs/1016.txt
  fastlane/metadata/android/ja-JP/changelogs/1023.txt
  fastlane/metadata/android/ko-KR/changelogs/1016.txt
  fastlane/metadata/android/ko-KR/changelogs/1023.txt
  fastlane/metadata/android/nl-NL/changelogs/1023.txt
  fastlane/metadata/android/nl-NL/title.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/1016.txt
  fastlane/metadata/android/ru-RU/changelogs/1023.txt
  fastlane/metadata/android/sv-SE/changelogs/1016.txt
  fastlane/metadata/android/sv-SE/changelogs/1023.txt
  fastlane/metadata/android/tr-TR/changelogs/1016.txt
  fastlane/metadata/android/tr-TR/changelogs/1023.txt
  fastlane/metadata/android/zh-CN/changelogs/1016.txt
  fastlane/metadata/android/zh-CN/changelogs/1023.txt
  fastlane/metadata/android/zh-TW/changelogs/1016.txt
  fastlane/metadata/android/zh-TW/changelogs/1023.txt
Labels: Releases

#14361 List all likes in notifications
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngageItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedListNavigationEvent.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleAdapterDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/GetLikesHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/GetLikesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/LikedItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/LikerViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/ListScenario.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/ListScenarioUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/blocks/HeaderNoteBlock.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/config/LikesEnhancementsFeatureConfig.kt
  WordPress/src/main/res/layout/engaged_people_list_fragment.xml
  WordPress/src/main/res/layout/liker_user.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  build.gradle
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/sites/rest_v12_sites_comments_likes.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/sites/rest_v12_sites_posts_likes.json
Labels: Notifications, [Status] Needs Code Review, [Type] Enhancement

#14376 Replace pink with blue
  WordPress/src/main/java/org/wordpress/android/ui/CollapseFullScreenDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/MapViewHolder.kt
  WordPress/src/main/res/color/primary_neutral_30_selector.xml
  WordPress/src/main/res/drawable/bg_oval_blue_50_multiple_users_white_40dp.xml
  WordPress/src/main/res/drawable/bg_oval_blue_50_multiple_users_white_40dp_selector.xml
  WordPress/src/main/res/layout/my_site_fragment.xml
  WordPress/src/main/res/layout/reader_include_comment_box.xml
  WordPress/src/main/res/values-night/colors.xml
  WordPress/src/main/res/values-night/styles.xml
  WordPress/src/main/res/values/colors.xml
  WordPress/src/main/res/values/styles.xml
  libs/login/WordPressLoginFlow/src/main/res/values-night/themes.xml
  libs/login/WordPressLoginFlow/src/main/res/values/themes.xml
Labels: Design, [Type] Task

#14330 Use view binding in jetpack features - part 2
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/backup/download/BackupDownloadActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/backup/download/BackupDownloadFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/restore/RestoreActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/restore/RestoreFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/ScanActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/ScanFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/details/ThreatDetailsActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/details/ThreatDetailsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/details/adapters/viewholders/ThreatContextLineViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/history/ScanHistoryFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/history/ScanHistoryListFragment.kt
  WordPress/src/main/res/layout/scan_history_fragment.xml
Labels: Tech debt, [Type] Enhancement

#14401 Fixes small errors in release toolkit
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: Releases

#14398 Run image-editor unit tests on CI
  .circleci/config.yml
Labels: Tech debt

#14406 Removes github release prefix for gutenberg mobile
  fastlane/Fastfile
Labels: Tooling

#14396 Re-enable shortcuts except for new posts
  WordPress/src/jetpack/res/values/strings.xml
  WordPress/src/jetpack/res/xml/shortcuts.xml
  WordPress/src/jetpackJalapeno/res/xml/shortcuts.xml
  WordPress/src/jetpackWasabi/res/xml/shortcuts.xml
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/res/values/strings.xml
Labels: Jetpack App, [Type] Task

#14397 Issue/14299 add payload to fetch sites wp module
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/JetpackConnectionResultActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
  build.gradle
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginBaseFormFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginWpcomService.java
Labels: [Type] Task

#14198 Isse/7900 timezone selection - Rewrite Timezone selection using Kotlin with BottomSheetDialogFragment
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/people/WPEditTextWithChipsOutlined.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsTimezoneDialog.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/WPComSiteSettings.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/timezone/SiteSettingsTimezoneBottomSheet.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/timezone/SiteSettingsTimezoneViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/timezone/TimezoneAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/timezone/TimezoneHeaderViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/timezone/TimezoneViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/timezone/TimezonesList.kt
  WordPress/src/main/res/layout/site_settings_timezone_bottom_sheet_list.xml
  WordPress/src/main/res/layout/site_settings_timezone_bottom_sheet_list_header.xml
  WordPress/src/main/res/layout/site_settings_timezone_bottom_sheet_list_item.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/prefs/timezone/SiteSettingsTimezoneViewModelTest.kt
  build.gradle
Labels: Site Settings, [Status] Needs Code Review

#14390 Test/timezone picker ci test
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/people/WPEditTextWithChipsOutlined.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsTimezoneDialog.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/WPComSiteSettings.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/timezone/SiteSettingsTimezoneBottomSheet.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/timezone/SiteSettingsTimezoneViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/timezone/TimezoneAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/timezone/TimezoneHeaderViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/timezone/TimezoneViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/timezone/TimezonesList.kt
  WordPress/src/main/res/layout/site_settings_timezone_bottom_sheet_list.xml
  WordPress/src/main/res/layout/site_settings_timezone_bottom_sheet_list_header.xml
  WordPress/src/main/res/layout/site_settings_timezone_bottom_sheet_list_item.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/prefs/timezone/SiteSettingsTimezoneViewModelTest.kt
  build.gradle
Labels: Testing, [Status] Not Ready for Merge

#14413 Add notes about color updates
  RELEASE-NOTES.txt
Labels: [Type] Task

#14356 Jetpack App Basics: Handle sites
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/JetpackConnectionResultActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginEpilogueFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginBaseFormFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailPasswordFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginMode.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginWpcomService.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/util/SiteUtils.java
Labels: Jetpack App, [Status] Not Ready for Merge

#14409 Jetpack Section: Remove Jetpack Feature Flags
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/ActivityLogNavigationEvents.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/detail/ActivityLogDetailActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/detail/ActivityLogDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/detail/ActivityLogDetailNavigationEvents.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/ActivityLogAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/ActivityLogListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/ActivityLogListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/ActivityLogListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/EventItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/ScanAndBackupSource.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SiteListItemBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailListFragment.kt
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  WordPress/src/main/java/org/wordpress/android/util/SiteUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/analytics/ActivityLogTracker.kt
  WordPress/src/main/java/org/wordpress/android/util/config/ActivityLogFiltersFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/BackupDownloadFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/BackupScreenFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/RestoreFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/ScanScreenFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/ScanAndBackupSourceTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/SiteListItemBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/activitylog/ActivityLogDetailViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModelTest.kt
  config/detekt/baseline.xml
Labels: Jetpack App, Jetpack Mobile, [Type] Task

#14412 Merge/release 17.1 beta 1 into develop
  Gemfile.lock
  WordPress/build.gradle
  WordPress/metadata/release_notes.txt
  fastlane/Fastfile
  fastlane/resources/values/strings.xml
Labels: Releases

#14424 Fix initial login prologue screen
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
Labels: [Type] Bug

#14422 Prevents TransactionTooLargeException by removing the content from the parcel
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/mlp/ModalLayoutPickerViewModel.kt
  build.gradle
Labels: Pages List, [Type] Bug, [Type] Crash

#13804 Contact info api - featureConfig implementation
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  WordPress/src/main/java/org/wordpress/android/util/config/ContactInfoBlockFeatureConfig.kt
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergPropsBuilder.kt
Labels: Gutenberg, gutenberg-mobile

#14410 Update colors in login library to 2.5.0
  libs/login/WordPressLoginFlow/src/main/res/values-night/themes.xml
  libs/login/WordPressLoginFlow/src/main/res/values/colors.xml
Labels: Design, Login, [Type] Bug

#14423 Jetpack App (Basics): Update Base Colors
  WordPress/src/jetpack/res/values-night/colors_base.xml
  WordPress/src/jetpack/res/values/colors_base.xml
  WordPress/src/main/res/values-night/colors_base.xml
  WordPress/src/main/res/values/colors.xml
  WordPress/src/main/res/values/colors_base.xml
  WordPress/src/main/res/values/colors_semantic.xml
  WordPress/src/main/res/values/colors_studio_palette.xml
  WordPress/src/main/res/values/colors_translucent.xml
Labels: Jetpack App, Jetpack Mobile

#14431 Reverted materialVersion back to 1.2.1
  build.gradle
Labels: [Pri] High, [Status] Needs Code Review, [Type] Bug

#14428 Scan History: Add show/hide scrolling behaviour to toolbar
  WordPress/src/main/res/layout/scan_history_fragment.xml
Labels: Jetpack Mobile

#14429 Jetpack App (Basics): Update Nav Bar Colors (Bottom Bar)
  WordPress/src/jetpack/res/values-night/colors_base.xml
  WordPress/src/jetpack/res/values/colors_base.xml
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainNavigationView.kt
  WordPress/src/main/res/drawable/nav_bar_button_selector.xml
  WordPress/src/main/res/values-night/colors_base.xml
  WordPress/src/main/res/values-night/styles.xml
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/colors_base.xml
  WordPress/src/main/res/values/styles.xml
Labels: Jetpack App, Jetpack Mobile

#14439 Integrate gutenberg-mobile release 1.50.1
  build.gradle
Labels: gutenberg-mobile

#14420 Issue/14315 update about the app
  WordPress/src/jetpack/assets/licenses.html
  WordPress/src/jetpack/res/values/strings.xml
Labels: Jetpack App, [Type] Task

#14289 Use HTTP API calls to trigger release jobs
  .circleci/config.yml
  Gemfile.lock
  fastlane/Fastfile
  fastlane/env/user.env-example
Labels: Tooling

#14448 Crash Fix: Replace Instance with Static Reader Tracker
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/tracker/ReaderTracker.kt
Labels: Analytics, New Reader Android, Reader, [Type] Bug

#14375 Adding liker faces train in reader and allow to access the list of likers
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderDatabase.java
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java
  WordPress/src/main/java/org/wordpress/android/models/ReaderPost.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngageItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedListServiceRequestEvent.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/GetLikesHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/GetLikesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/LikerViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/ListScenario.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostLikersAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderNavigationEvents.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewholders/PostLikerItemDecorator.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewholders/PostLikerViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/InterceptingFrameLayout.kt
  WordPress/src/main/res/drawable/bg_oval_stroke_liker_2dp.xml
  WordPress/src/main/res/layout/engaged_people_list_activity.xml
  WordPress/src/main/res/layout/liker_face_item.xml
  WordPress/src/main/res/layout/reader_fragment_post_detail.xml
  WordPress/src/main/res/layout/reader_post_likers_faces_list.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt
Labels: Reader, [Type] Enhancement

#14387 Add "create a site" deeplink handling
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/DeepLinkNavigator.kt
  WordPress/src/main/java/org/wordpress/android/ui/DeepLinkUriUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/DeepLinkingIntentReceiverActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/DeepLinkingIntentReceiverViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/EditorLinkHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/ServerTrackingHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/util/UriWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/DeepLinkingIntentReceiverViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/EditorLinkHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/UriTestHelper.kt
Labels: Deeplinks, [Type] Enhancement

#14432 Merge/release 17.1 beta 2 into develop
  Gemfile.lock
  WordPress/build.gradle
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  WordPress/metadata/release_notes_short.txt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/mlp/ModalLayoutPickerViewModel.kt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-az/strings.xml
  WordPress/src/main/res/values-bg/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-cy/strings.xml
  WordPress/src/main/res/values-da/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-eu/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gd/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-hi/strings.xml
  WordPress/src/main/res/values-hr/strings.xml
  WordPress/src/main/res/values-hu/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-is/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-kmr/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-mk/strings.xml
  WordPress/src/main/res/values-ms/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sr/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-th/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  build.gradle
  fastlane/Pluginfile
Labels: Releases

#14454 Merge release 17.1 beta 3 into develop
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/tracker/ReaderTracker.kt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-da/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  build.gradle
Labels: Releases

#14453 Jetpack App (Basics): Disable login signup
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginPrologueFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/res/values/strings.xml
Labels: Jetpack App, [Type] Task

#14445 Improve firebase syncing
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SiteCreationTracker.kt
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsTrackerWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/config/AppConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/FeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/RemoteConfig.kt
  WordPress/src/test/java/org/wordpress/android/ui/photopicker/PhotoPickerViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/EditorTrackerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/util/config/AppConfigParametrizedTest.kt
  WordPress/src/test/java/org/wordpress/android/util/config/AppConfigTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/whatsnew/FeatureAnnouncementViewModelTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: My Site Dynamic Cards, [Type] Bug

#14447 Jetpack Scan: Display a warning for when server credentials are not configured
  WordPress/src/main/java/org/wordpress/android/Constants.java
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/common/JetpackListItemState.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/ScanFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/ScanNavigationEvents.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/ScanViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/builders/ScanStateListItemsBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/details/ThreatDetailsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/details/ThreatDetailsListItemsBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/details/ThreatDetailsNavigationEvents.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/details/ThreatDetailsViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/ScanViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/ThreatTestData.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/builders/ScanStateListItemsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/details/ThreatDetailsListItemsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/details/ThreatDetailsViewModelTest.kt
  build.gradle
Labels: Jetpack Mobile, Scan

#14452 Add random value to the MySiteImprovementsFeatureConfig.kt based on user ID
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginMagicLinkInterceptActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SiteCreationTracker.kt
  WordPress/src/main/java/org/wordpress/android/util/UriWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsTrackerWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/config/FeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/MySiteImprovementsFeatureConfig.kt
  WordPress/src/test/java/org/wordpress/android/util/config/MySiteImprovementsFeatureConfigTest.kt
Labels: My Site Dynamic Cards, [Type] Bug

#14457 Jetpack App (Basics): Update App Icons
  WordPress/src/jalapeno/res/mipmap-mdpi/app_icon.png
  WordPress/src/jetpack/res/drawable/app_icon_background.xml
  WordPress/src/jetpack/res/drawable/app_icon_foreground.xml
  WordPress/src/jetpack/res/mipmap-anydpi-v26/app_icon.xml
  WordPress/src/jetpack/res/mipmap-anydpi-v26/app_icon_round.xml
  WordPress/src/jetpack/res/mipmap-hdpi/app_icon.png
  WordPress/src/jetpack/res/mipmap-hdpi/app_icon_round.png
  WordPress/src/jetpack/res/mipmap-mdpi/app_icon.png
  WordPress/src/jetpack/res/mipmap-mdpi/app_icon_round.png
  WordPress/src/jetpack/res/mipmap-xhdpi/app_icon.png
  WordPress/src/jetpack/res/mipmap-xhdpi/app_icon_round.png
  WordPress/src/jetpack/res/mipmap-xxhdpi/app_icon.png
  WordPress/src/jetpack/res/mipmap-xxhdpi/app_icon_round.png
  WordPress/src/jetpack/res/mipmap-xxxhdpi/app_icon.png
  WordPress/src/jetpack/res/mipmap-xxxhdpi/app_icon_round.png
  WordPress/src/jetpackJalapeno/res/drawable/app_icon_background.xml
  WordPress/src/jetpackJalapeno/res/drawable/app_icon_foreground.xml
  WordPress/src/jetpackJalapeno/res/mipmap-anydpi-v26/app_icon.xml
  WordPress/src/jetpackJalapeno/res/mipmap-anydpi-v26/app_icon_round.xml
  WordPress/src/jetpackJalapeno/res/mipmap-hdpi/app_icon.png
  WordPress/src/jetpackJalapeno/res/mipmap-hdpi/app_icon_round.png
  WordPress/src/jetpackJalapeno/res/mipmap-mdpi/app_icon.png
  WordPress/src/jetpackJalapeno/res/mipmap-mdpi/app_icon_round.png
  WordPress/src/jetpackJalapeno/res/mipmap-xhdpi/app_icon.png
  WordPress/src/jetpackJalapeno/res/mipmap-xhdpi/app_icon_round.png
  WordPress/src/jetpackJalapeno/res/mipmap-xxhdpi/app_icon.png
  WordPress/src/jetpackJalapeno/res/mipmap-xxhdpi/app_icon_round.png
  WordPress/src/jetpackJalapeno/res/mipmap-xxxhdpi/app_icon.png
  WordPress/src/jetpackJalapeno/res/mipmap-xxxhdpi/app_icon_round.png
  WordPress/src/jetpackWasabi/res/drawable/app_icon_background.xml
  WordPress/src/jetpackWasabi/res/drawable/app_icon_foreground.xml
  WordPress/src/jetpackWasabi/res/mipmap-anydpi-v26/app_icon.xml
  WordPress/src/jetpackWasabi/res/mipmap-anydpi-v26/app_icon_round.xml
  WordPress/src/jetpackWasabi/res/mipmap-hdpi/app_icon.png
  WordPress/src/jetpackWasabi/res/mipmap-hdpi/app_icon_round.png
  WordPress/src/jetpackWasabi/res/mipmap-mdpi/app_icon.png
  WordPress/src/jetpackWasabi/res/mipmap-mdpi/app_icon_round.png
  WordPress/src/jetpackWasabi/res/mipmap-xhdpi/app_icon.png
  WordPress/src/jetpackWasabi/res/mipmap-xhdpi/app_icon_round.png
  WordPress/src/jetpackWasabi/res/mipmap-xxhdpi/app_icon.png
  WordPress/src/jetpackWasabi/res/mipmap-xxhdpi/app_icon_round.png
  WordPress/src/jetpackWasabi/res/mipmap-xxxhdpi/app_icon.png
  WordPress/src/jetpackWasabi/res/mipmap-xxxhdpi/app_icon_round.png
Labels: Jetpack App, Jetpack Mobile

#14465 WP Stories: relaxing the HEADING_END definition to avoid IOB
  WordPress/src/main/java/org/wordpress/android/ui/stories/SaveStoryGutenbergBlockUseCase.kt
Labels: WP Stories

#14460 Stories: add bounds check in saving, don't process an empty Story block
  WordPress/src/main/java/org/wordpress/android/ui/stories/SaveStoryGutenbergBlockUseCase.kt
  WordPress/src/test/java/org/wordpress/android/ui/stories/SaveStoryGutenbergBlockUseCaseTest.kt
Labels: WP Stories

#14469 Moves Trash/Delete to the last list position
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelper.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListItemUiStateHelperTest.kt
Labels: Post List

#14458 Replaces ConstraintLayout with RelativeLayout to bypass RTL rendering issue
  RELEASE-NOTES.txt
  WordPress/src/main/res/layout/my_site_item_block.xml
  WordPress/src/main/res/values/styles.xml
Labels: [Pri] Medium

#14470 Jetpack App (Basics) - Add About App icon
  WordPress/src/jetpack/res/drawable/ic_about_app_white_24dp.xml
  WordPress/src/main/res/drawable/ic_about_app_white_24dp.xml
  WordPress/src/main/res/layout/about_activity.xml
Labels: Jetpack Mobile, [Type] Task

#14472 Merge/release 17.1 beta 4 into develop
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginMagicLinkInterceptActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsTrackerWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/config/FeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/MySiteImprovementsFeatureConfig.kt
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-kmr/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/photopicker/PhotoPickerViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/EditorTrackerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/util/config/MySiteImprovementsFeatureConfigTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/whatsnew/FeatureAnnouncementViewModelTest.kt
Labels: Releases

#14474 Integrate gutenberg-mobile release 1.51.0
  RELEASE-NOTES.txt
  build.gradle
Labels: gutenberg-mobile

#14478 Update MySiteImprovementsFeatureConfig so it can handle null auth tokens
  WordPress/src/main/java/org/wordpress/android/util/config/MySiteImprovementsFeatureConfig.kt
Labels: My Site Dynamic Cards, [Type] Crash

#14441 Jetpack App (Basics): Update Tab Bar Colors (Top Bar)
  WordPress/src/main/res/values-night/styles.xml
  WordPress/src/main/res/values/styles.xml
Labels: Jetpack App, Jetpack Mobile, [Status] Not Ready for Merge

#14480 Merge Release/17.1 into develop
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/util/config/MySiteImprovementsFeatureConfig.kt
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-kmr/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/1023.txt
  fastlane/metadata/android/de-DE/changelogs/1023.txt
  fastlane/metadata/android/en-US/changelogs/1023.txt
  fastlane/metadata/android/en-US/changelogs/1032.txt
  fastlane/metadata/android/es-ES/changelogs/1023.txt
  fastlane/metadata/android/es-ES/changelogs/1032.txt
  fastlane/metadata/android/fr-CA/changelogs/1023.txt
  fastlane/metadata/android/fr-FR/changelogs/1023.txt
  fastlane/metadata/android/id/changelogs/1023.txt
  fastlane/metadata/android/it-IT/changelogs/1023.txt
  fastlane/metadata/android/iw-IL/changelogs/1023.txt
  fastlane/metadata/android/ja-JP/changelogs/1023.txt
  fastlane/metadata/android/ko-KR/changelogs/1023.txt
  fastlane/metadata/android/nl-NL/changelogs/1023.txt
  fastlane/metadata/android/nl-NL/changelogs/1032.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/1023.txt
  fastlane/metadata/android/ru-RU/changelogs/1032.txt
  fastlane/metadata/android/sv-SE/changelogs/1023.txt
  fastlane/metadata/android/tr-TR/changelogs/1023.txt
  fastlane/metadata/android/zh-CN/changelogs/1023.txt
  fastlane/metadata/android/zh-CN/changelogs/1032.txt
  fastlane/metadata/android/zh-TW/changelogs/1023.txt
Labels: Releases

#14482 Reformat jetpack package files
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/backup/download/BackupDownloadViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/backup/download/builders/BackupDownloadStateListItemBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/backup/download/usecases/GetBackupDownloadStatusUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/backup/download/usecases/PostDismissBackupDownloadUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/common/JetpackListItemState.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/common/adapters/JetpackBackupRestoreAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/common/providers/JetpackAvailableItemsProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/restore/RestoreViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/restore/builders/RestoreStateListItemBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/restore/usecases/GetRestoreStatusUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/ScanListItemState.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/ScanViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/builders/ScanStateListItemsBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/builders/ThreatItemBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/details/ThreatDetailsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/details/ThreatDetailsListItemState.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/details/ThreatDetailsListItemsBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/details/ThreatDetailsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/history/ScanHistoryListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/history/ScanHistoryViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/backup/download/BackupDownloadViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/backup/download/usecases/GetBackupDownloadStatusUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/backup/download/usecases/PostBackupDownloadUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/restore/RestoreViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/restore/usecases/GetRestoreStatusUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/ScanViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/ThreatTestData.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/builders/ScanStateListItemsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/builders/ThreatItemBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/details/ThreatDetailsListItemsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/details/ThreatDetailsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/details/usecases/IgnoreThreatUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/usecases/FetchFixThreatsStatusUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/usecases/FetchScanStateUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/usecases/FixThreatsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/usecases/StartScanUseCaseTest.kt
  config/detekt/baseline.xml
Labels: Jetpack, Jetpack Mobile

#14459 Jetpack App (Basics): Handle login
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginNavigationEvents.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/UnifiedLoginTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginNoSitesErrorFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginNoSitesErrorViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginSiteCheckErrorFragment.kt
  WordPress/src/main/res/layout/fragment_login_no_sites_error.xml
  WordPress/src/main/res/layout/fragment_login_site_check_error.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/accounts/LoginViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/accounts/login/LoginNoSitesErrorViewModelTest.kt
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java
Labels: Jetpack App, [Type] Task

#14456 Likers in reader enhancements
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewholders/PostLikerItemDecorator.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
  WordPress/src/main/res/layout/reader_post_likers_faces_list.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
Labels: Reader, [Status] Needs Code Review, [Type] Enhancement

#14489 Merge release 17.2 beta 1 into develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/metadata/release_notes.txt
  WordPress/metadata/release_notes_short.txt
  WordPress/src/main/res/values/strings.xml
  build.gradle
  fastlane/Fastfile
  fastlane/resources/values/strings.xml
Labels: Releases

#14488 ExPlat: Remove A/B experiment
  WordPress/src/main/java/org/wordpress/android/util/experiments/CreateMenuStoryFirstABExperiment.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModelTest.kt
Labels: ExPlat, [Type] Task

#14481 Jetpack App (Basics): Update Toolbar Title Typography
  WordPress/src/jetpack/res/values/styles_toolbar.xml
  WordPress/src/main/res/values-night/styles.xml
  WordPress/src/main/res/values-night/styles_toolbar.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/main/res/values/styles_toolbar.xml
Labels: Jetpack App, [Status] Needs Design Review, [Status] Not Ready for Merge, [Type] Task

#14491 Jetpack App (Basics): Update Zendesk ticket subject
  WordPress/src/jetpack/res/values/strings.xml
  WordPress/src/main/java/org/wordpress/android/support/ZendeskHelper.kt
  WordPress/src/main/res/values/strings.xml
Labels: Jetpack App, [Type] Task

#14466 Add stats email deeplink handling
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/DeepLinkNavigator.kt
  WordPress/src/main/java/org/wordpress/android/ui/DeepLinkUriUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/DeepLinkingIntentReceiverActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/DeepLinkingIntentReceiverViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/EditorLinkHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/StartLinkHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/StatsLinkHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsActivity.kt
  WordPress/src/main/java/org/wordpress/android/util/UriWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/DeepLinkUriUtilsTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/DeepLinkingIntentReceiverViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/EditorLinkHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/StartLinkHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/StatsLinkHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/UriTestHelper.kt
Labels: Deeplinks, [Type] Enhancement

#14495 Jetpack App (Basics): Updated internal "App" Icons
  WordPress/src/jetpack/res/drawable/ic_about_app_white_24dp.xml
  WordPress/src/jetpack/res/drawable/ic_app_white_24dp.xml
  WordPress/src/jetpack/res/drawable/ic_my_sites_white_24dp.xml
  WordPress/src/main/java/org/wordpress/android/push/GCMMessageHandler.java
  WordPress/src/main/java/org/wordpress/android/push/NativeNotificationsUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SiteListItemBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PublishNotificationReceiver.kt
  WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartReminderReceiver.java
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/services/SiteCreationServiceNotification.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowerTotalsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java
  WordPress/src/main/res/drawable/ic_about_app_white_24dp.xml
  WordPress/src/main/res/drawable/ic_app_white_24dp.xml
  WordPress/src/main/res/drawable/ic_wordpress_white_24dp.xml
  WordPress/src/main/res/layout/about_activity.xml
  WordPress/src/main/res/layout/my_site_fragment.xml
  WordPress/src/main/res/menu/menu_media_picker.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/SiteItemFixtures.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/FollowerTotalsUseCaseTest.kt
Labels: Jetpack App, [Type] Task

#14499 Enabling contact info in prod by toggling on feature flag.
  WordPress/build.gradle
Labels: [Type] Bug

#14471 Add deeplink support for posts sent via email
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/DeepLinkNavigator.kt
  WordPress/src/main/java/org/wordpress/android/ui/DeepLinkingIntentReceiverViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/ReaderLinkHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderConstants.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/utils/IntentUtils.kt
  WordPress/src/test/java/org/wordpress/android/ui/DeepLinkingIntentReceiverViewModelTest.kt
Labels: Deeplinks, [Type] Task

#14467 Jetpack App (Basics): Update Control Activated Colors (Checkbox, Switch, Etc)
  WordPress/src/main/res/layout/number_picker_dialog.xml
  WordPress/src/main/res/layout/plugin_detail_activity.xml
  WordPress/src/main/res/values/styles.xml
Labels: Jetpack App, Jetpack Mobile, [Status] Needs Design Review, [Status] Not Ready for Merge

#14497 Improve handling of tracking URLs for deeplinks
  WordPress/src/main/java/org/wordpress/android/ui/DeepLinkingIntentReceiverViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/DeepLinkingIntentReceiverViewModelTest.kt
Labels: Deeplinks, [Type] Enhancement

#14446 Remove unused encrypted logging files
  WordPress/build.gradle
  WordPress/src/androidTest/java/org/wordpress/android/util/EncryptionUtilsTest.kt
  WordPress/src/main/java/org/wordpress/android/util/encryptedlogging/EncryptedLogReader.kt
  WordPress/src/main/java/org/wordpress/android/util/encryptedlogging/EncryptedLogWriter.kt
  WordPress/src/main/java/org/wordpress/android/util/encryptedlogging/EncryptedSecretStreamKey.kt
  WordPress/src/main/java/org/wordpress/android/util/encryptedlogging/EncryptionUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/encryptedlogging/SecretStreamKey.kt
Labels: Tooling

#14504 Change Tracks Event Prefix
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/modules/TrackerModule.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Jetpack App, [Type] Task

#14515 Align wpandroid to fluxc di changes
  WordPress/src/androidTest/java/org/wordpress/android/modules/AppComponentTest.kt
  WordPress/src/debug/java/org/wordpress/android/modules/AppComponentDebug.java
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  build.gradle
Labels: General, [Type] Bug

#14498 ExPlat: Sync implementation with latest updates from FluxC
  WordPress/src/androidTest/java/org/wordpress/android/modules/AppComponentTest.kt
  WordPress/src/debug/java/org/wordpress/android/modules/AppComponentDebug.java
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/util/experiments/ExPlat.kt
  WordPress/src/test/java/org/wordpress/android/util/experiments/ExPlatTest.kt
  build.gradle
Labels: ExPlat, [Status] Not Ready for Merge, [Type] Enhancement

#14505 Fix keyboard overlapping comment details
  WordPress/src/main/AndroidManifest.xml
Labels: Comments, [Status] Needs Code Review

#14501 Add handling for notifications deeplinks
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/DeepLinkNavigator.kt
  WordPress/src/main/java/org/wordpress/android/ui/DeepLinkingIntentReceiverViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/NotificationsLinkHandler.kt
  WordPress/src/test/java/org/wordpress/android/ui/DeepLinkingIntentReceiverViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/NotificationsLinkHandlerTest.kt
Labels: Deeplinks, [Type] Task

#14514 Jetpack App (Basics): Update Notifications Colors
  WordPress/src/jetpack/res/drawable/bg_nav_badge.xml
  WordPress/src/jetpack/res/drawable/bg_note_avatar_badge.xml
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainNavigationView.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/adapters/NotesAdapter.java
  WordPress/src/main/res/drawable/bg_nav_badge.xml
  WordPress/src/main/res/drawable/bg_note_avatar_badge.xml
  WordPress/src/main/res/layout/navbar_item.xml
  WordPress/src/main/res/layout/notifications_list_item.xml
Labels: Jetpack App, Jetpack Mobile, [Status] Needs Design Review

#14385 Update gutenberg mobile version to use S3 maven repo
  build.gradle
  settings.gradle
Labels: Tooling, gutenberg-mobile

#14519 Deeplink improvements
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/ReaderLinkHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkNavigator.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkUriUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkingIntentReceiverActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkingIntentReceiverViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/EditorLinkHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/NotificationsLinkHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/ReaderLinkHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/ServerTrackingHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/StartLinkHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/StatsLinkHandler.kt
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/DeepLinkUriUtilsTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/DeepLinkingIntentReceiverViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/EditorLinkHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/NotificationsLinkHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/StartLinkHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/StatsLinkHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/UriTestHelper.kt
Labels: Deeplinks, [Type] Enhancement

#14524 Merge 17.2 release notes into develop
  Gemfile.lock
  WordPress/build.gradle
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  WordPress/metadata/release_notes_short.txt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sr/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
Labels: Releases

#14477 Adding pagination to list of post and comment likers
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngageItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleAdapterDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagementUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/GetLikesHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/GetLikesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/NextPageLoadViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
  WordPress/src/main/res/layout/load_or_action_item.xml
  build.gradle
Labels: Notifications, Reader, [Type] Enhancement

#14486 Show only host when displaying URL of a site you are trying to log-in
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginUsernamePasswordFragment.java
Labels: Login, [Status] Needs Code Review

#14528 Fixes Page Layout Picker not filtering layouts based on supported blocks
  build.gradle
Labels: [Type] Bug

#14516 Add illustration for no network state in comments list
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsListFragment.java
Labels: Comments, [Status] Needs Code Review

#14487 Make the IME Submit button work fullscreen reply dialog in landscape orientation
  WordPress/src/main/java/org/wordpress/android/ui/CommentFullScreenDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java
Labels: Comments, [Status] Needs Code Review

#14525 Issue/14137 likers analytics
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/engagement/BottomSheetUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngageItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedListNavigationEvent.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagementSources.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagementUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/LikedItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/LikerViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/ListScenario.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/ListScenarioUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/UserProfileBottomSheetFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/UserProfileViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/tracker/ReaderTracker.kt
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtilsWrapper.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Notifications, Reader, [Type] Enhancement

#14536 Integrate gutenberg-mobile release 1.51.1
  build.gradle
Labels: gutenberg-mobile

#14532 Adding like enhancements unit testing
  WordPress/src/test/java/org/wordpress/android/ui/engagement/EngagementUtilsTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/engagement/GetLikesHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/engagement/ListScenarioUtilsTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/engagement/usecases/GetLikesUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/engagement/utils/GetLikesTestUtils.kt
Labels: Notifications, Reader, [Type] Enhancement

#14520 Jetpack App (Basics): Update Stats Colors
  WordPress/src/jetpack/res/values-night/colors_stats.xml
  WordPress/src/jetpack/res/values/colors_stats.xml
  WordPress/src/main/res/values-night/colors.xml
  WordPress/src/main/res/values-night/colors_stats.xml
  WordPress/src/main/res/values/colors.xml
  WordPress/src/main/res/values/colors_stats.xml
Labels: Jetpack App, Jetpack Mobile, [Status] Needs Design Review

#14527 Jetpack App (Basics): Hide Reader
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainNavigationView.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragmentPage.kt
Labels: Jetpack App

#14542 Reader: Reattach listeners to collapsible reply dialog on config change.
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderCommentListActivity.java
Labels: Comments, Reader, [Status] Needs Code Review

#14549 Update/ci tools release branch
  .circleci/config.yml
  fastlane/Fastfile
Labels: Tooling

#14547 Adds test verifying that the supported-blocks.json is loading
  WordPress/src/androidTest/java/org/wordpress/android/util/SupportedBlocksProviderTest.kt
Labels: Testing

#14507 Jetpack App (Basics) - Add push notifications app key
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/push/GCMRegistrationIntentService.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/NotificationsUtils.java
Labels: Jetpack App, [Type] Task

#14494 Remove steps to install buldletool and install new jdk
  .circleci/config.yml
  fastlane/Fastfile
Labels: Tooling

#14534 Update release toolkit version to 0.18.0
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/ScreenshotFastfile
  tools/exported-language-codes.csv
  tools/review-language-codes.csv
  tools/update-translations.sh
Labels: Tooling

#14530 Deeplinks improvements
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkNavigator.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkUriUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkingIntentReceiverActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkingIntentReceiverViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/EditorLinkHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/PagesLinkHandler.kt
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/DeepLinkingIntentReceiverViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/EditorLinkHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/PagesLinkHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/UriTestHelper.kt
Labels: Deeplinks, [Type] Enhancement

#14541 Like enhancements unit testing 2
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/engagement/EngagedPeopleListViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/engagement/UserProfileViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/engagement/utils/GetLikesTestUtils.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt
Labels: Notifications, Reader, [Type] Enhancement

#14526 Add wildcard ignore for .configure-files folder
  .gitignore
Labels: Tooling

#14556 Bug Fix: Manage Topics and Sites Settings
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderSubsActivity.java
Labels: Reader, [Type] Bug

#14561 [WP Stories] Fix stories error snackbar handling
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SiteStoriesHandler.kt
Labels: WP Stories

#14553 Jetpack App (Emphasis): Remove FAB from My Site
  WordPress/src/main/java/org/wordpress/android/util/BuildConfigWrapper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModelTest.kt
Labels: Jetpack App

#14564 Update Dagger components to use `OkHttClientModule`
  WordPress/src/androidTest/java/org/wordpress/android/modules/AppComponentTest.kt
  WordPress/src/debug/java/org/wordpress/android/modules/AppComponentDebug.java
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  build.gradle
Labels: Tech debt

#14555 Deleting like clutter data by threshold timestamp.
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
  WordPress/src/main/res/layout/reader_fragment_post_detail.xml
  WordPress/src/main/res/layout/reader_post_likers_faces_list.xml
  WordPress/src/test/java/org/wordpress/android/ui/engagement/EngagedPeopleListViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt
Labels: Notifications, Reader, [Type] Enhancement

#14557 Move Story option to the top of the main Create menu
  WordPress/src/main/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListCreateMenuViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListCreateMenuViewModelTest.kt
Labels: WP Stories, [Type] Task

#14569 Fixing issue with multiple tap on same liker.
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleListFragment.kt
Labels: Notifications, Reader, [Type] Bug

#14572 Dont fetch likes for feeds
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
Labels: Notifications, Reader, [Type] Enhancement

#14573 Allow opening header blog by id and site url.
  WordPress/src/main/java/org/wordpress/android/ui/engagement/LikedItemViewHolder.kt
Labels: Notifications, Reader, [Type] Enhancement

#14568 Add retry to get expected like state
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/GetLikesHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/GetLikesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/LikedItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/engagement/GetLikesHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/engagement/usecases/GetLikesUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt
Labels: Notifications, Reader, [Type] Enhancement
