Repository wordpress-mobile/WordPress-Android, pull requests merged in 2021-08, with the labels that each got.

#15106 Issue/uc remove feature flag
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentsActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/ListItemAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SiteItemsBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SiteListItemBuilder.kt
  WordPress/src/main/java/org/wordpress/android/util/config/UnifiedCommentsListFeatureConfig.kt
  WordPress/src/main/res/layout/my_site_fragment.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/SiteItemFixtures.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/SiteItemsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/SiteListItemBuilderTest.kt
Labels: Comments Unification, [Status] Needs Code Review

#15113 Removes kotlin-gradle-plugin dependency from WordPressEditor
  libs/editor/WordPressEditor/build.gradle
Labels: Tooling

#15115 Update Buildkite Docker image to fix lint task
  .buildkite/pipeline.yml
Labels: Tooling

#15111 Merge 17.9-rc-3 into develop
  WordPress/src/main/res/values-da/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  version.properties
Labels: Releases

#15110 Onboarding Improvements: Enable Feature Flag
  WordPress/src/main/java/org/wordpress/android/util/config/OnboardingImprovementsFeatureConfig.kt
Labels: Onboarding Improvements: Existing Users, [Type] Task

#15121 Onboarding Improvements: Fix E2E UI Tests
  WordPress/src/androidTest/java/org/wordpress/android/e2e/LoginTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/flows/LoginFlow.java
  WordPress/src/androidTest/java/org/wordpress/android/support/BaseTest.java
Labels: Onboarding Improvements: Existing Users, Testing

#15122 Introduce `Quick Start - Dynamic Cards` feature flag and guard the feature
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/config/QuickStartDynamicCardsFeatureConfig.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: My Site Dashboard, My Site Dynamic Cards, [Type] Task

#15038 [Gutenberg] Add new block type badge to block inserter list
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  build.gradle
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragmentAbstract.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergContainerFragment.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergPropsBuilder.kt
Labels: [Type] Enhancement, gutenberg-mobile

#15119 Fluxc from s3
  WordPress/build.gradle
  build.gradle
  settings.gradle
Labels: Tooling

#15133 Integrate gutenberg-mobile release 1.58.2
  build.gradle
Labels: gutenberg-mobile

#15037 [Tooling] Fix hotfix lanes
  .bundle/config
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: Tooling

#15137 Issue/uc list check empty site
  WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentsActivity.kt
Labels: Comments Unification, [Status] Needs Code Review

#15138 Moves windowLayoutInDisplayCutoutMode & windowLightNavigationBar usage to API 27
  WordPress/src/main/res/values-v27/styles.xml
  WordPress/src/main/res/values/styles.xml
Labels: Tooling

#15060 Themes: Fix theme url to include the correct image resized url
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/themes/ThemeBrowserAdapter.java
Labels: Themes, [Type] Bug

#15140 Merge release/17.9 into develop (rc-4)
  .bundle/config
  Gemfile.lock
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  fastlane/Pluginfile
  version.properties
Labels: Releases

#15143 Issue/uc show retry button in footer after timeout
  WordPress/src/main/java/org/wordpress/android/models/usecases/PaginateCommentsResourceProvider.kt
  WordPress/src/main/java/org/wordpress/android/models/usecases/PaginateCommentsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/comments/usecases/PaginateCommentsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/comments/UnifiedCommentListViewModelTest.kt
Labels: [Status] Needs Code Review, Comments Unification

#15131 Reenables support for Global Style Colors with Full Site Editing Themes
  RELEASE-NOTES.txt
  WordPress/build.gradle
Labels: [Type] Enhancement, Posting/Editing

#15141 Migrate old Quick Start UI code to ImprovedMySiteFragment as Quick Start Block
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapterDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockViewHolder.kt
  WordPress/src/main/res/layout/quick_start_block.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockBuilderTest.kt
Labels: Quick Start, My Site Dashboard

#15142 Integrate gutenberg-mobile release 1.59.0
  RELEASE-NOTES.txt
  build.gradle
Labels: gutenberg-mobile

#15151 Add Create Site notification tracking
  WordPress/src/main/java/org/wordpress/android/push/NotificationType.kt
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/SystemNotificationsTracker.kt
  WordPress/src/main/java/org/wordpress/android/workers/CreateSiteNotificationHandler.kt
  WordPress/src/main/java/org/wordpress/android/workers/CreateSiteNotificationScheduler.kt
  WordPress/src/main/java/org/wordpress/android/workers/LocalNotificationHandlerFactory.kt
  WordPress/src/main/java/org/wordpress/android/workers/LocalNotificationWorker.kt
  WordPress/src/test/java/org/wordpress/android/ui/notifications/SystemNotificationsTrackerTest.kt
  WordPress/src/test/java/org/wordpress/android/workers/CreateSiteNotificationHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/workers/CreateSiteNotificationSchedulerTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Enhancement, Notifications

#15148 My Site Dashboard - Phase 1 - Fix QSP for the Site Picker and Login Epilogue Screens
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/mysite/ImprovedMySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SiteNavigationAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/QuickStartUtilsWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: [Type] Task, My Site Dashboard

#15147 Handle Quick Start - Task Type List Item action in `ImprovedMySiteFragment`
  WordPress/src/main/java/org/wordpress/android/ui/mysite/ImprovedMySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SiteNavigationAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockViewHolder.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockBuilderTest.kt
Labels: Quick Start, My Site Dashboard

#15156 Merge release/18.0 into develop (code freeze)
  RELEASE-NOTES.txt
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/release_notes.txt
  WordPress/src/main/res/values/strings.xml
  build.gradle
  fastlane/resources/values/strings.xml
  version.properties
Labels: Releases

#15159 Migrate `Quick Start - List Item` refresh logic to `ImprovedMySiteFragment`
  WordPress/src/main/java/org/wordpress/android/ui/mysite/ImprovedMySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/QuickStartRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockBuilder.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/QuickStartRepositoryTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockBuilderTest.kt
Labels: Quick Start, My Site Dashboard

#15155 My Site Dashboard - Phase 1 - Connect QSP with QS for the Improved My Site Screen
  WordPress/src/main/java/org/wordpress/android/ui/mysite/ImprovedMySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: [Type] Task, My Site Dashboard

#15051 [Gutenberg] Embed block: Implement specific Embed preview
  build.gradle
Labels: Gutenberg, gutenberg-mobile

#15162 Quick Start: Remove if conditions in the VM to display the quick start block
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: Quick Start, My Site Dashboard

#15173 Merge release/18.0 into develop (Release Notes)
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/JetpackPlayStoreStrings.po
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: Releases

#15166 Integrate gutenberg-mobile release 1.58.3
  build.gradle
Labels: gutenberg-mobile

#15174 Update login library to 0.0.4
  WordPress/build.gradle
  build.gradle
Labels: Login, Tooling

#15163 Migrate quick start notification reminders
  WordPress/src/main/java/org/wordpress/android/ui/mysite/QuickStartRepository.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/QuickStartRepositoryTest.kt
Labels: [Type] Task, My Site Dashboard

#15170 Integrate gutenberg-mobile release 1.59.1
  build.gradle
Labels: gutenberg-mobile

#15167 Migrate `Quick Start - More Menu` to `ImprovedMySiteFragment`
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/QuickStartRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SiteDialogModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockViewHolder.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/QuickStartRepositoryTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockBuilderTest.kt
Labels: Quick Start, My Site Dashboard

#15169 Unit tests for Quick Start Dynamic Card vs Block display
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: Quick Start, My Site Dashboard

#15186 Merge release/17.9.1 into release/18.0
  version.properties
Labels: Releases

#15153 Add debug cookies feature – Part 2
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/debug/DebugSettingsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/DebugSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/cookies/DebugCookie.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/cookies/DebugCookieManager.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/cookies/DebugCookiesActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/cookies/DebugCookiesAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/cookies/DebugCookiesFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/cookies/DebugCookiesViewModel.kt
  WordPress/src/main/res/layout/debug_cookie_item.xml
  WordPress/src/main/res/layout/debug_cookies_activity.xml
  WordPress/src/main/res/layout/debug_cookies_fragment.xml
  WordPress/src/main/res/values/strings.xml
  build.gradle
Labels: [Type] Enhancement, [Status] Not Ready for Merge

#15152 Add debug cookies feature – Part 1
  WordPress/build.gradle
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/debug/DebugSettingsActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/DebugSettingsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/DebugSettingsDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/DebugSettingsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/DebugSettingsItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/DebugSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/cookies/DebugCookie.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/cookies/DebugCookieManager.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/cookies/DebugCookiesActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/cookies/DebugCookiesAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/cookies/DebugCookiesFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/cookies/DebugCookiesViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/util/BuildConfigWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/DebugUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/config/AppConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/ManualFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/manual/FeatureAdapter.kt
  WordPress/src/main/java/org/wordpress/android/util/config/manual/FeatureDiffCallback.kt
  WordPress/src/main/res/layout/debug_cookie_item.xml
  WordPress/src/main/res/layout/debug_cookies_activity.xml
  WordPress/src/main/res/layout/debug_cookies_fragment.xml
  WordPress/src/main/res/layout/debug_settings_activity.xml
  WordPress/src/main/res/layout/debug_settings_button.xml
  WordPress/src/main/res/layout/debug_settings_feature.xml
  WordPress/src/main/res/layout/debug_settings_fragment.xml
  WordPress/src/main/res/layout/debug_settings_header.xml
  WordPress/src/main/res/layout/debug_settings_row.xml
  WordPress/src/main/res/values/key_strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/app_settings.xml
  WordPress/src/test/java/org/wordpress/android/ui/debug/DebugSettingsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/util/config/AppConfigParametrizedTest.kt
  WordPress/src/test/java/org/wordpress/android/util/config/AppConfigTest.kt
  WordPress/src/test/java/org/wordpress/android/util/config/ManualFeatureConfigTest.kt
Labels: [Type] Enhancement, [Status] Not Ready for Merge

#15194 Merge release/18.0 into develop
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/JetpackPlayStoreStrings.po
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  version.properties
Labels: Releases

#15190 Remove unused Gutenberg Mobile feature flags
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/util/config/ContactInfoBlockFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/LayoutGridBlockFeatureConfig.kt
Labels: [Type] Task, gutenberg-mobile

#15188 Merge hotfix 17.9.1 into trunk
  build.gradle
  version.properties
Labels: Releases

#15183 Hide keyboard on prologue screen
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginProloguePageFragment.kt
Labels: Login

#15178 Add tracking for time selection
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersAnalyticsTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersUiModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersAnalyticsTrackerTest.kt
Labels: [Type] Task, Blogging Reminders

#15195 Add Weekly Roundup notification
  WordPress/src/main/java/org/wordpress/android/push/NotificationPushIds.kt
  WordPress/src/main/java/org/wordpress/android/push/NotificationType.kt
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/SystemNotificationsTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/SiteUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/workers/WordPressWorkersFactory.kt
  WordPress/src/main/java/org/wordpress/android/workers/weeklyroundup/WeeklyRoundupData.kt
  WordPress/src/main/java/org/wordpress/android/workers/weeklyroundup/WeeklyRoundupNotification.kt
  WordPress/src/main/java/org/wordpress/android/workers/weeklyroundup/WeeklyRoundupNotifier.kt
  WordPress/src/main/java/org/wordpress/android/workers/weeklyroundup/WeeklyRoundupRepository.kt
  WordPress/src/main/java/org/wordpress/android/workers/weeklyroundup/WeeklyRoundupScheduler.kt
  WordPress/src/main/java/org/wordpress/android/workers/weeklyroundup/WeeklyRoundupUtils.kt
  WordPress/src/main/java/org/wordpress/android/workers/weeklyroundup/WeeklyRoundupWorker.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/notifications/SystemNotificationsTrackerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/StatsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/workers/weeklyroundup/WeeklyRoundupDataTest.kt
  WordPress/src/test/java/org/wordpress/android/workers/weeklyroundup/WeeklyRoundupNotifierTest.kt
  WordPress/src/test/java/org/wordpress/android/workers/weeklyroundup/WeeklyRoundupRepositoryTest.kt
  WordPress/src/test/java/org/wordpress/android/workers/weeklyroundup/WeeklyRoundupUtilsTest.kt
Labels: Notifications, [Type] Task

#15128 Time Selection Feature
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingReminderBottomSheetFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingReminderTimePicker.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingReminderUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersAnalyticsTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersModelMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersUiModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/DaySelectionBuilder.kt
  WordPress/src/main/java/org/wordpress/android/workers/reminder/ReminderScheduler.kt
  WordPress/src/main/java/org/wordpress/android/workers/reminder/ReminderWorker.kt
  WordPress/src/main/res/layout/blogging_reminders_time.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersAnalyticsTrackerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/bloggingreminders/DaySelectionBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/bloggingreminders/EpilogueBuilderTest.kt
  build.gradle
Labels: [Type] Task, Blogging Reminders

#15206 Force FluxC version to be strict and update it to the latest
  WordPress/build.gradle
  build.gradle
Labels: Tooling

#15204 Update copy to Site Settings
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Enhancement, /My site

#15211 Integrate gutenberg-mobile release 1.59.2
  build.gradle
Labels: gutenberg-mobile

#15196 [Gutenberg] Remove image count from gallery processor
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/GalleryBlockProcessor.java
  WordPress/src/test/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/TestContent.kt
Labels: gutenberg-mobile, Tech debt

#15207 Fix/15184 domain results hidden in landscape
  WordPress/src/main/res/layout/site_creation_search_input_item.xml
Labels: [Type] Bug, Domain Search

#15218 Merge release/18.0 into develop
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  version.properties
Labels: Releases

#15217 Feature/15214 blogging reminders add time on epilogue
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/EpilogueBuilder.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/bloggingreminders/EpilogueBuilderTest.kt
Labels: [Type] Task, Blogging Reminders

#15164 Enable editor help menu for eligible users
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  build.gradle
Labels: [Type] Enhancement, gutenberg-mobile

#15221 Update time for Blogging Reminders Site Settings
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/DayLabelUtils.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersViewModelTest.kt
Labels: [Type] Task, Blogging Reminders

#15203 My Site Dashboard - Phase 1 - Quick Start
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockViewHolder.kt
  WordPress/src/main/res/drawable/ic_list_checkmark_white_24dp.xml
  WordPress/src/main/res/layout/quick_start_block.xml
  WordPress/src/main/res/layout/quick_start_task_type_item.xml
  WordPress/src/main/res/layout/quick_start_toolbar.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockBuilderTest.kt
Labels: Quick Start, My Site Dashboard

#15223 Integrate gutenberg-mobile release 1.60.0
  RELEASE-NOTES.txt
  build.gradle
Labels: gutenberg-mobile

#15225 Update release notes to include Blogging Reminders v2 and Weekly Roundup
  RELEASE-NOTES.txt
Labels: [Type] Task, Blogging Reminders

#15219 Track analytic event when editor help is shown
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsTrackerWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtils.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Enhancement, Analytics

#14533 Prepublishing publish button cut off on some devices
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingBottomSheetFragment.kt
  WordPress/src/main/java/org/wordpress/android/util/KeyboardResizeViewUtil.java
  WordPress/src/main/res/layout/prepublishing_action_list_item.xml
  WordPress/src/main/res/layout/prepublishing_home_publish_button_list_item.xml
  WordPress/src/main/res/layout/prepublishing_story_title_list_item.xml
  WordPress/src/main/res/values/dimens.xml
Labels: [Type] Task, Prepublishing Nudges

#15224 Comment details like status on background.
  build.gradle
Labels: [Type] Bug, Comments Unification

#15100 Fix NPE crash in PostFormatsError class
  RELEASE-NOTES.txt
  build.gradle
Labels: Site Settings, Post Settings

#15227 Domain Purchase Feature Flag
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/util/config/DomainPurchaseFeatureConfig.kt
Labels: [Type] Task, Domain Selling

#15233 Merge release/18.1 into develop (code freeze)
  RELEASE-NOTES.txt
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/release_notes.txt
  WordPress/src/main/res/values/strings.xml
  build.gradle
  fastlane/resources/values/strings.xml
  version.properties
Labels: Releases

#15216 Remove translations reviewers build
  .circleci/config.yml
Labels: Tooling

#15197 My Site Dashboard - Phase 1 - Refactor use of Repository in favor of Prefs for Selected Site
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginEpilogueActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/mysite/DomainRegistrationHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/ImprovedMySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteSource.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteStateProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/QuickStartRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/ScanAndBackupSource.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SelectedSiteRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SiteIconUploadHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/dynamiccards/DynamicCardsSource.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/receivers/NotificationsPendingDraftsReceiver.java
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartFullScreenDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartMySitePrompts.kt
  WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartReminderReceiver.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsSiteProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
  WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/QuickStartUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/mlp/ModalLayoutPickerViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/DomainRegistrationHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/QuickStartRepositoryTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/ScanAndBackupSourceTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/SelectedSiteRepositoryTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/dynamiccards/DynamicCardsSourceTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/StatsSiteProviderTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/mlp/ModalLayoutPickerViewModelTest.kt
  config/detekt/baseline.xml
  docs/faq.md
Labels: [Type] Task, My Site Dashboard

#15232 Site domains setting
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/util/config/SiteDomainsFeatureConfig.kt
  WordPress/src/main/res/values/key_strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/site_settings.xml
Labels: [Type] Task, Domain Selling

#15236 Migrate Snackbar Reminders to ImprovedMySiteFragment
  WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/ImprovedMySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/QuickStartRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/SnackbarMessageHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostConflictResolver.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/QuickStartUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/SnackbarSequencer.kt
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/QuickStartRepositoryTest.kt
Labels: Quick Start, My Site Dashboard

#15237 My Site Dashboard: Phase 1 - Quick Start finetune UI
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockViewHolder.kt
  WordPress/src/main/res/drawable/ic_list_checkmark_white_24dp.xml
  WordPress/src/main/res/drawable/quick_start_card_progress_drawable.xml
  WordPress/src/main/res/layout/quick_start_block.xml
  WordPress/src/main/res/layout/quick_start_task_type_item.xml
  WordPress/src/main/res/layout/quick_start_toolbar.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockBuilderTest.kt
Labels: [Type] Task, [Status] Needs Design Review, Quick Start, My Site Dashboard

#15254 Merge release/18.1 into develop (rc-2)
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-az/strings.xml
  WordPress/src/main/res/values-bg/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-cy/strings.xml
  WordPress/src/main/res/values-da/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-eu/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gd/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-hi/strings.xml
  WordPress/src/main/res/values-hr/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-is/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-kmr/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-ms/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sr/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-th/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  build.gradle
  version.properties
Labels: Releases

#15230 [Tooling] Use same version for WP and JP
  Gemfile.lock
  WordPress/build.gradle
  fastlane/Fastfile
  fastlane/Pluginfile
  version.properties
Labels: Tooling

#15248 Train of likes animation
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagedPeopleListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagementUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/GetLikesHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/GetLikesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostLikersAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostLikersAdapterDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/TrainOfFacesItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewholders/BloggingLikersTextViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewholders/PostLikerItemDecorator.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewholders/PostLikerViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewholders/TrainOfFacesViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
  WordPress/src/main/res/layout/blogger_likers_text_item.xml
  WordPress/src/main/res/layout/liker_face_item.xml
  WordPress/src/main/res/layout/reader_post_likers_faces_list.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/engagement/EngagedPeopleListViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/engagement/GetLikesHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/engagement/usecases/GetLikesUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt
Labels: [Type] Enhancement, Reader, Likes

#15255 My Site Dashboard: Phase 1 - Reminder Notifications Fix
  WordPress/src/main/java/org/wordpress/android/util/QuickStartUtilsWrapper.kt
Labels: [Type] Task, My Site Dashboard

#15257 Fixes 13644 NullPointerException updatedSite must not be null
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListEventListener.kt
Labels: [Type] Bug, Pages List, [Type] Crash

#15247 My Site Dashboard: Phase 1 - Quick Actions: Hide more menu
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/quickactions/QuickActionsBlockBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/quickactions/QuickActionsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockViewHolder.kt
  WordPress/src/main/res/layout/my_site_card_toolbar.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteItemTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/quickactions/QuickActionsBlockBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/quickstart/QuickStartBlockBuilderTest.kt
Labels: Quick Start, My Site Dashboard
