Repository wordpress-mobile/WordPress-Android, pull requests merged in 2021-03, with the labels that each got.

#14109 Improvement: Reader: Add sorting option to Discover or Topics
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderDatabase.java
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderDiscoverCardsTable.kt
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderDiscoverCardsTableWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/DiscoverSortingType.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/repository/ReaderDiscoverDataProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/repository/usecases/FetchDiscoverCardsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/repository/usecases/GetDiscoverCardsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/services/discover/ReaderDiscoverJobService.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/services/discover/ReaderDiscoverLogic.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/services/discover/ReaderDiscoverService.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/services/discover/ReaderDiscoverServiceStarter.kt
  WordPress/src/main/java/org/wordpress/android/util/config/FilterDiscoverFeatureConfig.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/repository/ReaderDiscoverDataProviderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/repository/usecases/GetDiscoverCardsUseCaseTest.kt
Labels: New Reader Android

#14164 Issue/14128 reader related posts UI refactoring
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderRelatedPostsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderRelatedPostViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailUiStateBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSimplePostContainerView.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSimplePostContainerView.kt
  WordPress/src/main/res/layout/reader_cardview_related_post.xml
  WordPress/src/main/res/layout/reader_simple_posts_container_view.xml
  WordPress/src/test/java/org/wordpress/android/ui/reader/ReaderPostDetailsUiStateBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt
  config/detekt/baseline.xml
Labels: New Reader Android

#14159 Small Reader Improvements: Topics Management
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/RequestCodes.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderSubsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/interests/ReaderInterestsActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/interests/ReaderInterestsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/interests/ReaderInterestsViewModel.kt
  WordPress/src/main/res/layout/reader_activity_subs.xml
  WordPress/src/main/res/layout/reader_interests_activity.xml
  WordPress/src/main/res/layout/reader_interests_fragment_layout.xml
  WordPress/src/main/res/layout/reader_listitem_tag.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/interests/ReaderInterestsViewModelTest.kt
Labels: New Reader Android

#14176 Update Stats item layout to support larger font sizes
  WordPress/src/main/res/layout/stats_block_dialog_buttons_item.xml
Labels: Accessibility, Stats, [Type] Bug

#14149 Fix empty screen when logging in without a site
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SelectedSiteRepository.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/SelectedSiteRepositoryTest.kt
Labels: /My site, My Site Dynamic Cards, [Type] Bug

#14163 Issue/14128 related posts actions refactoring
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderNavigationEvents.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostCardActionsHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderRelatedPostViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailUiStateBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSimplePostContainerView.kt
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtilsWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/ReaderPostDetailUiStateBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/usecases/ReaderPostSeenStatusToggleUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt
  config/detekt/baseline.xml
Labels: New Reader Android

#14179 Start QS only for the newly created site
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/mysite/ImprovedMySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/QuickStartRepository.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/QuickStartRepositoryTest.kt
Labels: /My site, My Site Dynamic Cards, [Type] Bug

#14114 Video compression: managing npe and tracking it in MEDIA_VIDEO_CANT_OPTIMIZE event
  WordPress/src/main/java/org/wordpress/android/ui/uploads/VideoOptimizer.java
Labels: Media, [Type] Bug, [Type] Crash

#14169 Add fading edges to Quick Start list
  WordPress/src/main/java/org/wordpress/android/ui/mysite/QuickStartCardViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/QuickStartListItemDecoration.kt
  WordPress/src/main/res/layout/quick_start_card.xml
Labels: /My site, My Site Dynamic Cards, [Type] Enhancement

#14139 Add max width constraint to the My Site fragment layout
  WordPress/src/main/res/layout/new_my_site_fragment.xml
Labels: /My site, My Site Dynamic Cards, [Type] Task

#14173 Update example encrypted logging key
  gradle.properties-example
Labels: Tooling

#14185 Catch and log exception when the end index of the Story block is out of bounds
  WordPress/src/main/java/org/wordpress/android/ui/stories/SaveStoryGutenbergBlockUseCase.kt
  WordPress/src/test/java/org/wordpress/android/ui/stories/SaveStoryGutenbergBlockUseCaseTest.kt
Labels: WP Stories, [Type] Crash

#14144 Adds categories to the Home Page Picker
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/ButtonsUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/CategoriesAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/CategoriesDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/CategoryListItemUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/CategoryViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutCategoryAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutCategoryDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutCategoryModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutCategoryUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutListItemUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutPickerUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutPickerViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutsDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutsItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/ThumbDimensionProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/mlp/GutenbergPageLayouts.kt
  WordPress/src/main/java/org/wordpress/android/ui/mlp/LayoutListItemUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/mlp/LayoutsDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/mlp/ModalLayoutPickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/ThumbDimensionProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/usecases/FetchHomePageLayoutsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/UiHelpers.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/mlp/ModalLayoutPickerViewModel.kt
  WordPress/src/main/res/layout-land/home_page_picker_header_section.xml
  WordPress/src/main/res/layout-sw600dp/home_page_picker_header_section.xml
  WordPress/src/main/res/layout/home_page_picker_fragment.xml
  WordPress/src/main/res/layout/home_page_picker_header_section.xml
  WordPress/src/main/res/layout/home_page_picker_item.xml
  WordPress/src/main/res/layout/home_page_picker_loading_skeleton.xml
  WordPress/src/main/res/values-sw600dp-land/dimens.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/theme/FetchHomePageLayoutsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/mlp/ModalLayoutPickerViewModelTest.kt
  build.gradle
  config/detekt/baseline.xml
Labels: [Type] Enhancement

#14174 Add issue triage guideline for tracks issues
  docs/issue-triage.md
Labels: Documentation

#14183 Issue/14004 menu item order
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderMenuAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderCardUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostUiStateBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderPostViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
  WordPress/src/main/res/layout/reader_popup_menu_item.xml
  WordPress/src/main/res/layout/reader_popup_menu_spacer_item.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilderTest.kt
  config/detekt/baseline.xml
Labels: New Reader Android

#14181 Update singular strings for threats to use 1
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/ScanViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/builders/ScanStateListItemsBuilder.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/ScanViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/builders/ScanStateListItemsBuilderTest.kt
Labels: Localization

#14191 Add content logging to help debug a Story post crash
  WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadReadyListener.java
  WordPress/src/main/java/org/wordpress/android/ui/stories/SaveStoryGutenbergBlockUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadReadyProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
  WordPress/src/test/java/org/wordpress/android/ui/stories/SaveStoryGutenbergBlockUseCaseTest.kt
Labels: WP Stories, [Type] Crash

#14190 Merge Release/16.8 beta 3 into develop
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/ScanViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/builders/ScanStateListItemsBuilder.kt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-kmr/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/ScanViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/builders/ScanStateListItemsBuilderTest.kt
  fastlane/resources/values/strings.xml
Labels: Releases

#14187 Issue/14128 reader related posts UI cleanup + design update
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailUiStateBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostCardActionsHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderRelatedPostViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/models/ReaderSimplePost.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSimplePostContainerView.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSimplePostView.java
  WordPress/src/main/res/drawable/box_with_pages_top.xml
  WordPress/src/main/res/layout/reader_cardview_related_post.xml
  WordPress/src/main/res/layout/reader_fragment_post_detail.xml
  WordPress/src/main/res/layout/reader_simple_post_view.xml
  WordPress/src/main/res/layout/reader_simple_posts_container_view.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/reader_styles.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/reader/ReaderPostDetailUiStateBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt
Labels: New Reader Android

#14122 Enable My Site Dynamic Cards remote feature flag
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/util/config/MySiteImprovementsFeatureConfig.kt
Labels: /My site, My Site Dynamic Cards, [Type] Task

#14194 Issue/14128 reader related posts
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/DeepLinkingIntentReceiverActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderConstants.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderEvents.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailUiStateBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderPostActions.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderPostActionsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderRelatedPostsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderNavigationEvents.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderRelatedPostViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/models/ReaderSimplePost.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/usecases/ReaderFetchRelatedPostsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailUiStateBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSimplePostContainerView.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSimplePostContainerView.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSimplePostView.java
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtilsWrapper.kt
  WordPress/src/main/res/drawable/box_with_pages_top.xml
  WordPress/src/main/res/layout/reader_cardview_related_post.xml
  WordPress/src/main/res/layout/reader_fragment_post_detail.xml
  WordPress/src/main/res/layout/reader_simple_post_view.xml
  WordPress/src/main/res/layout/reader_simple_posts_container_view.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/reader_styles.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/reader/ReaderPostDetailUiStateBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/usecases/ReaderFetchRelatedPostsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/usecases/ReaderPostSeenStatusToggleUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt
  config/detekt/baseline.xml
Labels: New Reader Android

#14196 Issue/13973 rename interests to topics and reads to blogs
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Task

#14197 Dynamic cards tracking
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/mysite/QuickStartRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/QuickStartUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/QuickStartRepositoryTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PageListViewModelTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: /My site, My Site Dynamic Cards, [Type] Bug

#14199 Scan: Fix strings for translation
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Bug

#14192 Adds Analytics event to capture when a category filter is selected
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutPickerTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutPickerViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mlp/ModalLayoutPickerTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SiteCreationTracker.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Analytics, [Type] Enhancement

#14165 Issue/14129 topics you might like
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderCardUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostUiStateBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderInterestViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderInterestsCardViewHolder.kt
  WordPress/src/main/res/layout/reader_interest_card.xml
  WordPress/src/main/res/layout/reader_interest_item.xml
  WordPress/src/main/res/values-night/colors.xml
  WordPress/src/main/res/values/colors.xml
  WordPress/src/main/res/values/reader_styles.xml
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderPostUiStateBuilderTest.kt
Labels: New Reader Android, Reader, [Status] Needs Design Review

#14205 Added Aztec Editor deprecation notice
  RELEASE-NOTES.txt
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java
  libs/editor/WordPressEditor/src/main/res/values/strings.xml
Labels: Aztec

#14206 Fix AztecEditor e2e test broken by deprecation dialog
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/EditorPage.java
Labels: Aztec, Testing

#14207 RI You Might Like Card: Add gesture detector to manage horizontal scrolls
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderInterestsCardViewHolder.kt
Labels: New Reader Android

#14189 [Tooling] Mark *.enc configure files as binary
  .gitattributes
Labels: Tooling

#14210 Update .editorconfig
  .editorconfig
Labels: Tooling

#14208 Init view bindings
  WordPress/build.gradle
Labels: [Type] Enhancement

#14213 Merge Release/16.9 into develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/metadata/release_notes.txt
  WordPress/metadata/release_notes_short.txt
  WordPress/src/main/res/values/strings.xml
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#14209 Feature/view binding in gif picker
  WordPress/src/main/java/org/wordpress/android/ui/gif/GifMediaViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/gif/GifPickerActivity.kt
Labels: [Type] Enhancement

#14203 Update terms in code to use more inclusive language
  WordPress/src/androidTest/java/org/wordpress/android/e2e/BlockEditorTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/EditorTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/components/MainNavBarComponent.java
  WordPress/src/androidTest/java/org/wordpress/android/util/AutolinkUtilsTest.java
  WordPress/src/main/java/org/wordpress/android/models/JetpackSettingsModel.java
  WordPress/src/main/java/org/wordpress/android/models/NoticonUtils.kt
  WordPress/src/main/java/org/wordpress/android/models/NotificationsSettings.java
  WordPress/src/main/java/org/wordpress/android/models/SiteSettingsModel.java
  WordPress/src/main/java/org/wordpress/android/push/GCMMessageHandler.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsInterface.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/WPComSiteSettings.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsDialogPreference.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/PrefMainSwitchToolbarView.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java
  WordPress/src/main/java/org/wordpress/android/util/AutolinkUtils.java
  WordPress/src/main/java/org/wordpress/android/util/WPMeShortlinks.java
  WordPress/src/main/res/layout/notifications_settings_activity.xml
  WordPress/src/main/res/layout/notifications_tab_disabled_text_layout.xml
  WordPress/src/main/res/layout/notifications_tab_for_blog_title_layout.xml
  WordPress/src/main/res/layout/preferences_main_switch_toolbar.xml
  WordPress/src/main/res/menu/notifications_settings_secondary.xml
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/key_strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/site_settings.xml
  config/detekt/baseline.xml
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Task

#14212 Removes gutenberg builds from CI
  .circleci/config.yml
  WordPress/lint-baseline.xml
  WordPress/lint.xml
Labels: Part of a WIP Feature, Tooling

#14223 Update analytics events to use more inclusive language
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Task

#14186 Use viewModelScope in the ScopedViewModel.kt class
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/ScopedViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListViewModel.kt
Labels: [Type] Enhancement

#14211 Use View Binding in Jetpack feature ViewHolders
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/common/adapters/JetpackBackupRestoreAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/common/viewholders/JetpackBackupRestoreBulletViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/common/viewholders/JetpackBackupRestoreFootnoteViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/common/viewholders/JetpackBackupRestoreSubHeaderViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/common/viewholders/JetpackButtonViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/common/viewholders/JetpackCheckboxViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/common/viewholders/JetpackDescriptionViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/common/viewholders/JetpackHeaderViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/common/viewholders/JetpackIconViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/common/viewholders/JetpackProgressViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/common/viewholders/JetpackViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/adapters/ScanAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/adapters/viewholders/ThreatLoadingSkeletonViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/adapters/viewholders/ThreatViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/adapters/viewholders/ThreatsDateHeaderViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/adapters/viewholders/ThreatsHeaderViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/details/adapters/ThreatDetailsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/details/adapters/viewholders/ThreatContextLinesViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/details/adapters/viewholders/ThreatDetailHeaderViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/details/adapters/viewholders/ThreatFileNameViewHolder.kt
Labels: [Type] Enhancement

#14232 Use viewModelScope instead of casting ViewModel to CoroutineScope
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerFragment.kt
Labels: Media, [Type] Crash

#14225 Use View Binding in Reader ViewHolders
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderInterestViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderInterestsCardViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderPostViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderRecommendedBlogViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderRecommendedBlogsCardViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderRelatedPostViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/WelcomeBannerViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/util/ViewBindingUtils.kt
Labels: Reader, Tech debt, [Type] Enhancement

#14217 Use view binding in stats
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/AppBarUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailFragment.kt
  WordPress/src/main/res/layout/stats_detail_activity.xml
  WordPress/src/main/res/layout/stats_list_activity.xml
  WordPress/src/main/res/layout/stats_list_fragment.xml
  WordPress/src/main/res/layout/stats_view_all_activity.xml
  WordPress/src/main/res/layout/stats_view_all_fragment.xml
Labels: [Type] Enhancement

#14230 Add My Site feature flag handling to connected tests
  WordPress/src/androidTest/java/org/wordpress/android/e2e/BlockEditorTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/EditorTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/components/MainNavBarComponent.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/MySitesPage.java
Labels: /My site, My Site Dynamic Cards, Testing, [Type] Bug

#14237 Merge Release/16.9 release notes into develop
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  WordPress/metadata/release_notes_short.txt
Labels: Releases

#14233 Use View Binding in My Site
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/DomainRegistrationViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/ImprovedMySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCategoryViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteInfoViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/QuickActionsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/QuickStartCardViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/QuickStartTaskCardAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/dynamiccards/DynamicCardMenuFragment.kt
Labels: /My site, Tech debt, [Type] Enhancement

#14241 Use View Binding in Me screen
  WordPress/src/main/java/org/wordpress/android/ui/main/MainBottomSheetFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/res/layout/me_activity.xml
Labels: /Me, Tech debt, [Type] Enhancement

#14229 Merge Release/16.8.1 into develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
Labels: Releases

#14255 Merge update 16.9 release notes into develop
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  WordPress/metadata/release_notes_short.txt
Labels: Releases

#14140 Use tabs for comment filters
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsDetailActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentsListPagerAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/comments/LoadCommentsTask.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/res/layout/comment_activity.xml
  WordPress/src/main/res/layout/comment_list_fragment.xml
  WordPress/src/main/res/values/key_strings.xml
  build.gradle
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Comments, [Status] Needs Code Review

#14224 Use View Binding in Reader Activities and Fragments
  WordPress/src/main/java/org/wordpress/android/ui/reader/NoSiteToReblogActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/interests/ReaderInterestsActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/interests/ReaderInterestsFragment.kt
  WordPress/src/main/res/layout/reader_interests_fragment_layout.xml
  WordPress/src/main/res/layout/reader_no_site_to_reblog.xml
Labels: Reader, Tech debt, [Type] Enhancement

#14251 Use View Binding in Reader views
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderBookmarkButton.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderPostDetailHeaderView.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSimplePostContainerView.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderTagHeaderView.kt
  WordPress/src/main/res/color/on_surface_medium_primary_selector.xml
  WordPress/src/main/res/layout/reader_bookmark_button.xml
  WordPress/src/main/res/values/strings.xml
Labels: Reader, Tech debt, [Type] Enhancement

#14252 Use View Binding in Notifications
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragmentPage.kt
Labels: Reader, Tech debt, [Type] Enhancement

#14258 Fix featured image not displaying for some posts with another image
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/FeaturedImageUtils.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/utils/FeaturedImageUtilsTest.kt
Labels: New Reader Android

#14227 Use view binding in activity log
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/detail/ActivityLogDetailActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/detail/ActivityLogDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/ActivityLogListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/ActivityLogListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/list/filter/ActivityLogTypeFilterFragment.kt
  WordPress/src/main/res/layout/activity_log_detail_activity.xml
  WordPress/src/main/res/layout/activity_log_type_filter_fragment.xml
  WordPress/src/main/res/layout/progress_layout.xml
Labels: [Type] Enhancement

#14235 Use view binding in domain registration
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationResultFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainSuggestionsFragment.kt
  WordPress/src/main/res/layout/domain_suggestions_activity.xml
Labels: [Type] Enhancement

#14236 Use view binding in media picker
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerFragment.kt
Labels: [Type] Enhancement

#14249 Feature/use view binding in posts
  WordPress/src/main/java/org/wordpress/android/ui/posts/HistoryListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListCreateMenuFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingAddCategoryFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingBottomSheetFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingCategoriesAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingCategoriesFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingCategoriesViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingHomeFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingTagsFragment.kt
  WordPress/src/main/res/layout/prepublishing_add_category_fragment.xml
  WordPress/src/main/res/layout/prepublishing_tags_fragment.xml
Labels: [Type] Enhancement

#14250 Use view binding in settings and stories
  WordPress/src/main/java/org/wordpress/android/ui/stories/StoryTitleHeaderView.kt
  WordPress/src/main/java/org/wordpress/android/ui/stories/intro/StoriesIntroDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/util/config/manual/ManualFeatureConfigActivity.kt
  WordPress/src/main/java/org/wordpress/android/util/config/manual/ManualFeatureConfigFragment.kt
Labels: [Type] Enhancement

#14264 Remove Tenor feature configuration
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/util/config/ExampleRemoteFeature.kt
  WordPress/src/main/java/org/wordpress/android/util/config/TenorFeatureConfig.kt
  WordPress/src/test/java/org/wordpress/android/ui/photopicker/PhotoPickerViewModelTest.kt
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java
Labels: Tech debt, [Type] Enhancement

#14247 Fixes failed media upload tracking after rotation
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java
Labels: Media, [Type] Bug, gutenberg-mobile

#14265 Remove AnyFileUploadFeatureConfig.kt
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/util/config/AnyFileUploadFeatureConfig.kt
Labels: Tech debt, [Type] Enhancement

#14243 Issue/refactor reader post details fragment part i
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailUiStateBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostWebViewCachingFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderNavigationEvents.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/HtmlUtilsWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/ReaderPostDetailUiStateBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt
  config/detekt/baseline.xml
Labels: New Reader Android, [Type] Task

#14268 Add missing ID to the progress layout
  WordPress/src/main/res/layout/wpwebview_activity.xml
Labels: [Type] Crash

#14161 Refactor NotificationsDetailListFragment to kotlin
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailListFragment.kt
Labels: Notifications, [Type] Task

#14244 Issue/refactor reader post details fragment part ii
  WordPress/src/main/java/org/wordpress/android/datasets/wrappers/ReaderPostTableWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderConstants.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailUiStateBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderPostActionsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderRelatedPostsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderRelatedPostViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/usecases/ReaderFetchPostUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/usecases/ReaderGetPostUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSimplePostContainerView.kt
  WordPress/src/main/java/org/wordpress/android/util/WpUrlUtilsWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/ReaderPostDetailUiStateBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/usecases/ReaderFetchPostUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/usecases/ReaderGetPostUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt
  config/detekt/baseline.xml
Labels: New Reader Android, [Type] Task

#14271 Issue/refactor reader post details fragment
  WordPress/src/main/java/org/wordpress/android/datasets/wrappers/ReaderPostTableWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderConstants.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailUiStateBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostWebViewCachingFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderPostActionsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderRelatedPostsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderNavigationEvents.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/viewholders/ReaderRelatedPostViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/usecases/ReaderFetchPostUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/usecases/ReaderGetPostUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderSimplePostContainerView.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/HtmlUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/WpUrlUtilsWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/ReaderPostDetailUiStateBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/usecases/ReaderFetchPostUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/usecases/ReaderGetPostUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt
  config/detekt/baseline.xml
Labels: New Reader Android

#14242 Prepublishing bottomsheet categories not loading in story creator
  WordPress/src/main/java/org/wordpress/android/ui/posts/GetCategoriesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingCategoriesFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingCategoriesViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/prepublishing/PrepublishingCategoriesViewModelTest.kt
Labels: [Type] Task

#14226 Use view binding in accounts
  WordPress/src/main/java/org/wordpress/android/ui/accounts/HelpActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/PostSignupInterstitialActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginPrologueFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginProloguePageFragment.kt
  WordPress/src/main/res/layout-land/post_signup_interstitial_activity.xml
  WordPress/src/main/res/layout-sw600dp/post_signup_interstitial_activity.xml
  WordPress/src/main/res/layout/login_signup_screen.xml
  WordPress/src/main/res/layout/post_signup_interstitial_activity.xml
Labels: [Type] Enhancement

#14238 Feature/use view binding in pages
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageParentActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageParentFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PageParentSearchFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/pages/PagesFragment.kt
  WordPress/src/main/res/layout/pages_activity.xml
  WordPress/src/main/res/layout/pages_parent_activity.xml
Labels: [Type] Enhancement

#14151 View milestone notifications
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/models/Note.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/blocks/NoteBlock.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/blocks/NoteBlockClickableSpan.java
  WordPress/src/main/java/org/wordpress/android/util/FormattableContentUtils.kt
  WordPress/src/main/res/layout/note_block_basic.xml
  WordPress/src/main/res/layout/notifications_detail_activity.xml
  WordPress/src/main/res/raw/confetti.json
  build.gradle
Labels: Milestone Notifications, [Type] Task

#14257 Update related posts title + header style
  WordPress/src/main/res/values/reader_styles.xml
Labels: New Reader Android, [Status] Needs Design Review

#14269 Remove homepage picker feature config
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVM.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/segments/SegmentsScreenListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/segments/SiteCreationSegmentViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/segments/SiteCreationSegmentsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/segments/SiteCreationSegmentsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/segments/SiteCreationSegmentsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/usecases/FetchDomainsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/util/config/HomePagePickerFeatureConfig.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVMTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/domains/SiteCreationDomainsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/segments/SiteCreationSegmentsViewModelTest.kt
  config/detekt/baseline.xml
Labels: Tech debt, [Type] Enhancement

#14286 ExPlat: Add A/B experiment
  WordPress/src/main/java/org/wordpress/android/util/experiments/CreateMenuStoryFirstABExperiment.kt
  WordPress/src/main/java/org/wordpress/android/util/experiments/ExPlat.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModel.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModelTest.kt
Labels: ExPlat, [Type] Enhancement

#14275 Remove UL&S flag
  WordPress/build.gradle
  WordPress/src/androidTest/java/org/wordpress/android/e2e/flows/LoginFlow.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/flows/SignupFlow.java
  WordPress/src/androidTest/java/org/wordpress/android/support/BaseTest.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/UnifiedLoginTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginPrologueFragment.kt
  WordPress/src/main/res/layout-land/login_prologue_bottom_buttons_container.xml
  WordPress/src/main/res/layout-land/login_prologue_bottom_buttons_container_unified.xml
  WordPress/src/main/res/layout-sw600dp/login_prologue_bottom_buttons_container.xml
  WordPress/src/main/res/layout-sw600dp/login_prologue_bottom_buttons_container_default.xml
  WordPress/src/main/res/layout-sw600dp/login_prologue_bottom_buttons_container_unified.xml
  WordPress/src/main/res/layout/login_prologue_bottom_buttons_container.xml
  WordPress/src/main/res/layout/login_signup_screen.xml
  WordPress/src/main/res/values/strings.xml
Labels: Tech debt, [Type] Enhancement

#14272 Update eventbus version to v3.2.0
  WordPress/build.gradle
Labels: Tech debt

#14290 Remove Gutenberg mentions flag
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/util/config/GutenbergMentionsFeatureConfig.kt
Labels: Tech debt, [Type] Enhancement

#14317 Remove consolidated media picker flag and unused code
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/MediaPickerLauncher.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/util/WPMediaUtils.java
  WordPress/src/main/java/org/wordpress/android/util/config/ConsolidatedMediaPickerFeatureConfig.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Tech debt, [Type] Enhancement

#14332 [Tooling] Mute fastlane's CHANGELOG and update check
  .circleci/config.yml
Labels: Tooling

#14324 update proguard rule to not obfuscate MeFragment
  WordPress/proguard.cfg
Labels: /Me

#14333 Merge Release/17.0 into develop
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/metadata/release_notes.txt
  WordPress/metadata/release_notes_short.txt
  WordPress/proguard.cfg
  build.gradle
  fastlane/resources/values/strings.xml
Labels: Releases

#14280 Reader : Support for *.wordpress.com deep links with custom domain as primary
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderSubsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderActions.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderPostActions.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderPostActionsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/usecases/ReaderFetchPostUseCase.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/usecases/ReaderFetchPostUseCaseTest.kt
Labels: Reader, [Type] Task

#14200 Feature/manage translations
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
  tools/merge_strings_xml.py
Labels: Part of a WIP Feature, Tooling

#14320 Jetpack App Basics: Initial project configuration
  WordPress/build.gradle
  WordPress/src/jetpack/res/values/strings.xml
  WordPress/src/jetpackJalapeno/res/values/strings.xml
  WordPress/src/jetpackWasabi/res/values/strings.xml
Labels: Jetpack App

#14281 Increased the CursorWindowSize to 20MB in hopes of reducing crashes
  WordPress/src/debug/java/org/wordpress/android/WPWellSqlConfig.kt
Labels: [Type] Enhancement, [Type] Task

#14276 Remove unused UL&S code
  WordPress/src/androidTest/java/org/wordpress/android/e2e/flows/LoginFlow.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/flows/SignupFlow.java
  WordPress/src/main/java/org/wordpress/android/ui/WPBottomSheetDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginEpilogueFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginPrologueListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingBottomSheetFragment.kt
  WordPress/src/main/res/drawable/ic_placeholder_blavatar_grey_lighten_20_40dp.xml
  WordPress/src/main/res/layout/login_epilogue_screen.xml
  WordPress/src/main/res/layout/signup_epilogue.xml
  WordPress/src/main/res/values/colors.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/Login2FaFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginBaseFormFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginEmailPasswordFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginListener.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/LoginUsernamePasswordFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupBottomSheetDialogFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/SignupEmailFragment.java
  libs/login/WordPressLoginFlow/src/main/java/org/wordpress/android/login/di/LoginFragmentModule.java
  libs/login/WordPressLoginFlow/src/main/res/drawable-ldrtl-v18/ic_arrow_left_white_24dp.xml
  libs/login/WordPressLoginFlow/src/main/res/drawable/ic_arrow_left_white_24dp.xml
  libs/login/WordPressLoginFlow/src/main/res/drawable/ic_domains_grey_24dp.xml
  libs/login/WordPressLoginFlow/src/main/res/drawable/ic_gridicons_user_circle_100dp.xml
  libs/login/WordPressLoginFlow/src/main/res/drawable/ic_lock_grey_24dp.xml
  libs/login/WordPressLoginFlow/src/main/res/drawable/ic_user_circle_grey_24dp.xml
  libs/login/WordPressLoginFlow/src/main/res/drawable/ic_user_grey_24dp.xml
  libs/login/WordPressLoginFlow/src/main/res/drawable/login_email_alert.xml
  libs/login/WordPressLoginFlow/src/main/res/drawable/shape_oval_green.xml
  libs/login/WordPressLoginFlow/src/main/res/drawable/shape_oval_red.xml
  libs/login/WordPressLoginFlow/src/main/res/drawable/shape_oval_translucent.xml
  libs/login/WordPressLoginFlow/src/main/res/layout-land/signup_bottom_sheet_dialog.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_email_screen_old.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/login_form_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/signup_bottom_sheet_dialog.xml
  libs/login/WordPressLoginFlow/src/main/res/layout/signup_email_screen.xml
  libs/login/WordPressLoginFlow/src/main/res/values/colors.xml
  libs/login/WordPressLoginFlow/src/main/res/values/dimens.xml
  libs/login/WordPressLoginFlow/src/main/res/values/strings.xml
  libs/login/WordPressLoginFlow/src/main/res/values/styles.xml
  libs/login/WordPressLoginFlow/src/main/res/values/themes.xml
Labels: Tech debt, [Type] Enhancement

#14325 Remove WP Stories feature config and the unused code
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListMainViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/config/WPStoriesFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModel.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/posts/PostListCreateMenuViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostListMainViewModelCopyPostTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostListMainViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/posts/PostListCreateMenuViewModelTest.kt
Labels: Tech debt, [Type] Enhancement

#14338 Stories publishing: use SingleLiveEvent for button clicks to show the prepublishing bottom sheet
  WordPress/src/main/java/org/wordpress/android/ui/stories/StoryComposerViewModel.kt
Labels: WP Stories

#14337 Update lanes taking into account the new build process
  fastlane/Fastfile
Labels: Part of a WIP Feature

#14344 Issue/14306 jetpack app disable widgets and shortcuts
  WordPress/src/jetpack/res/values/strings.xml
  WordPress/src/jetpack/res/xml/shortcuts.xml
  WordPress/src/jetpackJalapeno/res/xml/shortcuts.xml
  WordPress/src/jetpackWasabi/res/xml/shortcuts.xml
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/res/values/strings.xml
Labels: Jetpack App, [Type] Task

#14345 Check if Activity is destroyed before attempting to use context
  WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt
Labels: Media, Media Picker Consolidation

#14346 Merge release/17.0 -> develop after rc-2
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-bg/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-cy/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-eu/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-hi/strings.xml
  WordPress/src/main/res/values-hr/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-is/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-kmr/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-ms/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sr/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-th/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
Labels: Releases

#14334 Remove switch to classic from gutenberg
  WordPress/src/androidTest/java/org/wordpress/android/e2e/BlockEditorTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/BlockEditorPage.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/res/menu/edit_post.xml
  WordPress/src/main/res/values/strings.xml
Labels: Gutenberg, [Status] Not Ready for Merge

#14343 Do not track marking post as seen when opening it.
  WordPress/src/main/java/org/wordpress/android/ui/reader/usecases/ReaderSeenStatusToggleUseCase.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/usecases/ReaderPostSeenStatusToggleUseCaseTest.kt
Labels: Analytics, Reader, [Status] Needs Code Review, [Type] Task

#14349 Make the fragments pre-loaded by the view pager store the already rescued restoredNoteId
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailListFragment.kt
Labels: Notifications, [Type] Bug

#14358 Merge Release/17.0 release notes into develop
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: Releases

#14339 Use view binding in stats widgets and the insights
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/management/InsightsManagementActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/management/InsightsManagementFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ActivityViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BlockListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/alltime/StatsAllTimeWidgetConfigureActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetConfigureFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetSiteSelectionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetSiteViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/minified/StatsMinifiedWidgetConfigureActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/minified/StatsMinifiedWidgetConfigureFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/StatsTodayWidgetConfigureActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/StatsViewsWidgetConfigureActivity.kt
  WordPress/src/main/res/layout/stats_all_time_widget_configure_activity.xml
  WordPress/src/main/res/layout/stats_minified_widget_configure_activity.xml
  WordPress/src/main/res/layout/stats_today_widget_configure_activity.xml
  WordPress/src/main/res/layout/stats_views_widget_configure_activity.xml
Labels: Stats, Tech debt

#14340 Use view binding in stats detail, view all and list fragments
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/DetailListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/StatsDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/DateSelectorViewUtils.kt
  WordPress/src/main/res/layout/stats_detail_fragment.xml
Labels: Stats, Tech debt, [Type] Enhancement

#14341 Use view binding in Manual feature configuration
  WordPress/src/main/java/org/wordpress/android/util/config/manual/ManualFeatureConfigActivity.kt
  WordPress/src/main/java/org/wordpress/android/util/config/manual/ManualFeatureConfigFragment.kt
Labels: Tech debt, [Type] Enhancement

#14342 Use view binding in plans
  WordPress/src/main/java/org/wordpress/android/ui/plans/PlansActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/plans/PlansListFragment.kt
Labels: Tech debt, [Type] Enhancement

#14354 View bindings in homepage settings
  WordPress/src/main/java/org/wordpress/android/ui/prefs/homepage/HomepageSettingsDialog.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/interests/ReaderInterestsFragment.kt
Labels: Tech debt, [Type] Enhancement

#14351 Stories: crash fix - allow null value for event.frameId, simply don't process it
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/StoriesEventListener.kt
Labels: WP Stories, [Type] Crash

#14363 Move fastlane env file
  fastlane/env.example
  fastlane/env/user.env-example
Labels: Tooling

#14366 Lint: Changed severity of UseAppTint from warning to ignore
  WordPress/lint.xml
Labels: Lint

#14367 Remove libs/gutenberg-mobile submodule
  .gitmodules
Labels: Tooling

#14355 Use view binding in the WPEditTextWithChipsOutlined.kt
  WordPress/src/main/java/org/wordpress/android/ui/people/WPEditTextWithChipsOutlined.kt
Labels: Tech debt, [Type] Enhancement

#14270 Removes Preview mode from Gutenberg editor
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  build.gradle
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragmentAbstract.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergContainerFragment.java
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java
Labels: Tech debt

#14370 Update color palette to 2.5.0
  WordPress/src/main/res/values/colors.xml
Labels: [Type] Task
