Repository wordpress-mobile/WordPress-Android, pull requests merged in 2022-01, with the labels that each got.

#15781 Merge beta 18.9-rc-2 + editorialized release notes into `develop`
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sr/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  WordPress/src/main/res/xml/app_settings.xml
  version.properties
Labels: Releases

#15744 Added Several `Contact Support` tests.
  WordPress/src/androidTest/java/org/wordpress/android/e2e/ContactUsTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/flows/LoginFlow.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/ContactSupportScreen.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/HelpAndSupportScreen.java
  WordPress/src/androidTest/java/org/wordpress/android/support/WPSupportUtils.java
Labels: UI Tests

#15566 [Gutenberg] Bring in the React Native 0.66 upgrade of gutenberg-mobile
  build.gradle
Labels: gutenberg-mobile

#15784 Fix syntax error in .po file
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/metadata/PlayStoreStrings.po
Labels: Releases

#15791 Fix gutenberg mobile workflow
  .github/workflows/automated-version-update-pr.yml
Labels: gutenberg-mobile

#15788 My Site Dashboard - Phase 2 - Update Error Card & Stale Message Style & Copy
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItemDecoration.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
Labels: My Site Dashboard

#15792 Update the format sytext in github workflow
  .github/workflows/automated-version-update-pr.yml
Labels: gutenberg-mobile

#15796 [Gutenberg] Integrate alpha version `v1.69.0-alpha2`
  build.gradle
  libs/editor/WordPressEditor/build.gradle
Labels: gutenberg-mobile

#15794 My Site Dashboard - Phase 2 - Fix duplicate Error Snackbar
  WordPress/src/main/java/org/wordpress/android/ui/mysite/CurrentAvatarSource.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteSourceManager.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/ScanAndBackupSource.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsSource.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSource.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartCardSource.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/dynamiccards/DynamicCardsSource.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/CurrentAvatarSourceTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteSourceManagerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/ScanAndBackupSourceTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsSourceTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/domainregistration/DomainRegistrationSourceTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/dynamiccards/DynamicCardsSourceTest.kt
Labels: My Site Dashboard

#15799 My Site Dashboard - Phase2: Fix indefinite spinner on app close then reopen
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SelectedSiteSource.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/SelectedSiteSourceTest.kt
Labels: [Type] Bug, My Site Dashboard

#15725 Update release-toolkit to 2.3.0
  Gemfile.lock
  fastlane/Fastfile
Labels: Tooling

#15805 Integrate gutenberg-mobile release 1.69.0
  RELEASE-NOTES.txt
  build.gradle
Labels: gutenberg-mobile

#15810 My Site Dashboard [Phase 2]: Add Release Notes Entry
  RELEASE-NOTES.txt
Labels: My Site Dashboard

#15809 Update about automattic library to latest v0.0.4
  WordPress/src/main/java/org/wordpress/android/ui/about/UnifiedAboutViewModel.kt
  WordPress/src/main/res/values/strings.xml
  build.gradle
Labels: [Type] Task, Unified About

#15813 My Site Dashboard: Phase 2: Metrics - Track Post Card Item Tapped
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsTracker.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsTrackerTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: My Site Dashboard

#15812 [Tooling] Fix default branch in Fastfile back to develop
  fastlane/Fastfile
Labels: Tooling

#15815 Merge release/19.0 after code freeze
  RELEASE-NOTES.txt
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/release_notes.txt
  WordPress/src/main/res/values/strings.xml
  build.gradle
  fastlane/resources/values/strings.xml
  version.properties
Labels: Releases

#15817 My Site Dashboard - Stats Card - Add Feature Flag
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/util/config/MySiteDashboardStatsCardFeatureConfig.kt
Labels: My Site Dashboard

#15818 Put back Share with friends under Me
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
Labels: [Type] Task, Unified About

#15821 Merge release/19.0 into develop - 19.0-rc-2 + Release Notes
  RELEASE-NOTES.txt
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/jetpack_metadata/release_notes_short.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  WordPress/metadata/release_notes_short.txt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-az/strings.xml
  WordPress/src/main/res/values-bg/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-cy/strings.xml
  WordPress/src/main/res/values-da/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-eu/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gd/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-hi/strings.xml
  WordPress/src/main/res/values-hr/strings.xml
  WordPress/src/main/res/values-hu/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-is/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-kmr/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-mk/strings.xml
  WordPress/src/main/res/values-ms/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sr/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-th/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-uz/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  version.properties
Labels: Releases

#15674 [Gutenberg] Hide help button from UBE
  build.gradle
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/WPGutenbergWebViewActivity.java
Labels: Gutenberg, gutenberg-mobile

#15652 Update default branch to trunk
  .circleci/config.yml
  docs/coding-style.md
  docs/pull-request-guidelines.md
  fastlane/Fastfile
  fastlane/Pluginfile
  gradle.properties-example
  libs/mocks/README.md
Labels: Tooling

#15820 Update fastlane release toolkit default branch to trunk
  fastlane/Fastfile
Labels: Tooling, [Status] Not Ready for Merge

#15782 Add reader tests
  .circleci/config.yml
  WordPress/src/androidTest/java/org/wordpress/android/e2e/ReaderTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/ReaderPage.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/ReaderViewPage.java
  WordPress/src/androidTest/java/org/wordpress/android/support/WPSupportUtils.java
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/posts/rest_v11_sites_posts_likes_mine_delete.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/posts/rest_v11_sites_posts_likes_new.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/posts/rest_v11_sites_posts_replies.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/posts/rest_v12_sites_posts_likes.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/rest_v12_read_following.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/rest_v12_read_sites_post_125073.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/rest_v12_read_sites_post_439.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/rest_v12_read_sites_post_441.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/rest_v12_read_sites_post_related_125073.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/rest_v12_read_sites_post_related_439.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/rest_v12_read_sites_post_related_441.json
Labels: UI Tests

#15825 My Site Dashboard - Post Card - Adjust TextView Width
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/posts/PostItemViewHolder.kt
Labels: My Site Dashboard

#15823 Integrate gutenberg-mobile release 1.69.1
  build.gradle
Labels: gutenberg-mobile

#15830 Merge release/19.0 into trunk (19.0-rc-3)
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  version.properties
Labels: Releases

#15619 Initial Port of Jetpack Tiled Gallery Block
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/util/SiteUtils.java
  build.gradle
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergPropsBuilder.kt
Labels: Posting/Editing, Media, gutenberg-mobile

#15831 Fix unable to add image to story post
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/AddLocalMediaToPostUseCase.kt
Labels: [Type] Bug

#15832 Update stories version for error saving image fix
  build.gradle
Labels: [Type] Bug

#15838 Merge release/19.0 (19.0-rc-4)
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/AddLocalMediaToPostUseCase.kt
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  build.gradle
  version.properties
Labels: Releases

#15839 [Tooling] Extract translation checks in dedicated lane
  fastlane/Fastfile
Labels: Tooling

#15827 Temporarily disable option to connect a Facebook account to Publicize
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeListActivity.java
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Bug, Sharing, [Status] Needs Copy Review, [Status] Not Ready for Merge

#15836 Integrate gutenberg-mobile release 1.70.0
  RELEASE-NOTES.txt
  build.gradle
Labels: gutenberg-mobile

#15837 Replace jcenter with jcenter-mirror
  WordPress/build.gradle
  build.gradle
  libs/analytics/WordPressAnalytics/build.gradle
  libs/editor/WordPressEditor/build.gradle
  libs/editor/build.gradle
  libs/editor/example/build.gradle
  libs/networking/WordPressNetworking/build.gradle
Labels: Tooling

#15842 Update icons set
  RELEASE-NOTES.txt
  WordPress/src/main/res/drawable/app_icon_background.xml
  WordPress/src/main/res/drawable/app_icon_foreground.xml
  WordPress/src/main/res/mipmap-hdpi/app_icon.png
  WordPress/src/main/res/mipmap-xhdpi/app_icon.png
  WordPress/src/main/res/mipmap-xxhdpi/app_icon.png
  WordPress/src/main/res/mipmap-xxxhdpi/app_icon.png
Labels: [Pri] High, [Type] Task

#15627 A/B test Land In the Editor
  WordPress/src/main/java/org/wordpress/android/modules/ExperimentModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/RequestCodes.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/mysite/HomePageDataLoader.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SiteNavigationAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/EditorActionsProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/prepublishing/home/usecases/GetButtonUiStateUseCase.kt
  WordPress/src/main/java/org/wordpress/android/util/experiments/LandOnTheEditorABExperiment.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/editor/EditorActionsProviderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/prepublishing/home/usecases/GetButtonUiStateUseCaseTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Site Creation, ExPlat

#15841 Added `allDayStatsLoad` UI test.
  WordPress/src/androidTest/java/org/wordpress/android/e2e/StatsTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/MySitesPage.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/ReaderPage.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/StatsPage.java
  WordPress/src/androidTest/java/org/wordpress/android/support/WPSupportUtils.java
  WordPress/src/androidTest/java/org/wordpress/android/util/StatsDataClasses.kt
  WordPress/src/androidTest/java/org/wordpress/android/util/StatsMocksReader.kt
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/stats/stats_clicks-day.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/stats/stats_country-views-day.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/stats/stats_file-downloads-day.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/stats/stats_referrers-day.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/stats/stats_referrers.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/stats/stats_search-terms_day.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/stats/stats_top-authors-day.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/stats/stats_top-authors.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/stats/stats_top-posts-day.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/stats/stats_top-posts.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/stats/stats_video-plays-day.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/stats/stats_video-plays.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/stats/stats_visits_unit_day_15.json
Labels: UI Tests

#15845 Update Buildkite docker image tag to v1.1.0
  .buildkite/pipeline.yml
Labels: Tooling

#15854 Merge release/19.1 into trunk (19.1-rc-1 code freeze)
  RELEASE-NOTES.txt
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/jetpack_metadata/release_notes_short.txt
  WordPress/metadata/release_notes.txt
  WordPress/metadata/release_notes_short.txt
  WordPress/src/main/res/values/strings.xml
  build.gradle
  fastlane/resources/values/strings.xml
  version.properties
Labels: Releases

#15856 Issue/15397 comment list update
  WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentsEditViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/comments/viewmodels/UnifiedCommentsEditViewModelTest.kt
Labels: [Type] Bug, [Status] Needs Code Review, Comments Unification

#15852 MSD: Remove "No Content" text for an empty excerpt in a draft post card
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/posts/PostCardBuilder.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/dashboard/posts/PostCardBuilderTest.kt
Labels: My Site Dashboard

#15863 Merge release/19.1 — Release Notes
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/jetpack_metadata/release_notes_short.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  WordPress/metadata/release_notes_short.txt
Labels: Releases

#15866 Adds org.wordpress.wellsql to s3 repositories
  WordPress/build.gradle
Labels: Tooling

#15864 Editor: Handles media from share action
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: [Type] Bug, Posting/Editing, Media

#15867 Upgrade wordPressUtilsVersion to 2.3.0
  build.gradle
Labels: Tooling

#15874 Fix snackbar no suitable parent found crash on the Reader tab
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
Labels: Quick Start

#15872 Filter media list to call processMediaUri just once
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/AddLocalMediaToPostUseCase.kt
Labels: [Type] Bug
