Repository wordpress-mobile/WordPress-Android, pull requests merged in 2022-12, with the labels that each got.

#17586 Integrate gutenberg-mobile release 1.85.1
  build.gradle
Labels: gutenberg-mobile

#17588 [Jetpack Content Migration Flow] Logs the user out on failure
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModelTest.kt
Labels: [Type] Bug, Jetpack Focus

#17582 Help Screen: Fetches account data when those are not available
  WordPress/src/main/java/org/wordpress/android/ui/accounts/HelpActivity.kt
Labels: [Type] Bug, Jetpack Focus

#17584 [Tooling] Report Firebase Test Failures as Buildkite Annotations (take 2)
  Gemfile
  Gemfile.lock
  fastlane/lanes/test.rb
Labels: Tooling

#17600 Merge 21.3 beta 3 into trunk
  WordPress/src/jetpack/AndroidManifest.xml
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/ContentMigrationAnalyticsTracker.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationResult.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestrator.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/HelpActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/state/WelcomeStep.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/JetpackAppMigrationFlowUtils.kt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/utils/JetpackAppMigrationFlowUtilsTest.kt
  WordPress/src/wordpress/AndroidManifest.xml
  build.gradle
  fastlane/resources/values/strings.xml
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
  version.properties
Labels: Releases

#17611 Merge 21.3 release notes into trunk
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: Releases

#17605 [Dependency Updates] Remove Unused Dependencies for Libs Modules
  WordPress/build.gradle
  build.gradle
  libs/editor/build.gradle
  libs/image-editor/build.gradle
  libs/mocks/build.gradle
Labels: Tech Debt, dependency update

#17607 Fix INSTALL_FAILED_DUPLICATE_PERMISSION error
  WordPress/src/jetpack/AndroidManifest.xml
  WordPress/src/wordpress/AndroidManifest.xml
Labels: [Type] Bug, Notifications

#17604 Blocks reader user locally
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/datasets/BlockedAuthorTable.java
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderDatabase.java
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActionsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderCardUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostCardActionsHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/repository/usecases/BlockUserUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderPostCardActionsHandlerTest.kt
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Reader, [Type] Task

#17579 [Dependency Updates] Remove WireMock Mock Version
  build.gradle
  libs/mocks/build.gradle
Labels: Tech Debt, dependency update

#17599 Add block site option to followed posts menu
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderBlockedBlogTable.java
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderDatabase.java
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilder.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilderTest.kt
Labels: Reader, [Type] Task, Jetpack Mobile

#17621 Update mockitoVersion to 4.9.0
  build.gradle
Labels: dependency update

#17622 Update mockitoKotlinVersion to 4.1.0
  build.gradle
Labels: dependency update

#17618 Update assertjVersion to 3.23.1
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/usecases/FetchScanStateUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/dynamiccards/DynamicCardsSourceTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/uploads/UploadActionUseCaseTest.kt
  build.gradle
Labels: dependency update

#17629 Disable PREVENT_DUPLICATE_NOTIFS_REMOTE_FIELD
  WordPress/build.gradle
Labels: [Type] Task

#17632 [Jetpack Migration Flow] Update unit tests
  WordPress/src/test/java/org/wordpress/android/localcontentmigration/LocalMigrationResultTest.kt
  WordPress/src/test/java/org/wordpress/android/localcontentmigration/MigrationEmailHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/localcontentmigration/SharedLoginHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/reader/savedposts/resolver/ReaderSavedPostsHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestratorTest.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolverTest.kt
  WordPress/src/test/java/org/wordpress/android/userflags/resolver/UserFlagsHelperTest.kt
Labels: [Type] Enhancement, Jetpack Focus

#17637 Prevent logout when going back from delete WP app screen
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationFragment.kt
Labels: [Type] Bug, Jetpack Focus

#17066 [Gutenberg] - React Native 0.69.4 Upgrade
  WordPress/build.gradle
  build.gradle
  libs/editor/build.gradle
Labels: gutenberg-mobile

#17627 Implement edit and delete category
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/DeleteCategoryUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditCategoryUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/GetCategoriesUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/detail/CategoryDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/detail/CategoryDetailUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/detail/CategoryDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/list/CategoriesListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/list/SiteSettingsCategoriesAdapter.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/prefs/categories/detail/CategoryDetailViewModelTest.kt
Labels: Tag/Category Management

#17606 Add report user option in Reader post menu
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderCardUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderNavigationEvents.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostCardActionsHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/tracker/ReaderTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/main/res/drawable/ic_flag_white_24dp.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderPostCardActionsHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilderTest.kt
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Reader, [Type] Task, [Status] Not Ready for Merge

#17639 Integrate gutenberg-mobile release 1.86.0
  RELEASE-NOTES.txt
  build.gradle
Labels: gutenberg-mobile

#17641 Fix RTL tab swipe direction in notifications
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragmentPage.kt
  WordPress/src/main/res/layout/notifications_list_fragment.xml
Labels: Notifications

#17648 [Jetpack Migration Flow] Migrate app theme, initial screen and recently picked sites
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/UserFlagsProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java
  WordPress/src/main/java/org/wordpress/android/util/LocaleManagerWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModelTest.kt
Labels: [Type] Task, Jetpack Focus

#17642 [Dependency Updates] Update `androidxArchCoreVersion` to 2.1.0
  WordPress/build.gradle
  build.gradle
Labels: Tech Debt, dependency update

#17658 Add autoverify to deep link intent receiver
  WordPress/src/main/AndroidManifest.xml
Labels: [Type] Task, Jetpack Focus

#17652 Improvements on Category managment feature
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/detail/CategoryDetailActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/detail/CategoryDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/detail/CategoryDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/list/CategoriesListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/list/CategoriesListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/list/CategoriesListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/config/ManageCategoriesFeatureConfig.kt
Labels: [Type] Enhancement, Tag/Category Management

#17649 Migrate services to hilt
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/push/GCMMessageService.java
  WordPress/src/main/java/org/wordpress/android/push/GCMRegistrationIntentService.java
  WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java
  WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaDeleteService.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/services/discover/ReaderDiscoverJobService.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/services/discover/ReaderDiscoverLogic.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/services/discover/ReaderDiscoverService.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/services/SiteCreationService.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java
Labels: [Type] Enhancement, Tech Debt

#17651 Ports Google Play User Generated Content Policy Compliance to 21.3
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/datasets/BlockedAuthorTable.java
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderBlockedBlogTable.java
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderDatabase.java
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActionsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderCardUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderNavigationEvents.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostCardActionsHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/repository/usecases/BlockUserUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/tracker/ReaderTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/main/res/drawable/ic_flag_white_24dp.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderPostCardActionsHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilderTest.kt
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Reader, [Type] Task, Jetpack App

#17663 Update squareupMockWebServerVersion to 4.9.3
  WordPress/build.gradle
  build.gradle
Labels: dependency update

#17524 Reader: Fix labels translation when language is changed via app settings
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/DateTimeUtilsWrapper.kt
Labels: Reader, i18n

#17668 Add Jetpack branding to Scan screens starting from Phase One
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/ScanActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/ScanFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/ScanViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/history/ScanHistoryActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/history/ScanHistoryFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/history/ScanHistoryListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/history/ScanHistoryListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/history/ScanHistoryViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalBrandingUtil.kt
  WordPress/src/main/java/org/wordpress/android/util/JetpackBrandingUtils.kt
  WordPress/src/main/res/layout/scan_activity.xml
  WordPress/src/main/res/layout/scan_history_fragment.xml
  WordPress/src/test/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalBrandingUtilTest.kt
Labels: [Type] Task, Jetpack Focus

#17662 Hide Scan Login Code when 2FA is active.
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/util/config/QRCodeAuthFlowFeatureConfig.kt
  build.gradle
Labels: [Type] Enhancement, Jetpack App, QRCode Auth

#17671 Donot merge - only to trigger CI on PR https://github.com/wordpress-mobile/WordPress-Android/pull/16383
  WordPress/src/main/java/org/wordpress/android/ui/prefs/DetailListPreference.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/AccountSettingsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/AccountSettingsViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/prefs/accountsettings/AccountSettingsViewModelTest.kt
Labels: [Type] Bug

#17669 Removes line break to fix text wrapping issue
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Bug, Jetpack Focus

#17677 Always Land on My Site after migration flow
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/UserFlagsProviderHelper.kt
Labels: [Type] Task, Jetpack Focus

#17675 [Blogging Prompts] Prompts list feature flag
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItemBuilderParams.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/bloggingprompts/BloggingPromptCardBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/bloggingprompts/BloggingPromptCardViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/util/config/BloggingPromptsListFeatureConfig.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/CardsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/dashboard/bloggingprompts/BloggingPromptCardBuilderTest.kt
Labels: Blogging Prompts Enhancement

#17678 Merge/21.3 rc 6 into trunk
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/src/jetpack/AndroidManifest.xml
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/bloggingreminders/resolver/BloggingRemindersResolver.kt
  WordPress/src/main/java/org/wordpress/android/datasets/BlockedAuthorTable.java
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderBlockedBlogTable.java
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderDatabase.java
  WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentResolver.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/UserFlagsProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActionsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderCardUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderNavigationEvents.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostCardActionsHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/repository/usecases/BlockUserUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/tracker/ReaderTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java
  WordPress/src/main/java/org/wordpress/android/util/LocaleManagerWrapper.kt
  WordPress/src/main/res/drawable/ic_flag_white_24dp.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/localcontentmigration/LocalMigrationResultTest.kt
  WordPress/src/test/java/org/wordpress/android/localcontentmigration/MigrationEmailHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/localcontentmigration/SharedLoginHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/reader/savedposts/resolver/ReaderSavedPostsHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestratorTest.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolverTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderPostCardActionsHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderPostMoreButtonUiStateBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/userflags/resolver/UserFlagsHelperTest.kt
  WordPress/src/wordpress/AndroidManifest.xml
  fastlane/resources/values/strings.xml
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
  version.properties
Labels: Releases

#17674 Decrease bottom empty space on migration screens
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/components/ButtonsColumn.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/state/WelcomeStep.kt
Labels: [Type] Task, Jetpack Focus

#17683 Merge final 21.3 changes into trunk
  version.properties
Labels: Releases

#17667 Implement Remote field config feature
  WordPress/src/main/java/org/wordpress/android/ui/debug/DebugSettingsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/DebugSettingsItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/DebugSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/config/AppConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/FeatureFlagConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/JetpackFeatureRemovalRemoteFields.kt
  WordPress/src/main/java/org/wordpress/android/util/config/RemoteConfigField.kt
  WordPress/src/main/java/org/wordpress/android/util/config/RemoteFieldConfigRepository.kt
  WordPress/src/main/res/layout/debug_settings_remote_field.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/debug/DebugSettingsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/util/config/AppConfigParametrizedTest.kt
  WordPress/src/test/java/org/wordpress/android/util/config/AppConfigTest.kt
  build.gradle
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
  libs/annotations/src/main/java/org/wordpress/android/annotation/RemoteFieldDefaultGenerater.kt
  libs/mocks/src/main/assets/mocks/mappings/wpcom/mobile/remote-configs.json
  libs/processors/src/main/java/org/wordpress/android/processor/RemoteConfigProcessor.kt
  libs/processors/src/main/java/org/wordpress/android/processor/RemoteFeatureConfigCheckBuilder.kt
  libs/processors/src/main/java/org/wordpress/android/processor/RemoteFeatureConfigDefaultsBuilder.kt
  libs/processors/src/main/java/org/wordpress/android/processor/RemoteFieldConfigDefaultsBuilder.kt
  libs/processors/src/test/kotlin/org/wordpress/android/processor/RemoteFeatureConfigDefaultsBuilderTest.kt
Labels: [Type] Task

#17682 [Blogging Prompts] Create Prompts List Activity placeholder and navigation
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/promptslist/BloggingPromptsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/promptslist/BloggingPromptsListScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItemBuilderParams.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/bloggingprompts/BloggingPromptCardBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/bloggingprompts/BloggingPromptCardViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabFragment.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/CardsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/dashboard/bloggingprompts/BloggingPromptCardBuilderTest.kt
Labels: Blogging Prompts Enhancement

#17686 [Blogging Prompts] Prompts List analytics tracking
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/promptslist/BloggingPromptsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/promptslist/BloggingPromptsListAnalyticsTracker.kt
  WordPress/src/test/java/org/wordpress/android/ui/bloggingprompts/promptslist/BloggingPromptsListAnalyticsTrackerTest.kt
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Analytics, Blogging Prompts Enhancement

#17687 Fix Jetpack variant test compilation (missing annotation)
  WordPress/src/testJetpack/java/org.wordpress.android/ui.accounts.login/LoginPrologueViewModelTest.kt
Labels: Testing

#17643 [Dependency Updates] Update `androidxLifecycleVersion` to 2.5.1
  WordPress/build.gradle
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ConversationNotificationsViewModelTest.kt
  build.gradle
  libs/editor/build.gradle
  libs/image-editor/build.gradle
Labels: Tech Debt, dependency update

#17692 Jetpack Focus: Add Jetpack feature card show rule
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/jetpackfeature/JetpackFeatureCardHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/jetpackfeature/JetpackFeatureCardHelperTest.kt
Labels: [Type] Task, Jetpack Focus

#17691 [Dependency Updates] Update `androidxCoreVersion` to 1.8.0
  WordPress/src/main/java/org/wordpress/android/util/ContentDescriptionListAnnouncer.kt
  WordPress/src/main/java/org/wordpress/android/util/extensions/ContextExtensions.kt
  build.gradle
  libs/editor/build.gradle
Labels: Tech Debt, dependency update

#17700 Integrate gutenberg-mobile release 1.86.1
  build.gradle
Labels: gutenberg-mobile

#17703 Fix LazyColumn crash in Jetpack Welcome Screen (duplicate keys)
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/state/WelcomeStep.kt
  WordPress/src/test/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModelTest.kt
Labels: Jetpack Focus

#17706 Finish the activity after logging out
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
Labels: [Type] Bug, /Me

#17587 [Gutenberg] Disable editor Jetpack-powered features based on Jetpack Features Removal phases
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalPhaseHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  build.gradle
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergPropsBuilder.kt
Labels: gutenberg-mobile
