Repository wordpress-mobile/WordPress-Android, pull requests merged in 2022-11, with the labels that each got.

#17393 Detekt - Resolve/Suppress All Baseline Warnings - Long methods warnings_ MediaPickerViewModel
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerViewModel.kt
  config/detekt/baseline.xml
Labels: Tooling, Tech debt

#17385 Refactor Frosted Glass Component to be Reusable
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/LoginPrologueRevampedFragment.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/LoopingTextWithBackground.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/ColumnWithFrostedGlassBackground.kt
Labels: [Type] Task, Login

#17410 Merge release notes for 21.1
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: Releases

#17408 [UI Tests] Ignored (disabled) `e2ePublishFullPost` UI test.
  WordPress/src/androidTest/java/org/wordpress/android/e2e/BlockEditorTests.java
Labels: UI Tests

#17411 [Jetpack App] Fix Login Screens Navbar Appear Under System Topbar
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/LoginPrologueRevampedFragment.kt
Labels: Login, Jetpack App

#17390 Increase reader menu line height for long texts
  WordPress/src/main/res/layout/reader_popup_menu_item.xml
Labels: [Type] Bug, Reader, i18n

#17414 Merge release/21.1 after `21.1-rc-2` beta
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/LoginPrologueRevampedFragment.kt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  version.properties
Labels: Releases

#17386 [Jetpack Content Migration Flow] Add Jetpack Migration feature flag
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/util/config/JetpackMigrationFlowFeatureConfig.kt
Labels: [Type] Task, Jetpack Focus

#17387 [Jetpack Content Migration Flow] Add blank Welcome Screen (1)
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolver.kt
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/LoadingState.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/ScreenIcon.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/WelcomeStep.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/JetpackAppMigrationFlowUtils.kt
  WordPress/src/main/res/drawable/ic_wordpress_jetpack_logo.xml
  WordPress/src/main/res/layout/activity_jetpack_migration.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolverTest.kt
Labels: [Type] Task, Jetpack Focus

#17388 [Jetpack Content Migration Flow] Add static UI to Welcome Screen (2)
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/compose/unit/FontSize.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/Message.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/PrimaryButton.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/SecondaryButton.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/Subtitle.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/Title.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/UserAvatarImage.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/WelcomeStep.kt
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Task, Jetpack Focus

#17389 [Jetpack Content Migration Flow] Add site list to Welcome Screen (3)
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/ColumnWithFrostedGlassBackground.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/modifiers/Modifiers.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/Message.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/PrimaryButton.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/ScreenIcon.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/SecondaryButton.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/SiteList.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/Subtitle.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/Title.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/UserAvatarImage.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/components/WelcomeStep.kt
  WordPress/src/main/java/org/wordpress/android/util/SiteUtilsWrapper.kt
  WordPress/src/main/res/drawable/bg_rectangle_placeholder_globe_margin_8dp.xml
  WordPress/src/main/res/values-night/colors.xml
  WordPress/src/main/res/values/colors.xml
  WordPress/src/main/res/values/colors_translucent.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Task, Jetpack Focus

#17396 [Tooling] [Screenshots] Update API level of emulators used for screenshots
  fastlane/lanes/screenshots.rb
Labels: Tooling

#17398 [Jetpack Content Migration Flow] Local migration content provider
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalEligibilityStatusProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentProvider.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentResolver.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalPostProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalSiteProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/TrustedQueryContentProvider.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolver.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/JetpackAppMigrationFlowUtils.kt
  WordPress/src/test/java/org/wordpress/android/localcontentmigration/LocalContentEntityTest.kt
  WordPress/src/test/java/org/wordpress/android/localcontentmigration/LocalPostProviderHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolverTest.kt
  WordPress/src/wordpress/AndroidManifest.xml
Labels: [Status] Not Ready for Merge, Jetpack Focus

#17420 Flag for preventing duplicate notifications
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/util/config/PreventDuplicateNotifsFeatureConfig.kt
Labels: Jetpack Focus

#17391 Self hosted shared login
  WordPress/src/main/java/org/wordpress/android/resolver/DbWrapper.kt
  WordPress/src/main/java/org/wordpress/android/resolver/ResolverUtility.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/SharedLoginAnalyticsTracker.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/SharedLoginData.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/provider/SharedLoginProvider.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolver.kt
  WordPress/src/main/java/org/wordpress/android/userflags/provider/UserFlagsProvider.kt
  WordPress/src/test/java/org/wordpress/android/resolver/ResolverUtilityTest.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/SharedLoginAnalyticsTrackerTest.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolverTest.kt
Labels: [Type] Enhancement, Shared login

#17422 [Blogging Reminders Sync] Including self hosted in reminders
  WordPress/src/main/java/org/wordpress/android/bloggingreminders/provider/BloggingRemindersProvider.kt
  WordPress/src/main/java/org/wordpress/android/bloggingreminders/resolver/BloggingRemindersResolver.kt
  WordPress/src/test/java/org/wordpress/android/bloggingreminders/resolver/BloggingRemindersResolverTest.kt
Labels: [Type] Task, Blogging Reminders

#17409 Detekt - Resolve/Suppress All Baseline Warnings - Long methods warnings_ PhotoPickerFragment
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerFragment.kt
Labels: Tooling, Tech debt

#17415 [Do Not Merge] - CI Trigger for #17409
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerFragment.kt
Labels: [Status] Not Ready for Merge

#17399 [Jetpack Content Migration Flow] Refactor login resolver as orchestrator
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalAccessTokenProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentProvider.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentResolver.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalSiteProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/sharedlogin/provider/SharedLoginProvider.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestrator.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/test/java/org/wordpress/android/localcontentmigration/LocalAccessTokenProviderHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolverTest.kt
  WordPress/src/wordpress/AndroidManifest.xml
Labels: Jetpack Focus

#17439 Fix stats widget not loading stats activity correctly
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/utils/WidgetUtils.kt
Labels: Stats, Stats Widgets

#17436 Detekt - Resolve/Suppress All Baseline Warnings - Long methods warnings_ PublishSettingsFragment & PrepublishingHomeViewModel
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingHomeViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PublishSettingsFragment.kt
  config/detekt/baseline.xml
Labels: Tooling, Tech debt

#17443 [Do Not Merge] - CI Trigger for #17436
  WordPress/src/main/java/org/wordpress/android/ui/posts/PrepublishingHomeViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PublishSettingsFragment.kt
  config/detekt/baseline.xml
Labels: [Status] Not Ready for Merge

#17437 Copying QS data with indexes
  WordPress/src/main/java/org/wordpress/android/provider/ProviderUtility.kt
  WordPress/src/main/java/org/wordpress/android/resolver/ResolverUtility.kt
  WordPress/src/main/java/org/wordpress/android/userflags/UserFlagsData.kt
  WordPress/src/main/java/org/wordpress/android/userflags/provider/UserFlagsProvider.kt
  WordPress/src/main/java/org/wordpress/android/userflags/resolver/UserFlagsResolver.kt
  WordPress/src/test/java/org/wordpress/android/resolver/ResolverUtilityTest.kt
  WordPress/src/test/java/org/wordpress/android/userflags/resolver/UserFlagsResolverTest.kt
Labels: [Type] Enhancement, Local User Flags

#17458 Merge release/21.2 after Code Freeze (21.2-rc-1)
  RELEASE-NOTES.txt
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
  version.properties
Labels: Releases

#17423 [Jetpack Content Migration Flow] Refactor - Unify user flags provider
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalContentEntity.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentProvider.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/UserFlagsProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/provider/ProviderUtility.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestrator.kt
  WordPress/src/main/java/org/wordpress/android/userflags/UserFlagsData.kt
  WordPress/src/main/java/org/wordpress/android/userflags/provider/UserFlagsProvider.kt
  WordPress/src/main/java/org/wordpress/android/userflags/resolver/UserFlagsResolver.kt
  WordPress/src/test/java/org/wordpress/android/userflags/resolver/UserFlagsResolverTest.kt
  WordPress/src/wordpress/AndroidManifest.xml
Labels: Jetpack Focus

#17424 [Jetpack Content Migration Flow] Refactor - Unify reader saved posts provider
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalContentEntity.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentProvider.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/ReaderSavedPostsProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/reader/savedposts/provider/ReaderSavedPostsProvider.kt
  WordPress/src/main/java/org/wordpress/android/reader/savedposts/resolver/ReaderSavedPostsResolver.kt
  WordPress/src/wordpress/AndroidManifest.xml
Labels: Jetpack Focus

#17457 [Jetpack Content Migration Flow] Refactor - Unify blogging reminders provider
  WordPress/src/main/java/org/wordpress/android/bloggingreminders/provider/BloggingRemindersProvider.kt
  WordPress/src/main/java/org/wordpress/android/bloggingreminders/resolver/BloggingRemindersResolver.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/BloggingRemindersProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalContentEntity.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentProvider.kt
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/test/java/org/wordpress/android/bloggingreminders/resolver/BloggingRemindersResolverTest.kt
  WordPress/src/wordpress/AndroidManifest.xml
Labels: Jetpack Focus

#17469 Merge Release Notes for 21.2
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: Releases

#17435 [Jetpack Content Migration Flow] Add Notifications Screen to the flow
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/state/NotificationsStep.kt
  WordPress/src/main/res/drawable/ic_jetpack_migration_notifications.xml
  WordPress/src/main/res/values-night/colors.xml
  WordPress/src/main/res/values/colors_translucent.xml
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Task, Jetpack Focus

#17468 Detekt - Resolve/Suppress All Baseline Warnings - Long methods warnings_ HomePageSettingsDialog
  WordPress/src/main/java/org/wordpress/android/ui/prefs/homepage/HomepageSettingsDialog.kt
  config/detekt/baseline.xml
Labels: Tooling, Tech debt

#17470 [Do Not Merge] - CI Trigger for #17468
  WordPress/src/main/java/org/wordpress/android/ui/prefs/homepage/HomepageSettingsDialog.kt
  config/detekt/baseline.xml
Labels: [Status] Not Ready for Merge

#17449 [Jetpack Content Migration Flow] Add Help Screen
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/HelpActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/HelpViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/components/UserAvatarImage.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/state/WelcomeStep.kt
  WordPress/src/main/res/layout/help_activity.xml
  WordPress/src/main/res/values-land/dimens.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/accounts/HelpViewModelTest.kt
Labels: [Type] Task, Jetpack Focus

#17456 Containment fix for My Site > Comments crash with standalone JP plugins.
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalAccessTokenProviderHelper.kt
  build.gradle
Labels: Comments, [Type] Crash

#17472 Guard mutex unlock in isLocked check to avoid errors during local data uploads
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt
Labels: Offline Support

#17442 [Tooling] Allow Installable Build step to fail silently (and still have the step pass) on retries
  Gemfile
  Gemfile.lock
  fastlane/Pluginfile
  fastlane/lanes/build.rb
Labels: Tooling

#17474 Fix large font size accessibility issue on migration screens by making the content scrollable
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/components/ButtonsColumn.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/components/Message.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/components/ScreenIcon.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/components/SiteList.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/components/Subtitle.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/components/Title.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/state/DoneStep.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/state/NotificationsStep.kt
Labels: [Type] Task, Accessibility, Jetpack Focus

#17482 Merge release/21.2 after 21.2-rc-2
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadStarter.kt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-kmr/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  version.properties
Labels: Releases

#17477 Fixes: Notifications Pending Intent Mutability issue
  build.gradle
Labels: [Type] Bug, [Status] Not Ready for Merge

#17438 Adds org.wordpress-mobile.react-native-libraries.* group to repositories
  WordPress/build.gradle
  libs/editor/build.gradle
Labels: Tooling

#17498 Prevent onMainSwitchCheckedChanged call on initialization
  WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/PrefMainSwitchToolbarView.kt
Labels: [Type] Bug, Tracks

#17371 Jetpack focus: Disable push notifications for WP
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/wordpress/AndroidManifest.xml
  WordPress/src/wordpress/java/org/wordpress/android/ui/mysite/jetpackbadge/JetpackAppInstallReceiver.kt
Labels: [Type] Task, Jetpack Focus

#17495 Jetpack Focus: Open web links with Jetpack - Add custom scheme deep link receiver
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncherWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkingCustomIntentReceiverActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkingCustomIntentReceiverViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/DeepLinkingCustomIntentReceiverViewModelTest.kt
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Task, Deeplinks, Jetpack Focus

#17502 [Jetpack Content Migration Flow] Fixes compile error on temporarily disabled tests
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolverTest.kt
Labels: [Type] Task, Jetpack Focus

#17492 [Jetpack Content Migration Flow] Implement Error Screen support
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/components/ScreenIcon.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/components/SecondaryButton.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/state/ErrorStep.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/state/WelcomeStep.kt
  WordPress/src/main/res/drawable/ic_jetpack_migration_error.xml
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Task, Jetpack Focus

#17473 [Jetpack Content Migration Flow] Standardize local data migration steps
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/BloggingRemindersProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalAccessTokenProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalContentEntity.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalEligibilityStatusProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentProvider.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentResolver.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalPostProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalSiteProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/ReaderSavedPostsProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/UserFlagsProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/provider/query/QueryResult.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestrator.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/test/java/org/wordpress/android/localcontentmigration/LocalContentEntityTest.kt
  WordPress/src/test/java/org/wordpress/android/localcontentmigration/LocalPostProviderHelperTest.kt
Labels: Jetpack Focus

#17483 [Jetpack Content Migration Flow] Standardize shared login
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalContentEntity.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalEligibilityStatusProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentProvider.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/SharedLoginHelper.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestrator.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolverTest.kt
Labels: Jetpack Focus

#17484 [Jetpack Content Migration Flow] Standardize sites helper
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalContentEntity.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/SitesMigrationHelper.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestrator.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolverTest.kt
Labels: Jetpack Focus

#17487 [Jetpack Content Migration Flow] Standardize user flags helper
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalContentEntity.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationError.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationResult.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestrator.kt
  WordPress/src/main/java/org/wordpress/android/userflags/resolver/UserFlagsHelper.kt
  WordPress/src/main/java/org/wordpress/android/userflags/resolver/UserFlagsResolver.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolverTest.kt
  WordPress/src/test/java/org/wordpress/android/userflags/resolver/UserFlagsHelperTest.kt
Labels: Jetpack Focus

#17485 [Jetpack Content Migration Flow] Standardize reader saved posts helper
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationError.kt
  WordPress/src/main/java/org/wordpress/android/reader/savedposts/resolver/ReaderSavedPostsHelper.kt
  WordPress/src/main/java/org/wordpress/android/reader/savedposts/resolver/ReaderSavedPostsResolver.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestrator.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolverTest.kt
Labels: Jetpack Focus

#17486 [Jetpack Content Migration Flow] Standardize posts helper
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/EligibilityHelper.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalContentEntity.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationResult.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalPostsHelper.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestrator.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolverTest.kt
Labels: Jetpack Focus

#17503 Make 'WordPress is better with Jetpack' bottom sheet text and button fully visible with big fonts
  RELEASE-NOTES.txt
  WordPress/src/main/res/layout-land/jetpack_powered_bottom_sheet.xml
  WordPress/src/main/res/layout/jetpack_powered_bottom_sheet.xml
Labels: Jetpack Focus

#17497 Jetpack Focus: Open web links with Jetpack - Initialization
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkOpenWebLinksWithJetpackHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/FirebaseRemoteConfigWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/PackageManagerWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/config/OpenWebLinksWithJetpackFlowFeatureConfig.kt
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/DeepLinkOpenWebLinksWithJetpackHelperTest.kt
Labels: [Type] Task, [Status] Not Ready for Merge, Jetpack Focus

#17504 Jetpack Focus: Open web links with Jetpack - Add App Setting
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkOpenWebLinksWithJetpackHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/util/BuildConfigWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/config/OpenWebLinksWithJetpackFlowFeatureConfig.kt
  WordPress/src/main/res/values/key_strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/app_settings.xml
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/DeepLinkOpenWebLinksWithJetpackHelperTest.kt
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Task, Jetpack Focus

#17432 Jetpack focus: Show full screen overlay for Jetpack Features
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureFullScreenOverlayFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureFullScreenOverlayViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureOverlayContentBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureOverlayShownTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalOverlayUtil.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalPhaseHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackOverlayUIState.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/DateTimeUtilsWrapper.kt
  WordPress/src/main/res/layout/jetpack_feature_removal_overlay.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalOverlayUtilTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/StatsViewModelTest.kt
Labels: Jetpack, [Status] Needs Design Review, [Status] Not Ready for Merge

#17496 Disable local notifications with Notification Settings switch
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/usecase/UpdateNotificationSettingsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/workers/notification/createsite/CreateSiteNotificationHandler.kt
  WordPress/src/main/java/org/wordpress/android/workers/weeklyroundup/WeeklyRoundupNotifier.kt
  WordPress/src/main/java/org/wordpress/android/workers/weeklyroundup/WeeklyRoundupScheduler.kt
  WordPress/src/test/java/org/wordpress/android/workers/notification/createsite/CreateSiteNotificationHandlerTest.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/mysite/jetpackbadge/JetpackAppInstallReceiver.kt
  build.gradle
Labels: [Type] Bug, Notifications

#17511 Avoid truncation of 'Try Jetpack" button with big fonts
  RELEASE-NOTES.txt
  WordPress/src/main/res/drawable/bg_rectangle_rounded_jetpack_ripple.xml
  WordPress/src/main/res/layout-land/jetpack_powered_bottom_sheet.xml
  WordPress/src/main/res/layout/jetpack_powered_bottom_sheet.xml
  WordPress/src/main/res/values/dimens.xml
Labels: Jetpack Focus

#17500 [Jetpack Content Migration Flow] Fail with errors in posts helper
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationError.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalPostsHelper.kt
Labels: [Type] Task, Jetpack Focus

#17507 [Jetpack Content Migration Flow] Migrate pages along with posts
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationContentResolver.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationError.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalPostProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalPostsHelper.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/SitesMigrationHelper.kt
  WordPress/src/main/java/org/wordpress/android/resolver/DbWrapper.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestrator.kt
  WordPress/src/main/java/org/wordpress/android/userflags/resolver/UserFlagsHelper.kt
  WordPress/src/test/java/org/wordpress/android/localcontentmigration/LocalPostProviderHelperTest.kt
Labels: [Type] Task, Jetpack Focus

#17514 Jetpack Focus: Open web links with Jetpack - Update App pref setting
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkOpenWebLinksWithJetpackHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/util/PackageManagerWrapper.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/DeepLinkOpenWebLinksWithJetpackHelperTest.kt
Labels: [Type] Task, Jetpack Focus

#17516 [Jetpack Content Migration Flow] Integrate local migration with UI
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/EligibilityHelper.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalAccessTokenProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalContentEntity.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationResult.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/SharedLoginHelper.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestrator.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/JetpackAppMigrationFlowUtils.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolverTest.kt
Labels: [Type] Task, Jetpack Focus

#17518 [Jetpack Content Migration Flow] Pre flight checks for posts / pages
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/ContentMigrationAnalyticsTracker.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalContentEntity.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalEligibilityStatusProviderHelper.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestrator.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/JetpackAppMigrationFlowUtils.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolverTest.kt
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Task, Jetpack Focus

#17515 [JP Content Migration Flow] Add success card to "My Site"
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapterDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItemBuilderParams.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/items/singleactioncard/SingleActionCardBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/items/singleactioncard/SingleActionCardViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/publicdata/AppStatus.kt
  WordPress/src/main/java/org/wordpress/android/util/publicdata/PackageManagerWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/signature/SignatureUtils.kt
  WordPress/src/main/res/drawable/ic_wordpress_blue_32dp.xml
  WordPress/src/main/res/layout/my_site_single_action_card_item.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/util/publicdata/AppStatusTest.kt
Labels: [Type] Task, Jetpack Focus

#17520 Merge release/21.2 after 21.2-rc-3 beta
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  tools/list_missing_translations.sh
  version.properties
Labels: Releases

#17101 Adds: the logic for fetching and storing the remote feature flags from BE
  WordPress/src/main/java/org/wordpress/android/AppInitializer.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/DebugSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/config/AppConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/FeatureFlagConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/RemoteConfig.kt
  WordPress/src/test/java/org/wordpress/android/ui/debug/DebugSettingsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/util/config/AppConfigParametrizedTest.kt
  WordPress/src/test/java/org/wordpress/android/util/config/AppConfigTest.kt
  build.gradle
  libs/mocks/src/main/assets/mocks/mappings/wpcom/mobile/feature-flags.json
Labels: [Type] Task, [Status] Ready to Merge, Jetpack App

#17523 Jetpack Focus: Prepare DeepLinkIntent Receiver to launch open web links flow
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkEntryPoint.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkOpenWebLinksWithJetpackHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkingCustomIntentReceiverActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkingCustomIntentReceiverViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkingIntentReceiverActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkingIntentReceiverViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/PackageManagerWrapper.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/DeepLinkingCustomIntentReceiverViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/DeepLinkingIntentReceiverViewModelTest.kt
Labels: [Type] Task, Jetpack Focus

#17526 Jetpack Focus: Jetpack app uninstall receiver
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkOpenWebLinksWithJetpackHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/wordpress/AndroidManifest.xml
  WordPress/src/wordpress/java/org/wordpress/android/ui/deeplinks/JetpackAppUninstallReceiver.kt
Labels: [Type] Task, Jetpack Focus

#17512 Add analytics event for tracking Jetpack full screen overlay events
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureFullScreenOverlayFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureFullScreenOverlayViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureOverlayContentBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalOverlayUtil.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalPhaseHelper.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalOverlayUtilTest.kt
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Jetpack, [Status] Not Ready for Merge

#17493 Jetpack focus display Site creation overlay
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureFullScreenOverlayFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureFullScreenOverlayViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureOverlayContentBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalOverlayUtil.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalPhaseHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackOverlayUIState.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVM.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalOverlayUtilTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVMTest.kt
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Jetpack

#17501 Update Apache Commons Text to 1.10.0
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/models/Note.java
  WordPress/src/main/java/org/wordpress/android/ui/domains/DomainRegistrationDetailsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapterDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostSettingsUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/DetailListPreference.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/MostPopularInsightsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateFormatter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsDateUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/ArrayUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/DateUtils.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostSettingsUtilsTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/MostPopularInsightsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/util/ArrayUtilsTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/activitylog/ActivityLogViewModelTest.kt
  build.gradle
  config/detekt/baseline.xml
  libs/editor/build.gradle
  libs/editor/src/main/java/org/wordpress/android/editor/MetadataUtils.java
  libs/editor/src/main/java/org/wordpress/android/editor/MetadataUtils.kt
  libs/mocks/build.gradle
Labels: Tooling, Tech debt

#17480 Gradle Wrapper Validation
  .buildkite/beta-builds.yml
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
  .github/workflows/gradle-wrapper-validation.yml
Labels: Tooling

#17527 [JP Content Migration Flow] Implement success card dialog
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationResult.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestrator.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/compose/state/DeleteStep.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapterDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SiteNavigationAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/res/drawable/ic_jetpack_migration_delete.xml
  WordPress/src/main/res/layout/activity_jetpack_migration.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModelTest.kt
Labels: [Type] Task, Jetpack Focus

#17532 Jetpack Focus: Show open web links with Jetpack Overlay from deep link intent receiver
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncherWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkNavigator.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkOpenWebLinksWithJetpackHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkingIntentReceiverActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkingIntentReceiverViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureFullScreenOverlayFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureFullScreenOverlayViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureOverlayContentBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalOverlayUtil.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalPhaseHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackOverlayUIState.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/DeepLinkingIntentReceiverViewModelTest.kt
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Task, Jetpack Focus

#17529 [Build] Remove Fetch Style Plugin
  build.gradle
  settings.gradle
Labels: Tooling, Tech Debt

#17531 [JP Content Migration Flow] Adds jetpack migration email api call
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/ContentMigrationAnalyticsTracker.kt
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/MigrationEmailHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModelTest.kt
  build.gradle
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Task, Jetpack Focus

#17536 [JP Content Migration Flow] Check Wordpress version compatibility
  WordPress/src/main/java/org/wordpress/android/ui/utils/JetpackAppMigrationFlowUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/publicdata/WordPressPublicData.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/WordPressPublicDataTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/utils/JetpackAppMigrationFlowUtilsTest.kt
Labels: [Type] Task, Jetpack Focus

#17513 Disable notifications on WP app in migration flow on JP app
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModelTest.kt
Labels: [Type] Task, Jetpack Focus

#17537 Jetpack focus: Adds site creation source parameter to analytics
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkingIntentReceiverActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureFullScreenOverlayFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureFullScreenOverlayViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureRemovalOverlayUtil.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationActivity.kt
Labels: Jetpack

#17534 Fix disabling create site notification issue
  WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/usecase/UpdateNotificationSettingsUseCase.kt
Labels: [Type] Bug, Notifications

#17533 Jetpack App: Fix QR Code auth flow not translated in app language
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/qrcodeauth/QRCodeAuthActivity.kt
Labels: i18n, QRCode Auth

#17539 Adds: Missing database schema for version 9
  build.gradle
Labels: Tech Debt

#17540 Fixes: Try the jetpack app not being shown properly when the font size is large
  WordPress/src/main/res/layout-land/jetpack_feature_removal_overlay.xml
  WordPress/src/main/res/layout-land/jetpack_powered_bottom_sheet.xml
  WordPress/src/main/res/layout/jetpack_feature_removal_overlay.xml
  WordPress/src/main/res/layout/jetpack_powered_bottom_sheet.xml
Labels: Jetpack, [Status] Needs Design Review

#17538 [JP Content Migration Flow] Enables Jetpack migration flow
  RELEASE-NOTES.txt
  WordPress/build.gradle
Labels: [Type] Task, Jetpack Focus

#17541 Jetpack Focus: Show open links with Jetpack Overlay from reader deep link receiver
  WordPress/src/main/java/org/wordpress/android/AppInitializer.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkOpenWebLinksWithJetpackHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkingIntentReceiverActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkingIntentReceiverViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureOverlayContentBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.java
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/app_settings.xml
Labels: [Type] Task, Jetpack Focus

#17547 Jetpack Focus: Open links in Jetpack refactoring
  WordPress/src/main/java/org/wordpress/android/AppInitializer.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkOpenWebLinksWithJetpackHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkingIntentReceiverViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/JetpackFeatureOverlayContentBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.java
  WordPress/src/main/java/org/wordpress/android/util/PackageManagerWrapper.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/deeplinks/DeepLinkOpenWebLinksWithJetpackHelperTest.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/deeplinks/JetpackAppUninstallReceiver.kt
Labels: [Type] Task, Jetpack Focus

#17546 Disable quick start notifications with Notification Settings switch
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartReminderReceiver.java
Labels: [Type] Bug, Notifications

#17549 Local content migration - handle ineligible scenarios gracefully
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationResult.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestrator.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/JetpackAppMigrationFlowUtils.kt
  WordPress/src/main/java/org/wordpress/android/userflags/resolver/UserFlagsHelper.kt
  WordPress/src/test/java/org/wordpress/android/localcontentmigration/LocalPostProviderHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/utils/JetpackAppMigrationFlowUtilsTest.kt
Labels: Jetpack Focus

#17553 [Jetpack Migration Flow] Add welcome screen data to successful migration state
  WordPress/src/main/java/org/wordpress/android/localcontentmigration/LocalMigrationResult.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/LocalMigrationOrchestrator.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
Labels: [Type] Bug, Jetpack Focus

#17535 [Dependency Updates] Restructure Dependency Versions
  WordPress/build.gradle
  build.gradle
  fastlane/lanes/localization.rb
  libs/analytics/build.gradle
  libs/editor/build.gradle
  libs/image-editor/build.gradle
  libs/mocks/build.gradle
  libs/networking/build.gradle
  libs/processors/build.gradle
Labels: Tooling, Tech Debt

#17573 Fix redeclaring disable notif permission issue
  WordPress/src/jetpack/AndroidManifest.xml
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/wordpress/AndroidManifest.xml
Labels: [Type] Bug, Notifications

#17395 [Tooling] [Screenshots] Update documentation for screenshots
  fastlane/SCREENSHOT_DEVICE_SETUP.md
  fastlane/screenshots/README.md
  fastlane/screenshots/assets/fonts/NotoSerif-Bold.ttf
  fastlane/screenshots/assets/fonts/NotoSerif-BoldItalic.ttf
  fastlane/screenshots/assets/fonts/NotoSerif-Italic.ttf
  fastlane/screenshots/assets/fonts/NotoSerif-Regular.ttf
Labels: Tooling

#17576 [Tooling] Delete old `changelogs/1287.txt` files accidentally introduced during #17505
  fastlane/jetpack_metadata/android/en-US/changelogs/1287.txt
  fastlane/jetpack_metadata/android/id/changelogs/1287.txt
  fastlane/metadata/android/en-US/changelogs/1287.txt
  fastlane/metadata/android/es-ES/changelogs/1287.txt
  fastlane/metadata/android/fr-CA/changelogs/1287.txt
  fastlane/metadata/android/fr-FR/changelogs/1287.txt
  fastlane/metadata/android/id/changelogs/1287.txt
  fastlane/metadata/android/sv-SE/changelogs/1287.txt
Labels: Tooling

#17581 [Tooling] Report Firebase Test Failures as Buildkite Annotations
  Gemfile
  Gemfile.lock
  fastlane/lanes/test.rb
Labels: Tooling, [Status] Not Ready for Merge

#17583 Revert "[Tooling] Report Firebase Test Failures as Buildkite Annotations"
  Gemfile
  Gemfile.lock
  fastlane/lanes/test.rb
Labels: Tooling
