Repository wordpress-mobile/WordPress-Android, pull requests merged in 2022-09, with the labels that each got.

#17113 Fix the lint error caused by a string resource
  WordPress/src/main/res/values-zh-rTW/strings.xml
Labels: [Type] Bug, Lint

#17107 [Jetpack App] Add deep links from Calypso's app banners
  WordPress/src/jetpack/AndroidManifest.xml
Labels: Jetpack App, Deeplinks

#17110 Integrate gutenberg-mobile release 1.82.0
  RELEASE-NOTES.txt
  build.gradle
Labels: gutenberg-mobile

#17116 Fix PR link in 20.7 release notes
  RELEASE-NOTES.txt
Labels: Documentation

#17100 Jetpack focus: Enable widgets on jetpack app
  RELEASE-NOTES.txt
  WordPress/src/jetpack/AndroidManifest.xml
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/granular/usecases/OverviewUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/WidgetService.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/WidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsColorSelectionViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsDataTypeSelectionViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsSiteSelectionViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsWidgetConfigureFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/utils/WidgetUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/weeks/StatsWeekWidget.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/weeks/StatsWeekWidgetConfigureActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/weeks/WeekViewsWidgetListProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/weeks/WeekViewsWidgetListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/weeks/WeekViewsWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/weeks/WeekWidgetBlockListProviderFactory.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/weeks/WeekWidgetBlockListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsAnalyticsUtils.kt
  WordPress/src/main/res/drawable-hdpi/stats_weeks_widget_preview.png
  WordPress/src/main/res/drawable-mdpi/stats_weeks_widget_preview.png
  WordPress/src/main/res/drawable-xhdpi/stats_weeks_widget_preview.png
  WordPress/src/main/res/drawable-xxhdpi/stats_weeks_widget_preview.png
  WordPress/src/main/res/drawable-xxxhdpi/stats_weeks_widget_preview.png
  WordPress/src/main/res/layout/stats_week_views_widget_configure_activity.xml
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/stats_week_views_widget_info.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/configuration/StatsDataTypeSelectionViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/weeks/WeekViewsWidgetListViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/widget/weeks/WeekWidgetBlockListViewModelTest.kt
Labels: [Type] Task, Jetpack Focus

#17109 Jetpack Social: Update the strings to reflect the new publicize branding
  WordPress/src/main/res/values/strings.xml
Labels: Jetpack

#17059 [Jetpack focus] Implement shared login credentials
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/provider/query/QueryContentProvider.kt
  WordPress/src/main/java/org/wordpress/android/provider/query/QueryResult.kt
  WordPress/src/main/java/org/wordpress/android/resolver/ContentResolverWrapper.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/JetpackPublicData.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/JetpackSharedLoginFlag.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/WordPressPublicData.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/provider/SharedLoginProvider.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolver.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/AccountActionBuilderWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/config/JetpackSharedLoginFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/signature/SignatureUtils.kt
  WordPress/src/test/java/org/wordpress/android/provider/query/QueryResultTest.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/JetpackPublicDataTest.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/JetpackSharedLoginFlagTest.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/WordPressPublicDataTest.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolverTest.kt
  WordPress/src/wordpress/AndroidManifest.xml
Labels: [Type] Task, Shared login

#17119 [Tooling] Remove `play_store_desc_old_copy_do_not_translate` from `PlayStoreStrings.po`
  WordPress/metadata/PlayStoreStrings.po
Labels: Tooling

#17121 Remove wrong format strings from es strings.xml
  WordPress/src/main/res/values-es/strings.xml
Labels: [Type] Bug, Lint

#17122 Add accessibility label to me button
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
Labels: [Type] Enhancement, Accessibility

#17123 Integrate gutenberg-mobile release 1.81.2
  build.gradle
Labels: gutenberg-mobile

#17124 [Hotfix] Show Jetpack Overlay only when the remote flag is enabled
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/detail/ActivityLogDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/jetpackbadge/MySiteJetpackBadgeViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/util/config/JetpackPoweredBottomSheetFeatureConfig.kt
Labels: Jetpack Focus

#17134 [Tooling] Remove `upload_to_play_store:true` unused option #trivial
  .buildkite/commands/release-build.sh
Labels: Tooling

#17145 Merge **unreleased** 20.7 code freeze and editorialized release notes into `trunk`
  RELEASE-NOTES.txt
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
  version.properties
Labels: Releases

#17136 Merge hotfix `release/20.6.1` into current `release/20.7`
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/detail/ActivityLogDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/jetpackbadge/MySiteJetpackBadgeViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/util/config/JetpackPoweredBottomSheetFeatureConfig.kt
Labels: Releases

#17135 Integrate gutenberg-mobile release 1.82.1
  build.gradle
Labels: gutenberg-mobile

#17146 Merge changes from hotfix 20.6.1, 20.7 code freeze, and 20.7-rc.2 into `trunk`
  WordPress/src/main/java/org/wordpress/android/ui/activitylog/detail/ActivityLogDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/jetpackbadge/MySiteJetpackBadgeViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/util/config/JetpackPoweredBottomSheetFeatureConfig.kt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-kmr/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-ms/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sr/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  build.gradle
  fastlane/lanes/release.rb
  version.properties
Labels: Releases

#17138 [Local user flags] Implement feature flag
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/util/config/JetpackLocalUserFlagsFeatureConfig.kt
Labels: Jetpack Focus, Local User Flags

#17127 [Jetpack focus] Implement shared login credentials analytics
  WordPress/src/main/java/org/wordpress/android/sharedlogin/SharedLoginAnalyticsTracker.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/data/JetpackPublicData.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/data/WordPressPublicData.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/provider/SharedLoginProvider.kt
  WordPress/src/main/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolver.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/JetpackPublicDataTest.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/SharedLoginAnalyticsTrackerTest.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/WordPressPublicDataTest.kt
  WordPress/src/test/java/org/wordpress/android/sharedlogin/resolver/SharedLoginResolverTest.kt
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Jetpack Focus, Shared login

#17150 Merge `release/20.7` after `20.7-rc-3`
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  version.properties
Labels: Releases

#17083 My Site Dashboard: List Scrolling positions are not maintained #16436
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabFragment.kt
Labels: My Site Dashboard

#17156 Do not merge - Only here to trigger CI on https://github.com/wordpress-mobile/WordPress-Android/pull/17083
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabFragment.kt
Labels: [Type] Bug, [Status] Not Ready for Merge

#17157 Merge changes from 20.7-rc-4
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  version.properties
Labels: Releases

#17140 Jetpack focus enable more widgets on jetpack app
  RELEASE-NOTES.txt
  WordPress/src/jetpack/res/drawable-hdpi/stats_weeks_widget_preview.png
  WordPress/src/jetpack/res/drawable-mdpi/stats_weeks_widget_preview.png
  WordPress/src/jetpack/res/drawable-xhdpi/stats_weeks_widget_preview.png
  WordPress/src/jetpack/res/drawable-xxhdpi/stats_weeks_widget_preview.png
  WordPress/src/jetpack/res/drawable-xxxhdpi/stats_weeks_widget_preview.png
  WordPress/src/jetpack/res/xml-v31/stats_week_views_widget_info.xml
  WordPress/src/jetpack/res/xml/stats_week_views_widget_info.xml
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/alltime/AllTimeWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/minified/MinifiedWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/today/TodayWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/views/ViewsWidgetUpdater.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/weeks/WeekViewsWidgetUpdater.kt
  WordPress/src/main/res/layout/stats_all_time_widget_preview.xml
  WordPress/src/main/res/layout/stats_minified_widget_preview.xml
  WordPress/src/main/res/layout/stats_today_widget_preview.xml
  WordPress/src/main/res/layout/stats_views_widget_item_negative_preview.xml
  WordPress/src/main/res/layout/stats_views_widget_item_neutral_preview.xml
  WordPress/src/main/res/layout/stats_views_widget_item_positive_preview.xml
  WordPress/src/main/res/layout/stats_views_widget_preview.xml
  WordPress/src/main/res/layout/stats_week_views_widget_preview.xml
  WordPress/src/main/res/layout/stats_widget_block_item_dark.xml
  WordPress/src/main/res/layout/stats_widget_block_item_light.xml
  WordPress/src/main/res/layout/stats_widget_title_dark.xml
  WordPress/src/main/res/layout/stats_widget_title_light.xml
  WordPress/src/main/res/values/attrs.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/xml-v31/stats_all_time_widget_info.xml
  WordPress/src/main/res/xml-v31/stats_minified_widget_info.xml
  WordPress/src/main/res/xml-v31/stats_today_widget_info.xml
  WordPress/src/main/res/xml-v31/stats_views_widget_info.xml
Labels: Stats, Stats Widgets

#17160 Enforce western arabic numerals for Stats
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/widgets/MaterialTextViewWithNumerals.kt
  WordPress/src/main/res/layout/my_site_todays_stats_card.xml
  WordPress/src/main/res/layout/stats_block_bar_chart_item.xml
  WordPress/src/main/res/layout/stats_block_list_item.xml
  WordPress/src/main/res/layout/stats_block_list_item_with_image.xml
  WordPress/src/main/res/layout/stats_block_map_legend_item.xml
  WordPress/src/main/res/layout/stats_block_pie_chart_item.xml
  WordPress/src/main/res/layout/stats_block_selectable_column.xml
  WordPress/src/main/res/layout/stats_block_value_item.xml
  WordPress/src/main/res/layout/stats_block_value_with_chart_item.xml
  WordPress/src/main/res/layout/stats_block_values_item.xml
  WordPress/src/main/res/layout/stats_date_selector.xml
  WordPress/src/main/res/layout/stats_quick_scan_item.xml
Labels: [Type] Enhancement, i18n, General

#17120 Add Author button to post settings
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/people/utils/PeopleUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/people/utils/PeopleUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostSettingsListDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PublishSettingsViewModel.kt
  WordPress/src/main/res/layout/edit_post_settings_fragment.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/posts/PublishSettingsViewModelTest.kt
  build.gradle
  libs/mocks/src/main/assets/mocks/mappings/wpcom/sites/site_106707880_users.json
  libs/mocks/src/main/assets/mocks/mappings/wpcom/sites/sites_users.json
Labels: [Type] Task, Post Settings

#17164 Detekt - Resolve/Suppress All Baseline Warnings - max line warnings
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewUsageCategory.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/XPostsCapabilityChecker.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stories/SaveStoryGutenbergBlockUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stories/StoryComposerActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stories/media/StoryMediaSaveUploadBridge.kt
  WordPress/src/main/java/org/wordpress/android/ui/whatsnew/FeatureAnnouncementViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/config/AppConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt
  config/detekt/baseline.xml
Labels: Tooling, Tech debt

#17165 Do not merge - Only here to trigger CI on PR - https://github.com/wordpress-mobile/WordPress-Android/pull/17164
  WordPress/src/main/java/org/wordpress/android/ui/WPWebViewUsageCategory.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/XPostsCapabilityChecker.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stories/SaveStoryGutenbergBlockUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stories/StoryComposerActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stories/media/StoryMediaSaveUploadBridge.kt
  WordPress/src/main/java/org/wordpress/android/ui/whatsnew/FeatureAnnouncementViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/config/AppConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/image/ImageManager.kt
  config/detekt/baseline.xml
Labels: [Status] Not Ready for Merge

#17172 Merge release/20.8 after Code Freeze (20.8-rc-1)
  RELEASE-NOTES.txt
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/release_notes.txt
  build.gradle
  fastlane/resources/values/strings.xml
  version.properties
Labels: Releases

#17167 Jetpack Focus: Recommend App in Me view
  WordPress/src/jetpack/res/values/strings.xml
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
Labels: [Type] Task, Jetpack Focus

#17152 Do not merge - Only here to trigger CI on PR - https://github.com/wordpress-mobile/WordPress-Android/pull/17077
  WordPress/src/main/res/drawable/tab_indicator_color.xml
  WordPress/src/main/res/values-land/dimens.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/styles.xml
Labels: [Status] Not Ready for Merge

#17166 Fixes: Inconsistency of Light mode and Dark mode in screenshots
  WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/JPScreenshotTest.java
  WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java
Labels: Tooling, UI Tests

#17104 [Jetpack focus] Remove carousel and implement WordPress landing screen redesign
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/res/values-night/colors.xml
  WordPress/src/main/res/values/colors.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/LoginPrologueFragment.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/LoginPrologueRevampedFragment.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/LoginPrologueViewModel.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/compose/components/PrimaryButton.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/compose/components/SecondaryButton.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/compose/components/Tagline.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/compose/theme/Fonts.kt
  WordPress/src/wordpress/res/drawable-mdpi/brush_stroke.png
  WordPress/src/wordpress/res/drawable-night-mdpi/brush_stroke.png
  WordPress/src/wordpress/res/drawable-night-xhdpi/brush_stroke.png
  WordPress/src/wordpress/res/drawable-night-xxxhdpi/brush_stroke.png
  WordPress/src/wordpress/res/drawable-xhdpi/brush_stroke.png
  WordPress/src/wordpress/res/drawable-xxxhdpi/brush_stroke.png
  WordPress/src/wordpress/res/drawable/ic_wordpress_gridicon.xml
  WordPress/src/wordpress/res/font/eb_garamond.ttf
Labels: Jetpack Focus

#17185 Fix editor role publish issue
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/res/layout/edit_post_settings_fragment.xml
  WordPress/src/test/java/org/wordpress/android/ui/posts/PublishSettingsViewModelTest.kt
Labels: [Type] Bug, Post Settings

#17189 Update FluxC version to 1.54.1
  build.gradle
Labels: [Type] Task, dependency update

#17084 Long title problem on stats cards #16887
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/TitleWithMoreViewHolder.kt
Labels: [Type] Bug, Stats Revamp

#17184 Fix prompts answers string localization
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingUiStateMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/bloggingprompts/BloggingPromptCardBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/UiHelpers.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/UiString.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingUiStateMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/dashboard/bloggingprompts/BloggingPromptCardBuilderTest.kt
Labels: [Type] Enhancement, Localization, Blogging Prompts v1

#17193 Merge release branch after 20.8-rc-2 beta
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPublishSettingsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/res/layout/edit_post_settings_fragment.xml
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-az/strings.xml
  WordPress/src/main/res/values-bg/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-cy/strings.xml
  WordPress/src/main/res/values-da/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-eu/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gd/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-hi/strings.xml
  WordPress/src/main/res/values-hr/strings.xml
  WordPress/src/main/res/values-hu/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-is/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-kmr/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-mk/strings.xml
  WordPress/src/main/res/values-ms/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sr/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-th/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-uz/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/posts/PublishSettingsViewModelTest.kt
  build.gradle
  version.properties
Labels: Releases

#17194 Merge Editorialized Release Notes for 20.8
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: Releases

#17196 Document updateContextLocale contract to remove confusion about context non-null requirement
  WordPress/src/main/java/org/wordpress/android/AppInitializer.kt
Labels: Tooling

#17195 [Compile Warnings As Errors] Annotations Module - Enable All Warnings as Errors
  build.gradle
  libs/annotations/build.gradle
  libs/editor/build.gradle
  libs/image-editor/build.gradle
  libs/processors/build.gradle
Labels: Tooling, Tech debt

#17159 Reader: "Manage Topics & Sites" not translated #17112
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderSubsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/discover/interests/ReaderInterestsActivity.kt
Labels: [Type] Bug, i18n

#17199 [Tooling] Improve the Installable Build comment
  fastlane/Fastfile
  fastlane/lanes/build.rb
Labels: Tooling

#17204 [Compile Warnings As Errors] Editor Module - Resolve Warnings & Enable All Warnings as Errors
  libs/editor/build.gradle
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergDialogFragment.kt
Labels: Tooling, Tech debt

#17197 [Compile Warnings As Errors] Processors Module - Resolve Warnings & Enable All Warnings as Errors
  build.gradle
  libs/editor/build.gradle
  libs/processors/build.gradle
  libs/processors/src/main/java/org/wordpress/android/processor/RemoteConfigCheckBuilder.kt
  libs/processors/src/main/java/org/wordpress/android/processor/RemoteConfigProcessor.kt
Labels: Tooling, Tech debt

#17209 Hilt migration of login screens
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/LoginPrologueFragment.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/LoginPrologueViewModel.kt
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginEpilogueActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginMagicLinkInterceptActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginEpilogueFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/jetpack/LoginNoSitesFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/jetpack/LoginNoSitesViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/jetpack/LoginSiteCheckErrorFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/jetpack/LoginSiteCheckErrorViewModel.kt
  WordPress/src/wordpress/java/org.wordpress.android.ui.accounts.login/LoginPrologueFragment.kt
Labels: [Type] Enhancement, Tech debt

#17188 Removes: click on before every input event in login flow
  WordPress/src/androidTest/java/org/wordpress/android/e2e/flows/LoginFlow.java
Labels: [Status] Not Ready for Merge, UI Tests

#16947 Fix percent sign should be localized
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/backup/download/BackupDownloadViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/backup/download/builders/BackupDownloadStateListItemBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/restore/RestoreViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/restore/builders/RestoreStateListItemBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/builders/ScanStateListItemsBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/MostPopularInsightsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/text/PercentFormatter.kt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-kmr/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sr/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/backup/download/BackupDownloadViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/restore/RestoreViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/restore/builders/RestoreStateListItemBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/builders/ScanStateListItemsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostDayViewsMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/MostPopularInsightsUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtilsTest.kt
  fastlane/resources/values/strings.xml
Labels: [Type] Bug, Localization

#17216 Do not merge - Only here to trigger CI on PR - https://github.com/wordpress-mobile/WordPress-Android/pull/17187
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModel.kt
Labels: Quick Start

#17169 Fix dark mode issue on countries card
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/MapViewHolder.kt
  WordPress/src/main/res/layout/stats_block_web_view_item.xml
Labels: [Type] Bug, Stats, Dark Mode

#17203 [Jetpack Focus] Revamp Landing Screen
  RELEASE-NOTES.txt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/LoginPrologueRevampedFragment.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/ColumnWithFrostedGlassBackground.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/JetpackLogo.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/LoopingText.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/LoopingTextWithBackground.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/PrimaryButton.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/SecondaryButton.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/TopLinearGradient.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/compose/components/AutoScrollingLazyColumn.kt
  WordPress/src/jetpack/res/drawable-hdpi/bg_jetpack_login_splash.png
  WordPress/src/jetpack/res/drawable-mdpi/bg_jetpack_login_splash.png
  WordPress/src/jetpack/res/drawable-xhdpi/bg_jetpack_login_splash.png
  WordPress/src/jetpack/res/drawable/bg_jetpack_login_splash_top_gradient.xml
  WordPress/src/jetpack/res/values-night/colors.xml
  WordPress/src/jetpack/res/values/colors.xml
  WordPress/src/jetpack/res/values/strings.xml
  WordPress/src/jetpack/res/values/texts_login_prologue_jetpack_features.xml
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/compose/unit/Margin.kt
  WordPress/src/main/java/org/wordpress/android/util/extensions/NumberExtensions.kt
  WordPress/src/main/res/values-night/colors.xml
  WordPress/src/main/res/values/colors.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/wordpress/java/org.wordpress.android.ui.accounts.login/LoginPrologueFragment.kt
  WordPress/src/wordpress/java/org.wordpress.android.ui.accounts.login/LoginPrologueViewModel.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/LoginPrologueFragment.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/LoginPrologueRevampedFragment.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/LoginPrologueViewModel.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/compose/components/PrimaryButton.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/compose/components/SecondaryButton.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/compose/components/Tagline.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/compose/theme/Fonts.kt
  WordPress/src/wordpress/res/drawable-mdpi/brush_stroke.png
  WordPress/src/wordpress/res/drawable-night-mdpi/brush_stroke.png
  WordPress/src/wordpress/res/drawable-night-xhdpi/brush_stroke.png
  WordPress/src/wordpress/res/drawable-night-xxxhdpi/brush_stroke.png
  WordPress/src/wordpress/res/drawable-xhdpi/brush_stroke.png
  WordPress/src/wordpress/res/drawable-xxxhdpi/brush_stroke.png
  WordPress/src/wordpress/res/drawable/ic_wordpress_gridicon.xml
  WordPress/src/wordpress/res/font/eb_garamond.ttf
Labels: Jetpack Focus

#17078 Feature Request: Support "Enter" key for Excerpt editing in Post settings #16479
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostSettingsInputDialogFragment.java
  WordPress/src/main/res/layout/post_settings_input_dialog.xml
Labels: [Type] Enhancement, Post Settings

#17228 Fix RTL rendering on Reader Post detail
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java
Labels: [Type] Bug, Reader

#17207 [Jetpack Focus] Revamp Landing Screen - Sensor animation
  RELEASE-NOTES.txt
  WordPress/build.gradle
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/LoginPrologueRevampedFragment.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/LoginPrologueRevampedViewModel.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/ColumnWithFrostedGlassBackground.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/LoopingText.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/RepeatingColumn.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/compose/components/AutoScrollingLazyColumn.kt
Labels: Jetpack Focus

#17226 Integrate gutenberg-mobile release 1.83.0
  build.gradle
Labels: gutenberg-mobile

#17225 [Jetpack Focus]: Split feature announcements "Whats new" by app
  WordPress/src/main/java/org/wordpress/android/ui/whatsnew/FeatureAnnouncementProvider.kt
  build.gradle
Labels: [Type] Task, What's New, Jetpack Focus
