Repository wordpress-mobile/WordPress-Android, pull requests merged in 2022-04, with the labels that each got.

#16214 Issue/16201 disable comment user data editing for registered users
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/unified/CommentEssentials.kt
  WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentsEditViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/comments/utils/CommentsTestUtils.kt
  WordPress/src/test/java/org/wordpress/android/ui/comments/viewmodels/UnifiedCommentsEditViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/util/UnifiedCommentLevelerTest.kt
  build.gradle
Labels: [Type] Enhancement, Comments, [Status] Needs Code Review

#16213 My Site Dashboard: Tabs - Track events with tab source
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabFragment.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: [Type] Task, My Site Dashboard

#16217 Fixes: Title is not shown on My Site Dashboard with no sites & Tab height
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/res/layout/my_site_fragment.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: [Status] Needs Code Review, [Type] Task, [Status] Needs Design Review, My Site Dashboard

#16229 Fixes: Scrolling and focusing Quick Start position
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
Labels: [Type] Bug, My Site Dashboard

#16230 My Site Dashboard: Feature Announcement
  WordPress/src/main/res/layout/feature_announcement_dialog_fragment.xml
Labels: My Site Dashboard

#16231 [Tooling] Add WordPressEditor lib to the list of `strings.xml` files to merge during code-freeze
  fastlane/Fastfile
Labels: Tooling

#16216 Implement Blogging Prompts introduction dialog UI
  WordPress/src/main/java/org/wordpress/android/models/usecases/GetBloggingPromptUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingUiStateMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/featureintroduction/FeatureIntroductionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/util/extensions/ViewExtensions.kt
  WordPress/src/main/res/color/lightbulb_orange_background.xml
  WordPress/src/main/res/drawable/bg_rectangle_black_60_radius_2dp.xml
  WordPress/src/main/res/drawable/ic_outline_lightbulb_orange_gradient_40dp.xml
  WordPress/src/main/res/layout/blogging_prompts_omboarding_dialog_content_view.xml
  WordPress/src/main/res/layout/blogging_prompts_onboarding_dialog_fragment.xml
  WordPress/src/main/res/layout/feature_introduction_dialog_fragment.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingUiStateMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingViewModelTest.kt
Labels: [Type] Enhancement, Blogging Prompts v1

#16238 Fix: Quick Start Prompt not shown on API 25
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
Labels: My Site Dashboard

#16232 [Site Intent Question] Replaces continue button with a custom list item
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SiteCreationTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsViewModel.kt
  WordPress/src/main/res/layout/site_creation_intents_fragment.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsViewModelTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Task, Site Creation

#16228 [Site Intent Question] Turns feature flag ON
  WordPress/build.gradle
Labels: [Type] Task, Site Creation

#16243 [Site Intent Question] Adds release note
  RELEASE-NOTES.txt
Labels: [Type] Task, Site Creation

#16170 Update espresso and AndroidX test dependencies
  WordPress/build.gradle
  WordPress/src/androidTest/java/org/wordpress/android/e2e/BlockEditorTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/EditorTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/LoginTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/ReaderTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/SignUpTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/flows/LoginFlow.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/flows/SignupFlow.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/ReaderViewPage.java
  WordPress/src/androidTest/java/org/wordpress/android/support/BaseTest.java
  WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/JPScreenshotTest.java
  WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java
  WordPress/src/test/java/org/wordpress/android/RobolectricSetupTest.java
  WordPress/src/test/java/org/wordpress/android/ui/posts/reactnative/ReactNativeRequestHandlerTest.kt
  build.gradle
  libs/editor/example/build.gradle
  libs/image-editor/ImageEditor/build.gradle
Labels: [Type] Enhancement

#16242 [Site Intent Question] Search screen improvements
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsViewModel.kt
Labels: [Type] Task, Site Creation

#16223 [Tooling] Fastfile cleanup - phase 1
  fastlane/Fastfile
  fastlane/completion.zsh
  fastlane/lanes/build.rb
  fastlane/lanes/localization.rb
  fastlane/lanes/release.rb
  fastlane/lanes/screenshots.rb
Labels: Tooling

#16247 [Tooling] Fix Fastlane crash after refactor from #16223
  fastlane/lanes/release.rb
Labels: Tooling

#16251 Merge release/19.6 (code freeze)
  RELEASE-NOTES.txt
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/release_notes.txt
  WordPress/src/main/res/values/strings.xml
  build.gradle
  fastlane/resources/values/strings.xml
  libs/editor/WordPressEditor/src/main/res/values/strings.xml
  version.properties
Labels: Releases

#16252 My Site Dashboard: Initial Screen App Setting
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/res/values/key_strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/app_settings.xml
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Task, [Status] Not Ready for Merge, My Site Dashboard

#16260 More logs to the dependency tree script
  tools/dependency-tree-diff/dependency-tree-diff.sh
Labels: Tooling

#16254 My Site Dashboard: Tabs - Allow tabs + Show dashboard cards in Jetpack app
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteSourceManager.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteSourceManagerTest.kt
Labels: My Site Dashboard

#16262 [DO NOT MERGE] Trigger CI for PR #16239
  WordPress/src/main/java/org/wordpress/android/ui/LayoutBehaviors.kt
  WordPress/src/main/java/org/wordpress/android/ui/WPTooltipView.kt
  WordPress/src/main/res/layout/post_list_activity.xml
Labels: [Status] Not Ready for Merge

#16250 My Site Dashboard - Implement quick link ribbons
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapterDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItemBuilderParams.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItemDecoration.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/CardsBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quicklinkribbons/QuickLinkRibbonBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quicklinkribbons/QuickLinkRibbonItemAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quicklinkribbons/QuickLinkRibbonItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quicklinkribbons/QuickLinkRibbonViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepository.kt
  WordPress/src/main/res/layout/quick_link_ribbon_item.xml
  WordPress/src/main/res/layout/quick_link_ribbon_list.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/CardsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/quicklinkribbons/QuickLinkRibbonBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepositoryTest.kt
Labels: [Status] Needs Design Review, 1, Quick Start, My Site Dashboard

#16261 [DO NOT MERGE] Add Gradle Enterprise to Project
  build.gradle
  settings.gradle
Labels: Tooling

#16258 Stats revamp v2 views and visitors card
  WordPress/src/main/java/org/wordpress/android/ui/stats/StatsViewType.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/BlockDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewAllViewModelFactory.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/management/InsightsManagementMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ViewsAndVisitorsMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ViewsAndVisitorsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ChipsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/TitleWithMoreViewHolder.kt
  WordPress/src/main/res/layout/stats_block_title_with_more_item.xml
  WordPress/src/main/res/layout/stats_block_two_chips_item.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/management/InsightsManagementMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ViewsAndVisitorsMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ViewsAndVisitorsUseCaseTest.kt
  build.gradle
Labels: [Type] Task, Stats Revamp

#16259 Display site name screen in site creation flow
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ExperimentModule.kt
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVM.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationStep.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/sitename/SiteCreationSiteNameFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/sitename/SiteCreationSiteNameViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/sitename/SiteNameScreenListener.kt
  WordPress/src/main/java/org/wordpress/android/util/config/SiteNameFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/experiments/SiteNameABExperiment.kt
  WordPress/src/main/res/layout/site_creation_site_name_fragment.xml
  WordPress/src/main/res/layout/site_creation_site_name_header.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/util/wizard/WizardManagerTest.kt
Labels: [Type] Task, Site Creation

#16266 Merge release/19.6 - Release Notes
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: Releases

#16271 My Site Dashboard: Tabs - Refactor default tab to use initial screen
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteDefaultTabExperiment.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteDefaultTabExperimentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: [Type] Task, My Site Dashboard

#16269 My Site Dashboard: Tabs - Add release notes
  RELEASE-NOTES.txt
Labels: [Type] Task, My Site Dashboard

#16268 My Site Dashboard: Display small nudge on Today's Stats when there's no views
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItemBuilderParams.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/todaysstats/TodaysStatsCardBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/todaysstats/TodaysStatsCardViewHolder.kt
  WordPress/src/main/res/layout/my_site_todays_stats_card.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/CardsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/dashboard/todaysstats/TodaysStatsCardBuilderTest.kt
Labels: [Type] Task, My Site Dashboard

#16276 My Site Dashboard: Add tracking for Today's Stats nudge
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SiteNavigationAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/todaysstats/TodaysStatsCardViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabFragment.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsTrackerTest.kt
Labels: My Site Dashboard

#16275 Integrate gutenberg-mobile release 1.73.1
  build.gradle
Labels: gutenberg-mobile

#16236 Wire "Remind Me" button to open site picker or reminders flow
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsReminderSchedulerListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingReminderBottomSheetFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersAnalyticsTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/featureintroduction/FeatureIntroductionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/res/color/lightbulb_orange_background.xml
  WordPress/src/main/res/drawable/ic_outline_lightbulb_orange_gradient_40dp.xml
  WordPress/src/main/res/layout/blogging_prompts_onboarding_dialog_content_view.xml
  WordPress/src/main/res/layout/feature_introduction_dialog_fragment.xml
  WordPress/src/test/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersViewModelTest.kt
Labels: [Type] Enhancement, Blogging Prompts v1

#16273 Integrate AB Experiment with feature config
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationStep.kt
  WordPress/src/main/java/org/wordpress/android/util/config/SiteNameFeatureConfig.kt
Labels: [Type] Task, Site Creation

#16267 Quickstart focus point change to quick link ribbon
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItemBuilderParams.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickactions/QuickActionsCardBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quicklinkribbons/QuickLinkRibbonBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quicklinkribbons/QuickLinkRibbonItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quicklinkribbons/QuickLinkRibbonViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepository.kt
  WordPress/src/main/res/layout/quick_link_ribbon_item.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/CardsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/quickactions/QuickActionsCardBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/quicklinkribbons/QuickLinkRibbonBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepositoryTest.kt
Labels: Quick Start, My Site Dashboard

#16277 My Site Dashboard: Tabs - Show Dynamic Cards on either tab
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: My Site Dashboard

#16284 Add track events for quick link ribbon
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Quick Start, My Site Dashboard

#16285 Merge release/19.6 (rc-2)
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-az/strings.xml
  WordPress/src/main/res/values-bg/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-cy/strings.xml
  WordPress/src/main/res/values-da/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-eu/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gd/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-hi/strings.xml
  WordPress/src/main/res/values-hr/strings.xml
  WordPress/src/main/res/values-hu/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-is/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-kmr/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-mk/strings.xml
  WordPress/src/main/res/values-ms/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sr/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-th/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-uz/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  WordPress/src/main/res/values/strings.xml
  build.gradle
  config/lint.xml
  fastlane/resources/values/strings.xml
  version.properties
Labels: Releases

#16279 [Tooling] Get rid of python script to merge GutenbergMobile strings
  WordPress/src/main/res/values/strings.xml
  fastlane/lanes/localization.rb
  tools/merge_strings_xml.py
Labels: Tooling

#16282 [Site Intent Question] String corrections and input sanitisation
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsViewModelTest.kt
Labels: [Type] Bug, Site Creation

#16293 [Tooling] Ignore `values-night/colors_aztec.xml` linter errors properly this time
  WordPress/src/main/res/values-night/colors_aztec.xml
  config/lint.xml
Labels: Tooling

#16264 Issue/16150 blogging prompt list of respondents
  WordPress/src/main/java/org/wordpress/android/models/bloggingprompts/BloggingPrompt.kt
  WordPress/src/main/java/org/wordpress/android/models/bloggingprompts/BloggingPromptRespondent.kt
  WordPress/src/main/java/org/wordpress/android/ui/avatars/AvatarItemDecorator.kt
  WordPress/src/main/java/org/wordpress/android/ui/avatars/AvatarViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/avatars/TrailingLabelViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/avatars/TrainOfAvatarsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/avatars/TrainOfAvatarsAdapterDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/avatars/TrainOfAvatarsItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/avatars/TrainOfAvatarsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingUiStateMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/engagement/EngagementUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/bloggingprompts/BloggingPromptCardBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/bloggingprompts/BloggingPromptCardViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostLikersAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/TrainOfFacesItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewholders/BloggingLikersTextViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewholders/PostLikerViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewholders/TrainOfFacesViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/UiHelpers.kt
  WordPress/src/main/java/org/wordpress/android/ui/utils/UiString.kt
  WordPress/src/main/res/layout/avatar_item.xml
  WordPress/src/main/res/layout/my_site_blogging_promp_card.xml
  WordPress/src/main/res/layout/reader_post_likers_faces_list.xml
  WordPress/src/main/res/layout/trailing_label_item.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingUiStateMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/dashboard/bloggingprompt/BloggingPromptCardBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt
Labels: [Type] Enhancement, [Status] Needs Code Review, Blogging Prompts v1

#16292 My Site Dashboard - Tabs - Enable Feature
  WordPress/src/main/java/org/wordpress/android/util/config/MySiteDashboardTabsFeatureConfig.kt
Labels: [Type] Task, My Site Dashboard

#16278 [Site Name] Use site name value and skip domain name
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/services/SiteCreationServiceData.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/services/SiteCreationServiceManager.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/usecases/CreateSiteUseCase.kt
  WordPress/src/main/res/layout/site_creation_site_name_fragment.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/previews/CreateSiteUseCaseTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/services/SiteCreationServiceManagerTest.kt
  build.gradle
Labels: [Type] Task, Site Creation, [Status] Not Ready for Merge

#16299 Update comments for build variants
  WordPress/build.gradle
Labels: Documentation

#16303 Display stats insights tab when clicking on Today's stats card #16302
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SiteNavigationAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabFragment.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: My Site Dashboard

#16297 Change reported file format for detekt violations
  WordPress/build.gradle
Labels: Tooling

#16306 [Site Name] Removes Site Intent Question A/B test
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SiteCreationTracker.kt
  WordPress/src/main/java/org/wordpress/android/util/config/SiteIntentQuestionFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/experiments/SiteIntentQuestionABExperiment.kt
  WordPress/src/test/java/org/wordpress/android/util/experiments/SiteIntentQuestionABExperimentTest.kt
Labels: [Type] Task, Site Creation

#16315 [Site Name] Adapt the Site name screen layout for landscape orientation
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/sitename/SiteCreationSiteNameFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsFragment.kt
  WordPress/src/main/java/org/wordpress/android/util/DisplayUtilsWrapper.kt
  WordPress/src/main/res/layout-land/site_creation_header_v2.xml
  WordPress/src/main/res/layout/site_creation_header_v2.xml
  WordPress/src/main/res/layout/site_creation_intents_fragment.xml
  WordPress/src/main/res/layout/site_creation_intents_header.xml
  WordPress/src/main/res/layout/site_creation_site_name_fragment.xml
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Task, Site Creation

#16286 [Gutenberg] Add Quote Block V2 flag
  build.gradle
Labels: gutenberg-mobile

#16317 My Site Dashboard: Today's Stats - Update nudge text
  WordPress/src/main/res/values/strings.xml
Labels: My Site Dashboard

#16289 Blogging prompts create local notification trigger introduction dialog
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/push/NotificationType.kt
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/SystemNotificationsTracker.kt
  WordPress/src/main/java/org/wordpress/android/util/config/BloggingPromptsNotificationConfig.kt
  WordPress/src/main/java/org/wordpress/android/workers/LocalNotificationHandlerFactory.kt
  WordPress/src/main/java/org/wordpress/android/workers/WordPressWorkersFactory.kt
  WordPress/src/main/java/org/wordpress/android/workers/notification/bloggingprompts/BloggingPromptsOnboardingNotificationHandler.kt
  WordPress/src/main/java/org/wordpress/android/workers/notification/bloggingprompts/BloggingPromptsOnboardingNotificationScheduler.kt
  WordPress/src/main/java/org/wordpress/android/workers/notification/createsite/CreateSiteNotificationHandler.kt
  WordPress/src/main/java/org/wordpress/android/workers/notification/createsite/CreateSiteNotificationScheduler.kt
  WordPress/src/main/java/org/wordpress/android/workers/notification/local/LocalNotification.kt
  WordPress/src/main/java/org/wordpress/android/workers/notification/local/LocalNotificationHandlerFactory.kt
  WordPress/src/main/java/org/wordpress/android/workers/notification/local/LocalNotificationScheduler.kt
  WordPress/src/main/java/org/wordpress/android/workers/notification/local/LocalNotificationWorker.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/notifications/SystemNotificationsTrackerTest.kt
  WordPress/src/test/java/org/wordpress/android/workers/notification/bloggingprompts/BloggingPromptsOnboardingNotificationHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/workers/notification/bloggingprompts/BloggingPromptsOnboardingNotificationSchedulerTest.kt
  WordPress/src/test/java/org/wordpress/android/workers/notification/createsite/CreateSiteNotificationHandlerTest.kt
  WordPress/src/test/java/org/wordpress/android/workers/notification/createsite/CreateSiteNotificationSchedulerTest.kt
  WordPress/src/test/java/org/wordpress/android/workers/notification/local/LocalNotificationHandlerFactoryTest.kt
Labels: [Type] Enhancement, Blogging Prompts v1

#16314 Fix notification detail crash for GB File block and similar objects
  RELEASE-NOTES.txt
  build.gradle
Labels: Notifications, [Type] Crash

#16319 Merge release/19.6 (19.6-rc-3)
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsViewModel.kt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-az/strings.xml
  WordPress/src/main/res/values-bg/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-cy/strings.xml
  WordPress/src/main/res/values-da/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-el/strings.xml
  WordPress/src/main/res/values-en-rAU/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rMX/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-eu/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gd/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-hi/strings.xml
  WordPress/src/main/res/values-hr/strings.xml
  WordPress/src/main/res/values-hu/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-is/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-kmr/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-mk/strings.xml
  WordPress/src/main/res/values-ms/strings.xml
  WordPress/src/main/res/values-nb/strings.xml
  WordPress/src/main/res/values-night/colors_aztec.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sk/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sr/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-th/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-uz/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsViewModelTest.kt
  config/lint.xml
  fastlane/resources/values/strings.xml
  version.properties
Labels: Releases

#16324 [Site Name] Corrects the API parameters in the site creation call
  build.gradle
Labels: [Type] Bug, Site Creation

#16307 Changes: The tab title to Menu from Site Menu
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteDefaultTabExperiment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabType.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteDefaultTabExperimentTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: My Site Dashboard

#16326 Integrate gutenberg-mobile release 1.74.0
  RELEASE-NOTES.txt
  build.gradle
Labels: gutenberg-mobile

#16325 [Site name] Complete the site title quickstart task when site name is entered
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginEpilogueActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/QuickStartUtilsWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVMTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModelTest.kt
Labels: [Type] Task, Site Creation

#16328 [Site Name] Display the site intent in the header title if available
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/sitename/SiteCreationSiteNameFragment.kt
  WordPress/src/main/res/layout/site_creation_header_v2.xml
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Task, Site Creation

#16336 [Site Name] Turn the feature flag ON by default
  RELEASE-NOTES.txt
  WordPress/build.gradle
Labels: [Type] Task, Site Creation

#16335 Site name tracks events continued...
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVM.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SiteCreationTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/sitename/SiteCreationSiteNameViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVMTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/sitename/SiteCreationSiteNameViewModelTest.kt
Labels: [Type] Task, Site Creation

#16338 My Site Dashboard: Adjust QS focus points for Stats and Pages
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItemBuilderParams.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickactions/QuickActionsCardBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickactions/QuickActionsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quicklinkribbons/QuickLinkRibbonBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quicklinkribbons/QuickLinkRibbonItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quicklinkribbons/QuickLinkRibbonViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/items/SiteItemsBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/items/listitem/SiteListItemBuilder.kt
  WordPress/src/main/res/layout/quick_actions_card.xml
  WordPress/src/main/res/layout/quick_link_ribbon_item.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/CardsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/quickactions/QuickActionsCardBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/quicklinkribbons/QuickLinkRibbonBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepositoryTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/items/SiteItemsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/items/listitem/SiteListItemBuilderTest.kt
Labels: My Site Dashboard

#16340 My Site Dashboard - Hide the Quick Actions under Site menu for users to default tab variant
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/CardsBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteDefaultTabExperiment.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/CardsBuilderTest.kt
Labels: My Site Dashboard

#16330 [Site Name] Add tracks events
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVM.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SiteCreationTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/sitename/SiteCreationSiteNameViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVMTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/sitename/SiteCreationSiteNameViewModelTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Task, Site Creation

#16339 [Site Name] Removes the username parameter from the site creation call
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/usecases/CreateSiteUseCase.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/previews/CreateSiteUseCaseTest.kt
  build.gradle
Labels: [Type] Task, Site Creation

#16270 Update Aztec to 1.5.7
  build.gradle
  libs/editor/WordPressEditor/build.gradle
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/MediaToolbarAction.java
Labels: Aztec

#16342 My Site Dashboard: Hide tabs for self hosted sites
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/CardsBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabsAdapter.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/CardsBuilderTest.kt
Labels: My Site Dashboard

#15675 Drop jetifier
  .configure
  .configure-files/gradle.properties.enc
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaPreviewFragment.java
  aars/tenor-android-core-jetified.aar
  build.gradle
  gradle.properties-example
  libs/editor/WordPressEditor/build.gradle
Labels: Tech debt

#16358 Quick Start for Existing Users V2 - Add Feature Flag
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/util/config/QuickStartExistingUsersV2FeatureConfig.kt
Labels: Quick Start

#16363 [ExPlat] Only make assignment requests for authenticated users
  WordPress/src/main/java/org/wordpress/android/util/experiments/ExPlat.kt
  WordPress/src/test/java/org/wordpress/android/util/experiments/ExPlatTest.kt
Labels: [Type] Bug, ExPlat

#16360 [Site Name] Adjusts design picker buttons for treatment variation
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/DesignPreviewFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerFragment.kt
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Task, Site Creation

#16359 Issue/16334 link blogging reminders with prompts onboarding
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingUiStateMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingReminderBottomSheetFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/DaySelectionBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/featureintroduction/FeatureIntroductionDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/res/layout/blogging_reminders_prompt_switch.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingUiStateMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/bloggingreminders/DaySelectionBuilderTest.kt
Labels: [Type] Enhancement, Blogging Prompts v1

#16281 [Tooling] Remove release_notes.xml file now that changelog upload has been automated via supply
  fastlane/jetpack_metadata/android/release_notes.xml
  fastlane/lanes/localization.rb
  fastlane/metadata/android/release_notes.xml
Labels: Tooling

#16375 Refactor video duration check to simplify the nested ifs
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/AddLocalMediaToPostUseCase.kt
  WordPress/src/main/java/org/wordpress/android/util/MediaUtilsWrapper.kt
Labels: [Type] Enhancement, Tech debt

#16322 Enable larger video uploads for Jetpack customers with standalone VideoPress subs
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/AddLocalMediaToPostUseCase.kt
  WordPress/src/main/java/org/wordpress/android/util/MediaUtilsWrapper.kt
Labels: [Type] Bug, Media

#16372 Quick Start for Existing Users V2 - Changes to Existing Tasks - Reader (Part i)
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartTaskDetails.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModel.kt
  WordPress/src/main/res/layout/tab_custom_view.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/reader/ReaderPostListViewModelTest.kt
Labels: Quick Start

#16376 Merge release/19.7 Release Notes
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/DesignPreviewFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerFragment.kt
  WordPress/src/main/res/values/strings.xml
  fastlane/jetpack_metadata/android/release_notes.xml
  fastlane/lanes/localization.rb
  fastlane/metadata/android/release_notes.xml
  fastlane/resources/values/strings.xml
Labels: Releases

#16346 Adding Hilt
  WordPress/build.gradle
  WordPress/src/androidTest/java/org/wordpress/android/InitializationRule.kt
  WordPress/src/androidTest/java/org/wordpress/android/UserAgentTest.java
  WordPress/src/androidTest/java/org/wordpress/android/WordPressTest.kt
  WordPress/src/androidTest/java/org/wordpress/android/WordPressTestRunner.kt
  WordPress/src/androidTest/java/org/wordpress/android/e2e/BlockEditorTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/ContactUsTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/EditorTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/LoginTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/ReaderTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/SignUpTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/StatsTests.java
  WordPress/src/androidTest/java/org/wordpress/android/modules/AppComponentTest.kt
  WordPress/src/androidTest/java/org/wordpress/android/modules/DummyInterceptorModule.kt
  WordPress/src/androidTest/java/org/wordpress/android/modules/InterceptorModuleTest.kt
  WordPress/src/androidTest/java/org/wordpress/android/modules/TrackerTestModule.kt
  WordPress/src/androidTest/java/org/wordpress/android/support/BaseTest.java
  WordPress/src/debug/java/org/wordpress/android/WellSqlInitializer.kt
  WordPress/src/debug/java/org/wordpress/android/WordPressDebug.java
  WordPress/src/debug/java/org/wordpress/android/modules/AppComponentDebug.java
  WordPress/src/debug/java/org/wordpress/android/modules/InterceptorModule.java
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/AppInitializer.kt
  WordPress/src/main/java/org/wordpress/android/WordPress.kt
  WordPress/src/main/java/org/wordpress/android/WordPressApp.java
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/AppConfigModule.java
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/modules/CrashLoggingModule.kt
  WordPress/src/main/java/org/wordpress/android/modules/ExperimentModule.kt
  WordPress/src/main/java/org/wordpress/android/modules/FluxCModule.kt
  WordPress/src/main/java/org/wordpress/android/modules/LegacyModule.java
  WordPress/src/main/java/org/wordpress/android/modules/LoginAnalyticsModule.java
  WordPress/src/main/java/org/wordpress/android/modules/LoginModule.kt
  WordPress/src/main/java/org/wordpress/android/modules/SupportModule.kt
  WordPress/src/main/java/org/wordpress/android/modules/ThreadModule.kt
  WordPress/src/main/java/org/wordpress/android/modules/TrackerModule.kt
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/suggestion/SuggestionSourceSubcomponent.kt
  WordPress/src/release/AndroidManifest.xml
  WordPress/src/release/java/org/wordpress/android/WordPressRelease.kt
  build.gradle
Labels: [Type] Enhancement, [Status] Needs Code Review

#16379 App Data Coverage: add more tracking to the Change Username flow
  WordPress/src/main/java/org/wordpress/android/ui/FullScreenDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/BaseUsernameChangerFullScreenDialogFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SettingsUsernameChangerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/UsernameChangerFullScreenDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AccountSettingsFragment.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Task, Tracks

#16366 Implement answer prompt local notification
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/workers/WordPressWorkersFactory.kt
  WordPress/src/main/java/org/wordpress/android/workers/reminder/PromptReminderNotifier.kt
  WordPress/src/main/java/org/wordpress/android/workers/reminder/ReminderNotification.kt
  WordPress/src/main/java/org/wordpress/android/workers/reminder/ReminderWorker.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/workers/reminder/PromptReminderNotifierTest.kt
Labels: [Type] Enhancement, Blogging Prompts v1

#16377 Merge Gutenberg 1.74.0 after branch
  build.gradle
  libs/editor/WordPressEditor/build.gradle
  libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/MediaToolbarAction.java
Labels: gutenberg-mobile

#16296 Allow previewing unsaved edits of draft posts on self-hosted sites
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelper.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/RemotePreviewLogicHelperTest.kt
Labels: Previews

#16332 Use external browser for all atomic previews to avoid caching issue
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
Labels: Previews

#16361 Quick Start for Existing Users V2 - Changes to existing task - Stats
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItemBuilderParams.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/CardsBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quicklinksribbon/QuickLinkRibbonBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quicklinksribbon/QuickLinkRibbonItemAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quicklinksribbon/QuickLinkRibbonItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quicklinksribbon/QuickLinkRibbonViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/items/SiteItemsBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartNoticeDetails.java
  WordPress/src/main/res/layout/quick_link_ribbon_item.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/CardsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/quicklinksribbon/QuickLinkRibbonBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepositoryTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/items/SiteItemsBuilderTest.kt
Labels: Quick Start

#16143 Hilt migration
  WordPress/build.gradle
  WordPress/src/androidTest/java/org/wordpress/android/InitializationRule.kt
  WordPress/src/androidTest/java/org/wordpress/android/UserAgentTest.java
  WordPress/src/androidTest/java/org/wordpress/android/WordPressTest.kt
  WordPress/src/androidTest/java/org/wordpress/android/WordPressTestRunner.kt
  WordPress/src/androidTest/java/org/wordpress/android/e2e/BlockEditorTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/ContactUsTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/EditorTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/LoginTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/ReaderTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/SignUpTests.java
  WordPress/src/androidTest/java/org/wordpress/android/e2e/StatsTests.java
  WordPress/src/androidTest/java/org/wordpress/android/modules/AppComponentTest.kt
  WordPress/src/androidTest/java/org/wordpress/android/modules/DummyInterceptorModule.kt
  WordPress/src/androidTest/java/org/wordpress/android/modules/InterceptorModuleTest.kt
  WordPress/src/androidTest/java/org/wordpress/android/modules/TrackerTestModule.kt
  WordPress/src/androidTest/java/org/wordpress/android/networking/WPNetworkImageViewTest.java
  WordPress/src/androidTest/java/org/wordpress/android/support/BaseTest.java
  WordPress/src/debug/java/org/wordpress/android/WellSqlInitializer.kt
  WordPress/src/debug/java/org/wordpress/android/WordPressDebug.java
  WordPress/src/debug/java/org/wordpress/android/modules/AppComponentDebug.java
  WordPress/src/debug/java/org/wordpress/android/modules/InterceptorModule.java
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/AppInitializer.kt
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/WordPress.kt
  WordPress/src/main/java/org/wordpress/android/WordPressApp.java
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/AppConfigModule.java
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/modules/CrashLoggingModule.kt
  WordPress/src/main/java/org/wordpress/android/modules/ExperimentModule.kt
  WordPress/src/main/java/org/wordpress/android/modules/FluxCModule.kt
  WordPress/src/main/java/org/wordpress/android/modules/LegacyModule.java
  WordPress/src/main/java/org/wordpress/android/modules/LoginAnalyticsModule.java
  WordPress/src/main/java/org/wordpress/android/modules/LoginModule.kt
  WordPress/src/main/java/org/wordpress/android/modules/SupportModule.kt
  WordPress/src/main/java/org/wordpress/android/modules/ThreadModule.kt
  WordPress/src/main/java/org/wordpress/android/modules/TrackerModule.kt
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderPostActions.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderVideoUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/stories/StoryComposerActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/suggestion/SuggestionSourceSubcomponent.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java
  WordPress/src/release/AndroidManifest.xml
  WordPress/src/release/java/org/wordpress/android/WellSqlInitializer.kt
  WordPress/src/release/java/org/wordpress/android/WordPressRelease.kt
  build.gradle
Labels: [Type] Enhancement, [Status] In Progress

#16388 App Data Coverage: Add site dialog and create site flow accessed events
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginEpilogueActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/PostSignupInterstitialActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/deeplinks/DeepLinkNavigator.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SiteNavigationAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVM.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SiteCreationSource.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SiteCreationTracker.kt
  WordPress/src/main/java/org/wordpress/android/workers/notification/createsite/CreateSiteNotificationHandler.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVMTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Task, Tracks

#16385 Merge release/19.7 — Beta 19.7-rc-2
  Gemfile.lock
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationActivity.kt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  version.properties
Labels: Releases

#16280 [Tooling] Identify the source library when merging strings and add tools:ignore="UnusedResources" when appropriate
  Gemfile.lock
  fastlane/Pluginfile
  fastlane/lanes/localization.rb
Labels: Tooling, [Status] Not Ready for Merge

#16400 Jetpack Scan: add VaultPress message and option to open the dashboard
  WordPress/src/main/java/org/wordpress/android/Constants.java
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/ScanFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/ScanNavigationEvents.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/ScanViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpack/scan/usecases/FetchScanStateUseCase.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/ScanViewModelTest.kt
  build.gradle
Labels: Jetpack App

#16373 Quick Start for Existing Users V2-Changes to existing task-Preview Site
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/siteinfo/SiteInfoHeaderCardBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/items/SiteItemsBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartMySitePrompts.kt
  WordPress/src/main/res/layout/my_site_info_header_card.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteCardAndItemTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/siteinfo/SiteInfoHeaderCardBuilderTest.kt
Labels: Quick Start

#16396 App Data Coverage: Add site picker track events
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Task, Tracks

#16401 Integrate gutenberg-mobile release 1.74.1
  build.gradle
Labels: gutenberg-mobile

#16406 Merge release/19.7 (19.7-rc-3)
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  version.properties
Labels: Releases

#16404 Quick win: Remove custom `android_update_metadata_source` action
  fastlane/actions/android_update_metadata_source.rb
  fastlane/lanes/localization.rb
Labels: Localization, Tooling

#16327 Stats revamp v2 views and visitors graph
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/BlockDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/LineChartMarkerView.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BlockListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ViewsAndVisitorsMapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ViewsAndVisitorsUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ChartLegendsBlueViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ChartLegendsPurpleViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ChipsViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/LineChartViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/TextViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/TitleWithMoreViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/ValuesViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/LineChartAccessibilityHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/LineChartLabelFormatter.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtils.kt
  WordPress/src/main/res/drawable/bg_chart_marker_view.xml
  WordPress/src/main/res/drawable/bg_rectangle_stats_line_chart_blue_gradient.xml
  WordPress/src/main/res/drawable/bg_rectangle_stats_line_chart_purple_gradient.xml
  WordPress/src/main/res/drawable/bg_stats_legend_start.xml
  WordPress/src/main/res/layout/stats_block_legends_blue_item.xml
  WordPress/src/main/res/layout/stats_block_legends_purple_item.xml
  WordPress/src/main/res/layout/stats_block_line_chart_item.xml
  WordPress/src/main/res/layout/stats_block_title_with_more_item.xml
  WordPress/src/main/res/layout/stats_block_two_chips_item.xml
  WordPress/src/main/res/layout/stats_block_values_item.xml
  WordPress/src/main/res/layout/stats_line_chart_marker.xml
  WordPress/src/main/res/values-night/colors_stats.xml
  WordPress/src/main/res/values-zh-rCN/colors_stats.xml
  WordPress/src/main/res/values/colors_stats.xml
  WordPress/src/main/res/values/stats_styles.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ViewsAndVisitorsMapperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/usecases/ViewsAndVisitorsUseCaseTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Task, Stats Revamp

#16382 Enable domains purchase on Jetpack Mobile app
  WordPress/src/main/java/org/wordpress/android/ui/mysite/items/listitem/SiteListItemBuilder.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/items/SiteItemFixtures.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/items/SiteItemsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/items/listitem/SiteListItemBuilderTest.kt
Labels: [Type] Task, [Status] Not Ready for Merge, Jetpack Mobile, Domains

#16416 Revert "Enable domains purchase on Jetpack Mobile app "
  WordPress/src/main/java/org/wordpress/android/ui/mysite/items/listitem/SiteListItemBuilder.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/items/SiteItemFixtures.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/items/SiteItemsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/items/listitem/SiteListItemBuilderTest.kt
Labels: Jetpack App

#16418 Fix a unit test in QuickStartRepositoryTest
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepositoryTest.kt
Labels: [Type] Bug, [Status] Needs Code Review, Testing

#16411 App Data Coverage: add more tracking for page list
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt
Labels: Pages List, [Type] Task, Tracks

#16420 Remove jitpack repository from root level repositories
  build.gradle
  libs/image-editor/ImageEditor/build.gradle
Labels: Tooling

#16419 [Site design revamp] Remove unused string resource hpp_subtitle
  WordPress/src/main/res/values/strings.xml
Labels: Site Creation, Part of a WIP Feature

#16432 Gradle Enterprise: Obfuscate personal data
  settings.gradle
Labels: Tooling

#16425 MSD - Tabs - Fix spinner keeps showing occasionally
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabFragment.kt
Labels: My Site Dashboard

#16421 Fixes self-hosted upload failure when the filename is non-latin
  RELEASE-NOTES.txt
  build.gradle
Labels: [Type] Bug, Media, i18n

#16426 Fixes Media Picker video selection Accessibility issue
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaThumbnailViewUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/PhotoThumbnailViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/VideoThumbnailViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoThumbnailViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/ThumbnailViewUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/VideoThumbnailViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stockmedia/StockMediaPickerActivity.java
  WordPress/src/main/java/org/wordpress/android/util/PhotoPickerUtils.java
  WordPress/src/main/res/layout/media_picker_thumbnail_item.xml
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Bug, Accessibility, TalkBack, Media Picker

#16433 Quick Start - Track card tapped
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsTracker.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsTrackerTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Quick Start, My Site Dashboard

#16434 issue/16402-my-site-dashboard-show-next-steps-card-at-the-top
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapterDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabFragment.kt
Labels: Quick Start

#16415 [Site design revamp] Remove bottom toolbar
  WordPress/src/main/java/org/wordpress/android/ui/layoutpicker/LayoutPickerViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerViewModel.kt
  WordPress/src/main/res/layout-sw600dp/home_page_picker_bottom_toolbar.xml
  WordPress/src/main/res/layout/home_page_picker_bottom_toolbar.xml
  WordPress/src/main/res/layout/home_page_picker_fragment.xml
Labels: Site Creation, Part of a WIP Feature

#16429 App Data Coverage: Add more tracking for sharing management
  WordPress/src/main/java/org/wordpress/android/ui/publicize/PublicizeButtonPrefsFragment.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Sharing, [Type] Task, [Status] Not Ready for Merge, Tracks

#16430 App Data Coverage: Add more tracking for people management
  WordPress/src/main/java/org/wordpress/android/ui/people/PeopleInviteFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/people/PeopleListFragment.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Task, People Management, Tracks

#16435 MSD - Auto select initial tab without restarting the app
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
Labels: Quick Start, My Site Dashboard

#16387 [Blogging Prompts v1] Implement dismiss action for local notifications
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/DismissNotificationReceiver.kt
  WordPress/src/main/java/org/wordpress/android/workers/notification/bloggingprompts/BloggingPromptsOnboardingNotificationHandler.kt
  WordPress/src/main/java/org/wordpress/android/workers/notification/bloggingprompts/BloggingPromptsOnboardingNotificationScheduler.kt
  WordPress/src/main/java/org/wordpress/android/workers/notification/createsite/CreateSiteNotificationHandler.kt
  WordPress/src/main/java/org/wordpress/android/workers/notification/createsite/CreateSiteNotificationScheduler.kt
  WordPress/src/main/java/org/wordpress/android/workers/notification/local/LocalNotification.kt
  WordPress/src/main/java/org/wordpress/android/workers/notification/local/LocalNotificationHandlerFactory.kt
  WordPress/src/main/java/org/wordpress/android/workers/notification/local/LocalNotificationWorker.kt
  WordPress/src/main/java/org/wordpress/android/workers/reminder/PromptReminderNotifier.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/workers/notification/bloggingprompts/BloggingPromptsOnboardingNotificationSchedulerTest.kt
Labels: [Type] Enhancement, Blogging Prompts v1

#16398 Migrate remaining InstrumentationTestCases to hilt
  WordPress/src/androidTest/java/org/wordpress/android/networking/AuthenticatorRequestTest.java
  WordPress/src/androidTest/java/org/wordpress/android/networking/GravatarApiTest.java
  WordPress/src/androidTest/java/org/wordpress/android/networking/WPNetworkImageViewTest.java
  WordPress/src/androidTest/java/org/wordpress/android/ui/notifications/NotesParseTest.java
  WordPress/src/androidTest/java/org/wordpress/android/ui/notifications/NotificationsUtilsTest.java
  WordPress/src/androidTest/java/org/wordpress/android/ui/posts/PostUtilsTest.java
  WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/JPScreenshotTest.java
  WordPress/src/androidTest/java/org/wordpress/android/ui/screenshots/WPScreenshotTest.java
  WordPress/src/androidTest/java/org/wordpress/android/util/AutolinkUtilsTest.java
  WordPress/src/androidTest/java/org/wordpress/android/util/SupportedBlocksProviderTest.kt
  WordPress/src/androidTest/java/org/wordpress/android/util/UploadWorkerTest.kt
  WordPress/src/androidTest/java/org/wordpress/android/util/UrlUtilsTest.java
  WordPress/src/androidTest/java/org/wordpress/android/util/WPUrlUtilsTest.java
Labels: [Type] Enhancement, [Status] Needs Code Review, Testing

#16410 Integrate gutenberg-mobile release 1.75.0
  RELEASE-NOTES.txt
  build.gradle
Labels: gutenberg-mobile

#16331 Introduce updated locale picker
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/language/LocalePickerAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/language/LocalePickerBottomSheet.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/language/LocalePickerListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/language/LocalePickerListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/language/LocalePickerListViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/language/LocalePickerViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java
  WordPress/src/main/java/org/wordpress/android/util/LocaleProvider.kt
  WordPress/src/main/res/layout/locale_picker_bottom_sheet.xml
  WordPress/src/main/res/layout/locale_picker_list_item.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/app_settings.xml
  WordPress/src/test/java/org/wordpress/android/ui/prefs/locale/LocalePickerViewModelTest.kt
Labels: [Type] Enhancement, i18n

#16431 Migrate stats screens to hilt
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  build.gradle
Labels: [Type] Enhancement

#16439 Fixes Blurred Featured Image on Post Settings for Self-Hosted sites
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/FeaturedImageHelper.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/FeaturedImageHelperTest.kt
Labels: [Type] Bug, Posting/Editing, Self-hosted, Media Editing

#16440 App Data Coverage: Add more tracking to reader filter, manage and search
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderSubsActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/SubfilterBottomSheetFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/subfilter/SubFilterViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/tracker/ReaderTracker.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Reader, [Type] Task, Tracks

#16446 Crash fix on Clicking at Top tips link on Translations
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/todaysstats/TodaysStatsCardViewHolder.kt
Labels: My Site Dashboard
