Repository wordpress-mobile/WordPress-Android, pull requests merged in 2022-03, with the labels that each got.

#15999 Improve error message when registering internationalized domain names
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Enhancement, [Pri] Low, Domain Search, i18n, Site Creation

#16016 My Site Dashboard: Tabs - Hide/Show Tabs
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteDashboardTabFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteDashboardTabViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteMenuTabFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteMenuTabViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/util/BuildConfigWrapper.kt
  WordPress/src/main/res/layout/my_site_dashboard_tab_fragment.xml
  WordPress/src/main/res/layout/my_site_fragment.xml
  WordPress/src/main/res/layout/my_site_menu_tab_fragment.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/tabs/MySiteDashboardTabViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/tabs/MySiteMenuTabViewModelTest.kt
Labels: My Site Dashboard

#16025 Update login lib hash that allows wpcom site address login for JetPack app
  build.gradle
Labels: Jetpack App, Jetpack App - Enable Features

#16034 Update login lib tag
  build.gradle
Labels: Login, Jetpack App

#16000 Render comments in list using same logic as comments details.
  WordPress/build.gradle
  WordPress/src/androidTest/java/org/wordpress/android/util/WPHtmlTest.java
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/unified/CommentListUiUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/util/HtmlToSpannedConverter.java
  WordPress/src/main/java/org/wordpress/android/util/WPHtml.java
  WordPress/src/main/res/drawable-hdpi/media_image_placeholder.png
  WordPress/src/main/res/drawable-xhdpi/media_image_placeholder.png
  WordPress/src/main/res/drawable-xxhdpi/media_image_placeholder.png
Labels: [Type] Enhancement, Comments

#15979 Allow choosing email app during signup and login
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/util/WPActivityUtils.java
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Enhancement, Login, Signup, Unified Login & Sign-Up

#16039 Merge release/19.3 (19.3-rc-2)
  Gemfile.lock
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-eu/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  build.gradle
  version.properties
Labels: Releases

#16038 Fixes: Jetpack App Auto-dismiss keyboard when the error screen is displayed
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/jetpack/LoginSiteCheckErrorFragment.kt
Labels: Jetpack App

#16037 Save media capture path during orientation changes
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
Labels: Media

#16028 Hide customize insights card
  build.gradle
Labels: [Type] Task, Stats Revamp

#16036 Stats: update default insights list
  RELEASE-NOTES.txt
  build.gradle
Labels: [Type] Task, Stats Revamp

#16041 Fixes: Logout needs to be pressed twice
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/WordPress.java
Labels: Jetpack App

#16042 Integrate gutenberg-mobile release 1.71.3
  RELEASE-NOTES.txt
  build.gradle
Labels: gutenberg-mobile

#16054 Stats: Track new Insights events
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/management/InsightsManagementFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/insights/management/InsightsManagementViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsAnalyticsUtils.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: Stats, [Type] Task, Stats Revamp

#16059 Merge release/19.4 after code-freeze
  RELEASE-NOTES.txt
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/release_notes.txt
  WordPress/metadata/release_notes_short.txt
  build.gradle
  fastlane/resources/values/strings.xml
  version.properties
Labels: Releases

#16066 Adds: Skeleton classes for Category Detail Screen
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/detail/CategoryDetailActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/detail/CategoryDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/detail/CategoryDetailViewModel.kt
  WordPress/src/main/res/layout/category_detail_activity.xml
  WordPress/src/main/res/layout/category_detail_fragment.xml
  WordPress/src/test/java/org/wordpress/android/ui/prefs/categories/detail/CategoryDetailViewModelTest.kt
Labels: Tag/Category Management

#16071 Fixed comment menu rtl visibility.
  WordPress/src/main/res/layout/reader_listitem_comment.xml
Labels: [Type] Bug, [Status] Needs Code Review

#16057 Remove is_fse_active, is_fse_eligible fields from mock responses
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/me/jetpack_rest_v11_me_sites.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/me/rest_v11_me_sites.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/rest_v12_read_sites_post_125073.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/rest_v12_read_sites_post_439.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/rest_v12_read_sites_post_441.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/rest_v12_read_sites_post_related_125073.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/rest_v12_read_sites_post_related_441.json
  libs/mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/sites/rest_v11_sites_181851495.json
Labels: [Status] Not Ready for Merge, UI Tests

#16076 Android 12: Security and privacy - Safer component exporting
  WordPress/src/main/AndroidManifest.xml
Labels: Android 12

#16079 Merge release notes and PlayStore title for 19.4
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/jetpack_metadata/release_notes_short.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  WordPress/metadata/release_notes_short.txt
  WordPress/metadata/title.txt
Labels: Releases

#16086 [Tooling] Update PlayStore metadata character limits in translator comments
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/metadata/PlayStoreStrings.po
Labels: Releases

#16088 Fixes event tracking when selecting an avatar from the signup epilogue screen
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Bug, Signup

#16078 Use line height as a maximum for image rendering.
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/unified/CommentListUiUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/NotificationsUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderCommentAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewholders/CommentViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/util/image/getters/WPCustomImageGetter.kt
  WordPress/src/main/res/values/dimens.xml
Labels: [Type] Bug, Comments, [Status] Needs Code Review

#16085 Navigate not logged in user to launch screen from Notification Settings
  WordPress/src/main/java/org/wordpress/android/ui/prefs/notifications/NotificationsSettingsFragment.java
Labels: [Type] Bug, [Status] Needs Code Review

#16101 Update Dagger to 2.41
  build.gradle
Labels: [Type] Enhancement, Tech debt

#16089 Build: Remove Duplicate Coroutines Version
  build.gradle
Labels: Tooling

#16033 [Gutenberg] Update gesture handler and reanimated libraries
  build.gradle
Labels: gutenberg-mobile

#16099 My Site Dashboard: Tabs - Refactor MySiteFragment to support tabs
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteDashboardTabFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteDashboardTabViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteMenuTabFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteMenuTabViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabType.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabsAdapter.kt
  WordPress/src/main/res/layout/my_site_dashboard_tab_fragment.xml
  WordPress/src/main/res/layout/my_site_fragment.xml
  WordPress/src/main/res/layout/my_site_menu_tab_fragment.xml
  WordPress/src/main/res/layout/my_site_tab_fragment.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/tabs/MySiteDashboardTabViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/tabs/MySiteMenuTabViewModelTest.kt
Labels: [Type] Task, My Site Dashboard

#16104 My Site Dashboard: Tabs - Add fling support for the Dynamic Card rows
  WordPress/src/main/java/org/wordpress/android/ui/mysite/dynamiccards/quickstart/QuickStartDynamicCardViewHolder.kt
Labels: [Type] Task, My Site Dashboard

#16108 [Gutenberg] Include initial changes of `1.72.0`
  build.gradle
Labels: gutenberg-mobile

#16083 [Gutenberg] Use original repository for some `react-native-editor` dependencies
  WordPress/build.gradle
  build.gradle
  libs/editor/WordPressEditor/build.gradle
Labels: gutenberg-mobile

#16091 Category Management: Add category implementation
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/ParentCategorySpinnerAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/detail/CategoryDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/detail/CategoryDetailUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/detail/CategoryDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/list/CategoriesListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/list/CategoriesListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/list/CategoriesListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/list/CategoriesListingUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/list/SiteSettingsCategoriesAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/list/SiteSettingsCategoriesDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/categories/list/SiteSettingsCategoriesViewHolder.kt
  WordPress/src/main/res/layout/category_detail_fragment.xml
  WordPress/src/main/res/layout/site_settings_categories_list_activity.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/prefs/categories/CategoriesListViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/prefs/categories/detail/CategoryDetailViewModelTest.kt
Labels: [Status] Needs Code Review, Tag/Category Management, [Status] Needs Design Review

#16116 Merge release/19.4 — rc-2: getting latest translations
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rCA/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es-rVE/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-pt-rBR/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  version.properties
Labels: Releases

#16105 Fix TransactionTooLargeException when opening HistoryDetailActivity
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/history/HistoryDetailActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/history/HistoryDetailContainerFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/viewmodel/history/HistoryViewModel.kt
  build.gradle
Labels: [Type] Bug

#16118 Weekly roundup notification channel
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/workers/weeklyroundup/WeeklyRoundupNotification.kt
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Enhancement, Notifications, [Status] Needs Code Review

#16106 [Gutenberg] Update `react-native-reanimated` version to `2.4.1`
  build.gradle
Labels: gutenberg-mobile

#16119 Integrate gutenberg-mobile release 1.72.0
  RELEASE-NOTES.txt
  build.gradle
Labels: gutenberg-mobile

#16055 Hilt migration: Add AppInitializer
  WordPress/src/debug/java/org/wordpress/android/WellSqlInitializer.kt
  WordPress/src/debug/java/org/wordpress/android/WordPressDebug.java
  WordPress/src/main/java/org/wordpress/android/AppInitializer.kt
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/release/java/org/wordpress/android/WellSqlInitializer.kt
Labels: [Type] Enhancement, [Status] Needs Code Review

#16092 [HACK WEEK] Add Dependabot & Dependency Tree Diff Configuration
  .circleci/config.yml
  .github/dependabot.yml
  WordPress/build.gradle
  tools/dependency-tree-diff/dependency-tree-diff.sh
Labels: Tooling

#16139 Merge release/19.5 after code-freeze (19.5-rc-1)
  RELEASE-NOTES.txt
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/jetpack_metadata/release_notes_short.txt
  WordPress/jetpack_metadata/short_description.txt
  WordPress/jetpack_metadata/title.txt
  WordPress/metadata/release_notes.txt
  WordPress/metadata/release_notes_short.txt
  WordPress/src/main/res/values/strings.xml
  build.gradle
  fastlane/Fastfile
  fastlane/resources/values/strings.xml
  version.properties
Labels: Releases

#16120 Implement Blogging Prompts introduction dialog boilerplate
  WordPress/src/main/java/org/wordpress/android/models/bloggingprompts/BloggingPrompt.kt
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/onboarding/BloggingPromptsOnboardingViewModel.kt
  WordPress/src/main/res/layout/blogging_prompts_onboarding_dialog_fragment.xml
  WordPress/src/main/res/layout/feature_announcement_dialog_fragment.xml
  WordPress/src/main/res/layout/stories_intro_dialog_fragment.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
Labels: Blogging Prompts v1

#16082 Android 12: Security and privacy - Pending intents mutability
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/push/GCMMessageHandler.java
  WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/receivers/NotificationsPendingDraftsReceiver.java
  WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/PendingDraftsNotificationsUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PublishSettingsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/quickstart/QuickStartReminderReceiver.java
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/utils/WidgetUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java
  WordPress/src/main/java/org/wordpress/android/util/QuickStartUtils.kt
  WordPress/src/main/java/org/wordpress/android/workers/LocalNotificationWorker.kt
  WordPress/src/main/java/org/wordpress/android/workers/reminder/ReminderNotifier.kt
  build.gradle
Labels: Android 12

#16131 My Site Dashboard: Tabs - Display `QuickStartCard` based on `QuickStartOrigin`
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepository.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartCardSourceTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepositoryTest.kt
Labels: My Site Dashboard

#16126 Display list of default verticals on the Site Intent Question screen
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVM.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/IntentsScreenListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsViewModel.kt
  WordPress/src/main/res/layout/site_creation_intents_fragment.xml
  WordPress/src/main/res/layout/site_creation_intents_item.xml
  WordPress/src/main/res/values-night/colors.xml
  WordPress/src/main/res/values/colors.xml
  WordPress/src/main/res/values/site_creation_intents.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/SiteCreationMainVMTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/previews/SitePreviewViewModelTest.kt
Labels: [Type] Enhancement, Site Creation

#16144 Merge release/19.5 to fix typo in string
  WordPress/src/main/res/values/strings.xml
  fastlane/resources/values/strings.xml
Labels: Releases

#16124 Issue/16122 add blogging prompt option to reminders
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersUiModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/DaySelectionBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingreminders/PrologueBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/util/config/BloggingPromptsFeatureConfig.kt
  WordPress/src/main/res/layout/blogging_reminders_prompt_switch.xml
  WordPress/src/main/res/layout/blogging_reminders_time.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/bloggingreminders/BloggingRemindersViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/bloggingreminders/DaySelectionBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/bloggingreminders/PrologueBuilderTest.kt
Labels: [Status] Needs Code Review, [Type] Task, Blogging Prompts v1

#16145 Removes Land In the Editor ExPlat experiment
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/modules/ExperimentModule.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/config/LandOnTheEditorFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/experiments/LandOnTheEditorABExperiment.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: Site Creation

#16113 Use Automattic-Tracks-Android library from S3 Maven
  WordPress/build.gradle
  build.gradle
  libs/analytics/WordPressAnalytics/build.gradle
Labels: Tooling

#16142 My Site Dashboard: Tabs - Custom view with QS focus point, introduce `TabsUiState`
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabType.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabsAdapter.kt
  WordPress/src/main/res/layout/my_site_tab_custom_view.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: My Site Dashboard

#16158 Integrate verticals list
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsViewModel.kt
  WordPress/src/main/res/values/site_creation_intents.xml
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Enhancement, Site Creation

#16125 Fix crash too many sql variables
  build.gradle
Labels: Posting/Editing, Post List, [Type] Crash

#16161 My Site View Model Test: Fix dashboard cards initialisation
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: My Site Dashboard

#15865 Upgrade Gradle to 7.4 & AGP to 7.1.1
  .buildkite/pipeline.yml
  WordPress/build.gradle
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/push/NotificationsProcessingService.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/QuickStartPromptDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java
  WordPress/src/main/java/org/wordpress/android/util/LocaleManager.java
  WordPress/src/main/java/org/wordpress/android/util/extensions/DialogExtensions.kt
  WordPress/src/main/res/values-large-hdpi/dimens.xml
  WordPress/src/main/res/values-large-tvdpi/dimens.xml
  WordPress/src/main/res/values-night/colors.xml
  WordPress/src/main/res/values-night/colors_aztec.xml
  WordPress/src/main/res/values-night/styles.xml
  WordPress/src/main/res/values-sw720dp/dimens.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/main/res/values/styles_toolbar.xml
  build.gradle
  config/lint.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  libs/editor/WordPressEditor/build.gradle
Labels: Tooling

#16162 Merge release/19.5 — Release Notes
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: Releases

#16160 Enable submitting a custom vertical on the Site Intent Question screen
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/theme/HomePagePickerViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsViewModel.kt
  WordPress/src/main/res/layout-land/site_creation_intents_header.xml
  WordPress/src/main/res/layout/site_creation_intents_fragment.xml
  WordPress/src/main/res/layout/site_creation_intents_header.xml
  WordPress/src/main/res/layout/site_creation_intents_titlebar.xml
  WordPress/src/main/res/layout/site_creation_segment_item.xml
  WordPress/src/main/res/layout/site_creation_segments_progress.xml
  WordPress/src/main/res/layout/site_creation_segments_screen.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsViewModelTest.kt
Labels: [Type] Enhancement, Site Creation

#16169 Stats: Fix duplicate `stats_{section}_accessed` events tracking
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
Labels: Stats, My Site Dashboard

#16171 Stats: Fix `stats_insights_accessed` initial section tracking
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/StatsViewModelTest.kt
Labels: Stats, [Status] Not Ready for Merge

#16168 Issue/16150 blogging prompt card scaffolding
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItemBuilderParams.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsShownTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/bloggingprompts/BloggingPromptCardBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/bloggingprompts/BloggingPromptCardViewHolder.kt
  WordPress/src/main/res/drawable/ic_outline_lightbulb_white_24dp.xml
  WordPress/src/main/res/layout/my_site_blogging_promp_card.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/CardsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsBuilderTest.kt
Labels: [Status] Needs Code Review, [Type] Task, Blogging Prompts v1

#16151 Add common parent class for application classes
  WordPress/src/androidTest/java/org/wordpress/android/WordPressTest.kt
  WordPress/src/androidTest/java/org/wordpress/android/networking/WPNetworkImageViewTest.java
  WordPress/src/debug/java/org/wordpress/android/WordPressDebug.java
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/AppInitializer.kt
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/WordPress.kt
  WordPress/src/main/java/org/wordpress/android/WordPressApp.java
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderBlogActions.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/actions/ReaderPostActions.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderVideoUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/stories/StoryComposerActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/PostUploadNotifier.java
Labels: [Type] Enhancement, [Status] Needs Code Review

#16172 Fix: Show Quickstart focus point when Site Info header Toolbar is collapsed
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabFragment.kt
Labels: [Status] Needs Code Review, Quick Start, My Site Dashboard

#16175 My Site Dashboard: Tabs Add feature flags for default tab experiment
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/util/config/MySiteDefaultTabExperimentFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/MySiteDefaultTabExperimentVariationDashboardFeatureConfig.kt
Labels: [Type] Task, My Site Dashboard

#16159 My Site Dashboard: Tabs - Add "Site Menu" QS step, show QS focus point on tab
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepository.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepositoryTest.kt
Labels: My Site Dashboard

#16179 My Site Dashboard: Tabs - Remove Domain Registration Card from Home tab
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: [Type] Task, My Site Dashboard

#16183 My Site Dashboard: Tabs - Track experiment property with all events
  WordPress/src/main/java/org/wordpress/android/WordPress.java
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteDefaultTabExperiment.kt
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsTrackerWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteDefaultTabExperimentTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsInjectExperimentProperties.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
Labels: [Type] Task, My Site Dashboard

#16177 Fix "Multiple substitutions specified in non-positional format" errors
  WordPress/src/main/res/values/strings.xml
Labels: i18n, Tooling

#16186 Adds real estate vertical
  WordPress/src/main/res/values/site_creation_intents.xml
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Enhancement, Site Creation

#16185 Removes vertical_id from analytics tracking on Android
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SiteCreationTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsViewModel.kt
Labels: [Type] Enhancement, Site Creation

#16193 Stats Revamp V2: Add Feature Config
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/util/config/StatsRevampV2FeatureConfig.kt
Labels: [Type] Task, Stats Revamp

#16195 Beta Fix: Unable to select WordPress app when sharing images or videos
  WordPress/src/main/AndroidManifest.xml
Labels: [Type] Bug

#16187 My Site Dashboard: Tabs - Track default tab experiment variant assigned
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteDefaultTabExperiment.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteDefaultTabExperimentTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Task, My Site Dashboard

#16197 Merge release/19.5 (19.5-rc-3)
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sq/strings.xml
  WordPress/src/main/res/values-vi/strings.xml
  version.properties
Labels: Releases

#16184 Clickable site header on collapsed state
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
Labels: [Type] Bug, [Status] Needs Code Review, My Site Dashboard

#16189 My Site Dashboard: Tabs - Track tab tapped and tab shown events
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: My Site Dashboard

#16207 Fixes Connected tests : Removes deleted site from displaying #16063
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
Labels: [Type] Bug, /My site

#16198 [Site Intent Question] Enables searching through verticals on the Site Intent Question screen
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/VerticalsSearchResultsProvider.kt
  WordPress/src/test/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsViewModelTest.kt
Labels: [Type] Task, Site Creation

#16128 Add A/B test for site intent question
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/misc/SiteCreationTracker.kt
  WordPress/src/main/java/org/wordpress/android/util/config/SiteIntentQuestionFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/experiments/SiteIntentQuestionABExperiment.kt
  WordPress/src/test/java/org/wordpress/android/util/experiments/SiteIntentQuestionABExperimentTest.kt
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java
Labels: [Type] Task, Site Creation

#16030 My Site Dashboard: Tabs - Refactor My Site Header
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapter.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteAdapterDiffCallback.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteCardAndItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/CardsBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/siteinfo/MySiteInfoViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/siteinfo/SiteInfoHeaderCardBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabFragment.kt
  WordPress/src/main/res/layout/my_site_fragment.xml
  WordPress/src/main/res/layout/my_site_info_header_card.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/styles.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteCardAndItemTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/CardsBuilderTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/siteinfo/SiteInfoHeaderCardBuilderTest.kt
Labels: Part of a WIP Feature, My Site Dashboard

#16211 Integrate gutenberg-mobile release 1.72.1
  build.gradle
Labels: gutenberg-mobile

#16218 Adjust site verticals animations and styles
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/verticals/SiteCreationIntentsFragment.kt
  WordPress/src/main/res/layout/site_creation_intents_fragment.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Enhancement, Site Creation

#16221 Merge release/19.5 (19.5-rc-4) with conflict resolution
  WordPress/src/main/res/values-cs/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  version.properties
Labels: Releases

#16199 My Site Dashboard: Tabs - Implement default tab experiment logic + Show QS Card on default tab
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quickstart/QuickStartRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteDefaultTabExperiment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/tabs/MySiteTabFragment.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
Labels: [Status] Not Ready for Merge, My Site Dashboard

#16222 Integrate gutenberg-mobile release 1.73.0
  build.gradle
Labels: gutenberg-mobile

#16215 Issue/expand comment editing tracking
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentsEditViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewholders/CommentViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/util/analytics/AnalyticsUtilsWrapper.kt
  WordPress/src/test/java/org/wordpress/android/ui/comments/viewmodels/UnifiedCommentsEditViewModelTest.kt
Labels: [Type] Enhancement, Comments, Analytics
