Repository wordpress-mobile/WordPress-Android, pull requests merged in 2024-06, with the labels that each got.

#20928 Replaces OAuth2 section with self-hosted test instructions
  README.md
Labels: [Type] Task, Documentation

#20925 [Reader] Show "Create Post" FAB in Reader
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/analytics/MainCreateSheetTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/utils/MainCreateSheetHelper.kt
  WordPress/src/main/java/org/wordpress/android/util/SiteUtilsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/config/ReaderFloatingButtonFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModel.kt
  WordPress/src/main/res/layout/filtered_list_component.xml
  WordPress/src/test/java/org/wordpress/android/ui/main/analytics/MainCreateSheetTrackerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/main/utils/MainCreateSheetHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/main/WPMainActivityViewModelTest.kt
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
Labels: Reader, [Type] Task

#20854 Set targetSdk to 34.
  build.gradle
Labels: [Type] Task, Android 14

#20932 Integrate gutenberg-mobile release v1.119.1
  build.gradle
Labels: Gutenberg

#20936 Adds: delays for app restart in InAppUpdateManagerImpl
  WordPress/src/main/java/org/wordpress/android/inappupdate/InAppUpdateAnalyticsTracker.kt
  WordPress/src/main/java/org/wordpress/android/inappupdate/InAppUpdateManagerImpl.kt
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/test/java/org/wordpress/android/inappupdate/InAppUpdateManagerImplTest.kt
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
Labels: [Type] Bug

#20934 Change the circular avatar to a rounded corner avatar.
  WordPress/src/main/java/org/wordpress/android/ui/main/ChooseSiteViewHolder.kt
  WordPress/src/main/res/layout/item_choose_site.xml
  WordPress/src/main/res/values/dimens.xml
  WordPress/src/main/res/values/styles.xml
Labels: Site Picker

#20937 [Hack Week] A generic solution for resolving the ANRs caused by accessing local database
  WordPress/src/main/java/org/wordpress/android/datasets/AsyncTaskHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java
Labels: Reader, [Type] ANR

#20940 [Reader] Show custom lists directly if there are 2 or fewer items
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderTopBarMenuHelper.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/utils/ReaderTopBarMenuHelperTest.kt
Labels: Reader, Reader IA

#20926 Updating fluxc lib for testing the fluxc bug fix.
  build.gradle
Labels: [Type] Task

#20942 Integrate gutenberg-mobile release v1.120.0
  build.gradle
Labels: Gutenberg

#20945 Convert `BlockProcessor` to kotlin
  WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadReadyListener.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/AudioBlockProcessor.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/BlockProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/BlockProcessor.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/BlockProcessorFactory.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/CoverBlockProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/FileBlockProcessor.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/GalleryBlockProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/ImageBlockProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/MediaBlockType.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/MediaTextBlockProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/MediaUploadCompletionProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/VideoBlockProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/VideoPressBlockProcessor.kt
  WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadReadyProcessor.java
  libs/editor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java
Labels: [Type] Enhancement, Tech Debt

#20944 Comment details menu redesign
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/SharedCommentDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/comments/unified/CommentActionPopupHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailListFragment.kt
Labels: Notifications, Comments

#20862 Fix crash in GutenbergContainerFragment
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java
Labels: [Type] Crash, Gutenberg

#20939 Post List: Fix excessive media requests
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListEventListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostListFeaturedImageTracker.kt
  WordPress/src/test/java/org/wordpress/android/ui/posts/PostListFeaturedImageTrackerTest.kt
Labels: [Type] Bug, Post List, unit-tests-exemption

#20946 Bump Gravatar SDK to 1.0.0
  WordPress/src/main/java/org/wordpress/android/ui/accounts/SignupEpilogueActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/res/layout/signup_epilogue.xml
  build.gradle
Labels: Gravatar

#20955 [Issue/20295] Location metadata in uploaded pictures
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/PhotoPickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/editor/media/AddLocalMediaToPostUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/util/WPMediaUtils.java
  WordPress/src/main/java/org/wordpress/android/util/WPPermissionUtils.java
  WordPress/src/main/res/values/strings.xml
  build.gradle
Labels: [Type] Bug

#20964 Revert "Merge pull request #20854 from wordpress-mobile/andy/target-s…
  build.gradle
Labels: [Type] Task

#20966 Merge 25.1-rc-2 to trunk
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  build.gradle
  version.properties
Labels: Releases

#20943 Fix a potential issue related to lifecycle
  WordPress/src/main/java/org/wordpress/android/datasets/AsyncTaskExecutor.kt
  WordPress/src/main/java/org/wordpress/android/datasets/AsyncTaskHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderPostAdapter.java
Labels: [Type] Bug, [Type] ANR

#20938 Adds os_version parameter in feature flags and dynamic dashboard cards
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/dashboard/CardViewModelSlice.kt
  WordPress/src/main/java/org/wordpress/android/util/BuildConfigWrapper.kt
  WordPress/src/main/java/org/wordpress/android/util/config/FeatureFlagConfig.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/dashboard/CardsViewModelSliceTest.kt
  build.gradle
  libs/mocks/src/main/assets/mocks/mappings/wpcom/mobile/feature-flags.json
Labels: [Type] Enhancement, Dynamic Dashboard Cards

#20952 Comment details trash moderation redesign
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/comments/SharedCommentDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailActivity.java
  WordPress/src/main/res/drawable/trash_24.xml
  WordPress/src/main/res/layout/comment_detail_fragment.xml
  WordPress/src/main/res/layout/comment_trash.xml
  WordPress/src/main/res/values/strings.xml
Labels: Notifications, Comments

#20967 Fix crash in PluginBrowserViewModel
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderFragment.kt
Labels: [Type] Crash

#20977 Merge 25.1 editorialized release notes to trunk
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: Releases

#20933 Migrated `AddCategoryFragment` to ViewBinding
  WordPress/src/main/java/org/wordpress/android/ui/posts/AddCategoryFragment.java
Labels: Core, Tech Debt

#20970 [Do Not Merge] - CI Trigger for #20933
  WordPress/src/main/java/org/wordpress/android/ui/posts/AddCategoryFragment.java
Labels: [Status] Not Ready for Merge

#20979 [Voice to Content] Error logging, tracking, and error state
  WordPress/src/main/java/org/wordpress/android/ui/ActivityNavigator.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/PrepareVoiceToContentUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentTelemetry.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/voicetocontent/VoiceToContentViewModelTest.kt
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
Labels: [Type] Task, unit-tests-exemption, Voice to Content

#20978 [Revert] This reverts adding foregroundServiceType to many services.
  WordPress/src/main/AndroidManifest.xml
Labels: [Type] Task

#20981 [Voice to Content] Update waveform
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/WaveformVisualizer.kt
  WordPress/src/main/java/org/wordpress/android/util/audio/AudioRecorder.kt
Labels: [Type] Task, unit-tests-exemption, Voice to Content

#20983 [Voice to Content] Clear recorder resources
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/RecordingUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/audio/AudioRecorder.kt
  WordPress/src/main/java/org/wordpress/android/util/audio/IAudioRecorder.kt
Labels: [Type] Task, unit-tests-exemption, Voice to Content

#20993 Update wordPressLoginVersion to 1.16.0
  build.gradle
Labels: [Type] Bug, dependency update

#20984 [Voice to Content\ Implement elapsed time indicator
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/audio/AudioRecorder.kt
  WordPress/src/main/java/org/wordpress/android/util/audio/RecordingUpdate.kt
Labels: [Type] Task, unit-tests-exemption, Voice to Content

#20941 Migrated `PostSettingsInputDialogFragment` to ViewBinding
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostSettingsInputDialogFragment.java
Labels: Core, Tech Debt

#20971 [Do Not Merge] - CI Trigger for #20941
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostSettingsInputDialogFragment.java
Labels: [Status] Not Ready for Merge

#20997 [Fix] IllegalArgumentException: in ReaderPostRenderer
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java
Labels: [Type] Task, [Type] Crash, unit-tests-exemption

#20960 Convert BlockProcessor's child classes to Kotlin
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/AudioBlockProcessor.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/BlockProcessor.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/BlockProcessorFactory.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/BlockProcessorFactory.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/CoverBlockProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/CoverBlockProcessor.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/FileBlockProcessor.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/GalleryBlockProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/GalleryBlockProcessor.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/ImageBlockProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/ImageBlockProcessor.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/MediaTextBlockProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/MediaTextBlockProcessor.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/MediaUploadCompletionProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/VideoBlockProcessor.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/VideoBlockProcessor.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/VideoPressBlockProcessor.kt
Labels: [Type] Enhancement, Tech Debt

#21002 Integrate gutenberg-mobile release v1.120.1
  build.gradle
Labels: Gutenberg

#21003 Upgrade targetSdk from 33 to 34.
  build.gradle
Labels: [Type] Task

#20992 [Voice to Content] Launch edit post with AI content
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivityConstants.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentActionEvent.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentViewModel.kt
  libs/editor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java
  libs/editor/src/main/java/org/wordpress/android/editor/EditorFragmentAbstract.java
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java
Labels: [Type] Task, unit-tests-exemption, Voice to Content

#20995 [Voice to Content] Support device rotation while recording
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/MicToStopIcon.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/RecordingUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentUiState.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentViewModel.kt
  WordPress/src/main/java/org/wordpress/android/util/audio/AudioRecorder.kt
  WordPress/src/main/java/org/wordpress/android/util/audio/IAudioRecorder.kt
  build.gradle
Labels: [Type] Task, unit-tests-exemption, Voice to Content

#20968 Migrate `PluginDetailActivity` to ViewBinding
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginDetailActivity.java
  WordPress/src/main/res/layout/plugin_detail_activity.xml
Labels: Core, Tech Debt

#21009 [Do Not Merge] - CI Trigger for #20968
  WordPress/src/main/java/org/wordpress/android/ui/plugins/PluginDetailActivity.java
  WordPress/src/main/res/layout/plugin_detail_activity.xml
Labels: [Status] Not Ready for Merge

#21012 Fix the crashes in UploadUtilsWrapper caused by null snackbarAttachView
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtilsWrapper.kt
Labels: Posting/Editing, [Type] Crash

#21004 Update camerax to 1.3.4 and fix the API change, which deprecates setTargetSolution
  WordPress/src/main/java/org/wordpress/android/ui/barcodescanner/BarcodeScanner.kt
  build.gradle
Labels: [Type] Task

#21014 Merge 25.1-rc-3 to trunk
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java
  WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadUtilsWrapper.kt
  WordPress/src/main/res/values-ar/strings.xml
  WordPress/src/main/res/values-de/strings.xml
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-es-rCO/strings.xml
  WordPress/src/main/res/values-es/strings.xml
  WordPress/src/main/res/values-fr-rCA/strings.xml
  WordPress/src/main/res/values-fr/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-he/strings.xml
  WordPress/src/main/res/values-id/strings.xml
  WordPress/src/main/res/values-it/strings.xml
  WordPress/src/main/res/values-ja/strings.xml
  WordPress/src/main/res/values-ko/strings.xml
  WordPress/src/main/res/values-nl/strings.xml
  WordPress/src/main/res/values-pl/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  WordPress/src/main/res/values-ru/strings.xml
  WordPress/src/main/res/values-sv/strings.xml
  WordPress/src/main/res/values-tr/strings.xml
  WordPress/src/main/res/values-zh-rCN/strings.xml
  WordPress/src/main/res/values-zh-rHK/strings.xml
  WordPress/src/main/res/values-zh-rTW/strings.xml
  build.gradle
  version.properties
Labels: Releases

#21016 Fix - EditPostActivity - Update fetching for the block editor's settings logic
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
Labels: [Type] Bug, Themes, Gutenberg

#21018 Merge 25.1-rc-4 to trunk
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-es-rCL/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  version.properties
Labels: Releases

#21019 [Do Not Merge] - CI Trigger for #20975
  WordPress/src/main/java/org/wordpress/android/ui/CollapseFullScreenDialogFragment.java
Labels: [Status] Not Ready for Merge
