Repository wordpress-mobile/WordPress-Android, pull requests merged in 2024-10, with the labels that each got.

#21262 [Deps] Migrate to Version Catalogs
  WordPress/build.gradle
  build.gradle
  config/lint/lint.xml
  docs/test_instructions_per_dependency_update.md
  gradle/libs.versions.toml
  libs/analytics/build.gradle
  libs/annotations/build.gradle
  libs/editor/build.gradle
  libs/image-editor/build.gradle
  libs/mocks/build.gradle
  libs/networking/build.gradle
  libs/processors/build.gradle
  settings.gradle
Labels: Core, Tooling

#21276 [Deps] Migrate EventBus to Version Catalogs
  WordPress/build.gradle
Labels: Core, Tooling

#21275 Self-hosted user UI
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SiteNavigationAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/ListItemActionHandler.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/items/listitem/ListItemAction.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/items/listitem/SiteItemsBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/items/listitem/SiteListItemBuilder.kt
  WordPress/src/main/java/org/wordpress/android/ui/selfhostedusers/SampleUsers.kt
  WordPress/src/main/java/org/wordpress/android/ui/selfhostedusers/SelfHostedUserComposables.kt
  WordPress/src/main/java/org/wordpress/android/ui/selfhostedusers/SelfHostedUsersActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/selfhostedusers/SelfHostedUsersScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/selfhostedusers/SelfHostedUsersViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/items/listitem/SiteListItemBuilderTest.kt
Labels: Self-hosted, unit-tests-exemption, Self-hosted users

#21287 Issue/21283 no connection message
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/loader/GifMediaDataSource.kt
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/loader/MediaLibraryDataSource.kt
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/loader/StockMediaDataSource.kt
  WordPress/src/main/java/org/wordpress/android/ui/selfhostedusers/SelfHostedUserComposables.kt
  WordPress/src/main/java/org/wordpress/android/ui/selfhostedusers/SelfHostedUsersActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/selfhostedusers/SelfHostedUsersScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/selfhostedusers/SelfHostedUsersViewModel.kt
  WordPress/src/main/res/layout/actionable_empty_view.xml
  WordPress/src/test/java/org/wordpress/android/ui/mediapicker/loader/GifMediaDataSourceTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mediapicker/loader/MediaLibraryDataSourceTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mediapicker/loader/StockMediaDataSourceTest.kt
Labels: Offline Support, UI

#21290 Self hosted users accessibility
  WordPress/src/main/java/org/wordpress/android/ui/selfhostedusers/SampleUsers.kt
  WordPress/src/main/java/org/wordpress/android/ui/selfhostedusers/SelfHostedUserComposables.kt
  WordPress/src/main/java/org/wordpress/android/ui/selfhostedusers/SelfHostedUsersScreen.kt
  WordPress/src/main/res/values/strings.xml
Labels: Self-hosted users

#21295 Fix Jetpack poster line spacing
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/staticposter/compose/JetpackStaticPoster.kt
Labels: UI

#21286 Coil image loader singleton
  WordPress/src/main/java/org/wordpress/android/WordPress.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/MediaUriPager.kt
Labels: Media

#21293 Self hosted users lazy list
  WordPress/src/main/java/org/wordpress/android/ui/selfhostedusers/SelfHostedUserComposables.kt
  WordPress/src/main/java/org/wordpress/android/ui/selfhostedusers/SelfHostedUsersScreen.kt
Labels: Self-hosted users

#21296 Merge 25.4 release notes to `release/25.4`
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: Releases

#21301 Bump WordPress-Login-Flow to 1.18.0
  gradle/libs.versions.toml
Labels: dependency update

#21299 Bump FluxC to 2.98.0
  gradle/libs.versions.toml
Labels: dependency update

#21300 Material3 primary and secondary buttons
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/buttons/PrimaryButtonM3.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/buttons/SecondaryButtonM3.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/staticposter/JetpackStaticPosterFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/staticposter/compose/JetpackStaticPoster.kt
Labels: Tech Debt, UI

#21223 Add GutenbergKit
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivityConstants.kt
  WordPress/src/main/java/org/wordpress/android/util/config/NewGutenbergFeatureConfig.kt
  config/gradle/included_builds.gradle
  gradle/libs.versions.toml
  libs/editor/build.gradle
  libs/editor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java
  libs/editor/src/main/java/org/wordpress/android/editor/EditorFragmentAbstract.java
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java
  local-builds.gradle-example
Labels: Gutenberg

#21313 [Localization] Fix Remote Libraries Strings Paths
  fastlane/lanes/localization.rb
Labels: Releases, Localization, Tooling

#21315 Material 3 Login Prologue
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/LoginPrologueRevampedFragment.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/LoopingText.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/LoopingTextWithBackground.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/PrimaryButton.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/SecondaryButton.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/TopLinearGradient.kt
Labels: Tech Debt, UI

#21316 Rename M3Theme to AppThemeM3
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/LoginPrologueRevampedFragment.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/LoopingText.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/LoopingTextWithBackground.kt
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/components/TopLinearGradient.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/ProgressDialog.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/buttons/PrimaryButtonM3.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/theme/AppThemeM3.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/preferences/DebugSharedPreferenceFlagsActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/preferences/DebugSharedPreferenceFlagsScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/management/DomainManagementActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/management/DomainStatusRow.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/management/DomainsListCard.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/management/MyDomainsScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/management/composable/DomainsSearchTextField.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/management/composable/PrimaryButton.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/management/newdomainsearch/NewDomainSearchActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/management/purchasedomain/PurchaseDomainActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/management/purchasedomain/composable/PurchaseDomainScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/feedbackform/FeedbackFormScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/staticposter/JetpackStaticPosterFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/staticposter/compose/JetpackStaticPoster.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/components/AccountClosureDialog.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/components/CloseAccountButton.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/components/FlatButtons.kt
  WordPress/src/main/java/org/wordpress/android/ui/selfhostedusers/SelfHostedUserComposables.kt
Labels: UI

#21261 Adjust build configuration to use vendored FluxC and WordPressLoginFlow
  .buildkite/commands/run-unit-tests.sh
  .buildkite/pipeline.yml
  WordPress/build.gradle
  build.gradle
  config/detekt/detekt.yml
  config/gradle/code_coverage.gradle
  config/gradle/included_builds.gradle
  config/lint/lint.xml
  fastlane/lanes/localization.rb
  gradle/libs.versions.toml
  libs/fluxc-annotations/build.gradle
  libs/fluxc-processor/build.gradle
  libs/fluxc/build.gradle
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/BaseWPComRestClient.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/PostSqlUtils.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/utils/DateUtils.kt
  libs/fluxc/src/test/java/org/wordpress/android/fluxc/endpoints/WPComV2EndpointTest.java
  libs/fluxc/src/test/java/org/wordpress/android/fluxc/example/utils/ArrayUtilsTest.kt
  libs/fluxc/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/BaseWPComRestClientTest.java
  libs/login/build.gradle
  libs/login/gradle.properties-example
  libs/login/src/main/java/org/wordpress/android/login/Login2FaFragment.java
  libs/login/src/main/java/org/wordpress/android/login/LoginEmailFragment.java
  libs/login/src/main/java/org/wordpress/android/login/LoginGoogleFragment.java
  libs/login/src/main/java/org/wordpress/android/login/SignupConfirmationFragment.kt
  libs/login/src/main/java/org/wordpress/android/login/SignupGoogleFragment.java
  libs/login/src/main/java/org/wordpress/android/login/widgets/WPLoginInputRow.java
  libs/login/src/main/res/drawable/img_envelope.xml
  libs/login/src/main/res/drawable/img_success_tablet.xml
  libs/login/src/main/res/drawable/login_toolbar_icon.xml
  libs/networking/README.md
  local-builds.gradle-example
  settings.gradle
Labels: Core

#21324 feat: Toggle editor theme styles via feature flag
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  WordPress/src/main/java/org/wordpress/android/util/config/NewGutenbergThemeStylesFeatureConfig.kt
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java
Labels: [Type] Enhancement, Gutenberg

#21310 Issue/17453-Multi line display of text in 'About me'
  WordPress/src/main/java/org/wordpress/android/ui/TextInputDialogFragment.java
Labels: UI

#21330 Material 3 bar code & QR code scanners
  WordPress/src/main/java/org/wordpress/android/ui/barcodescanner/BarcodeScannerScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/qrcodeauth/QRCodeAuthFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/qrcodeauth/compose/components/PrimaryButton.kt
  WordPress/src/main/java/org/wordpress/android/ui/qrcodeauth/compose/components/SecondaryButton.kt
  WordPress/src/main/java/org/wordpress/android/ui/qrcodeauth/compose/components/Subtitle.kt
  WordPress/src/main/java/org/wordpress/android/ui/qrcodeauth/compose/components/Title.kt
  WordPress/src/main/java/org/wordpress/android/ui/qrcodeauth/compose/state/ContentState.kt
  WordPress/src/main/java/org/wordpress/android/ui/qrcodeauth/compose/state/ErrorState.kt
  WordPress/src/main/java/org/wordpress/android/ui/qrcodeauth/compose/state/LoadingState.kt
Labels: Tech Debt, UI

#21341 Test/21137
  WordPress/src/main/java/org/wordpress/android/ui/posts/BasicFragmentDialog.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/values/styles.xml
Labels: Testing

#21342 Convert Bloganuary screen to Material3
  WordPress/src/main/java/org/wordpress/android/ui/bloganuary/learnmore/BloganuaryNudgeLearnMoreOverlay.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloganuary/learnmore/BloganuaryNudgeLearnMoreOverlayFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
Labels: Tech Debt, UI

#21349 Configure dependabot to only observe version catalog file
  .github/dependabot.yml
Labels: Tooling

#21355 Warn A8C users when accessing Zendesk
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/HelpActivity.kt
  WordPress/src/main/res/values/strings.xml
Labels: Support

#21360 Match iOS Feedback Form Tracks Events
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/main/feedbackform/FeedbackFormViewModel.kt
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
Labels: Analytics

#21353 Post FluxC vendor improvements: remove unused Wiremock files, migrate to local version catalog
  gradle/libs.versions.toml
  libs/fluxc-processor/build.gradle
  libs/fluxc/build.gradle
  libs/fluxc/gradle.properties-example
  libs/fluxc/src/test/resources/wc/attribute-term-operation-response.json
  libs/fluxc/src/test/resources/wc/attribute-terms-full-list.json
  libs/fluxc/src/test/resources/wc/leaderboards-response-example.json
  libs/fluxc/src/test/resources/wc/lineitems.json
  libs/fluxc/src/test/resources/wc/order-shipment-providers.json
  libs/fluxc/src/test/resources/wc/order-shipment-trackings-multiple.json
  libs/fluxc/src/test/resources/wc/order-shipping-lines.json
  libs/fluxc/src/test/resources/wc/order-summaries-extended.json
  libs/fluxc/src/test/resources/wc/order-summaries.json
  libs/fluxc/src/test/resources/wc/order_notes.json
  libs/fluxc/src/test/resources/wc/order_status_options.json
  libs/fluxc/src/test/resources/wc/print-shipping-labels.json
  libs/fluxc/src/test/resources/wc/product-attribute-create.json
  libs/fluxc/src/test/resources/wc/product-attribute-delete.json
  libs/fluxc/src/test/resources/wc/product-attribute-update.json
  libs/fluxc/src/test/resources/wc/product-attributes-all.json
  libs/fluxc/src/test/resources/wc/product-bundle-with-max-quantity.json
  libs/fluxc/src/test/resources/wc/product-bundle-with-min-quantity.json
  libs/fluxc/src/test/resources/wc/product-bundle-with-quantity-rules.json
  libs/fluxc/src/test/resources/wc/product-categories.json
  libs/fluxc/src/test/resources/wc/product-reviews.json
  libs/fluxc/src/test/resources/wc/product-settings-response.json
  libs/fluxc/src/test/resources/wc/product-with-addons.json
  libs/fluxc/src/test/resources/wc/product-with-incorrect-addons-key.json
  libs/fluxc/src/test/resources/wc/product_reliability_booleans.json
  libs/fluxc/src/test/resources/wc/purchase-shipping-labels.json
  libs/fluxc/src/test/resources/wc/reports-product-response-example.json
  libs/fluxc/src/test/resources/wc/revenue-stats-data.json
  libs/fluxc/src/test/resources/wc/shipping-labels-account-settings.json
  libs/fluxc/src/test/resources/wc/shipping-labels-carriers.json
  libs/fluxc/src/test/resources/wc/shipping-labels-packages.json
  libs/fluxc/src/test/resources/wc/shipping-labels.json
  libs/fluxc/src/test/resources/wc/site-setting-option-response.json
  libs/fluxc/src/test/resources/wc/site-settings-general-response.json
  libs/fluxc/src/test/resources/wc/status-shipping-labels-1.json
  libs/fluxc/src/test/resources/wc/status-shipping-labels-2.json
  libs/fluxc/src/test/resources/wc/status-shipping-labels-error.json
  libs/fluxc/src/test/resources/wc/store-user-role.json
  libs/fluxc/src/test/resources/wc/system-status.json
  libs/fluxc/src/test/resources/wc/tax-based-on-settings-response.json
  libs/fluxc/src/test/resources/wc/tax-rate-response.json
  libs/fluxc/src/test/resources/wc/top-performer-product-1.json
  libs/fluxc/src/test/resources/wc/top-performer-product-2.json
  libs/fluxc/src/test/resources/wc/top-performer-product-3.json
  libs/fluxc/src/test/resources/wc/visitor-stats-data.json
  libs/fluxc/src/test/resources/wc/visitor-stats-fields.json
  libs/fluxc/src/test/resources/wc/wrong-visitor-stats-data.json
  libs/login/gradle.properties-example
  settings.gradle
Labels: Core

#21367 Migrate `login` to version catalogs
  .github/dependabot.yml
  WordPress/build.gradle
  build.gradle
  config/lint/lint.xml
  gradle/libs.versions.toml
  libs/analytics/build.gradle
  libs/editor/build.gradle
  libs/image-editor/build.gradle
  libs/login/build.gradle
  libs/networking/build.gradle
  settings.gradle
Labels: Core

#21369 Jetpack overlay Material3
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/individualplugin/WPJetpackIndividualPluginFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/individualplugin/compose/MultipleSitesContent.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/individualplugin/compose/SingleSiteContent.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/individualplugin/compose/WPJetpackIndividualPluginOverlayScreen.kt
Labels: Tech Debt, UI

#21371 Jetpack plugin install Material3
  WordPress/src/main/java/org/wordpress/android/ui/jetpackplugininstall/fullplugin/install/JetpackFullPluginInstallActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackplugininstall/fullplugin/onboarding/JetpackFullPluginInstallOnboardingDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackplugininstall/fullplugin/onboarding/compose/component/JPInstallFullPluginAnimation.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackplugininstall/fullplugin/onboarding/compose/component/PluginDescription.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackplugininstall/fullplugin/onboarding/compose/component/TermsAndConditions.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackplugininstall/fullplugin/onboarding/compose/state/LoadedState.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackplugininstall/install/compose/JetpackPluginInstallScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackplugininstall/install/compose/state/BaseState.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackplugininstall/install/compose/state/DoneState.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackplugininstall/install/compose/state/ErrorState.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackplugininstall/install/compose/state/InitialState.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackplugininstall/install/compose/state/InstallingState.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackplugininstall/remoteplugin/JetpackRemoteInstallActivity.kt
Labels: Tech Debt, UI

#21381 Move "Send feedback" to HelpActivity
  WordPress/src/main/java/org/wordpress/android/ui/accounts/HelpActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/res/layout/help_activity.xml
  WordPress/src/main/res/layout/me_fragment.xml
  WordPress/src/main/res/values/strings.xml
Labels: Support
