Repository wordpress-mobile/WordPress-Android, pull requests merged in 2024-11, with the labels that each got.

#21378 Issue/reading view compose m3
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/menu/dropdown/MenuColors.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderReadingPreferencesDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderTagsFeedFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderTopBarMenuHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderAnnouncementCardView.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/ReaderAnnouncementCard.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/ReaderTopAppBar.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/dropdown/JetpackDropdownMenu.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/dropdown/JetpackDropdownMenuButton.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/dropdown/JetpackDropdownMenuColors.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/dropdown/JetpackMenuElementData.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/filter/ReaderFilterChipGroup.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/readingpreferences/ReadingPreferencesButtons.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/readingpreferences/ReadingPreferencesFontSizeSlider.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/readingpreferences/ReadingPreferencesPreviewTag.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/readingpreferences/ReadingPreferencesScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/tagsfeed/ReaderTagsFeed.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/tagsfeed/ReaderTagsFeedPostListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/tagsfeed/ReaderTagsFeedPostListItemLoading.kt
  WordPress/src/test/java/org/wordpress/android/ui/compose/components/menu/JetpackMenuElementDataTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/utils/ReaderTopBarMenuHelperTest.kt
Labels: Tech Debt, UI

#21411 [Tooling] Update gems dependencies & fix Rubocop violations
  .github/workflows/run-danger.yml
  Gemfile
  Gemfile.lock
  fastlane/lanes/localization.rb
Labels: Tooling

#21383 Blogging prompts m3
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/promptslist/BloggingPromptsListActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/promptslist/compose/BloggingPromptsListItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/bloggingprompts/promptslist/compose/BloggingPromptsListScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/EmptyContentM3.kt
Labels: Tech Debt, UI

#21413 Remove GlobalStyleSupportFeatureConfig
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SelectedSiteRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  WordPress/src/main/java/org/wordpress/android/util/config/GlobalStyleSupportFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/SelectedSiteRepositoryTest.kt
  WordPress/src/test/java/org/wordpress/android/viewmodel/pages/PageListViewModelTest.kt
Labels: Tech Debt

#21396 Site monitoring Material3
  WordPress/src/main/java/org/wordpress/android/ui/sitemonitor/SiteMonitorParentActivity.kt
Labels: Tech Debt, UI

#21391 Migrate available dependencies to `ksp`
  build.gradle
  config/lint/lint.xml
  gradle/libs.versions.toml
  libs/fluxc/build.gradle
  libs/login/build.gradle
Labels: [Type] Enhancement, Core

#21397 [Tooling] Fix `update_appstore_strings` backmerge PR creation
  fastlane/lanes/localization.rb
  fastlane/lanes/release.rb
Labels: Tooling

#21431 Remove `violations-comments-to-github-gradle-plugin`
  WordPress/build.gradle
  build.gradle
  gradle/libs.versions.toml
Labels: Tooling

#21427 Material 3: Voice to content
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/MicToStopIcon.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/VoiceToContentScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/voicetocontent/WaveformVisualizer.kt
Labels: Tech Debt, UI

#21256 Merge some of the WordPress lint rules, to reduce number of reported issues
  WordPress/build.gradle
  config/lint/lint.xml
  gradle/libs.versions.toml
  libs/analytics/build.gradle
  libs/editor/build.gradle
  libs/fluxc/build.gradle
  libs/fluxc/src/test/java/org/wordpress/android/fluxc/store/StatsStoreTest.kt
  libs/image-editor/build.gradle
  libs/login/build.gradle
  libs/mocks/build.gradle
  libs/networking/build.gradle
Labels: Core

#21433 Change the domain used for prototypes
  fastlane/Fastfile
Labels: Tooling

#21430 Updated constraintlayout version to fix #21429
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/compose/DomainItem.kt
  WordPress/src/main/res/values/strings.xml
  config/lint/lint.xml
  gradle/libs.versions.toml
Labels: [Type] Crash, /My site

#21436 Enable configuration cache
  .configure
  .configure-files/gradle.properties.enc
  WordPress/build.gradle
  gradle.properties-example
Labels: Core

#21428 [Deps] Update Kotlin to 2.0.21
  .gitignore
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/support/SupportWebViewClient.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/migration/JetpackMigrationFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/services/SiteCreationServiceState.kt
  WordPress/src/main/java/org/wordpress/android/util/EnumWithFallbackValueTypeAdapterFactory.kt
  WordPress/src/main/java/org/wordpress/android/util/image/getters/WPRemoteResourceViewTarget.kt
  WordPress/src/test/java/org/wordpress/android/localcontentmigration/MigrationEmailHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/blaze/blazecampaigns/CampaignListingViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/jetpack/scan/details/ThreatDetailsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/discover/interests/ReaderInterestsViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderPostDetailViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/StatsViewModelTest.kt
  build.gradle
  gradle/libs.versions.toml
  libs/annotations/build.gradle
  libs/editor/build.gradle
  libs/fluxc-annotations/build.gradle
  libs/fluxc-processor/build.gradle
  libs/fluxc/build.gradle
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.kt
  libs/image-editor/build.gradle
  libs/login/build.gradle
  libs/processors/build.gradle
  libs/processors/src/test/kotlin/org/wordpress/android/processor/RemoteConfigProcessorTest.kt
Labels: Core, Tech Debt, dependency update

#21435 Material 3: Blaze
  WordPress/src/main/java/org/wordpress/android/ui/blaze/blazecampaigns/campaigndetail/CampaignDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/blaze/blazecampaigns/campaignlisting/CampaignListRow.kt
  WordPress/src/main/java/org/wordpress/android/ui/blaze/blazecampaigns/campaignlisting/CampaignListingFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/blaze/blazeoverlay/BlazeOverlayFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/blaze/blazepromote/BlazePromoteWebViewFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/buttons/ImageButtonM3.kt
Labels: Tech Debt, UI

#21440 Material 3: My Site Menu Activity
  WordPress/src/main/java/org/wordpress/android/ui/mysite/menu/MenuActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/menu/MenuViewModel.kt
Labels: Tech Debt, UI

#21441 Material 3: My Site Personalization
  WordPress/src/main/java/org/wordpress/android/ui/mysite/personalization/PersonalizationActivity.kt
Labels: Tech Debt, UI

#21311 Bump :gravatar to 2.0.1
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginHeaderViewHolder.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/comments/CommentDetailFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/comments/unified/UnifiedCommentViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/java/org/wordpress/android/util/WPAvatarUtils.java
  gradle/libs.versions.toml
  libs/login/src/main/java/org/wordpress/android/login/util/AvatarHelper.kt
Labels: Gravatar

#21443 Remove Gradle tasks wrapping `configure` tool
  build.gradle
Labels: Tooling

#21437 [Tooling] Use `buildkite_pipeline_upload` action to inline Buildkite release pipelines
  .buildkite/beta-builds.yml
  .buildkite/commands/checkout-editorial-branch.sh
  .buildkite/commands/checkout-release-branch.sh
  .buildkite/complete-code-freeze.yml
  .buildkite/finalize-release.yml
  .buildkite/publish-release.yml
  .buildkite/release-builds.yml
  .buildkite/update-release-notes.yml
  fastlane/lanes/release.rb
Labels: Tooling

#21426 Remove SiteIntentQuestionFeatureConfig
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/SiteCreationStep.kt
  WordPress/src/main/java/org/wordpress/android/util/config/SiteIntentQuestionFeatureConfig.kt
Labels: Tech Debt

#21450 Show the correct years for stats
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostAverageViewsPerDayUseCase.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostMonthsAndYearsUseCase.kt
Labels: Stats

#21445 Personalization accessibility
  WordPress/src/main/java/org/wordpress/android/ui/mysite/personalization/PersonalizationActivity.kt
  WordPress/src/main/res/values/strings.xml
Labels: Accessibility

#21452 Don't send sentry mapping files from local machines
  WordPress/build.gradle
  build.gradle
  config/gradle/gradle_build_cache.gradle
  config/gradle/gradle_build_scan.gradle
  settings.gradle
Labels: Core

#21446 Issue/prefs privacy m3
  WordPress/src/main/java/org/wordpress/android/ui/prefs/privacy/banner/PrivacyBannerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/privacy/banner/PrivacyBannerScreen.kt
Labels: Tech Debt, UI

#21457 Stats: remove avg "view more" link
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostAverageViewsPerDayUseCase.kt
  WordPress/src/test/java/org/wordpress/android/ui/stats/refresh/lists/detail/PostAverageViewsPerDayUseCaseTest.kt
Labels: Stats, Tech Debt

#21459 feat: Experimental features settings
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/res/values/key_strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/app_settings.xml
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
Labels: [Type] Enhancement, App Settings

#21442 Introduce `secrets.properties`. Use `gradle.properties` only for build configuration.
  .buildkite/commands/lint.sh
  .buildkite/commands/run-unit-tests.sh
  .buildkite/finalize-release.yml
  .buildkite/new-beta-release.yml
  .buildkite/pipeline.yml
  .buildkite/schedules/dependency-analysis.yml
  .configure
  .configure-files/secrets.properties.enc
  .github/workflows/submit-gradle-dependencies.yml
  .gitignore
  README.md
  WordPress/build.gradle
  build.gradle
  defaults.properties
  gradle.properties
  gradle.properties-example
  libs/fluxc/build.gradle
  libs/fluxc/developer.properties-example
  libs/fluxc/gradle.properties-example
  libs/login/build.gradle
  libs/login/developer.properties-example
  libs/login/gradle.properties-example
Labels: Core

#21399 feat: GutenbergKit Media Library support
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mediapicker/MediaPickerSetup.kt
  WordPress/src/main/java/org/wordpress/android/ui/photopicker/MediaPickerLauncher.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  gradle/libs.versions.toml
  libs/editor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java
  libs/editor/src/main/java/org/wordpress/android/editor/EditorFragmentAbstract.java
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java
Labels: [Type] Enhancement, Gutenberg

#21312 Implement Gravatar QuickEditor
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/barcodescanner/BarcodeScanner.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/utils/MeGravatarLoader.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/readingpreferences/ReadingPreferencesScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/tagsfeed/ReaderTagsFeed.kt
  WordPress/src/main/java/org/wordpress/android/util/WPAvatarUtils.java
  WordPress/src/main/java/org/wordpress/android/util/config/GravatarQuickEditorFeatureConfig.kt
  config/gradle/included_builds.gradle
  gradle/libs.versions.toml
  libs/image-editor/build.gradle
Labels: Gravatar, unit-tests-exemption

#21453 Enable Zendesk tickets from Automatticians
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/HelpActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/res/values/strings.xml
Labels: Support

#21470 Update dependabot config to ignore more A8c dependencies
  .github/dependabot.yml
Labels: [Type] Enhancement

#21467 feat: Relocate experimental features settings
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/ExperimentalFeaturesActivity.kt
  WordPress/src/main/res/drawable/ic_science_24.xml
  WordPress/src/main/res/layout/me_fragment.xml
  WordPress/src/main/res/values/key_strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/app_settings.xml
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
Labels: [Type] Enhancement, /Me

#21466 Removed feedback link from reading preferences
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderReadingPreferencesDialogFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/tracker/ReaderReadingPreferencesTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/viewmodels/ReaderReadingPreferencesViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/views/compose/readingpreferences/ReadingPreferencesScreen.kt
  WordPress/src/main/java/org/wordpress/android/util/config/ReaderReadingPreferencesFeedbackFeatureConfig.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/tracker/ReaderReadingPreferencesTrackerTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/reader/viewmodels/ReaderReadingPreferencesViewModelTest.kt
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
Labels: Reader

#21476 Stats: Use correct color for visitors
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/viewholders/BarChartViewHolder.kt
Labels: Stats

#21480 Add default values for e2e secrets
  defaults.properties
Labels: Core

#21477 build: Update GutenbergKit ref
  config/gradle/included_builds.gradle
  gradle/libs.versions.toml
Labels: Gutenberg

#21483 [Tooling] Update `Dangerfile` to run Rubocop with `bundle exec`
  Dangerfile
Labels: Tooling

#21482 Stop using restricted APIs in WPMainNavigationView
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainNavigationView.kt
Labels: Tech Debt

#21481 Remove fixed screen orientation
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/blaze/blazecampaigns/BlazeCampaignParentActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/blaze/blazecampaigns/campaignlisting/CampaignListingFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/blaze/blazepromote/BlazePromoteParentActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderVideoViewerActivity.java
Labels: Tech Debt, UI

#21489 Update feedback form note
  WordPress/src/main/java/org/wordpress/android/ui/main/feedbackform/FeedbackFormActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/feedbackform/FeedbackFormScreen.kt
  WordPress/src/main/res/values/strings.xml
Labels: Support, User Feedback

#21493 refactor: Separate Gutenberg editor implementations
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivityConstants.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostEditorAnalyticsSession.java
  WordPress/src/main/java/org/wordpress/android/util/config/GutenbergKitFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/GutenbergKitThemeStylesFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/NewGutenbergFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/NewGutenbergThemeStylesFeatureConfig.kt
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergKitEditorFragment.java
Labels: [Type] Task, Gutenberg, unit-tests-exemption

#21486 Support dark mode in Zendesk chat
  WordPress/src/main/java/org/wordpress/android/support/SupportWebViewActivity.kt
Labels: UI

#21491 Remove unused key from configure and unused tooling scripts
  .configure
  tools/check-missing-drawables.py
  tools/fix-style.sh
  tools/get-translated-release-notes.sh
  tools/gradle-functions.sh
  tools/inject_version_in_manifest.py
  tools/install-app-bundle.sh
  tools/language-codes.csv
  tools/list_missing_translations.sh
  tools/release-notes-language-codes.csv
  tools/remove-unused-strings.sh
  tools/rename_apk_aab.sh
  tools/validate-login-strings.sh
Labels: Tooling
