Repository wordpress-mobile/WordPress-Android, pull requests merged in 2025-04, with the labels that each got.

#21773 feat: Allow remote editor for WPCOM Simple sites
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/ExperimentalFeaturesActivity.kt
  WordPress/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergKitEditorFragment.java
Labels: [Type] Enhancement, Gutenberg

#21783 Email verification banner tests
  WordPress/src/main/java/org/wordpress/android/ui/main/emailverificationbanner/EmailVerificationViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/main/emailverificationbanner/EmailVerificationViewModelTest.kt
Labels: /Me, Testing

#21787 Integrate remote build cache for local builds
  .buildkite/commands/gradle-cache-build.sh
  .buildkite/pipeline.yml
  .configure
  .configure-files/secrets.properties.enc
  .gitignore
  WordPress/build.gradle
  build.gradle
  config/gradle/gradle_build_cache.gradle
  developer.properties-example
  gradle/libs.versions.toml
  settings.gradle
Labels: [Type] Enhancement, Tooling

#21798 Populate Gradle Build Cache on trunk (or: not only for PRs)
  .buildkite/pipeline.yml
Labels: Tooling

#21794 Make the UserAgent class a Singleton
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/UserAgent.kt
Labels: Tech Debt

#21808 Update Gravatar to 2.4.0
  gradle/libs.versions.toml
  settings.gradle
Labels: Gravatar

#21810 task: Remote feature flag gates GutenbergKit
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  WordPress/src/main/java/org/wordpress/android/util/config/GutenbergKitFeature.kt
Labels: [Type] Task, Gutenberg, unit-tests-exemption

#21812 Catch exception when attempting to load login uri in CustomTabsIntent
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
Labels: [Type] Crash, Login

#21814 Changed default avatar version to 1 to fix gravatar not loading after…
  WordPress/src/main/java/org/wordpress/android/ui/main/utils/MeGravatarLoader.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
Labels: /Me, Gravatar

#21816 Full screen reader detail
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/main/BaseAppCompatActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.java
  WordPress/src/main/res/layout/reader_activity_post_pager.xml
  WordPress/src/main/res/values/reader_styles.xml
Labels: Reader, Android 15

#21819 docs: Simplify GitHub templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation

#21820 Issue: CMM 256 deleted websites still appear in the site list
  WordPress/src/main/java/org/wordpress/android/ui/main/ChooseSiteActivity.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/model/SiteModel.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteWPComRestResponse.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/SiteSqlUtils.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
  libs/fluxc/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClientTest.kt
Labels: [Type] Bug

#21824 Update Gravatar to 2.4.1
  gradle/libs.versions.toml
Labels: Gravatar

#21822 Convert ReaderPostPagerActivity to Kotlin
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.kt
Labels: Reader, Tech Debt, unit-tests-exemption

#21825 [Tooling] Update Ruby gems
  Gemfile.lock
Labels: Tooling

#21791 refactor: Fetch and cache GutenbergKit editor settings
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  gradle/libs.versions.toml
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergKitEditorFragment.java
  libs/editor/src/main/res/layout/fragment_gutenberg_kit_editor.xml
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/action/EditorSettingsAction.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/action/EditorSettingsActionBuilder.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/model/EditorSettings.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/EditorSettingsSqlUtils.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/store/EditorSettingsStore.kt
Labels: [Type] Enhancement, Gutenberg, unit-tests-exemption

#21811 Prevent reusing OAuth code when login activity is recreated
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/WPcomLoginHelper.kt
Labels: [Type] Crash, Login

#21829 Issue: CMM 168 stats not properly updated when pulling to refresh
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/StatsFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/StatsListViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/sections/BaseStatsUseCase.kt
Labels: [Type] Bug

#21832 Check for null `workInfo` in UploadWorkerTest
  WordPress/src/androidTest/java/org/wordpress/android/util/UploadWorkerTest.kt
Labels: Testing

#21831 Convert reader adapter to ViewPager2
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.kt
  WordPress/src/main/res/layout/reader_activity_post_pager.xml
Labels: Reader, Tech Debt

#21841 build: Update GutenbergKit version
  gradle/libs.versions.toml
Labels: [Type] Task, Gutenberg

#21844 Updating API RS library
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/selfhostedusers/SampleUsers.kt
  gradle/libs.versions.toml
Labels: [Type] Task

#21842 Convert reader post list activity to Kotlin
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/main/BaseAppCompatActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListActivity.kt
Labels: Reader, Tech Debt

#21846 Convert LoginSiteAddressFragment to Kotlin
  libs/login/src/main/java/org/wordpress/android/login/LoginBaseFormFragment.java
  libs/login/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.java
  libs/login/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.kt
Labels: [Type] Task
