Repository wordpress-mobile/WordPress-Android, pull requests merged in 2025-03, with the labels that each got.

#21719 Fix positioning of toolbar in reader detail
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/main/BaseAppCompatActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
Labels: Reader

#21713 WordPress.com News images don't show in the reader
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/CustomRedirectInterceptor.kt
Labels: Reader

#21708 Merge 25.7 final to trunk
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  WordPress/src/main/res/values-ro/strings.xml
  fastlane/jetpack_metadata/android/ar/changelogs/default.txt
  fastlane/jetpack_metadata/android/de-DE/changelogs/default.txt
  fastlane/jetpack_metadata/android/pt-BR/changelogs/default.txt
  fastlane/metadata/android/ar/changelogs/default.txt
  fastlane/metadata/android/de-DE/changelogs/default.txt
  version.properties
Labels: Releases

#21731 Hotfix: Exclude editor from edge-to-edge
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/main/BaseAppCompatActivity.kt
Labels: Releases, Android 15

#21738 Merges 25.7.1 into trunk
  version.properties
Labels: Releases

#21741 [Dependabot] Update Ignore Configuration (`AGP`, `FluxC`, `Login` and `Stories`)
  .github/dependabot.yml
Labels: Core, Tooling, dependency update

#21736 [AndroidManifest] Reveal Manifest Changes in PR
  .buildkite/commands/diff-merged-manifest.sh
  .buildkite/pipeline.yml
  .buildkite/shared-pipeline-vars
Labels: Core, Tooling

#21740 Disable Samsung predictive text in the Aztec editor
  libs/editor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java
Labels: Aztec

#21745 [Tooling] Automate GitHub release publishing for beta builds
  fastlane/lanes/release.rb
Labels: Tooling

#21755 fix: DocsBot initialization
  WordPress/src/jetpack/assets/support_chat_widget.js
Labels: [Type] Bug, Support

#21756 Hotfix for 25.7.2 Docsbot and crop toolbar
  WordPress/src/jetpack/assets/support_chat_widget.js
  libs/image-editor/src/main/res/values-v35/styles.xml
Labels: [Type] Bug

#21757 Merge `25.7.2` to `trunk`
  version.properties
Labels: Releases

#21764 [Tooling] Move Gradle Wrapper Validation to the `linter` queue
  .buildkite/pipeline.yml
Labels: Tooling

#21760 Me onboarding banner
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/emailverificationbanner/EmailVerificationBanner.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/emailverificationbanner/EmailVerificationViewModel.kt
  WordPress/src/main/res/layout/me_fragment.xml
  WordPress/src/main/res/values/strings.xml
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/store/AccountStore.java
Labels: /Me, unit-tests-exemption
