Repository wordpress-mobile/WordPress-Android, pull requests merged in 2025-01, with the labels that each got.

#21552 Fix gravatar_quick_editor feature flag setup
  WordPress/build.gradle
  WordPress/src/main/java/org/wordpress/android/util/config/GravatarQuickEditorFeatureConfig.kt
Labels: Gravatar

#21564 feat: Introduce `gutenberg_kit` editor session property
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
Labels: [Type] Enhancement, Gutenberg

#21568 Fix: Check if email verified before allowing to update avatar
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/res/values/strings.xml
Labels: Gravatar

#21565 [Tooling] Fix handling of empty release notes
  fastlane/lanes/localization.rb
Labels: Tooling

#21566 Fix IllegalStateException in domain registration fragment
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/compose/DomainItem.kt
Labels: [Type] Crash, Domains

#21570 feat: GutenbergKit history navigation
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  gradle/libs.versions.toml
  libs/editor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java
  libs/editor/src/main/java/org/wordpress/android/editor/EditorFragmentAbstract.java
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergKitEditorFragment.java
Labels: [Type] Enhancement, Gutenberg

#21575 Remove Jetpack Lazy Images setting
  WordPress/src/main/java/org/wordpress/android/models/JetpackSettingsModel.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/SiteSettingsInterface.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/WPComSiteSettings.java
  WordPress/src/main/res/values/key_strings.xml
  WordPress/src/main/res/values/strings.xml
  WordPress/src/main/res/xml/site_settings.xml
Labels: Jetpack, Tech Debt

#21580 fix: Support experimental features in production builds
  WordPress/src/main/java/org/wordpress/android/ui/LocaleAwareActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/ExperimentalFeaturesActivity.kt
  WordPress/src/main/java/org/wordpress/android/util/PerAppLocaleManager.kt
  WordPress/src/main/java/org/wordpress/android/util/config/GutenbergKitFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/GutenbergKitThemeStylesFeatureConfig.kt
Labels: [Type] Bug, /Me, unit-tests-exemption

#21583 Finish m2 to m3 conversion
  .idea/inspectionProfiles/Project_Default.xml
  WordPress/src/main/java/org/wordpress/android/ui/barcodescanner/BarcodeScanner.kt
  WordPress/src/main/java/org/wordpress/android/ui/barcodescanner/BarcodeScanningFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/ButtonsColumn.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/ColumnWithFrostedGlassBackground.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/ContentAlphaProvider.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/EmptyContent.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/MainTopAppBar.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/TrainOfIcons.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/buttons/PrimaryButton.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/buttons/SecondaryButton.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/buttons/WPSwitch.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/text/Message.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/text/Subtitle.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/components/text/Title.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/theme/AppThemeM2.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/theme/AppThemeM3.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/theme/JetpackColors.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/theme/WordPressColors.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/utils/ColorExtensions.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/utils/ComposeUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/compose/views/TrainOfAvatarsView.kt
  WordPress/src/main/java/org/wordpress/android/ui/debug/preferences/DebugSharedPreferenceFlagsScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/management/MyDomainsScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/management/composable/PrimaryButton.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/management/newdomainsearch/composable/NewDomainSearchScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/domains/management/purchasedomain/composable/PurchaseDomainScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/jetpackoverlay/individualplugin/compose/WPJetpackIndividualPluginOverlayScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/jetpack/staticposter/compose/JetpackStaticPoster.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostJetpackSocialConnectionsContainer.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostJetpackSocialConnectionsList.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsJetpackSocialContainerView.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsJetpackSocialNoConnections.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsJetpackSocialSharesContainer.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostResolutionOverlay.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/PostResolutionOverlayFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/prepublishing/home/PrepublishingHomeViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/prepublishing/home/compose/PrepublishingHomeSocialNoConnectionsItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/prepublishing/social/PrepublishingSocialFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/prepublishing/social/compose/PrepublishingSocialScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/sharemessage/EditJetpackSocialShareMessageActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/social/compose/PostSocialConnectionItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/social/compose/PostSocialMessageItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/social/compose/PostSocialSharesText.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/social/compose/PostSocialSharingItem.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/accountsettings/AccountSettingsFragment.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/LoginPrologueRevampedFragment.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/compose/components/PrimaryButton.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/compose/components/SecondaryButton.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/compose/components/Tagline.kt
  config/lint/lint.xml
Labels: Tech Debt, Material3

#21593 Jetpack pre-publishing: use correct colors in categories and tags
  WordPress/src/jetpack/res/values-night/colors_base.xml
  WordPress/src/jetpack/res/values/colors_base.xml
  WordPress/src/main/res/values-night/colors_base.xml
  WordPress/src/main/res/values/colors_base.xml
Labels: Material3

#21595 Minor tweaks to pre-pub tags, pre-pub categories, and social connections
  WordPress/src/main/res/layout/add_category.xml
  WordPress/src/main/res/layout/prepublishing_tags_fragment.xml
  WordPress/src/main/res/layout/publicize_list_fragment.xml
  WordPress/src/main/res/values/strings.xml
Labels: UI

#21586 feat: Send editor feedback
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java
  WordPress/src/main/java/org/wordpress/android/ui/main/feedbackform/FeedbackFormActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/feedbackform/FeedbackFormViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  WordPress/src/main/res/menu/edit_post.xml
Labels: [Type] Enhancement, Gutenberg

#21582 feat: GutenbergKit code editor
  RELEASE-NOTES.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  gradle/libs.versions.toml
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergKitEditorFragment.java
Labels: [Type] Enhancement, Gutenberg

#21584 [Dependency Cache] Enable Dependency Cache on CI
  .buildkite/commands/lint.sh
  .buildkite/commands/prototype-build.sh
  .buildkite/commands/restore-cache.sh
  .buildkite/commands/run-instrumented-tests.sh
  .buildkite/commands/run-unit-tests.sh
  .buildkite/commands/save-cache.sh
  .buildkite/schedules/dependency-cache.yml
  .buildkite/shared-pipeline-vars
Labels: Core, Tooling

#21591 Remove UsingMaterialAndMaterial3Libraries from lint
  config/lint/lint.xml
Labels: Material3

#21601 Merge 25.6 release notes to trunk
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefs.java
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/ExperimentalFeaturesActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/sitecreation/domains/compose/DomainItem.kt
  WordPress/src/main/java/org/wordpress/android/util/config/GutenbergKitFeatureConfig.kt
  WordPress/src/main/java/org/wordpress/android/util/config/GutenbergKitThemeStylesFeatureConfig.kt
Labels: Releases

#21599 Update to Android 15
  WordPress/src/debug/java/org/wordpress/android/WordPressDebug.java
  WordPress/src/debug/java/org/wordpress/android/WordPressDebug.kt
  WordPress/src/main/java/org/wordpress/android/AppInitializer.kt
  WordPress/src/main/java/org/wordpress/android/support/SupportWebViewActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/signup/SignupEpilogueFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/MeFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainNavigationView.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/quicklinksitem/QuickLinksItemViewModelSlice.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/items/listitem/MySiteListItemViewHolder.kt
  WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/utils/WidgetUtils.kt
  WordPress/src/main/java/org/wordpress/android/util/WPActivityUtils.java
  WordPress/src/main/java/org/wordpress/android/util/extensions/WindowExtensions.kt
  WordPress/src/main/java/org/wordpress/android/util/signature/SignatureUtils.kt
  build.gradle
  libs/fluxc/src/test/java/org/wordpress/android/fluxc/comment/CommentSqlUtilsTest.kt
Labels: unit-tests-exemption, Android 15

#21569 Update automattic-about to 1.5.1
  gradle/libs.versions.toml
Labels: dependency update

#21414 Use a webview for WP.com login
  .configure
  .configure-files/secrets.properties.enc
  WordPress/build.gradle
  WordPress/src/jetpack/java/org/wordpress/android/ui/accounts/login/LoginPrologueRevampedFragment.kt
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/modules/AppConfigModule.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginNavigationEvents.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/UnifiedLoginTracker.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/LoginPrologueListener.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/WPcomLoginHelper.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/LoginPrologueFragment.kt
  WordPress/src/wordpress/java/org/wordpress/android/ui/accounts/login/LoginPrologueRevampedFragment.kt
  gradle/libs.versions.toml
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/WPcomLoginClient.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/applicationpasswords/WPcomAuthorizationCodeResponse.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/auth/AppSecrets.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/store/AccountStore.java
Labels: unit-tests-exemption

#21611 Removed collapsing toolbar from stats fragment
  WordPress/src/main/res/layout/stats_fragment.xml
Labels: Stats, Android 15

#21617 Fix Zendesk contact support overlap for Android 15 (SDK 35)
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/main/BaseAppCompatActivity.kt
  WordPress/src/main/java/org/wordpress/android/util/extensions/WindowExtensions.kt
  WordPress/src/main/res/values/styles.xml
Labels: Support, UI

#21619 Use separate link text for JP/WP feedback form
  WordPress/src/main/java/org/wordpress/android/ui/main/feedbackform/FeedbackFormScreen.kt
  WordPress/src/main/res/values/strings.xml
Labels: Support

#21627 [Tests] Fix Android Tests Compilation Failure
  WordPress/src/androidTest/java/org/wordpress/android/e2e/pages/ContactSupportScreen.kt
Labels: UI Tests

#21626 Merge `25.6` final to `trunk`
  WordPress/src/main/res/values-en-rGB/strings.xml
  WordPress/src/main/res/values-gl/strings.xml
  fastlane/jetpack_metadata/android/ar/changelogs/default.txt
  fastlane/jetpack_metadata/android/de-DE/changelogs/default.txt
  fastlane/jetpack_metadata/android/en-US/changelogs/default.txt
  fastlane/jetpack_metadata/android/es-ES/changelogs/default.txt
  fastlane/jetpack_metadata/android/fr-FR/changelogs/default.txt
  fastlane/jetpack_metadata/android/id/changelogs/default.txt
  fastlane/jetpack_metadata/android/it-IT/changelogs/default.txt
  fastlane/jetpack_metadata/android/iw-IL/changelogs/default.txt
  fastlane/jetpack_metadata/android/ja-JP/changelogs/default.txt
  fastlane/jetpack_metadata/android/ko-KR/changelogs/default.txt
  fastlane/jetpack_metadata/android/nl-NL/changelogs/default.txt
  fastlane/jetpack_metadata/android/pt-BR/changelogs/default.txt
  fastlane/jetpack_metadata/android/ru-RU/changelogs/default.txt
  fastlane/jetpack_metadata/android/sv-SE/changelogs/default.txt
  fastlane/jetpack_metadata/android/tr-TR/changelogs/default.txt
  fastlane/jetpack_metadata/android/zh-CN/changelogs/default.txt
  fastlane/jetpack_metadata/android/zh-TW/changelogs/default.txt
  fastlane/metadata/android/ar/changelogs/default.txt
  fastlane/metadata/android/de-DE/changelogs/default.txt
  fastlane/metadata/android/en-US/changelogs/default.txt
  fastlane/metadata/android/es-ES/changelogs/default.txt
  fastlane/metadata/android/fr-CA/changelogs/default.txt
  fastlane/metadata/android/fr-FR/changelogs/default.txt
  fastlane/metadata/android/id/changelogs/default.txt
  fastlane/metadata/android/it-IT/changelogs/default.txt
  fastlane/metadata/android/iw-IL/changelogs/default.txt
  fastlane/metadata/android/ja-JP/changelogs/default.txt
  fastlane/metadata/android/ko-KR/changelogs/default.txt
  fastlane/metadata/android/nl-NL/changelogs/default.txt
  fastlane/metadata/android/pl-PL/changelogs/default.txt
  fastlane/metadata/android/pt-BR/changelogs/default.txt
  fastlane/metadata/android/ru-RU/changelogs/default.txt
  fastlane/metadata/android/sv-SE/changelogs/default.txt
  fastlane/metadata/android/tr-TR/changelogs/default.txt
  fastlane/metadata/android/zh-CN/changelogs/default.txt
  fastlane/metadata/android/zh-TW/changelogs/default.txt
  version.properties
Labels: Releases

#21630 Remove feedback form from help activity
  WordPress/src/main/java/org/wordpress/android/ui/accounts/HelpActivity.kt
  WordPress/src/main/res/layout/help_activity.xml
Labels: Support

#21621 feat: Log GutenbergKit errors
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  gradle/libs.versions.toml
  libs/editor/src/main/java/org/wordpress/android/editor/AztecEditorFragment.java
  libs/editor/src/main/java/org/wordpress/android/editor/EditorFragmentAbstract.java
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergEditorFragment.java
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergKitEditorFragment.java
Labels: [Type] Enhancement, Gutenberg

#21624 Add missing `environment` parameter to Buildkite trigger call
  fastlane/lanes/release.rb
Labels: Tooling

#21635 Add autoVerify="true" to custom tabs service
  WordPress/src/main/AndroidManifest.xml
Labels: Support

#21623 Download store metadata when generating beta build
  fastlane/lanes/localization.rb
  fastlane/lanes/release.rb
  fastlane/lanes/screenshots.rb
Labels: Tooling

#21636 [Tooling] Rename `GHHELPER_REPO` to the standard `GITHUB_REPO`
  fastlane/Fastfile
  fastlane/lanes/build.rb
  fastlane/lanes/release.rb
Labels: Tooling

#21610 [Dependency Cache] Use Custom Init Gradle Task to Download Dependencies
  .buildkite/commands/lint.sh
  .buildkite/commands/prototype-build.sh
  .buildkite/commands/restore-cache.sh
  .buildkite/commands/run-instrumented-tests.sh
  .buildkite/commands/run-unit-tests.sh
  .buildkite/commands/save-cache.sh
  .buildkite/schedules/dependency-cache.yml
Labels: Core, Tooling

#21644 [Deps] Update Dependency Analysis to 2.8.0 [`++`]
  .buildkite/schedules/dependency-analysis.yml
  WordPress/build.gradle
  gradle/libs.versions.toml
  libs/analytics/build.gradle
  libs/annotations/build.gradle
  libs/editor/build.gradle
  libs/fluxc-annotations/build.gradle
  libs/fluxc-processor/build.gradle
  libs/fluxc/build.gradle
  libs/image-editor/build.gradle
  libs/login/build.gradle
  libs/mocks/build.gradle
  libs/networking/build.gradle
  libs/processors/build.gradle
Labels: Core, Tooling

#21650 feat: Request feedback when disabling the experimental editor
  WordPress/src/main/java/org/wordpress/android/ui/prefs/ExperimentalFeaturesActivity.kt
  WordPress/src/main/res/values/strings.xml
Labels: [Type] Enhancement, Gutenberg

#21649 build: Upgrade to GutenbergKit 0.0.5
  RELEASE-NOTES.txt
  gradle/libs.versions.toml
Labels: [Type] Enhancement, Gutenberg
