Repository wordpress-mobile/WordPress-Android, pull requests merged in 2025-05, with the labels that each got.

#21850 Convert reader post list fragment to Kotlin
  WordPress/src/main/java/org/wordpress/android/ui/FilteredRecyclerView.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderHistoryStack.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderSearchSuggestionListeners.kt
Labels: Reader, Tech Debt, unit-tests-exemption

#21851 Discover the login url for self-hosted sites and log it
  WordPress/src/main/java/org/wordpress/android/modules/ApplicationModule.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/test/java/org/wordpress/android/login/viewmodel/LoginSiteAddressViewModelTest.kt
  libs/login/build.gradle
  libs/login/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.kt
  libs/login/src/main/java/org/wordpress/android/login/viewmodel/LoginSiteAddressViewModel.kt
Labels: [Type] Task

#21853 Convert reader comment activity to kotlin
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderCommentListActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderCommentListActivity.kt
Labels: Reader, Tech Debt

#21864 Replace Dependabot reviewers config with CODEOWNERS
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: Tooling

#21855 Show password login webview and prepare internal architecture
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/WPcomLoginHelper.kt
  WordPress/src/test/java/org/wordpress/android/login/viewmodel/LoginSiteAddressViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/accounts/LoginViewModelTest.kt
  libs/login/build.gradle
  libs/login/src/main/java/org/wordpress/android/login/LoginSiteAddressFragment.kt
  libs/login/src/main/java/org/wordpress/android/login/viewmodel/LoginSiteAddressViewModel.kt
Labels: [Type] Task

#21866 Fix edge-to-edge on reader unfollow bottom sheet
  WordPress/src/main/res/values/styles.xml
Labels: Reader

#21867 Ignore site visibility
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/main/SiteRecord.kt
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/utils/SiteRecordUtil.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  WordPress/src/main/res/values/strings.xml
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/model/SiteModel.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.kt
  libs/fluxc/src/test/java/org/wordpress/android/fluxc/site/SiteStoreUnitTest.java
  libs/fluxc/src/test/java/org/wordpress/android/fluxc/site/SiteUtils.java
Labels: Site Management, Tech Debt

#21854 feat: GutenbergKit internationalization
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  gradle/libs.versions.toml
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergKitEditorFragment.java
Labels: [Type] Enhancement, i18n, Gutenberg

#21872 Merge 25.8 release notes to trunk
  WordPress/jetpack_metadata/PlayStoreStrings.po
  WordPress/jetpack_metadata/release_notes.txt
  WordPress/metadata/PlayStoreStrings.po
  WordPress/metadata/release_notes.txt
Labels: Releases

#21859 Handle and store application password
  WordPress/src/main/AndroidManifest.xml
  WordPress/src/main/java/org/wordpress/android/ui/accounts/ApplicationPasswordLoginActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/ApplicationPasswordLoginHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/WPcomLoginHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/accounts/LoginViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/accounts/login/ApplicationPasswordLoginHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/model/SiteModel.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
Labels: [Type] Task

#21874 Fix SQLite exception when updating the app after the new application password columns addition
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
Labels: [Type] Bug

#21875 No sites after login
  WordPress/src/main/java/org/wordpress/android/ui/AddQuickPressShortcutActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/ShareIntentReceiverActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/main/SitePickerAdapter.java
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/reblog/ReblogUseCase.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/reader/reblog/ReblogUseCaseTest.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/SiteSqlUtils.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.kt
Labels: [Type] Bug, /My site

#21876 Using proper errors when discovering Applicatin Password URL
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/MySiteViewModelTest.kt
  gradle/libs.versions.toml
Labels: Login

#21877 Convert ReaderPostRenderer and ReaderResourceVars to Kotlin
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostRenderer.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderResourceVars.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderResourceVars.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ImageSizeMap.java
Labels: Reader, Tech Debt

#21881 Convert reader scanners to Kotlin
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderEmbedScanner.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderEmbedScanner.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderHtmlUtils.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderHtmlUtils.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderIframeScanner.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderIframeScanner.kt
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderImageScanner.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderImageScanner.kt
Labels: Reader, Tech Debt

#21887 Setting jetpack flavour as the default one
  WordPress/build.gradle
Labels: [Type] Task

#21890 Disable smooth scroll to initial position
  WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostPagerActivity.kt
Labels: [Type] Bug, Reader

#21883 fix: Mitigate GutenbergKit text composition oddities
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  gradle/libs.versions.toml
  libs/editor/src/main/java/org/wordpress/android/editor/gutenberg/GutenbergKitEditorFragment.java
Labels: [Type] Bug, Gutenberg

#21888 Convert ImageSizeMap to Kotlin
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ImageSizeMap.java
  WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ImageSizeMap.kt
Labels: Reader, Tech Debt

#21886 Application password login add analytic events
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/ApplicationPasswordLoginHelper.kt
  WordPress/src/test/java/org/wordpress/android/ui/accounts/login/ApplicationPasswordLoginHelperTest.kt
  libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTracker.java
Labels: [Type] Task

#21880 [Tooling] Skip jobs if there are no relevant code changes
  .buildkite/commands/diff-merged-manifest.sh
  .buildkite/commands/gradle-cache-build.sh
  .buildkite/commands/lint.sh
  .buildkite/commands/prototype-build.sh
  .buildkite/commands/run-instrumented-tests.sh
  .buildkite/commands/run-unit-tests.sh
  .buildkite/commands/should-skip-job.sh
  .buildkite/pipeline.yml
  .buildkite/shared-pipeline-vars
Labels: Tooling

#21895 Disable Jetpack migration
  WordPress/build.gradle
Labels: [Type] Bug, Login

#21902 Make experimental features testable
  WordPress/src/main/java/org/wordpress/android/ui/mysite/SelectedSiteRepository.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/AppPrefsWrapper.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/experimentalfeatures/ExperimentalFeature.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/experimentalfeatures/ExperimentalFeatures.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/experimentalfeatures/ExperimentalFeaturesActivity.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/experimentalfeatures/ExperimentalFeaturesScreen.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/experimentalfeatures/ExperimentalFeaturesViewModel.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/SelectedSiteRepositoryTest.kt
Labels: unit-tests-exemption, Subscribers

#21903 Use Android KeyStore to encrypt application password credentials
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/ApplicationPasswordLoginHelper.kt
  WordPress/src/main/java/org/wordpress/android/util/encryption/EncryptionUtils.kt
  WordPress/src/test/java/org/wordpress/android/ui/accounts/login/ApplicationPasswordLoginHelperTest.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/model/SiteModel.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/WellSqlConfig.kt
Labels: [Type] Task

#21908 fix: GutenbergKit WebView presents native pickers
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
Labels: [Type] Bug, Gutenberg

#21912 Add the Application Password login flow as an experimental feature in debug
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/applicationpassword/ApplicationPasswordViewModelSlice.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/experimentalfeatures/ExperimentalFeatures.kt
  WordPress/src/main/java/org/wordpress/android/ui/prefs/experimentalfeatures/ExperimentalFeaturesViewModel.kt
  WordPress/src/main/res/values/strings.xml
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/applicationpassword/ApplicationPasswordViewModelSliceTest.kt
Labels: [Type] Task

#21913 Drop language migration
  WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java
  WordPress/src/main/java/org/wordpress/android/util/PerAppLocaleManager.kt
Labels: Localization, App Settings

#21914 Duplicate the regular login flow to allow application password first iteration
  WordPress/src/main/java/org/wordpress/android/modules/AppComponent.java
  WordPress/src/main/java/org/wordpress/android/modules/ViewModelModule.java
  WordPress/src/main/java/org/wordpress/android/ui/ActivityNavigator.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/LoginActivity.java
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/ApplicationPasswordLoginHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/applicationpassword/LoginSiteApplicationPasswordFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/applicationpassword/LoginSiteApplicationPasswordViewModel.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/MySiteFragment.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/applicationpassword/ApplicationPasswordViewModelSlice.kt
  WordPress/src/test/java/org/wordpress/android/ui/accounts/login/ApplicationPasswordLoginHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/accounts/login/applicationpassword/LoginSiteApplicationPasswordViewModelTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/applicationpassword/ApplicationPasswordViewModelSliceTest.kt
  libs/login/src/main/java/org/wordpress/android/login/LoginSiteAddressValidator.java
  libs/login/src/main/res/values/strings.xml
Labels: [Type] Task

#21919 Hotfix: revert to AGP 8.7.3
  gradle/libs.versions.toml
Labels: [Type] Bug, Localization

#21918 Inject the new Application Password credential into the old XML-RPC
  WordPress/src/main/java/org/wordpress/android/ui/accounts/login/ApplicationPasswordLoginHelper.kt
  WordPress/src/main/java/org/wordpress/android/ui/mysite/cards/applicationpassword/ApplicationPasswordViewModelSlice.kt
  WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.kt
  WordPress/src/test/java/org/wordpress/android/ui/accounts/login/ApplicationPasswordLoginHelperTest.kt
  WordPress/src/test/java/org/wordpress/android/ui/mysite/cards/applicationpassword/ApplicationPasswordViewModelSliceTest.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/encryption/EncryptionUtils.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/model/SiteModel.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/CookieNonceAuthenticator.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/NonceRestClient.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/site/SiteWPAPIRestClient.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/jetpacktunnel/JetpackRestClient.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/comment/CommentXMLRPCClient.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/comment/CommentsXMLRPCClient.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/media/MediaXMLRPCClient.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/media/XmlrpcUploadRequestBody.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/post/PostXMLRPCClient.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/site/SiteXMLRPCClient.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/taxonomy/TaxonomyXMLRPCClient.java
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/SiteSqlUtils.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.kt
  libs/fluxc/src/main/java/org/wordpress/android/fluxc/utils/extensions/SiteModelExtensions.kt
  libs/fluxc/src/test/java/org/wordpress/android/fluxc/TestSiteSqlUtils.kt
  libs/fluxc/src/test/java/org/wordpress/android/fluxc/site/SiteStoreUnitTest.java
  libs/login/src/main/java/org/wordpress/android/login/LoginUsernamePasswordFragment.java
Labels: [Type] Task
